ds5001/systemd/pddf-platform-init.service etc/systemd/system
ds5001/scripts/pddf_pre_driver_install.sh usr/local/bin
ds5001/scripts/pddf_post_device_create.sh usr/local/bin
ds5001/scripts/pre_pddf_init.sh usr/local/bin
ds5001/scripts/sensors usr/bin
ds5001/scripts/platform_sensors.py usr/local/bin
ds5001/scripts/ds5001_platform_shutdown.sh usr/local/bin
build-ds5001/sonic_platform-1.0-py3-none-any.whl usr/share/sonic/device/x86_64-cls_ds5001-r0/pddf
