#!/bin/bash
###########################################################################
# SONiC chassis_db configuration                                          #
#                                                                         #
# This script is used to add chassis_db address in local hosts and        #
# indicate to start database-chassis service. It should be excuted before #
# database-chassis.service started.                                       #
#                                                                         #
###########################################################################

config_chassis_db() {
    startdb_file="/etc/sonic/chassisdb.conf"
    chassisdb_address_file="/etc/sonic/chassisdb_address"
    [ ! -e $startdb_file ] || rm $startdb_file
    platform=${PLATFORM:-`sonic-cfggen -H -v DEVICE_METADATA.localhost.platform`}
    # database-chassis services will start when $chassis_config file exists
    chassis_config="/usr/share/sonic/device/$platform/chassisdb.conf"
    if [ ! -e $chassis_config ]; then
       echo "no chassisdb.conf found, bypass config-chassisdb service"
       exit 0
    fi

    # Read the various device attributes
    read -r is_supervisor is_disagg < <(python3 -c \
	    'import sonic_py_common.device_info as d; print(*[getattr(d,n,lambda:False)() \
	    for n in ("is_supervisor","is_disaggregated_chassis")])')

    # Check if this is a chassis
    read -r is_chassis < <(python3 -c 'import sonic_platform.platform as platform;\
	    chassis=platform.Platform().get_chassis(); m=chassis.get_module(0);\
	    name=m.get_name() if m else ""; print("SUPERVISOR" in name or "LINECARD" in name)')

    # Identify the midplane IP in each sonic platform
    if [[ "$is_chassis" == True ]]; then
        # With chassis handle supervisor and linecard
        if [[ "$is_supervisor" == True ]]; then
            midplane_interface_ip=$(ip -4 -o addr show "eth1-midplane" 2>/dev/null | \
                                  awk '{print $4}' | cut -d/ -f1 | head -n1)
        else
           midplane_interface_ip=$(python3 -c 'import sonic_platform.platform; \
                                 platform_chassis = sonic_platform.platform.Platform().get_chassis(); \
                                 sup_slot=platform_chassis.get_supervisor_slot(); print([m.get_midplane_ip() \
                                 for m in platform_chassis.get_all_modules() if m.get_slot() == sup_slot][0])' 2>/dev/null)
        fi
    elif [[ "$is_disagg" == True ]]; then
        # With disagg T2 pizza box it is docker0 bridge which is midplane
        midplane_interface_ip=$(ip -4 -o addr show "docker0" 2>/dev/null | \
                              awk '{print $4}' | cut -d/ -f1 | head -n1)
    fi

    # Generate the chassisdb_address_file from the midplane interface ip address
    if [[ -n "$midplane_interface_ip" ]]; then
        chassis_db_address="$midplane_interface_ip" j2 /usr/share/sonic/templates/chassisdb_address.j2 > "$chassisdb_address_file"
    else
        echo "Error: No IP address configured on midplane_interface"
        exit 0
    fi

    start_chassis_db=0
    chassis_db_address=""

    # source the platform/sku level chassisdb.conf, if the file exists
    source $chassis_config
    # source the new chassisdb_address_file, if the file exists
    [ -f $chassisdb_address_file ] && source $chassisdb_address_file

    # Introduce additional checks so that the chassis_db_address is valid
    # Check if the IP address is not 0.0.0.0
    if [[ "$chassis_db_address" == "0.0.0.0" ]]; then
        echo "Error: chassis_db address configured as 0.0.0.0"
        [ ! -e $chassisdb_address_file ] || rm $chassisdb_address_file
        exit 0
    fi
    # if the midplane subnet is defined make sure the IP address is part of the midplane subnet
    if [[ -n "$midplane_subnet" ]]; then
        result=$(python3 -c "import ipaddress; print(ipaddress.ip_address('$chassis_db_address') \
              in ipaddress.ip_network('$midplane_subnet'))")
        # Exit as error if chassis_db_address not in the midplane subnet
        if [[ $result == False ]]; then
            echo "Error: chassis_db address does not belong to midplane subnet"
            [ ! -e $chassisdb_address_file ] || rm $chassisdb_address_file
            exit 0
        fi
    fi

    if [[ "$start_chassis_db" == "1" ]]; then
       cp $chassis_config $startdb_file
       echo "start chassisdb"
    fi
    if [[ "$start_chassis_db" == "1" ]] || [[ -n "$chassis_db_address" ]]; then
        if [ -z "$chassis_db_address" ]; then
            echo "no user configured chassisdb address"
        else
            grep redis_chassis /etc/hosts
            if [ $? -ne 0 ]; then
                echo "$chassis_db_address redis_chassis.server" >> /etc/hosts
                echo "update chassis db address to $chassis_db_address"
            fi
        fi
    fi
}

# read SONiC immutable variables
[ -f /etc/sonic/sonic-environment ] && . /etc/sonic/sonic-environment

config_chassis_db

exit 0
