/*******************************************************************************
 *  Copyright Statement:
 *  --------------------
 *  This software and the information contained therein are protected by
 *  copyright and other intellectual property laws and terms herein is
 *  confidential. The software may not be copied and the information
 *  contained herein may not be used or disclosed except with the written
 *  permission of Clounix (Shanghai) Technology Limited. (C) 2020-2025
 *
 *  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 *  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("CLOUNIX SOFTWARE")
 *  RECEIVED FROM CLOUNIX AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
 *  AN "AS-IS" BASIS ONLY. CLOUNIX EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 *  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 *  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 *  NEITHER DOES CLOUNIX PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 *  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 *  SUPPLIED WITH THE CLOUNIX SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
 *  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. CLOUNIX SHALL ALSO
 *  NOT BE RESPONSIBLE FOR ANY CLOUNIX SOFTWARE RELEASES MADE TO BUYER'S
 *  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
 *
 *  BUYER'S SOLE AND EXCLUSIVE REMEDY AND CLOUNIX'S ENTIRE AND CUMULATIVE
 *  LIABILITY WITH RESPECT TO THE CLOUNIX SOFTWARE RELEASED HEREUNDER WILL BE,
 *  AT CLOUNIX'S OPTION, TO REVISE OR REPLACE THE CLOUNIX SOFTWARE AT ISSUE,
 *  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
 *  CLOUNIX FOR SUCH CLOUNIX SOFTWARE AT ISSUE.
 *
 *  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
 *  WITH THE LAWS OF THE PEOPLE'S REPUBLIC OF CHINA, EXCLUDING ITS CONFLICT OF
 *  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
 *  RELATED THERETO SHALL BE SETTLED BY LAWSUIT IN SHANGHAI,CHINA UNDER.
 *
 *******************************************************************************/

#ifndef __CLX_PCI_H__
#define __CLX_PCI_H__

#include <linux/device.h>
#include <linux/version.h>
#include "knet_types.h"

#define CLX_PCIE_VENDOR_ID_0 (0x1D9F)
#define CLX_PCIE_VENDOR_ID_1 (0x1F83)

#define CLX_DEVICE_ID_CL8300  (0x8300)
#define CLX_DEVICE_ID_CL8400  (0x8400)
#define CLX_DEVICE_ID_CL8500  (0x8500)
#define CLX_DEVICE_ID_CL8600  (0x8600)
#define CLX_INVALID_DEVICE_ID (0xFFFFFFFF)

#define CLX_DEVICE_IS_NAMCHABARWA(__dev_id__) (CLX_DEVICE_ID_CL8600 == (__dev_id__ & 0xFF00))
#define CLX_DEVICE_IS_KAWAGARBO(__dev_id__)   (CLX_DEVICE_ID_CL8400 == (__dev_id__ & 0xFF00))

#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 10, 0)
#define IOREMAP_API(a, b) ioremap_nocache(a, b)
#else
#define IOREMAP_API(a, b) ioremap(a, b)
#endif

int
clx_pci_init(void);
int
clx_pci_deinit(void);

int
clx_read_pci_reg(int unit, uint32_t offset, uint32_t *ptr_data, uint32_t len);
int
clx_write_pci_reg(int unit, uint32_t offset, uint32_t *ptr_data, uint32_t len);

#endif // __CLX_PCI_H__