[program:sshd]
command=/bin/sh -c '/usr/local/sbin/docker-ptf-ssh-host-keys.sh && exec /usr/sbin/sshd -D'
process_name=sshd
priority=10
stdout_logfile=/tmp/sshd.out.log
stderr_logfile=/tmp/sshd.err.log
redirect_stderr=false
autostart=true
autorestart=true
startsecs=1
numprocs=1
