/***********************************************************************************
 *                                                                                 *
 * Copyright: (c) 2021 Broadcom.                                                   *
 * Broadcom Proprietary and Confidential. All rights reserved.                     *
 *                                                                                 *
 ***********************************************************************************/

/***********************************************************************************
 ***********************************************************************************
 *                                                                                 *
 *  Revision    :    *
 *                                                                                 *
 *  Description :  Power management functions provided to IP User                  *
 *                                                                                 *
 ***********************************************************************************
 ***********************************************************************************/

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PEREGRINE5_PC_API_PWR_MGT_H
#define PEREGRINE5_PC_API_PWR_MGT_H

#include "peregrine5_pc_ipconfig.h"
#include "common/srds_api_enum.h"
#include "common/srds_api_err_code.h"
#include "peregrine5_pc_dependencies.h"
/*! @file
 *  @brief Power management functions provided to IP User
 */

/*! @addtogroup APITag
 * @{
 */

/*! @defgroup SerdesAPIPwrMgtTag Power Management APIs
 * Serdes API functions for powering on and off the Serdes.
 * Contains APIs for both powering down core(s) and lane(s).
 */

/*! @addtogroup SerdesAPIPwrMgtTag
 * @{
 */

#if !defined(SMALL_FOOTPRINT) 
/** Serdes Core Powerdown.
 * To complete a plp_aperta2_peregrine5_pc_core_pwrdn(), all of the lane(s) belonging to the core being powered down.
 * should also be issued a lane power down using plp_aperta2_peregrine5_pc_lane_pwrdn().
 * Note: To wake up from any powerdown mode, first call PWR_ON and then de-assert core_dp_reset [plp_aperta2_peregrine5_pc_core_dp_reset(sa__, 0)].
 * @param[in] sa__ is an opaque state vector passed through to device access functions.
 * @param[in] mode based on enum #plp_aperta2_srds_core_pwrdn_mode_enum select from PWR_ON, PWRDN, PWRDN_DEEP power down modes.
 * @return Error Code generated by API (returns ERR_CODE_NONE if no errors).
 */
err_code_t plp_aperta2_peregrine5_pc_core_pwrdn(srds_access_t *sa__, enum plp_aperta2_srds_core_pwrdn_mode_enum mode);
#endif /* !defined(SMALL_FOOTPRINT) */

#ifndef SMALL_FOOTPRINT

/*-----------------------*/
/*  IDDQ / Clkgate APIs  */
/*-----------------------*/
/** Core configuration for IDDQ.
 * Note: User also needs to configure all lanes through plp_aperta2_peregrine5_pc_lane_config_for_iddq()
 * before enabling IDDQ by asserting IDDQ pin.
 * @param[in] sa__ is an opaque state vector passed through to device access functions.
 * @return Error Code generated by API (returns ERR_CODE_NONE if no errors).
 */
err_code_t plp_aperta2_peregrine5_pc_core_config_for_iddq(srds_access_t *sa__);
/**************************************************/
/* LANE Based APIs - Required to be used per Lane */
/**************************************************/

/*--------------------------------------------------------------*/
/*  IDDQ / Powerdown / Deep Powerdown / Isolate Pins  */
/*--------------------------------------------------------------*/
/** Lane configurations for IDDQ.
 * Note: User needs to configure all lanes through plp_aperta2_peregrine5_pc_lane_config_for_iddq() and also call plp_aperta2_peregrine5_pc_core_config_for_iddq()
 * before enabling IDDQ by asserting IDDQ pin.
 * @param[in] sa__ is an opaque state vector passed through to device access functions.
 * @return Error Code generated by API (returns ERR_CODE_NONE if no errors).
 */
err_code_t plp_aperta2_peregrine5_pc_lane_config_for_iddq(srds_access_t *sa__);
#endif /* !defined(SMALL_FOOTPRINT) */

#if !defined(SMALL_FOOTPRINT) 
/** Serdes Lane Powerdown.
 * Powers down option available - TX only, RX only, TX only DEEP, RX only DEEP,
 * complete LANE, complete lane DEEP, complete lane DEEP OFF, PWR_ON, PWR_ON TX only, PWR_ON RX only.
 * Note: To wake up from any lane powerdown mode, first call PWR_ON and then de-assert lane dp reset.
 *       De-assert with plp_aperta2_peregrine5_pc_tx_dp_reset(..) when waking up from a TX only PWRDN, plp_aperta2_peregrine5_pc_rx_dp_reset(..)
 *       for a RX only PWRDN, and plp_aperta2_peregrine5_pc_ln_dp_reset(..) for both RX and TX.
 * Note: PWRDN_TX_DEEP, PWRDN_RX_DEEP, and PWRDN_DEEP may require lane reconfiguration upon a PWR_ON.
 * @param[in] sa__ is an opaque state vector passed through to device access functions.
 * @param[in] mode Enable/Disable lane powerdown based on #plp_aperta2_srds_core_pwrdn_mode_enum.
 * @return Error Code generated by API (returns ERR_CODE_NONE if no errors).
 */
err_code_t plp_aperta2_peregrine5_pc_lane_pwrdn(srds_access_t *sa__, enum plp_aperta2_srds_core_pwrdn_mode_enum mode);
#endif /* !defined(SMALL_FOOTPRINT) */

#ifndef SMALL_FOOTPRINT

/** Serdes All Powerdown.
 * Powers down the core along with all PLLs and all lanes within the core.
 * Note: PWRDN_DEEP may require lane reconfiguration upon a PWR_ON.
 * @param[in] sa__ is an opaque state vector passed through to device access functions.
 * @param[in] mode based on enum #plp_aperta2_srds_core_pwrdn_mode_enum select from PWRDN, or PWRDN_DEEP, or PWROFF_DEEP power down modes.
 * @return Error Code generated by API (returns ERR_CODE_NONE if no errors).
 */
err_code_t plp_aperta2_peregrine5_pc_pwrdn_all(srds_access_t *sa__, enum plp_aperta2_srds_core_pwrdn_mode_enum mode);

#endif /* !SMALL_FOOTPRINT */
/*! @} SerdesAPIPwrMgtTag */
/*! @} APITag */
#endif /* SERDES_API_PWR_MGT_H */
#ifdef __cplusplus
}
#endif
