/*************************************************************************************
 *                                                                                   *
 * Copyright: (c) 2021 Broadcom.                                                     *
 * Broadcom Proprietary and Confidential. All rights reserved.                       *
 *                                                                                   *
 *************************************************************************************/

/*************************************************************************************
 *************************************************************************************
 *                                                                                   *
 *  Revision      :  Id                                                              *
 *                                                                                   *
 *  Description   :  Defines and externed array used for plp_aperta2_peregrine5_pc_reg_dump()           *
 *                                                                                   *
 *************************************************************************************
 *************************************************************************************/


/* THIS FILE IS GENERATED USING AN AUTOMATED SCRIPT. PLEASE DO NOT EDIT THIS FILE DIRECTLY! */

#ifndef PEREGRINE5_PC_API_REG_DUMP_H
#define PEREGRINE5_PC_API_REG_DUMP_H

#include "peregrine5_pc_usr_includes.h"

/*! @file
 *  @brief Register addresses and types used for register dump APIs
 */

/*! @addtogroup APITag
 * @{
 */

/*! @defgroup SerdesAPIRegDumpTag Support for Register Dump APIs  */

/*! @addtogroup SerdesAPIRegDumpTag
 * @{
 */


/*! @def PEREGRINE5_PC_REG_DUMP_SECTIONS
 * The number of contiguous register address ranges that will have their contents dumped.
 */
#define PEREGRINE5_PC_REG_DUMP_SECTIONS  (98)

/*! @def PEREGRINE5_PC_REG_PLL_START
 * The register address of the first PLL register.
 * A value of 0xffff indicates there are no PLL registers for this IP.
 */
#define PEREGRINE5_PC_REG_PLL_START      (0xc000)

/*! @def PEREGRINE5_PC_REG_UC_START
 * The register address of the first UC register.
 * A value of 0xffff indicates there are no UC registers for this IP.
 */
#define PEREGRINE5_PC_REG_UC_START       (0xdc00)

/*! @def PEREGRINE5_PC_REG_CORE_START_INDEX
 * The peregrine5_pc_reg_dump_arr index of the first Core register.
 */
#define PEREGRINE5_PC_REG_CORE_START_INDEX      (76)    /* 0xd000 */

/*! @def PEREGRINE5_PC_REG_PLL_START_INDEX
 * The peregrine5_pc_reg_dump_arr index of the first PLL register.
  */
#define PEREGRINE5_PC_REG_PLL_START_INDEX      (91)    /* 0xc000 */

/*! @def PEREGRINE5_PC_REG_UC_START_INDEX
 * The peregrine5_pc_reg_dump_arr index of the first UC register.
 */
#define PEREGRINE5_PC_REG_UC_START_INDEX       (96)    /* 0xdc00 */

/*! peregrine5_pc_reg_dump_arr_t
 *
 */
typedef const uint16_t peregrine5_pc_reg_dump_arr_t[2];

/** Get peregrine5_pc_reg_dump_arr
 * @return Pointer to peregrine5_pc_reg_dump_arr, which is a 2-element array of const uint16_t.
 *         Element 1 = base address, Element 2 = mask of valid addresses from base address. 
 */
peregrine5_pc_reg_dump_arr_t *plp_aperta2_peregrine5_pc_get_reg_dump_arr(void);

/*! @} SerdesAPIRegDumpTag */
/*! @} APITag */

#endif /* SERDES_API_REG_DUMP_H */

