
/***********************************************************************************
 *                                                                                 *
 * Copyright: (c) 2021 Broadcom.                                                   *
 * Broadcom Proprietary and Confidential. All rights reserved.                     *
 *                                                                                 *
 **********************************************************************************/

/***********************************************************************************
 ***********************************************************************************
 *                                                                                 *
 *  Revision      :                                                            *
 *                                                                                 *
 *  Description   :  This file contains Unified API jump tables                    *
 *                                                                                 *
 ***********************************************************************************
 **********************************************************************************/

/* THIS FILE IS GENERATED USING AN AUTOMATED SCRIPT.DO NOT EDIT THIS FILE DIRECTLY! */

#include "peregrine5_pc_uapi_fields.h"
#include "peregrine5_pc_select_defns.h"
#include "peregrine5_pc_internal.h"
#include "peregrine5_pc_functions.h"

err_code_t plp_aperta2_peregrine5_pc_wr_uapi_afe_pga_boost_ctrl(srds_access_t *sa__, uint8_t wr_val) {
    err_code_t failcode = ERR_CODE_NONE;
    PEREGRINE5_PC_UAPI_WR_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE0):
            failcode = plp_aperta2_peregrine5_pc_acc_mwr_reg_u8(sa__, 0x1004, 0x000f, 0, wr_val);
            break;
        case(PEREGRINE5_PC_UAPI_CASE1):
            failcode = plp_aperta2_peregrine5_pc_acc_mwr_reg_u8(sa__, 0x1004, 0x000f, 0, wr_val);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            failcode = plp_aperta2_peregrine5_pc_acc_mwr_reg_u8(sa__, 0x1a0b, 0x000f, 0, wr_val);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_wr_uapi_afe_pga_boost_ctrl(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
            failcode = ERR_CODE_INVALID_UAPI_CASE;
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return failcode;
}

uint8_t plp_aperta2_peregrine5_pc_rd_uapi_afe_pga_boost_ctrl(srds_access_t *sa__, err_code_t *err_code_p) {
    uint8_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE0):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0x1004, 12, 12, err_code_p);
            break;
        case(PEREGRINE5_PC_UAPI_CASE1):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0x1004, 12, 12, err_code_p);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0x1a0b, 12, 12, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_rd_uapi_afe_pga_boost_ctrl(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

err_code_t plp_aperta2_peregrine5_pc_wr_uapi_tlb_err_analyze_update_freq(srds_access_t *sa__, uint8_t wr_val) {
    err_code_t failcode = ERR_CODE_NONE;
    PEREGRINE5_PC_UAPI_WR_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE0):
            failcode = plp_aperta2_peregrine5_pc_acc_mwr_reg_u8(sa__, 0xd004, 0x0060, 5, wr_val);
            break;
        case(PEREGRINE5_PC_UAPI_CASE1):
            failcode = plp_aperta2_peregrine5_pc_acc_mwr_reg_u8(sa__, 0xd004, 0x0060, 5, wr_val);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_wr_uapi_tlb_err_analyze_update_freq(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
            failcode = ERR_CODE_INVALID_UAPI_CASE;
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return failcode;
}

uint8_t plp_aperta2_peregrine5_pc_rd_uapi_tlb_err_analyze_update_freq(srds_access_t *sa__, err_code_t *err_code_p) {
    uint8_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE0):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0xd004, 9, 14, err_code_p);
            break;
        case(PEREGRINE5_PC_UAPI_CASE1):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0xd004, 9, 14, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_rd_uapi_tlb_err_analyze_update_freq(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

uint16_t plp_aperta2_peregrine5_pc_ex_uapi_tlb_err_analyze_update_freq(srds_access_t *sa__, uint16_t reg_value) {
    uint16_t ex_val = 0;
    PEREGRINE5_PC_UAPI_EX_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE0):
            ex_val = extract_field((reg_value), 6, 5);
            break;
        case(PEREGRINE5_PC_UAPI_CASE1):
            ex_val = extract_field((reg_value), 6, 5);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_ex_uapi_tlb_err_analyze_update_freq(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return ex_val;
}

err_code_t plp_aperta2_peregrine5_pc_wr_uapi_bc_enc_update(srds_access_t *sa__, uint8_t wr_val) {
    err_code_t failcode = ERR_CODE_NONE;
    PEREGRINE5_PC_UAPI_WR_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE0):
            failcode = plp_aperta2_peregrine5_pc_acc_mwr_reg_u8(sa__, 0x630e, 0x0001, 0, wr_val);
            break;
        case(PEREGRINE5_PC_UAPI_CASE1):
            failcode = plp_aperta2_peregrine5_pc_acc_mwr_reg_u8(sa__, 0x630e, 0x0001, 0, wr_val);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_wr_uapi_bc_enc_update(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
            failcode = ERR_CODE_INVALID_UAPI_CASE;
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return failcode;
}

uint8_t plp_aperta2_peregrine5_pc_rd_uapi_bc_enc_update(srds_access_t *sa__, err_code_t *err_code_p) {
    uint8_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE0):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0x630e, 15, 15, err_code_p);
            break;
        case(PEREGRINE5_PC_UAPI_CASE1):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0x630e, 15, 15, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_rd_uapi_bc_enc_update(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

uint16_t plp_aperta2_peregrine5_pc_ex_uapi_bc_enc_update(srds_access_t *sa__, uint16_t reg_value) {
    uint16_t ex_val = 0;
    PEREGRINE5_PC_UAPI_EX_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE0):
            ex_val = extract_field((reg_value), 0, 0);
            break;
        case(PEREGRINE5_PC_UAPI_CASE1):
            ex_val = extract_field((reg_value), 0, 0);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_ex_uapi_bc_enc_update(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return ex_val;
}

err_code_t plp_aperta2_peregrine5_pc_wr_uapi_tx_pi_sampler_max_cnt(srds_access_t *sa__, uint8_t wr_val) {
    err_code_t failcode = ERR_CODE_NONE;
    PEREGRINE5_PC_UAPI_WR_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE0):
            failcode = plp_aperta2_peregrine5_pc_acc_mwr_reg_u8(sa__, 0x7204, 0x0f00, 8, wr_val);
            break;
        case(PEREGRINE5_PC_UAPI_CASE1):
            failcode = plp_aperta2_peregrine5_pc_acc_mwr_reg_u8(sa__, 0x7204, 0x0f00, 8, wr_val);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            failcode = plp_aperta2_peregrine5_pc_acc_mwr_reg_u8(sa__, 0x7204, 0x3f00, 8, wr_val);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_wr_uapi_tx_pi_sampler_max_cnt(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
            failcode = ERR_CODE_INVALID_UAPI_CASE;
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return failcode;
}

uint8_t plp_aperta2_peregrine5_pc_rd_uapi_tx_pi_sampler_max_cnt(srds_access_t *sa__, err_code_t *err_code_p) {
    uint8_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE0):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0x7204, 4, 12, err_code_p);
            break;
        case(PEREGRINE5_PC_UAPI_CASE1):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0x7204, 4, 12, err_code_p);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0x7204, 2, 10, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_rd_uapi_tx_pi_sampler_max_cnt(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

uint16_t plp_aperta2_peregrine5_pc_ex_uapi_tx_pi_sampler_max_cnt(srds_access_t *sa__, uint16_t reg_value) {
    uint16_t ex_val = 0;
    PEREGRINE5_PC_UAPI_EX_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE0):
            ex_val = extract_field((reg_value), 11, 8);
            break;
        case(PEREGRINE5_PC_UAPI_CASE1):
            ex_val = extract_field((reg_value), 11, 8);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            ex_val = extract_field((reg_value), 13, 8);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_ex_uapi_tx_pi_sampler_max_cnt(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return ex_val;
}

uint8_t plp_aperta2_peregrine5_pc_rd_uapi_pll_lock_loss_intr_det_HL(srds_access_t *sa__, err_code_t *err_code_p) {
    uint8_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE1):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0xc207, 12, 15, err_code_p);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0xc207, 12, 15, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_rd_uapi_pll_lock_loss_intr_det_HL(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

uint16_t plp_aperta2_peregrine5_pc_ex_uapi_pll_lock_loss_intr_det_HL(srds_access_t *sa__, uint16_t reg_value) {
    uint16_t ex_val = 0;
    PEREGRINE5_PC_UAPI_EX_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE1):
            ex_val = extract_field((reg_value), 3, 3);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            ex_val = extract_field((reg_value), 3, 3);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_ex_uapi_pll_lock_loss_intr_det_HL(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return ex_val;
}

uint8_t plp_aperta2_peregrine5_pc_rd_uapi_pll_lock_loss_intr_det_LH(srds_access_t *sa__, err_code_t *err_code_p) {
    uint8_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE1):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0xc207, 13, 15, err_code_p);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0xc207, 13, 15, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_rd_uapi_pll_lock_loss_intr_det_LH(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

uint16_t plp_aperta2_peregrine5_pc_ex_uapi_pll_lock_loss_intr_det_LH(srds_access_t *sa__, uint16_t reg_value) {
    uint16_t ex_val = 0;
    PEREGRINE5_PC_UAPI_EX_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE1):
            ex_val = extract_field((reg_value), 2, 2);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            ex_val = extract_field((reg_value), 2, 2);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_ex_uapi_pll_lock_loss_intr_det_LH(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return ex_val;
}

err_code_t plp_aperta2_peregrine5_pc_wr_uapi_micro_rmi_upin_dr_ecc_uncorr_err_intr_en(srds_access_t *sa__, uint8_t wr_val) {
    err_code_t failcode = ERR_CODE_NONE;
    PEREGRINE5_PC_UAPI_WR_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE1):
            failcode = plp_aperta2_peregrine5_pc_acc_mwr_reg_u8(sa__, 0xda10, 0x0002, 1, wr_val);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            failcode = plp_aperta2_peregrine5_pc_acc_mwr_reg_u8(sa__, 0xda10, 0x0002, 1, wr_val);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_wr_uapi_micro_rmi_upin_dr_ecc_uncorr_err_intr_en(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
            failcode = ERR_CODE_INVALID_UAPI_CASE;
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return failcode;
}

uint8_t plp_aperta2_peregrine5_pc_rd_uapi_micro_rmi_upin_dr_ecc_uncorr_err_intr_en(srds_access_t *sa__, err_code_t *err_code_p) {
    uint8_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE1):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0xda10, 14, 15, err_code_p);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0xda10, 14, 15, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_rd_uapi_micro_rmi_upin_dr_ecc_uncorr_err_intr_en(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

uint16_t plp_aperta2_peregrine5_pc_ex_uapi_micro_rmi_upin_dr_ecc_uncorr_err_intr_en(srds_access_t *sa__, uint16_t reg_value) {
    uint16_t ex_val = 0;
    PEREGRINE5_PC_UAPI_EX_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE1):
            ex_val = extract_field((reg_value), 1, 1);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            ex_val = extract_field((reg_value), 1, 1);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_ex_uapi_micro_rmi_upin_dr_ecc_uncorr_err_intr_en(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return ex_val;
}

err_code_t plp_aperta2_peregrine5_pc_wr_uapi_micro_rmi_upin_cr_ecc_uncorr_err_intr_en(srds_access_t *sa__, uint8_t wr_val) {
    err_code_t failcode = ERR_CODE_NONE;
    PEREGRINE5_PC_UAPI_WR_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE1):
            failcode = plp_aperta2_peregrine5_pc_acc_mwr_reg_u8(sa__, 0xda10, 0x0001, 0, wr_val);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            failcode = plp_aperta2_peregrine5_pc_acc_mwr_reg_u8(sa__, 0xda10, 0x0001, 0, wr_val);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_wr_uapi_micro_rmi_upin_cr_ecc_uncorr_err_intr_en(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
            failcode = ERR_CODE_INVALID_UAPI_CASE;
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return failcode;
}

uint8_t plp_aperta2_peregrine5_pc_rd_uapi_micro_rmi_upin_cr_ecc_uncorr_err_intr_en(srds_access_t *sa__, err_code_t *err_code_p) {
    uint8_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE1):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0xda10, 15, 15, err_code_p);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0xda10, 15, 15, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_rd_uapi_micro_rmi_upin_cr_ecc_uncorr_err_intr_en(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

uint16_t plp_aperta2_peregrine5_pc_ex_uapi_micro_rmi_upin_cr_ecc_uncorr_err_intr_en(srds_access_t *sa__, uint16_t reg_value) {
    uint16_t ex_val = 0;
    PEREGRINE5_PC_UAPI_EX_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE1):
            ex_val = extract_field((reg_value), 0, 0);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            ex_val = extract_field((reg_value), 0, 0);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_ex_uapi_micro_rmi_upin_cr_ecc_uncorr_err_intr_en(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return ex_val;
}

uint8_t plp_aperta2_peregrine5_pc_rd_uapi_micro_rmi_upin_dr_ecc_uncorr_err_status(srds_access_t *sa__, err_code_t *err_code_p) {
    uint8_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE1):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0xda11, 14, 15, err_code_p);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0xda11, 14, 15, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_rd_uapi_micro_rmi_upin_dr_ecc_uncorr_err_status(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

uint16_t plp_aperta2_peregrine5_pc_ex_uapi_micro_rmi_upin_dr_ecc_uncorr_err_status(srds_access_t *sa__, uint16_t reg_value) {
    uint16_t ex_val = 0;
    PEREGRINE5_PC_UAPI_EX_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE1):
            ex_val = extract_field((reg_value), 1, 1);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            ex_val = extract_field((reg_value), 1, 1);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_ex_uapi_micro_rmi_upin_dr_ecc_uncorr_err_status(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return ex_val;
}

uint8_t plp_aperta2_peregrine5_pc_rd_uapi_micro_rmi_upin_cr_ecc_uncorr_err_status(srds_access_t *sa__, err_code_t *err_code_p) {
    uint8_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE1):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0xda11, 15, 15, err_code_p);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0xda11, 15, 15, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_rd_uapi_micro_rmi_upin_cr_ecc_uncorr_err_status(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

uint16_t plp_aperta2_peregrine5_pc_ex_uapi_micro_rmi_upin_cr_ecc_uncorr_err_status(srds_access_t *sa__, uint16_t reg_value) {
    uint16_t ex_val = 0;
    PEREGRINE5_PC_UAPI_EX_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE1):
            ex_val = extract_field((reg_value), 0, 0);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            ex_val = extract_field((reg_value), 0, 0);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_ex_uapi_micro_rmi_upin_cr_ecc_uncorr_err_status(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return ex_val;
}

uint8_t plp_aperta2_peregrine5_pc_rd_uapi_ln_a_dig_lpbk_en_intr(srds_access_t *sa__, err_code_t *err_code_p) {
    uint8_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0xdc18, 13, 15, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_rd_uapi_ln_a_dig_lpbk_en_intr(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

uint16_t plp_aperta2_peregrine5_pc_ex_uapi_ln_a_dig_lpbk_en_intr(srds_access_t *sa__, uint16_t reg_value) {
    uint16_t ex_val = 0;
    PEREGRINE5_PC_UAPI_EX_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            ex_val = extract_field((reg_value), 2, 2);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_ex_uapi_ln_a_dig_lpbk_en_intr(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return ex_val;
}

uint8_t plp_aperta2_peregrine5_pc_rd_uapi_ln_a_rx_restart_pmd_hold_intr(srds_access_t *sa__, err_code_t *err_code_p) {
    uint8_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0xdc18, 14, 15, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_rd_uapi_ln_a_rx_restart_pmd_hold_intr(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

uint16_t plp_aperta2_peregrine5_pc_ex_uapi_ln_a_rx_restart_pmd_hold_intr(srds_access_t *sa__, uint16_t reg_value) {
    uint16_t ex_val = 0;
    PEREGRINE5_PC_UAPI_EX_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            ex_val = extract_field((reg_value), 1, 1);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_ex_uapi_ln_a_rx_restart_pmd_hold_intr(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return ex_val;
}

uint8_t plp_aperta2_peregrine5_pc_rd_uapi_ln_a_rx_dp_reset_active_intr(srds_access_t *sa__, err_code_t *err_code_p) {
    uint8_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0xdc18, 15, 15, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_rd_uapi_ln_a_rx_dp_reset_active_intr(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

uint16_t plp_aperta2_peregrine5_pc_ex_uapi_ln_a_rx_dp_reset_active_intr(srds_access_t *sa__, uint16_t reg_value) {
    uint16_t ex_val = 0;
    PEREGRINE5_PC_UAPI_EX_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            ex_val = extract_field((reg_value), 0, 0);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_ex_uapi_ln_a_rx_dp_reset_active_intr(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return ex_val;
}

uint8_t plp_aperta2_peregrine5_pc_rd_uapi_ln_b_dig_lpbk_en_intr(srds_access_t *sa__, err_code_t *err_code_p) {
    uint8_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0xdc19, 13, 15, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_rd_uapi_ln_b_dig_lpbk_en_intr(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

uint16_t plp_aperta2_peregrine5_pc_ex_uapi_ln_b_dig_lpbk_en_intr(srds_access_t *sa__, uint16_t reg_value) {
    uint16_t ex_val = 0;
    PEREGRINE5_PC_UAPI_EX_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            ex_val = extract_field((reg_value), 2, 2);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_ex_uapi_ln_b_dig_lpbk_en_intr(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return ex_val;
}

uint8_t plp_aperta2_peregrine5_pc_rd_uapi_ln_b_rx_restart_pmd_hold_intr(srds_access_t *sa__, err_code_t *err_code_p) {
    uint8_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0xdc19, 14, 15, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_rd_uapi_ln_b_rx_restart_pmd_hold_intr(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

uint16_t plp_aperta2_peregrine5_pc_ex_uapi_ln_b_rx_restart_pmd_hold_intr(srds_access_t *sa__, uint16_t reg_value) {
    uint16_t ex_val = 0;
    PEREGRINE5_PC_UAPI_EX_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            ex_val = extract_field((reg_value), 1, 1);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_ex_uapi_ln_b_rx_restart_pmd_hold_intr(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return ex_val;
}

uint8_t plp_aperta2_peregrine5_pc_rd_uapi_ln_b_rx_dp_reset_active_intr(srds_access_t *sa__, err_code_t *err_code_p) {
    uint8_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0xdc19, 15, 15, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_rd_uapi_ln_b_rx_dp_reset_active_intr(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

uint16_t plp_aperta2_peregrine5_pc_ex_uapi_ln_b_rx_dp_reset_active_intr(srds_access_t *sa__, uint16_t reg_value) {
    uint16_t ex_val = 0;
    PEREGRINE5_PC_UAPI_EX_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            ex_val = extract_field((reg_value), 0, 0);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_ex_uapi_ln_b_rx_dp_reset_active_intr(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return ex_val;
}

err_code_t plp_aperta2_peregrine5_pc_wr_uapi_latency_match_en(srds_access_t *sa__, uint8_t wr_val) {
    err_code_t failcode = ERR_CODE_NONE;
    PEREGRINE5_PC_UAPI_WR_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            failcode = plp_aperta2_peregrine5_pc_acc_mwr_reg_u8(sa__, 0x4102, 0x8000, 15, wr_val);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_wr_uapi_latency_match_en(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
            failcode = ERR_CODE_INVALID_UAPI_CASE;
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return failcode;
}

uint8_t plp_aperta2_peregrine5_pc_rd_uapi_latency_match_en(srds_access_t *sa__, err_code_t *err_code_p) {
    uint8_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0x4102, 0, 15, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_rd_uapi_latency_match_en(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

uint16_t plp_aperta2_peregrine5_pc_ex_uapi_latency_match_en(srds_access_t *sa__, uint16_t reg_value) {
    uint16_t ex_val = 0;
    PEREGRINE5_PC_UAPI_EX_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            ex_val = extract_field((reg_value), 15, 15);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_ex_uapi_latency_match_en(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return ex_val;
}

err_code_t plp_aperta2_peregrine5_pc_wr_uapi_turn_off_dfe_4lvl_out_in_er_mode(srds_access_t *sa__, uint8_t wr_val) {
    err_code_t failcode = ERR_CODE_NONE;
    PEREGRINE5_PC_UAPI_WR_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            failcode = plp_aperta2_peregrine5_pc_acc_mwr_reg_u8(sa__, 0x4102, 0x0020, 5, wr_val);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_wr_uapi_turn_off_dfe_4lvl_out_in_er_mode(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
            failcode = ERR_CODE_INVALID_UAPI_CASE;
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return failcode;
}

uint8_t plp_aperta2_peregrine5_pc_rd_uapi_turn_off_dfe_4lvl_out_in_er_mode(srds_access_t *sa__, err_code_t *err_code_p) {
    uint8_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0x4102, 10, 15, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_rd_uapi_turn_off_dfe_4lvl_out_in_er_mode(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

uint16_t plp_aperta2_peregrine5_pc_ex_uapi_turn_off_dfe_4lvl_out_in_er_mode(srds_access_t *sa__, uint16_t reg_value) {
    uint16_t ex_val = 0;
    PEREGRINE5_PC_UAPI_EX_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            ex_val = extract_field((reg_value), 5, 5);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_ex_uapi_turn_off_dfe_4lvl_out_in_er_mode(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return ex_val;
}

err_code_t plp_aperta2_peregrine5_pc_wr_uapi_dig_lpbk_en_HL_intr_en(srds_access_t *sa__, uint8_t wr_val) {
    err_code_t failcode = ERR_CODE_NONE;
    PEREGRINE5_PC_UAPI_WR_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            failcode = plp_aperta2_peregrine5_pc_acc_mwr_reg_u8(sa__, 0x6002, 0x4000, 14, wr_val);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_wr_uapi_dig_lpbk_en_HL_intr_en(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
            failcode = ERR_CODE_INVALID_UAPI_CASE;
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return failcode;
}

uint8_t plp_aperta2_peregrine5_pc_rd_uapi_dig_lpbk_en_HL_intr_en(srds_access_t *sa__, err_code_t *err_code_p) {
    uint8_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0x6002, 1, 15, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_rd_uapi_dig_lpbk_en_HL_intr_en(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

uint16_t plp_aperta2_peregrine5_pc_ex_uapi_dig_lpbk_en_HL_intr_en(srds_access_t *sa__, uint16_t reg_value) {
    uint16_t ex_val = 0;
    PEREGRINE5_PC_UAPI_EX_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            ex_val = extract_field((reg_value), 14, 14);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_ex_uapi_dig_lpbk_en_HL_intr_en(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return ex_val;
}

err_code_t plp_aperta2_peregrine5_pc_wr_uapi_dig_lpbk_en_LH_intr_en(srds_access_t *sa__, uint8_t wr_val) {
    err_code_t failcode = ERR_CODE_NONE;
    PEREGRINE5_PC_UAPI_WR_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            failcode = plp_aperta2_peregrine5_pc_acc_mwr_reg_u8(sa__, 0x6002, 0x2000, 13, wr_val);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_wr_uapi_dig_lpbk_en_LH_intr_en(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
            failcode = ERR_CODE_INVALID_UAPI_CASE;
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return failcode;
}

uint8_t plp_aperta2_peregrine5_pc_rd_uapi_dig_lpbk_en_LH_intr_en(srds_access_t *sa__, err_code_t *err_code_p) {
    uint8_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0x6002, 2, 15, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_rd_uapi_dig_lpbk_en_LH_intr_en(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

uint16_t plp_aperta2_peregrine5_pc_ex_uapi_dig_lpbk_en_LH_intr_en(srds_access_t *sa__, uint16_t reg_value) {
    uint16_t ex_val = 0;
    PEREGRINE5_PC_UAPI_EX_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            ex_val = extract_field((reg_value), 13, 13);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_ex_uapi_dig_lpbk_en_LH_intr_en(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return ex_val;
}

uint8_t plp_aperta2_peregrine5_pc_rd_uapi_dig_lpbk_en_HL(srds_access_t *sa__, err_code_t *err_code_p) {
    uint8_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0x6064, 14, 15, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_rd_uapi_dig_lpbk_en_HL(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

uint16_t plp_aperta2_peregrine5_pc_ex_uapi_dig_lpbk_en_HL(srds_access_t *sa__, uint16_t reg_value) {
    uint16_t ex_val = 0;
    PEREGRINE5_PC_UAPI_EX_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            ex_val = extract_field((reg_value), 1, 1);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_ex_uapi_dig_lpbk_en_HL(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return ex_val;
}

uint8_t plp_aperta2_peregrine5_pc_rd_uapi_dig_lpbk_en_LH(srds_access_t *sa__, err_code_t *err_code_p) {
    uint8_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_field_u8(sa__, 0x6064, 15, 15, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_rd_uapi_dig_lpbk_en_LH(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

uint16_t plp_aperta2_peregrine5_pc_ex_uapi_dig_lpbk_en_LH(srds_access_t *sa__, uint16_t reg_value) {
    uint16_t ex_val = 0;
    PEREGRINE5_PC_UAPI_EX_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            ex_val = extract_field((reg_value), 0, 0);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_ex_uapi_dig_lpbk_en_LH(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return ex_val;
}

err_code_t plp_aperta2_peregrine5_pc_reg_wr_uapi_MICRO_C_COM_RMI_UPIN_EXT_ECC_UNCORR_INTR_CONTROL(srds_access_t *sa__, uint16_t wr_val) {
    err_code_t failcode = ERR_CODE_NONE;
    PEREGRINE5_PC_UAPI_WR_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE1):
            failcode = plp_aperta2_peregrine5_pc_acc_wr_reg(sa__, 0xda10, wr_val);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            failcode = plp_aperta2_peregrine5_pc_acc_wr_reg(sa__, 0xda10, wr_val);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_reg_wr_uapi_MICRO_C_COM_RMI_UPIN_EXT_ECC_UNCORR_INTR_CONTROL(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
            failcode = ERR_CODE_INVALID_UAPI_CASE;
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return failcode;
}

uint16_t plp_aperta2_peregrine5_pc_reg_rd_uapi_MICRO_C_COM_RMI_UPIN_EXT_ECC_UNCORR_INTR_CONTROL(srds_access_t *sa__, err_code_t *err_code_p) {
    uint16_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE1):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_reg(sa__, 0xda10, err_code_p);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_reg(sa__, 0xda10, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_reg_rd_uapi_MICRO_C_COM_RMI_UPIN_EXT_ECC_UNCORR_INTR_CONTROL(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

err_code_t plp_aperta2_peregrine5_pc_reg_wr_uapi_MICRO_C_COM_RMI_UPIN_EXT_ECC_UNCORR_INTR_STATUS(srds_access_t *sa__, uint16_t wr_val) {
    err_code_t failcode = ERR_CODE_NONE;
    PEREGRINE5_PC_UAPI_WR_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE1):
            failcode = plp_aperta2_peregrine5_pc_acc_wr_reg(sa__, 0xda11, wr_val);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            failcode = plp_aperta2_peregrine5_pc_acc_wr_reg(sa__, 0xda11, wr_val);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_reg_wr_uapi_MICRO_C_COM_RMI_UPIN_EXT_ECC_UNCORR_INTR_STATUS(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
            failcode = ERR_CODE_INVALID_UAPI_CASE;
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return failcode;
}

uint16_t plp_aperta2_peregrine5_pc_reg_rd_uapi_MICRO_C_COM_RMI_UPIN_EXT_ECC_UNCORR_INTR_STATUS(srds_access_t *sa__, err_code_t *err_code_p) {
    uint16_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE1):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_reg(sa__, 0xda11, err_code_p);
            break;
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_reg(sa__, 0xda11, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_reg_rd_uapi_MICRO_C_COM_RMI_UPIN_EXT_ECC_UNCORR_INTR_STATUS(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

err_code_t plp_aperta2_peregrine5_pc_reg_wr_uapi_DSC_G_RX_AUTO_PGA_CTRL_1(srds_access_t *sa__, uint16_t wr_val) {
    err_code_t failcode = ERR_CODE_NONE;
    PEREGRINE5_PC_UAPI_WR_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            failcode = plp_aperta2_peregrine5_pc_acc_wr_reg(sa__, 0x1a0b, wr_val);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_reg_wr_uapi_DSC_G_RX_AUTO_PGA_CTRL_1(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
            failcode = ERR_CODE_INVALID_UAPI_CASE;
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return failcode;
}

uint16_t plp_aperta2_peregrine5_pc_reg_rd_uapi_DSC_G_RX_AUTO_PGA_CTRL_1(srds_access_t *sa__, err_code_t *err_code_p) {
    uint16_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_reg(sa__, 0x1a0b, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_reg_rd_uapi_DSC_G_RX_AUTO_PGA_CTRL_1(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

err_code_t plp_aperta2_peregrine5_pc_reg_wr_uapi_MICRO_E_COM_MICRO_CORE_LN_A_RX_SHARED_IRQ27_INTERRUPT_STATUS0(srds_access_t *sa__, uint16_t wr_val) {
    err_code_t failcode = ERR_CODE_NONE;
    PEREGRINE5_PC_UAPI_WR_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            failcode = plp_aperta2_peregrine5_pc_acc_wr_reg(sa__, 0xdc18, wr_val);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_reg_wr_uapi_MICRO_E_COM_MICRO_CORE_LN_A_RX_SHARED_IRQ27_INTERRUPT_STATUS0(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
            failcode = ERR_CODE_INVALID_UAPI_CASE;
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return failcode;
}

uint16_t plp_aperta2_peregrine5_pc_reg_rd_uapi_MICRO_E_COM_MICRO_CORE_LN_A_RX_SHARED_IRQ27_INTERRUPT_STATUS0(srds_access_t *sa__, err_code_t *err_code_p) {
    uint16_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_reg(sa__, 0xdc18, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_reg_rd_uapi_MICRO_E_COM_MICRO_CORE_LN_A_RX_SHARED_IRQ27_INTERRUPT_STATUS0(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

err_code_t plp_aperta2_peregrine5_pc_reg_wr_uapi_MICRO_E_COM_MICRO_CORE_LN_B_RX_SHARED_IRQ28_INTERRUPT_STATUS0(srds_access_t *sa__, uint16_t wr_val) {
    err_code_t failcode = ERR_CODE_NONE;
    PEREGRINE5_PC_UAPI_WR_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            failcode = plp_aperta2_peregrine5_pc_acc_wr_reg(sa__, 0xdc19, wr_val);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_reg_wr_uapi_MICRO_E_COM_MICRO_CORE_LN_B_RX_SHARED_IRQ28_INTERRUPT_STATUS0(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
            failcode = ERR_CODE_INVALID_UAPI_CASE;
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return failcode;
}

uint16_t plp_aperta2_peregrine5_pc_reg_rd_uapi_MICRO_E_COM_MICRO_CORE_LN_B_RX_SHARED_IRQ28_INTERRUPT_STATUS0(srds_access_t *sa__, err_code_t *err_code_p) {
    uint16_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_reg(sa__, 0xdc19, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_reg_rd_uapi_MICRO_E_COM_MICRO_CORE_LN_B_RX_SHARED_IRQ28_INTERRUPT_STATUS0(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

err_code_t plp_aperta2_peregrine5_pc_reg_wr_uapi_TLB_RX_DIG_LPBK_EN_INTERRUPT_STATUS(srds_access_t *sa__, uint16_t wr_val) {
    err_code_t failcode = ERR_CODE_NONE;
    PEREGRINE5_PC_UAPI_WR_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            failcode = plp_aperta2_peregrine5_pc_acc_wr_reg(sa__, 0x6064, wr_val);
            break;
        default:
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_reg_wr_uapi_TLB_RX_DIG_LPBK_EN_INTERRUPT_STATUS(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
            failcode = ERR_CODE_INVALID_UAPI_CASE;
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return failcode;
}

uint16_t plp_aperta2_peregrine5_pc_reg_rd_uapi_TLB_RX_DIG_LPBK_EN_INTERRUPT_STATUS(srds_access_t *sa__, err_code_t *err_code_p) {
    uint16_t rd_val = 0;
    PEREGRINE5_PC_UAPI_RD_INIT
    switch(PEREGRINE5_PC_UAPI_SWITCH) {
        case(PEREGRINE5_PC_UAPI_CASE2):
            rd_val = plp_aperta2_peregrine5_pc_acc_rde_reg(sa__, 0x6064, err_code_p);
            break;
        default:
            *err_code_p = ERR_CODE_INVALID_UAPI_CASE;
            EFUN_PRINTF(("ERROR: Invalid PEREGRINE5_PC_UAPI_SWITCH value of '%d' for plp_aperta2_peregrine5_pc_reg_rd_uapi_TLB_RX_DIG_LPBK_EN_INTERRUPT_STATUS(..)\n", PEREGRINE5_PC_UAPI_SWITCH)); 
    }
    PEREGRINE5_PC_UAPI_TERMINATE
    return rd_val;
}

