/*************************************************************************************
 *                                                                                   *
 * Copyright: (c) 2021 Broadcom.                                                     *
 * Broadcom Proprietary and Confidential. All rights reserved.                       *
 *                                                                                   *
 *************************************************************************************/

/*************************************************************************************
 *************************************************************************************
 *                                                                                   *
 *  Revision      :  Id                                                              *
 *                                                                                   *
 *  Description   :  const array definition used by  plp_aperta2_peregrine5_pc_reg_dump().              *
 *                   Each row of peregrine5_pc_reg_dump_arr represents a block of 16        *
 *                   addresses. The first value of a row is the starting address of  *
 *                   a register block, and the second value is a valid register      *
 *                   enable bitmap. The bitmap represents which addresses are valid  *
 *                   within the block.                                               *
 *                                                                                   *
 *************************************************************************************
 *************************************************************************************/


/* THIS FILE IS GENERATED USING AN AUTOMATED SCRIPT... PLEASE DO NOT EDIT THIS FILE DIRECTLY !!! */

#include "peregrine5_pc_reg_dump.h"

/*! @file
 *
 */

peregrine5_pc_reg_dump_arr_t *plp_aperta2_peregrine5_pc_get_reg_dump_arr(void) {
    static const uint16_t peregrine5_pc_reg_dump_arr[PEREGRINE5_PC_REG_DUMP_SECTIONS][2] = {
    /* start register block, valid register enable */
    {0x0090, 0x1fc0},
    {0x1000, 0x1f3f},
    {0x1400, 0x6fff},
    {0x1410, 0xffff},
    {0x1420, 0x001f},
    {0x1430, 0x07fd},
    {0x1800, 0x4000},
    {0x1a00, 0x07ff},
    {0x2400, 0x1bff},
    {0x2420, 0xffff},
    {0x2430, 0xffff},
    {0x2440, 0x17ff},
    {0x2460, 0x0f07},
    {0x2470, 0x01ff},
    {0x2490, 0x000f},
    {0x24b0, 0x0003},
    {0x24c0, 0x0007},
    {0x3000, 0xffff},
    {0x3200, 0x007f},
    {0x3300, 0x1f07},
    {0x3400, 0x0031},
    {0x4000, 0xff3f},
    {0x4010, 0xfd00},
    {0x4020, 0x1fff},
    {0x4030, 0xfff3},
    {0x4040, 0x1ff7},
    {0x4050, 0xbfff},
    {0x4060, 0xffff},
    {0x4070, 0x0001},
    {0x4080, 0xc000},
    {0x4090, 0x007f},
    {0x40a0, 0xffff},
    {0x40b0, 0xffff},
    {0x40c0, 0x3fff},
    {0x4100, 0xffff},
    {0x4110, 0xffff},
    {0x4120, 0x0001},
    {0x4130, 0x7fff},
    {0x4140, 0x0f80},
    {0x4150, 0xc3ff},
    {0x4160, 0x0003},
    {0x4200, 0xff3f},
    {0x4210, 0xffff},
    {0x4220, 0x0fff},
    {0x4300, 0xfaff},
    {0x4310, 0x03ff},
    {0x4320, 0xc007},
    {0x4330, 0xffff},
    {0x4340, 0xffff},
    {0x4350, 0x3fff},
    {0x5000, 0xde6b},
    {0x5010, 0x0001},
    {0x5100, 0x71be},
    {0x5200, 0x31be},
    {0x5300, 0xde6b},
    {0x5310, 0x0001},
    {0x5400, 0xde6b},
    {0x5410, 0x0001},
    {0x6000, 0x7fff},
    {0x6010, 0x40e8},
    {0x6020, 0xffff},
    {0x6030, 0x1fff},
    {0x6050, 0x0001},
    {0x6060, 0x001f},
    {0x6300, 0x412f},
    {0x6310, 0x0040},
    {0x6320, 0x7fff},
    {0x6400, 0xefff},
    {0x6410, 0x0003},
    {0x6500, 0xffff},
    {0x6510, 0x0001},
    {0x7000, 0x5f1f},
    {0x7200, 0xcfff},
    {0x7210, 0x4000},
    {0x7600, 0xffff},
    {0x7610, 0x0003},
    {0xd000, 0x03ff},
    {0xd010, 0xffff},
    {0xd020, 0xffff},
    {0xd030, 0xffff},
    {0xd040, 0x0007},
    {0xd100, 0x45df},
    {0xd110, 0xf8ff},
    {0xd300, 0x01ff},
    {0xd500, 0x37ff},
    {0xd800, 0x7fff},
    {0xd900, 0x7fff},
    {0xda00, 0x77ff},
    {0xda10, 0x0003},
    {0xdb00, 0x400f},
    {0xffd0, 0x7000},
    {0xc000, 0xffff},
    {0xc010, 0x001f},
    {0xc200, 0xe39f},
    {0xc300, 0xffff},
    {0xc310, 0x011f},
    {0xdc00, 0xffff},
    {0xdc10, 0x03ff},
    };
    return peregrine5_pc_reg_dump_arr;
}
