/*
 *         
 * $Id: phymod.xml,v 1.1.2.5 Broadcom SDK $
 * 
 * $Copyright: (c) 2020 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *         
 *     
 * DO NOT EDIT THIS FILE!
 *
 */

#ifndef _plp_aperta2_PHYMOD_DIAGNOSTICS_H__H_
#define _plp_aperta2_PHYMOD_DIAGNOSTICS_H__H_

#include <phymod/phymod_definitions.h>
#include <phymod/phymod.h>
typedef struct plp_aperta2_phymod_slicer_position_s {
    uint32_t horizontal;
    uint32_t vertical;
} plp_aperta2_phymod_slicer_position_t;

/* plp_aperta2_phymod_slicer_position_t initialization and validation */
int plp_aperta2_phymod_slicer_position_t_validate(const plp_aperta2_phymod_slicer_position_t* phymod_slicer_position);
int plp_aperta2_phymod_slicer_position_t_init(plp_aperta2_phymod_slicer_position_t* phymod_slicer_position);

/*! 
 * @brief Flags for plp_aperta2_phymod_phy_rx_slicer_position_set/get APIs 
 */ 
#define PHYMOD_SLICER_F_LIVE_LINK 0x1 /**< Use the live-link slicer */

/*! 
 * plp_aperta2_phymod_phy_rx_slicer_position_set
 *
 * @brief Set/get slicer position 
 *
 * @param [in]  phy             - phy access information
 * @param [in]  flags           - 
 * @param [in]  position        - Slicer location to set
 */
int plp_aperta2_phymod_phy_rx_slicer_position_set(const plp_aperta2_phymod_phy_access_t* phy, uint32_t flags, const plp_aperta2_phymod_slicer_position_t* position);
/*! 
 * plp_aperta2_phymod_phy_rx_slicer_position_get
 *
 * @brief Set/get slicer position 
 *
 * @param [in]  phy             - phy access information
 * @param [in]  flags           - 
 * @param [out]  position        - Current slicer position
 */
int plp_aperta2_phymod_phy_rx_slicer_position_get(const plp_aperta2_phymod_phy_access_t* phy, uint32_t flags, plp_aperta2_phymod_slicer_position_t* position);

/*! 
 * plp_aperta2_phymod_phy_rx_slicer_position_max_get
 *
 * @brief Get slicer range limitation 
 *
 * @param [in]  phy             - phy access information
 * @param [in]  flags           - 
 * @param [in]  position_min    - Slicer minimum position
 * @param [in]  position_max    - Slicer maxumum position
 */
int plp_aperta2_phymod_phy_rx_slicer_position_max_get(const plp_aperta2_phymod_phy_access_t* phy, uint32_t flags, const plp_aperta2_phymod_slicer_position_t* position_min, const plp_aperta2_phymod_slicer_position_t* position_max);


/*!
 * @enum plp_aperta2_phymod_prbs_poly_e
 * @brief PRBS polynomial 
 */ 
typedef enum plp_aperta2_phymod_prbs_poly_e {
    phymodPrbsPoly7 = 0,
    phymodPrbsPoly9,
    phymodPrbsPoly11,
    phymodPrbsPoly15,
    phymodPrbsPoly23,
    phymodPrbsPoly31,
    phymodPrbsPoly58,
    phymodPrbsPoly49,
    phymodPrbsPoly10,
    phymodPrbsPoly20,
    phymodPrbsPoly13,
    phymodPrbsPolyQ13,
    phymodPrbsPolyCount
} plp_aperta2_phymod_prbs_poly_t;

#ifdef PHYMOD_DIAG
extern plp_aperta2_enum_mapping_t phymod_prbs_poly_t_mapping[];
#endif /*PHYMOD_DIAGNOSTICS_DIAG*/

/* plp_aperta2_phymod_prbs_poly_t validation */
int plp_aperta2_phymod_prbs_poly_t_validate(plp_aperta2_phymod_prbs_poly_t phymod_prbs_poly);
/*! 
 * @brief RX/TX selector. no flags means both 
 */ 
#define PHYMOD_PRBS_DIRECTION_RX 0x1 /**< Config RX */
#define PHYMOD_PRBS_DIRECTION_TX 0x2 /**< Config TX */

#define PHYMOD_PRBS_DIRECTION_RX_SET(flags) (flags |= PHYMOD_PRBS_DIRECTION_RX)
#define PHYMOD_PRBS_DIRECTION_TX_SET(flags) (flags |= PHYMOD_PRBS_DIRECTION_TX)

#define PHYMOD_PRBS_DIRECTION_RX_CLR(flags) (flags &= ~PHYMOD_PRBS_DIRECTION_RX)
#define PHYMOD_PRBS_DIRECTION_TX_CLR(flags) (flags &= ~PHYMOD_PRBS_DIRECTION_TX)

#define PHYMOD_PRBS_DIRECTION_RX_GET(flags) (flags & PHYMOD_PRBS_DIRECTION_RX ? 1 : 0)
#define PHYMOD_PRBS_DIRECTION_TX_GET(flags) (flags & PHYMOD_PRBS_DIRECTION_TX ? 1 : 0)


/*!
 * @struct plp_aperta2_phymod_prbs_s
 * @brief PRBS control 
 */ 
typedef struct plp_aperta2_phymod_prbs_s {
    plp_aperta2_phymod_prbs_poly_t poly;
    uint32_t invert;
} plp_aperta2_phymod_prbs_t;

/* plp_aperta2_phymod_prbs_t initialization and validation */
int plp_aperta2_phymod_prbs_t_validate(const plp_aperta2_phymod_prbs_t* phymod_prbs);
int plp_aperta2_phymod_prbs_t_init(plp_aperta2_phymod_prbs_t* phymod_prbs);

/*! 
 * plp_aperta2_phymod_phy_prbs_config_set
 *
 * @brief set/get PRBS configuration 
 *
 * @param [in]  phy             - phy access information
 * @param [in]  flags           - see PHYMOD_PRBS_DIRECTION_
 * @param [in]  prbs            - PRBS configuration to set
 */
int plp_aperta2_phymod_phy_prbs_config_set(const plp_aperta2_phymod_phy_access_t* phy, uint32_t flags , const plp_aperta2_phymod_prbs_t* prbs);
/*! 
 * plp_aperta2_phymod_phy_prbs_config_get
 *
 * @brief set/get PRBS configuration 
 *
 * @param [in]  phy             - phy access information
 * @param [in]  flags           - see PHYMOD_PRBS_DIRECTION_
 * @param [out]  prbs            - PRBS configuration
 */
int plp_aperta2_phymod_phy_prbs_config_get(const plp_aperta2_phymod_phy_access_t* phy, uint32_t flags , plp_aperta2_phymod_prbs_t* prbs);

/*! 
 * plp_aperta2_phymod_phy_prbs_enable_set
 *
 * @brief Set/get PRBS enable state 
 *
 * @param [in]  phy             - phy access information
 * @param [in]  flags           - see PHYMOD_PRBS_DIRECTION_
 * @param [in]  enable          - Enable \ disable PRBS
 */
int plp_aperta2_phymod_phy_prbs_enable_set(const plp_aperta2_phymod_phy_access_t* phy, uint32_t flags , uint32_t enable);
/*! 
 * plp_aperta2_phymod_phy_prbs_enable_get
 *
 * @brief Set/get PRBS enable state 
 *
 * @param [in]  phy             - phy access information
 * @param [in]  flags           - see PHYMOD_PRBS_DIRECTION_
 * @param [out]  enable          - PRBS state
 */
int plp_aperta2_phymod_phy_prbs_enable_get(const plp_aperta2_phymod_phy_access_t* phy, uint32_t flags , uint32_t* enable);


/*!
 * @struct plp_aperta2_phymod_prbs_status_s
 * @brief PRBS control 
 */ 
typedef struct plp_aperta2_phymod_prbs_status_s {
    uint32_t prbs_lock; /**< Whether PRBS is currently locked */
    uint32_t prbs_lock_loss; /**< Whether PRBS was unlocked since last call */
    uint32_t error_count; /**< PRBS errors count */
} plp_aperta2_phymod_prbs_status_t;

/* plp_aperta2_phymod_prbs_status_t initialization and validation */
int plp_aperta2_phymod_prbs_status_t_validate(const plp_aperta2_phymod_prbs_status_t* phymod_prbs_status);
int plp_aperta2_phymod_prbs_status_t_init(plp_aperta2_phymod_prbs_status_t* phymod_prbs_status);

/*! 
 * @brief Flags for plp_aperta2_phymod_phy_prbs_status_get API 
 */ 
#define PHYMOD_PRBS_STATUS_F_CLEAR_ON_READ 0x1 /**< Clear error counter on read */

/*! 
 * plp_aperta2_phymod_phy_prbs_status_get
 *
 * @brief Get PRBS Status 
 *
 * @param [in]  phy             - phy access information
 * @param [in]  flags           - 
 * @param [out]  prbs_status     - PRBS status
 */
int plp_aperta2_phymod_phy_prbs_status_get(const plp_aperta2_phymod_phy_access_t* phy, uint32_t flags, plp_aperta2_phymod_prbs_status_t* prbs_status);

typedef struct plp_aperta2_phymod_pattern_s {
    uint32_t pattern_len;
    uint32_t* pattern; /**< Pattern to set */
} plp_aperta2_phymod_pattern_t;

/* plp_aperta2_phymod_pattern_t initialization and validation */
int plp_aperta2_phymod_pattern_t_validate(const plp_aperta2_phymod_pattern_t* phymod_pattern);
int plp_aperta2_phymod_pattern_t_init(plp_aperta2_phymod_pattern_t* phymod_pattern);

/*! 
 * plp_aperta2_phymod_phy_pattern_config_set
 *
 * @brief Set/get pattern state 
 *
 * @param [in]  phy             - phy access information
 * @param [in]  pattern         - Pattern Configuration
 */
int plp_aperta2_phymod_phy_pattern_config_set(const plp_aperta2_phymod_phy_access_t* phy, const plp_aperta2_phymod_pattern_t* pattern);
/*! 
 * plp_aperta2_phymod_phy_pattern_config_get
 *
 * @brief Set/get pattern state 
 *
 * @param [in]  phy             - phy access information
 * @param [inout] pattern         - Pattern Configuration
 */
int plp_aperta2_phymod_phy_pattern_config_get(const plp_aperta2_phymod_phy_access_t* phy, plp_aperta2_phymod_pattern_t* pattern);

/*! 
 * plp_aperta2_phymod_phy_pattern_enable_set
 *
 * @brief Set/get pattern state 
 *
 * @param [in]  phy             - phy access information
 * @param [in]  enable          - Enable \ disable pattern send \ receive
 * @param [in]  pattern         - Pattern Configuration
 */
int plp_aperta2_phymod_phy_pattern_enable_set(const plp_aperta2_phymod_phy_access_t* phy, uint32_t enable, const plp_aperta2_phymod_pattern_t* pattern);
/*! 
 * plp_aperta2_phymod_phy_pattern_enable_get
 *
 * @brief Set/get pattern state 
 *
 * @param [in]  phy             - phy access information
 * @param [out]  enable          - Pattern state
 * @param [in]  pattern         - Pattern Configuration
 */
int plp_aperta2_phymod_phy_pattern_enable_get(const plp_aperta2_phymod_phy_access_t* phy, uint32_t* enable, const plp_aperta2_phymod_pattern_t* pattern);

typedef struct plp_aperta2_phymod_core_diagnostics_s {
    int32_t temperature;
    uint32_t pll_range;
    uint32_t voltage;
} plp_aperta2_phymod_core_diagnostics_t;

/* plp_aperta2_phymod_core_diagnostics_t initialization and validation */
int plp_aperta2_phymod_core_diagnostics_t_validate(const plp_aperta2_phymod_core_diagnostics_t* phymod_core_diagnostics);
int plp_aperta2_phymod_core_diagnostics_t_init(plp_aperta2_phymod_core_diagnostics_t* phymod_core_diagnostics);

/*! 
 * plp_aperta2_phymod_core_diagnostics_get
 *
 * @brief Get core diagnostics information 
 *
 * @param [in]  core            - core access information
 * @param [out]  diag            - Core diagnostics information
 */
int plp_aperta2_phymod_core_diagnostics_get(const plp_aperta2_phymod_core_access_t* core, plp_aperta2_phymod_core_diagnostics_t* diag);

typedef struct plp_aperta2_phymod_diag_slicer_offset_s {
    uint32_t offset_pe;
    uint32_t offset_ze;
    uint32_t offset_me;
    uint32_t offset_po;
    uint32_t offset_zo;
    uint32_t offset_mo;
} plp_aperta2_phymod_diag_slicer_offset_t;

/* plp_aperta2_phymod_diag_slicer_offset_t initialization and validation */
int plp_aperta2_phymod_diag_slicer_offset_t_validate(const plp_aperta2_phymod_diag_slicer_offset_t* phymod_diag_slicer_offset);
int plp_aperta2_phymod_diag_slicer_offset_t_init(plp_aperta2_phymod_diag_slicer_offset_t* phymod_diag_slicer_offset);

typedef struct plp_aperta2_phymod_diag_eyescan_s {
    uint32_t heye_left;
    uint32_t heye_right;
    uint32_t veye_upper;
    uint32_t veye_lower;
} plp_aperta2_phymod_diag_eyescan_t;

/* plp_aperta2_phymod_diag_eyescan_t initialization and validation */
int plp_aperta2_phymod_diag_eyescan_t_validate(const plp_aperta2_phymod_diag_eyescan_t* phymod_diag_eyescan);
int plp_aperta2_phymod_diag_eyescan_t_init(plp_aperta2_phymod_diag_eyescan_t* phymod_diag_eyescan);


/*!
 * @enum plp_aperta2_phymod_pmd_mode_e
 * @brief pmd modes 
 */ 
typedef enum plp_aperta2_phymod_pmd_mode_e {
    phymodPmdModeOs = 0,
    phymodPmdModeOsDfe,
    phymodPmdModeBrDfe,
    phymodPmdModeCount
} plp_aperta2_phymod_pmd_mode_t;

#ifdef PHYMOD_DIAG
extern plp_aperta2_enum_mapping_t phymod_pmd_mode_t_mapping[];
#endif /*PHYMOD_DIAGNOSTICS_DIAG*/

/* plp_aperta2_phymod_pmd_mode_t validation */
int plp_aperta2_phymod_pmd_mode_t_validate(plp_aperta2_phymod_pmd_mode_t phymod_pmd_mode);
typedef struct plp_aperta2_phymod_phy_diagnostics_s {
    uint32_t signal_detect;
    uint32_t vga_bias_reduced;
    uint32_t postc_metric;
    plp_aperta2_phymod_osr_mode_t osr_mode;
    plp_aperta2_phymod_pmd_mode_t pmd_mode;
    uint32_t rx_lock;
    uint32_t rx_ppm;
    uint32_t tx_ppm;
    uint32_t clk90_offset;
    uint32_t clkp1_offset;
    uint32_t p1_lvl;
    uint32_t m1_lvl;
    uint32_t dfe1_dcd;
    uint32_t dfe2_dcd;
    uint32_t slicer_target;
    plp_aperta2_phymod_diag_slicer_offset_t slicer_offset;
    plp_aperta2_phymod_diag_eyescan_t eyescan;
    uint32_t state_machine_status;
    uint32_t link_time;
    int pf_main;
    int pf_hiz;
    int pf_bst;
    int pf_low;
    int pf2_ctrl;
    int vga;
    int dc_offset;
    int p1_lvl_ctrl;
    int dfe1;
    int dfe2;
    int dfe3;
    int dfe4;
    int dfe5;
    int dfe6;
    int txfir_pre;
    int txfir_main;
    int txfir_post1;
    int txfir_post2;
    int txfir_post3;
    int tx_amp_ctrl;
    uint8_t br_pd_en;
    uint32_t state_mfg_diag_inst; /**< Specfic device block */
    int state_mfg_diag_op_type; /**< Operation type */
    int state_mfg_diag_op_cmd; /**< Operation type */
    void* state_mfg_diag_arg; /**< Argument pointer */
    int txfir_pre2;
    int pf3_ctrl;
    int ffe_enable;
    int ffe1;
    int ffe2;
    int8_t lane_reset_state;
    int8_t tx_reset_state;
    int8_t uc_stop_state;
    int8_t ucv_lane_status;
    int8_t tx_pll_select;
    int8_t rx_pll_select;
    int pcs_sync;
    int pcs_blk_lock;
    int pcs_rx_fault;
    int pcs_tx_fault;
    int pmd_rx_fault;
    int pmd_tx_fault;
    int hi_ber;
    int ber_cnt;
    int delay_skew;
} plp_aperta2_phymod_phy_diagnostics_t;

/* plp_aperta2_phymod_phy_diagnostics_t initialization and validation */
int plp_aperta2_phymod_phy_diagnostics_t_validate(const plp_aperta2_phymod_phy_diagnostics_t* phymod_phy_diagnostics);
int plp_aperta2_phymod_phy_diagnostics_t_init(plp_aperta2_phymod_phy_diagnostics_t* phymod_phy_diagnostics);

/*! 
 * plp_aperta2_phymod_phy_diagnostics_get
 *
 * @brief Get phy diagnostics information 
 *
 * @param [in]  phy             - phy access information
 * @param [inout] diag            - diagnostics get data variable
 */
int plp_aperta2_phymod_phy_diagnostics_get(const plp_aperta2_phymod_phy_access_t* phy, plp_aperta2_phymod_phy_diagnostics_t* diag);

typedef struct phymod_phy_pam4_diagnostics_s {
    uint32_t signal_detect;
    uint32_t vga_bias_reduced;
    uint32_t postc_metric;
    plp_aperta2_phymod_osr_mode_t osr_mode;
    plp_aperta2_phymod_pmd_mode_t pmd_mode;
    uint32_t rx_lock;
    uint32_t rx_ppm;
    uint32_t tx_ppm;
    uint32_t clk90_offset;
    uint32_t clkp1_offset;
    uint32_t p1_lvl;
    uint32_t m1_lvl;
    uint32_t dfe1_dcd;
    uint32_t dfe2_dcd;
    uint32_t slicer_target;
    plp_aperta2_phymod_diag_slicer_offset_t slicer_offset;
    plp_aperta2_phymod_diag_eyescan_t eyescan;
    uint32_t state_machine_status;
    uint32_t link_time;
    int pf_main;
    int pf_hiz;
    int pf_bst;
    int pf_low;
    int pf2_ctrl;
    int vga;
    int dc_offset;
    int p1_lvl_ctrl;
    int dfe1;
    int dfe2;
    int dfe3;
    int dfe4;
    int dfe5;
    int dfe6;
    int txfir_pre;
    int txfir_main;
    int txfir_post1;
    int txfir_post2;
    int txfir_post3;
    int tx_amp_ctrl;
    uint8_t br_pd_en;
    uint32_t state_mfg_diag_inst; /**< Specfic device block */
    int state_mfg_diag_op_type; /**< Operation type */
    int state_mfg_diag_op_cmd; /**< Operation type */
    void* state_mfg_diag_arg; /**< Argument pointer */
    int txfir_pre2;
    int pf3_ctrl;
    int ffe_enable;
    int ffe1;
    int ffe2;
    int8_t lane_reset_state;
    int8_t tx_reset_state;
    int8_t uc_stop_state;
    int8_t ucv_lane_status;
    int8_t tx_pll_select;
    int8_t rx_pll_select;
    phymod_plp_float_t rx_ppm_real;
    phymod_plp_float_t tx_ppm_real;
    uint8_t modulation;
    int8_t dc_offset_array[48];
    phymod_plp_float_t snr;
    phymod_plp_float_t slice_historgram;
    phymod_plp_float_t ffe_real[24];
    uint8_t tr_skew[8];
    uint8_t peaking_filter;
    int8_t capture_mem_adc[576];
    int8_t capture_mem_eq[576];
    int16_t tr_phase;
    phymod_plp_float_t dc_offset_real[48];
    int8_t dpga_array[48];
    phymod_plp_float_t dpga_real[48];
    int8_t eye_size;
    int txfir_pre3;
    int fga;
    uint8_t signal_detect_latch;
    uint8_t cdr_lock_status_latch;
    uint32_t laneid;
    uint8_t rx_pam_mode;
    uint8_t CDR;
    char tx_osr_mode_str[16];
    char rx_osr_mode_str[16];
    uint16_t UC_CFG;
    uint16_t UC_STS_EXT;
    uint8_t sig_det_chg;
    uint8_t pmd_lock_chg;
    uint8_t TP0;
    uint8_t TP1;
    uint8_t TP2;
    int ffe_n3;
    int ffe_n2;
    int ffe_n1;
    int ffe_m;
    int ffe_p1;
    int ffe_p2;
    int FLT_M;
    uint16_t FLT_S;
    uint8_t linktrn_en;
    char snr_str[10];
    uint8_t tx_prec_en;
    int EYE_U;
    int EYE_M;
    int EYE_L;
    char ber_str[32];
    uint8_t rx_tuning_done;
    uint8_t enable_6taps;
    uint8_t disable_eye_display;
    uint8_t tx_pam_mode;
    uint8_t tx_disable_status;
    int8_t txfir_nlc_upper_pct;
    int8_t txfir_nlc_lower_pct;
    uint8_t txfir_use_pam4_range;
    uint8_t tx_pmd_dp_invert;
    uint8_t rx_pmd_dp_invert;
    uint8_t rmt_lpbk_en;
    uint8_t dig_lpbk_en;
    uint8_t ilb_en;
    uint8_t tx_pi_en;
    char uc_sts_decoded[512];
    char uc_sts_ext_decoded[512];
} phymod_phy_pam4_diagnostics_t;

/* phymod_phy_pam4_diagnostics_t initialization and validation */
int plp_aperta2_phymod_phy_pam4_diagnostics_t_validate(const phymod_phy_pam4_diagnostics_t* phymod_phy_pam4_diagnostics);
int plp_aperta2_phymod_phy_pam4_diagnostics_t_init(phymod_phy_pam4_diagnostics_t* phymod_phy_pam4_diagnostics);

/*! 
 * plp_aperta2_phymod_phy_pam4_diagnostics_get
 *
 * @brief Get phy PAM4 diagnostics information 
 *
 * @param [in]  phy             - phy access information
 * @param [inout] diag            - 
 */
int plp_aperta2_phymod_phy_pam4_diagnostics_get(const plp_aperta2_phymod_phy_access_t* phy, phymod_phy_pam4_diagnostics_t* diag);

typedef struct phymod_phy_diagnostics_ext_config_s {
    uint32_t diag_ext_type; /**< Extended diagnostics type */
    uint16_t time_ms; /**< Amount of time to delay for BER calculation */
} phymod_phy_diagnostics_ext_config_t;

/* phymod_phy_diagnostics_ext_config_t initialization and validation */
int plp_aperta2_phymod_phy_diagnostics_ext_config_t_validate(const phymod_phy_diagnostics_ext_config_t* phymod_phy_diagnostics_ext_config);
int plp_aperta2_phymod_phy_diagnostics_ext_config_t_init(phymod_phy_diagnostics_ext_config_t* phymod_phy_diagnostics_ext_config);

typedef struct phymod_phy_diagnostics_ext_s {
    char ber_string[32]; /**< BER string */
} phymod_phy_diagnostics_ext_t;

/* phymod_phy_diagnostics_ext_t initialization and validation */
int plp_aperta2_phymod_phy_diagnostics_ext_t_validate(const phymod_phy_diagnostics_ext_t* phymod_phy_diagnostics_ext);
int plp_aperta2_phymod_phy_diagnostics_ext_t_init(phymod_phy_diagnostics_ext_t* phymod_phy_diagnostics_ext);

/*! 
 * plp_aperta2_phymod_phy_pmd_info_dump
 *
 * @brief Get phy diagnostics information 
 *
 * @param [in]  phy             - phy access information
 * @param [in]  type            - 
 */
int plp_aperta2_phymod_phy_pmd_info_dump(const plp_aperta2_phymod_phy_access_t* phy, char* type);

/*! 
 * plp_aperta2_phymod_phy_pcs_info_dump
 *
 * @brief Get phy diagnostics information 
 *
 * @param [in]  phy             - phy access information
 * @param [in]  type            - 
 */
int plp_aperta2_phymod_phy_pcs_info_dump(const plp_aperta2_phymod_phy_access_t* phy, char* type);

typedef struct plp_aperta2_phymod_phy_eyescan_options_s {
    uint32_t linerate_in_khz;
    uint16_t timeout_in_milliseconds;
    int8_t horz_max;
    int8_t horz_min;
    int8_t hstep;
    int8_t vert_max;
    int8_t vert_min;
    int8_t vstep;
    uint8_t ber_proj_scan_mode; /**< For BER projection Controls the direction and polarity of the test. */
    uint8_t ber_proj_timer_cnt; /**< BER proj total measurement time in units of ~1.3 seconds. */
    uint8_t ber_proj_err_cnt; /**< BER proj the error threshold it uses to step to next measurement in units of 16. */
    int8_t mode;
} plp_aperta2_phymod_phy_eyescan_options_t;

/* plp_aperta2_phymod_phy_eyescan_options_t initialization and validation */
int plp_aperta2_phymod_phy_eyescan_options_t_validate(const plp_aperta2_phymod_phy_eyescan_options_t* phymod_phy_eyescan_options);
int plp_aperta2_phymod_phy_eyescan_options_t_init(plp_aperta2_phymod_phy_eyescan_options_t* phymod_phy_eyescan_options);


/*!
 * @enum plp_aperta2_phymod_eyescan_mode_e
 * @brief Eyescan modes 
 */ 
typedef enum plp_aperta2_phymod_eyescan_mode_e {
    phymodEyescanModeFast = 0, /**< Fast eyescan resoultion. */
    phymodEyescanModeLowBER, /**< Allow more aquirate BER resolution. */
    phymodEyescanModeBERProj, /**< Do BER projection. */
    phymodEyescanModeCount
} plp_aperta2_phymod_eyescan_mode_t;

#ifdef PHYMOD_DIAG
extern plp_aperta2_enum_mapping_t phymod_eyescan_mode_t_mapping[];
#endif /*PHYMOD_DIAGNOSTICS_DIAG*/

/* plp_aperta2_phymod_eyescan_mode_t validation */
int plp_aperta2_phymod_eyescan_mode_t_validate(plp_aperta2_phymod_eyescan_mode_t phymod_eyescan_mode);
/*! 
 * @brief Eyescan flags 
 */ 
#define PHYMOD_EYESCAN_F_ENABLE 0x1 /**< Enable eyescan */
#define PHYMOD_EYESCAN_F_PROCESS 0x2 /**< Process eyescan */
#define PHYMOD_EYESCAN_F_DONE 0x4 /**< Eyescan done */
#define PHYMOD_EYESCAN_F_ENABLE_DONT_WAIT 0x8 /**< Don't wait to finish enable operation */

#define PHYMOD_EYESCAN_F_ENABLE_SET(flags) ((flags) |= PHYMOD_EYESCAN_F_ENABLE)
#define PHYMOD_EYESCAN_F_PROCESS_SET(flags) ((flags) |= PHYMOD_EYESCAN_F_PROCESS)
#define PHYMOD_EYESCAN_F_DONE_SET(flags) ((flags) |= PHYMOD_EYESCAN_F_DONE)
#define PHYMOD_EYESCAN_F_ENABLE_DONT_WAIT_SET(flags) ((flags) |= PHYMOD_EYESCAN_F_ENABLE_DONT_WAIT)

#define PHYMOD_EYESCAN_F_ENABLE_CLR(flags) ((flags) &= ~PHYMOD_EYESCAN_F_ENABLE)
#define PHYMOD_EYESCAN_F_PROCESS_CLR(flags) ((flags) &= ~PHYMOD_EYESCAN_F_PROCESS)
#define PHYMOD_EYESCAN_F_DONE_CLR(flags) ((flags) &= ~PHYMOD_EYESCAN_F_DONE)
#define PHYMOD_EYESCAN_F_ENABLE_DONT_WAIT_CLR(flags) ((flags) &= ~PHYMOD_EYESCAN_F_ENABLE_DONT_WAIT)

#define PHYMOD_EYESCAN_F_ENABLE_GET(flags) ((flags) & PHYMOD_EYESCAN_F_ENABLE ? 1 : 0)
#define PHYMOD_EYESCAN_F_PROCESS_GET(flags) ((flags) & PHYMOD_EYESCAN_F_PROCESS ? 1 : 0)
#define PHYMOD_EYESCAN_F_DONE_GET(flags) ((flags) & PHYMOD_EYESCAN_F_DONE ? 1 : 0)
#define PHYMOD_EYESCAN_F_ENABLE_DONT_WAIT_GET(flags) ((flags) & PHYMOD_EYESCAN_F_ENABLE_DONT_WAIT ? 1 : 0)

/*! 
 * plp_aperta2_phymod_phy_eyescan_run
 *
 * @brief Display eyescan information 
 *
 * @param [in]  phy             - phy access information
 * @param [in]  flags           - 
 * @param [in]  mode            - Select eyescan mode
 * @param [in]  eyescan_options   - Eyescan options. Set to NULL for eyescan types without options, or to use defaults.
 */
int plp_aperta2_phymod_phy_eyescan_run(const plp_aperta2_phymod_phy_access_t* phy, uint32_t flags, plp_aperta2_phymod_eyescan_mode_t mode, const plp_aperta2_phymod_phy_eyescan_options_t* eyescan_options);


/*!
 * @enum plp_aperta2_phymod_link_monitor_mode_e
 * @brief Link monitor modes 
 */ 
typedef enum plp_aperta2_phymod_link_monitor_mode_e {
    phymodLinkMonPCS49_1x10G = 0,
    phymodLinkMonPCS82_4x10G,
    phymodLinkMonPCS82_2x25G,
    phymodLinkMonPCS82_4x25G,
    phymodLinkMonFC4,
    phymodLinkMonFC8,
    phymodLinkMonFC16,
    phymodLinkMonFC32,
    phymodLinkMonCount
} plp_aperta2_phymod_link_monitor_mode_t;

#ifdef PHYMOD_DIAG
extern plp_aperta2_enum_mapping_t phymod_link_monitor_mode_t_mapping[];
#endif /*PHYMOD_DIAGNOSTICS_DIAG*/

/* plp_aperta2_phymod_link_monitor_mode_t validation */
int plp_aperta2_phymod_link_monitor_mode_t_validate(plp_aperta2_phymod_link_monitor_mode_t phymod_link_monitor_mode);

/*!
 * @enum phymod_diag_type_e
 * @brief diag types 
 */ 
typedef enum phymod_diag_type_e {
    phymod_diag_GENERAL = 0x00000001, /**< General device wide information.  */
    phymod_diag_TOPOLOGY = 0x00000002, /**< General device wide information.  */
    phymod_diag_LINK  = 0x00000004, /**< General device wide information.  */
    phymod_diag_SPEED = 0x00000008, /**< General device wide information.  */
    phymod_diag_ANEG = 0x00000010, /**< General device wide information.  */
    phymod_diag_TFC = 0x00000020, /**< General device wide information.  */
    phymod_diag_AN_TIMERS = 0x00000040, /**< General device wide information.  */
    phymod_diag_STATE = 0x00000080, /**< General device wide information.  */
    phymod_diag_DEBUG = 0x00000100, /**< General device wide information.  */
    phymod_diag_IEEE = 0x00000200, /**< General device wide information.  */
    phymod_diag_EEE = 0x00000400, /**< General device wide information.  */
    phymod_diag_BER = 0x00000800, /**< General device wide information.  */
    phymod_diag_CFG = 0x00001000, /**< General device wide information.  */
    phymod_diag_CL72 = 0x00002000, /**< General device wide information.  */
    phymod_diag_DSC = 0x00004000, /**< General device wide information.  */
    phymod_diag_DSC_STD = 0x00008000, /**< General device wide information.  */
    phymod_diag_ALL = 0x00010000, /**< General device wide information.  */
    phymod_diag_STATE_EYE = 0x00020000, /**< General device wide information.  */
    phymod_diag_Count
} phymod_diag_type_t;

#ifdef PHYMOD_DIAG
extern plp_aperta2_enum_mapping_t phymod_diag_type_t_mapping[];
#endif /*PHYMOD_DIAGNOSTICS_DIAG*/

/* phymod_diag_type_t validation */
int plp_aperta2_phymod_diag_type_t_validate(phymod_diag_type_t phymod_diag_type);
/*! 
 * plp_aperta2_phymod_phy_link_mon_enable_set
 *
 * @brief Get/Set link monitor enable/disable 
 *
 * @param [in]  phy             - phy access information
 * @param [in]  link_mon_mode   - 
 * @param [in]  enable          - 
 */
int plp_aperta2_phymod_phy_link_mon_enable_set(const plp_aperta2_phymod_phy_access_t* phy, plp_aperta2_phymod_link_monitor_mode_t link_mon_mode, uint32_t enable);
/*! 
 * plp_aperta2_phymod_phy_link_mon_enable_get
 *
 * @brief Get/Set link monitor enable/disable 
 *
 * @param [in]  phy             - phy access information
 * @param [in]  link_mon_mode   - 
 * @param [out]  enable          - 
 */
int plp_aperta2_phymod_phy_link_mon_enable_get(const plp_aperta2_phymod_phy_access_t* phy, plp_aperta2_phymod_link_monitor_mode_t link_mon_mode, uint32_t* enable);

/*! 
 * plp_aperta2_phymod_phy_link_mon_status_get
 *
 * @brief Get link monitor Status 
 *
 * @param [in]  phy             - phy access information
 * @param [out]  lock_status     - link mon status
 * @param [out]  lock_lost_lh    - Whether link mon was unlocked since last call
 * @param [out]  error_count     - link mon error count
 */
int plp_aperta2_phymod_phy_link_mon_status_get(const plp_aperta2_phymod_phy_access_t* phy, uint32_t* lock_status, uint32_t* lock_lost_lh, uint32_t* error_count);

/*! 
 * plp_aperta2_phymod_phy_fec_correctable_counter_get
 *
 * @brief Get FEC Corrected Codeword Counter 
 *
 * @param [in]  phy             - phy access information
 * @param [in]  fec_type        - fec type
 * @param [out]  count           - FEC corrected codeword counter
 */
int plp_aperta2_phymod_phy_fec_correctable_counter_get(const plp_aperta2_phymod_phy_access_t* phy, phymod_fec_type_t fec_type, uint32_t* count);

/*! 
 * plp_aperta2_phymod_phy_fec_uncorrectable_counter_get
 *
 * @brief Get FEC Uncorrected Codeword Counter 
 *
 * @param [in]  phy             - phy access information
 * @param [in]  fec_type        - fec type
 * @param [out]  count           - FEC uncorrected codeword counter
 */
int plp_aperta2_phymod_phy_fec_uncorrectable_counter_get(const plp_aperta2_phymod_phy_access_t* phy, phymod_fec_type_t fec_type, uint32_t* count);

typedef struct phymod_prbs_error_inject_s {
    uint32_t no_of_error_bits;
} phymod_prbs_error_inject_t;

/* phymod_prbs_error_inject_t initialization and validation */
int plp_aperta2_phymod_prbs_error_inject_t_validate(const phymod_prbs_error_inject_t* phymod_prbs_error_inject);
int plp_aperta2_phymod_prbs_error_inject_t_init(phymod_prbs_error_inject_t* phymod_prbs_error_inject);

/*! 
 * plp_aperta2_phymod_phy_prbs_error_inject_set
 *
 * @brief Set prbs error inject 
 *
 * @param [in]  phy             - phy access information
 * @param [in]  prbs_error_inject   - prbs error inject
 */
int plp_aperta2_phymod_phy_prbs_error_inject_set(const plp_aperta2_phymod_phy_access_t* phy, phymod_prbs_error_inject_t prbs_error_inject);

/*! 
 * plp_aperta2_phymod_phy_prbs_error_analyzer_proj
 *
 * @brief Display PRBS Error Analyzer Projection 
 *
 * @param [in]  phy             - phy access information
 * @param [in]  prbs_error_fec_size   - Size of FEC frames in bits
 * @param [in]  hist_errcnt_thresh   - Histogram Error Threshold (range [3-8])
 * @param [in]  timeout_s       - Time (in seconds) for which the PRBS errors are accumulated
 */
int plp_aperta2_phymod_phy_prbs_error_analyzer_proj(const plp_aperta2_phymod_phy_access_t* phy, uint16_t prbs_error_fec_size, uint8_t hist_errcnt_thresh, uint32_t timeout_s);

#endif /*_PHYMOD_DIAGNOSTICS_H_*/
