# Agera3 PAI Library Package - URL-based download similar to broncos
LIBSAI_AGERA3_VERSION = 4.1
LIBSAI_AGERA3_BRANCH_NAME = REL_4.1

LIBSAI_AGERA3_URL_PREFIX = "$(BUILD_PUBLIC_URL)/sai/bcmpai/$(LIBSAI_AGERA3_BRANCH_NAME)/$(LIBSAI_AGERA3_VERSION)"

# Runtime package`
LIBSAI_AGERA3 = libsaiagera3_$(LIBSAI_AGERA3_VERSION)_amd64.deb
$(LIBSAI_AGERA3)_URL = "$(LIBSAI_AGERA3_URL_PREFIX)/$(LIBSAI_AGERA3)"

ifneq ($($(LIBSAI_AGERA3)_URL),)

DOCKER_GBSYNCD_AGERA3_STEM = docker-gbsyncd-agera3
DOCKER_GBSYNCD_AGERA3 = $(DOCKER_GBSYNCD_AGERA3_STEM).gz
DOCKER_GBSYNCD_AGERA3_DBG = $(DOCKER_GBSYNCD_AGERA3_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_GBSYNCD_AGERA3)_FILES += $(DSSERVE)

$(DOCKER_GBSYNCD_AGERA3)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_TRIXIE)

$(DOCKER_GBSYNCD_AGERA3)_DBG_DEPENDS += $($(DOCKER_CONFIG_ENGINE_TRIXIE)_DBG_DEPENDS)

$(DOCKER_GBSYNCD_AGERA3)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_TRIXIE)_DBG_IMAGE_PACKAGES)

SONIC_DOCKER_IMAGES += $(DOCKER_GBSYNCD_AGERA3)
SONIC_TRIXIE_DOCKERS += $(DOCKER_GBSYNCD_AGERA3)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_GBSYNCD_AGERA3)

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_GBSYNCD_AGERA3_DBG)
SONIC_TRIXIE_DBG_DOCKERS += $(DOCKER_GBSYNCD_AGERA3_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_GBSYNCD_AGERA3_DBG)

$(DOCKER_GBSYNCD_AGERA3)_CONTAINER_NAME = gbsyncd
$(DOCKER_GBSYNCD_AGERA3)_RUN_OPT += --cap-add=SYS_RAWIO --cap-add=SYS_ADMIN --cap-add=NET_ADMIN -t --security-opt apparmor=unconfined --security-opt="systempaths=unconfined"
$(DOCKER_GBSYNCD_AGERA3)_RUN_OPT += -v /sys/class/mdio_bus:/sys/class/mdio_bus
$(DOCKER_GBSYNCD_AGERA3)_RUN_OPT += -v /sys/devices:/sys/devices
$(DOCKER_GBSYNCD_AGERA3)_RUN_OPT += -v /host/machine.conf:/etc/machine.conf
$(DOCKER_GBSYNCD_AGERA3)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_GBSYNCD_AGERA3)_RUN_OPT += -v /host/warmboot:/var/warmboot

# Add runtime package to online debs
SONIC_ONLINE_DEBS += $(LIBSAI_AGERA3)

$(DOCKER_GBSYNCD_AGERA3)_VERSION = 1.0.0
$(DOCKER_GBSYNCD_AGERA3)_PACKAGE_NAME = gbsyncd-agera3
$(DOCKER_GBSYNCD_AGERA3)_PATH = $(PLATFORM_PATH)/../components/docker-gbsyncd-agera3
$(DOCKER_GBSYNCD_AGERA3)_DEPENDS += $(SYNCD) $(LIBSAI_AGERA3) $(SSWSYNCD)

endif
