LIBSAI_BRFN_APRT_VERSION = 1.0
LIBSAI_BRFN_APRT_PATH_PREFIX = "src/sonic-celestica/bcm-brfn-aprt-sdk"
LIBSAI_BRFN_APRT = libsaibrfnaprt_$(LIBSAI_BRFN_APRT_VERSION)+deb12u1_amd64.deb
$(LIBSAI_BRFN_APRT)_PATH = "$(LIBSAI_BRFN_APRT_PATH_PREFIX)/$(LIBSAI_BRFN_APRT_VERSION)"

ifneq ($($(LIBSAI_BRFN_APRT)_PATH),)

DOCKER_GBSYNCD_BRFN_APRT_STEM = docker-gbsyncd-brfn-aprt
DOCKER_GBSYNCD_BRFN_APRT = $(DOCKER_GBSYNCD_BRFN_APRT_STEM).gz
DOCKER_GBSYNCD_BRFN_APRT_DBG = $(DOCKER_GBSYNCD_BRFN_APRT_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_GBSYNCD_BRFN_APRT)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)

$(DOCKER_GBSYNCD_BRFN_APRT)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_TRIXIE)

$(DOCKER_GBSYNCD_BRFN_APRT)_DBG_DEPENDS += $($(DOCKER_CONFIG_ENGINE_TRIXIE)_DBG_DEPENDS)

$(DOCKER_GBSYNCD_BRFN_APRT)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_TRIXIE)_DBG_IMAGE_PACKAGES)

SONIC_DOCKER_IMAGES += $(DOCKER_GBSYNCD_BRFN_APRT)
SONIC_TRIXIE_DOCKERS += $(DOCKER_GBSYNCD_BRFN_APRT)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_GBSYNCD_BRFN_APRT)

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_GBSYNCD_BRFN_APRT_DBG)
SONIC_TRIXIE_DBG_DOCKERS += $(DOCKER_GBSYNCD_BRFN_APRT_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_GBSYNCD_BRFN_APRT_DBG)

$(DOCKER_GBSYNCD_BRFN_APRT)_CONTAINER_NAME = gbsyncd
$(DOCKER_GBSYNCD_BRFN_APRT)_RUN_OPT += --privileged -t
$(DOCKER_GBSYNCD_BRFN_APRT)_RUN_OPT += -v /host/machine.conf:/etc/machine.conf
$(DOCKER_GBSYNCD_BRFN_APRT)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_GBSYNCD_BRFN_APRT)_RUN_OPT += -v /host/warmboot:/var/warmboot

SONIC_COPY_DEBS += $(LIBSAI_BRFN_APRT)

$(DOCKER_GBSYNCD_BRFN_APRT)_VERSION = 1.0.0
$(DOCKER_GBSYNCD_BRFN_APRT)_PACKAGE_NAME = gbsyncd-brfn-aprt
$(DOCKER_GBSYNCD_BRFN_APRT)_PATH = $(PLATFORM_PATH)/../components/docker-gbsyncd-brfn-aprt
$(DOCKER_GBSYNCD_BRFN_APRT)_DEPENDS += $(SYNCD) $(LIBSAI_BRFN_APRT) $(LIBSAICLS)
endif
