# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

variables:
  GIT_CLEAN_FLAGS: "-ffxd -e fsroot"
  #CI_DEBUG_TRACE: "true"
  HOME: "${CI_PROJECT_DIR}"
  SONIC_CONFIG_MAKE_JOBS: 16
  NOJESSIE: 1
  NOSTRETCH: 1
  BUILD_NUMBER: "${CI_PIPELINE_ID}-${CI_COMMIT_BRANCH}"
  PLUTO_PARENT_BRANCH: master
  PLUTO_BRANCH_DIR: files/sonic/build/${CI_COMMIT_BRANCH}
  PLUTO_COMMIT_DIR: files/sonic/build/${CI_COMMIT_BRANCH}/${CI_PIPELINE_ID}
  PLUTO_POSTED_LATEST: files/sonic/build/${PLUTO_PARENT_BRANCH}/latest
  DOCKER_EXTRA_OPTS: '--registry-mirror=https://docker-registry-remote.artifactory-fpark1.int.net.nokia.com'

before_script: |
  sudo rm -fr fsroot
  rm -f .gitconfig && touch $HOME/.gitconfig
  git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlabsr.nuq.ion.nokia.net/".insteadOf "git@gitlabsr.nuq.ion.nokia.net:"
  # commit title with things in brackets e.g. "[skip build] some change" will create variables, e.g. skip_build=1
  touch .ci-env
  echo $CI_COMMIT_TITLE | sed 's,[ -/:],_,g' | awk -v FS='(\\[|\\])' '{if($2!="")print $2"=1"}' > .ci-env
  ./.gitlab-ci-submodule-init.sh
  # always use latest of these submodules
  pushd altos && git fetch && git reset --hard origin/master && popd
  pushd src/sonic-mgmt && git fetch && git reset --hard origin/nokia-dev && popd

stages:
  - configure
  - build
  - test
  - post
  - deploy

configure:sonic:
  # one configure step to build all docker images used by subsequent build stage(s).
  # This is required to avoid conflicting docker image creation between 
  # build:broadcom and build:docker-syncd-brcm-rpc
  stage: configure
  parallel:
    matrix:
    - BUILD_ARCH: x86_64
    - BUILD_ARCH: armhf
    - BUILD_ARCH: aarch64
  tags:
    - ${BUILD_ARCH}
  script: |
    ./.gitlab-ci-submodule-init.sh
    . .ci-env
    ./build.sh

# Build with option to display build time for each component and sorted list of longest build times
build:sonic:
  stage: build
  parallel:
    matrix:
    - BUILD_ARCH: x86_64
    - BUILD_ARCH: armhf
    - BUILD_ARCH: aarch64
  tags:
    - ${BUILD_ARCH}
  needs:
    - configure:sonic
  script: |
    ./.gitlab-ci-submodule-init.sh
    . .ci-env
    ./build.sh
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - target/sonic-*.bin
    expire_in: 1 week

express:hw:ixre:
  stage: test
  tags:
    - regress_chassis7
  needs:
    - build:sonic
  rules:
    - if: $EXPRESS_HW == "true"
    - if: $BUILD_ARCH == "x86_64"
  script: |
    docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    echo "runner=${CI_RUNNER_DESCRIPTION} tags=\"${CI_RUNNER_TAGS}\" commit=${CI_COMMIT_SHORT_SHA}"
    ./run_test.sh -i target/sonic-broadcom-dnx.bin \
      -g https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlabsr.nuq.ion.nokia.net \
      -r ${CI_RUNNER_DESCRIPTION} --upgrade --configure --test --no_cleanup
  allow_failure: true
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    when: always
    paths:
      - output_files/
    expire_in: 1 month

.post:
  stage: post
  tags:
    - post
  script: |
    . .ci-env
    # with all express passed, we post images and update the symlink latest
    mkdir -p /var/www/html/${PLUTO_COMMIT_DIR}
    for f in `ls target/sonic-*.bin` ; do \
      cp -a --no-preserve=mode $f /var/www/html/${PLUTO_COMMIT_DIR}/ ; done
    echo "sonic_commitid=${CI_COMMIT_SHORT_SHA}" > /var/www/html/${PLUTO_COMMIT_DIR}/build-info.txt
    # make latest link and remove anything older than a week
    cd /var/www/html/${PLUTO_BRANCH_DIR} && \
      rm -f latest && ln -sf ${CI_PIPELINE_ID} latest && \
      find . -maxdepth 1 -type d -ctime +7 -exec rm -fr {} \+

post:sonic:
  extends: .post
  needs:
    - build:sonic

