############################################################
# mapping "gitlab-runner instance" to "physical setup"
# There are dedicated runners that have "limit=1".  One for
# each instance of a hw express setup.  Each runner will accept
# only 1 job at a time, thus providing mux.
# See also, sonic-mgmt/ansible/westford_hw_inventory
############################################################

sonic_tb15_regress_chassis8=ixre-chassis8
sonic_tb9_regress_chassis7=ixre-chassis7
sonic_tb11_regress_chassis10=ixre-chassis10
sonic_tb14_regress_chassis11=ixre-chassis11
sonic_tb12_regress_chassis9=ixre-chassis9
sonic_tb4_regress_chassis12=ixre-chassis12
sonic_regress_tb29=ixre-chassis19
sonic_regress_tb3=ixs-7215-pizza-GA-2
sonic_regress_tb7=ixs-7215-pizza-GA-1
sonic_regress_tb13=emerald
sonic_regress_tb20=amber
sonic_regress_tb21=ixs-7215-pizza-GA-4
sonic_regress_tb23=ixs-7215-discovery
sonic_regress_tb24=ixr-7220-h4-32d-12
sonic_regress_tb25=ixs-7215-pizza-GA-3
sonic_regress_tb26=ixs-7215-a1-76r4
sonic_regress_tb28=ixs-7215-a1-75r4
sonic_regress_tb39=ixre-chassis20
sonic_regress_tb44=ixr-7220-h4-64-1
sonic_regress_tb45=ixs-7215-pizza-GA-5

