############################################################
# mapping "gitlab-runner instance" to "physical setup"
# There are dedicated runners that have "limit=1".  One for
# each instance of a hw express setup.  Each runner will accept
# only 1 job at a time, thus providing mux.
# See also, sonic-mgmt/ansible/westford_hw_inventory
############################################################

##############################
# build machine wf 1 (sonic-pluto)
hw_express_runner_wf_1=ixr-7215-pizza3
hw_express_runner_wf_3=ixr-hr-chassis1
sonic_pluto_vdk=ixr-vdk-chassis3
sonic_tb12_vc_oc_regress=ixr-vdk-chassis4
sonic_tb10_eagle_express=ixre-chassis8
sonic_tb9_regress_chassis7=ixre-chassis7
sonic_tb15_regress_chassis10=ixre-chassis10
sonic_tb14_regress_chassis11=ixre-chassis11
sonic_tb12_regress_chassis9=ixre-chassis9
