# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

variables:
  GIT_CLEAN_FLAGS: "-ffxd -e fsroot"
  #CI_DEBUG_TRACE: "true"
  HOME: "${CI_PROJECT_DIR}"
  SONIC_CONFIG_MAKE_JOBS: 16
  NOJESSIE: 1
  NOSTRETCH: 1
  BUILD_NUMBER: "${CI_PIPELINE_ID}-${CI_COMMIT_BRANCH}"
  REGRESS_SONIC_MGMT_BRANCH: nokia-dev
  REGRESS_TOPO: t2
  PLUTO_PARENT_BRANCH: nokia-master
  PLUTO_BRANCH_DIR: files/sonic/build/${CI_COMMIT_BRANCH}
  PLUTO_COMMIT_DIR: files/sonic/build/${CI_COMMIT_BRANCH}/${CI_PIPELINE_ID}
  PLUTO_POSTED_LATEST: files/sonic/build/${PLUTO_PARENT_BRANCH}/latest
  DOCKER_EXTRA_OPTS: '--registry-mirror=https://docker-registry-remote.artifactory-fpark1.int.net.nokia.com'
  LEAN: "false" # set true to stub out most jobs, useful for debugging this file

.global_script:
  git_config: |
    sudo rm -fr fsroot
    rm -f .gitconfig && touch $HOME/.gitconfig
    git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlabsr.nuq.ion.nokia.net/".insteadOf "git@gitlabsr.nuq.ion.nokia.net:"
    touch .ci-env
    echo $CI_COMMIT_TITLE | sed 's,[ -/:],_,g' | awk -v FS='(\\[|\\])' '{if($2!="")print $2"=1"}' > .ci-env
    ./.gitlab-ci-submodule-init.sh
    pushd altos && git fetch && git reset --hard origin/master && popd
    echo "PLUTO_POSTED_LATEST: ${PLUTO_POSTED_LATEST}"

stages:
  - configure
  - build
  - test
  - post

.configure:sonic:
  # one configure step to build all docker images used by subsequent build stage(s).
  # This is required to avoid conflicting docker image creation between 
  # build:broadcom and build:docker-syncd-brcm-rpc
  stage: configure
  only:
    - branches
  tags:
    - ${BUILD_ARCH}
  before_script:
    - !reference [.global_script, git_config]
  script: |
    ./.gitlab-ci-submodule-init.sh
    . .ci-env
    case "$LEAN" in true) echo LEAN ; exit 0 ; esac
    if [ "$skip_build" = "1" ] && [ -z "${NO_SKIP_BUILD}" ]; then
      exit 0
    fi
    ./build.sh

configure:sonic:x86_64:
  extends: .configure:sonic
  variables:
    BUILD_ARCH: x86_64

configure:sonic:armhf:
  extends: .configure:sonic
  variables:
    BUILD_ARCH: armhf

configure:sonic:aarch64:
  extends: .configure:sonic
  variables:
    BUILD_ARCH: aarch64

.build:sonic:
  stage: build
  only:
    - branches
  tags:
    - ${BUILD_ARCH}
  before_script:
    - !reference [.global_script, git_config]
  script: |
    ./.gitlab-ci-submodule-init.sh
    . .ci-env
    case "$LEAN" in true) echo LEAN ; exit 0 ; esac
     # schedules can set NO_SKIP_BUILD to force a build to happen
    if [ "$skip_build" = "1" ] && [ -z "${NO_SKIP_BUILD}" ]; then
      # skip build and use the latest
      mkdir -p target
      for f in ${TARGET_BIN}; do
        curl -o target/$f http://sonic-pluto.wfr.ion.nokia.net/${PLUTO_POSTED_LATEST}/$f
      done
      exit 0
    fi
    ./build.sh ${BUILD_SH_OPTIONS}
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - target/sonic-*.bin
    expire_in: 1 week

build:sonic-gbsyncd:x86_64:
  extends: .build:sonic
  needs:
    - configure:sonic:x86_64
  before_script:
    - !reference [.global_script, git_config]
    - sed -i 's,^$(LIBSAI_MILLENIOB)_URL =,$(LIBSAI_MILLENIOB)_URL ="http://sonic-pluto.wfr.ion.nokia.net/files/sonic/build/pai/pai-3.14/1003120/libsaimilleniob_$(LIBSAI_MILLENIOB_VERSION)~13_amd64.deb",'  platform/components/docker-gbsyncd-milleniob.mk
  variables:
    BUILD_ARCH: x86_64
    TARGET_BIN: sonic-broadcom.bin sonic-broadcom-dnx.bin
  after_script:
    - mv target/sonic-broadcom.bin target/sonic-broadcom-gbsyncd.bin
    - mv target/sonic-broadcom-dnx.bin target/sonic-broadcom-dnx-gbsyncd.bin

build:sonic:x86_64:
  extends: .build:sonic
  needs:
    - configure:sonic:x86_64
  variables: 
    BUILD_ARCH: x86_64
    TARGET_BIN: sonic-broadcom.bin sonic-broadcom-dnx.bin

build:sonic:armhf:
  extends: .build:sonic
  needs:
    - configure:sonic:armhf
  variables:
    BUILD_ARCH: armhf
    TARGET_BIN: sonic-marvell-armhf.bin

build:sonic:aarch64:
  extends: .build:sonic
  needs:
    - configure:sonic:aarch64
  variables:
    BUILD_ARCH: aarch64
    TARGET_BIN: sonic-marvell-arm64.bin

build:sonic:features:x86_64:
  extends: .build:sonic
  when: manual
  needs:
    - configure:sonic:x86_64
  variables:
    BUILD_ARCH: x86_64
    TARGET_BIN: sonic-broadcom.bin
    BUILD_SH_OPTIONS: " --features"
  after_script:
    - mv target/sonic-broadcom.bin target/sonic-broadcom-features.bin

build:sonic:features:aarch64:
  extends: .build:sonic
  when: manual
  needs:
    - configure:sonic:aarch64
  variables:
    BUILD_ARCH: aarch64
    TARGET_BIN: sonic-marvell-arm64.bin
    BUILD_SH_OPTIONS: " --features"
  after_script:
    - mv target/sonic-marvell-arm64.bin target/sonic-marvell-arm64-features.bin

.build:brcm-rpc:
  stage: build
  only:
    - branches
  tags:
    - ${BUILD_ARCH}
  before_script:
    - !reference [.global_script, git_config]
  script: |
    ./.gitlab-ci-submodule-init.sh
    . .ci-env
    case "$LEAN" in true) echo LEAN ; exit 0 ; esac
    if [ "$skip_build" = "1" ] && [ -z "${NO_SKIP_BUILD}" ]; then
      # skip build and use the latest
      mkdir -p target
      curl -o target/${TARGET_BIN} http://sonic-pluto.wfr.ion.nokia.net/${PLUTO_POSTED_LATEST}/${TARGET_BIN}
    else
      ./build.sh --rpc-${TARGET_SAI}
    fi
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - target/${TARGET_BIN}
    expire_in: 1 week

build:brcm-rpc:x86_64:
  extends: .build:brcm-rpc
  needs:
    - configure:sonic:x86_64
  variables:
    BUILD_ARCH: x86_64
    TARGET_BIN: docker-syncd-brcm-rpc.gz
    TARGET_SAI: xgs

build:brcm-rpc-dnx:x86_64:
  extends: .build:brcm-rpc
  needs:
    - configure:sonic:x86_64
  variables:
    BUILD_ARCH: x86_64
    TARGET_BIN: docker-syncd-brcm-dnx-rpc.gz
    TARGET_SAI: dnx

express:chassis7:
  stage: test
  only:
    - branches
  tags:
    - regress_chassis7
  needs:
    - build:sonic:x86_64
  when: manual
  before_script:
    - !reference [.global_script, git_config]
  script: |
    docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    echo "runner=${CI_RUNNER_DESCRIPTION} tags=\"${CI_RUNNER_TAGS}\" commit=${CI_COMMIT_SHORT_SHA}"
    case "$LEAN" in true) echo LEAN ; exit 0 ; esac
    pushd src/sonic-mgmt && git fetch && git reset --hard origin/${REGRESS_SONIC_MGMT_BRANCH} && popd
    ./run_test.sh -i target/sonic-broadcom-dnx.bin \
      -g https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlabsr.nuq.ion.nokia.net \
      -r ${CI_RUNNER_DESCRIPTION} --upgrade --configure --test --no_cleanup
  allow_failure: true
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    when: always
    paths:
      - output_files/
    expire_in: 1 week

.regress:
  stage: test
  before_script:
    - !reference [.global_script, git_config]
  script: |
    if [ -n "${DELAY_START}" ]; then sleep ${DELAY_START}; fi
    docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    echo "runner=${CI_RUNNER_DESCRIPTION} tags=\"${CI_RUNNER_TAGS}\" commit=${CI_COMMIT_SHORT_SHA}"
    case "$LEAN" in true) echo LEAN ; exit 0 ; esac
    pushd src/sonic-mgmt && git fetch && git reset --hard origin/${REGRESS_SONIC_MGMT_BRANCH} && popd
    ./run_test.sh -i ${RUN_IMAGE} \
      -g https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlabsr.nuq.ion.nokia.net \
      -r ${CI_RUNNER_DESCRIPTION} --upgrade --configure --test \
      --run_in_order false --topology ${REGRESS_TOPO} ${EXTRA_RUN_TEST_ARGS} \
      --no_cleanup --post_results > ${CI_PROJECT_DIR}/run.log
  allow_failure: true
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    when: always
    paths:
      - output_files/
      - ${CI_PROJECT_DIR}/run.log
    expire_in: 1 week

regress:t2:chassis8:
  extends: .regress
  tags:
    - regress_chassis8
  needs:
    - build:sonic:x86_64
  variables:
    RUN_IMAGE: target/sonic-broadcom-dnx.bin
    DELAY_START: 0
    EXTRA_RUN_TEST_ARGS: --suite masic
  only:
    variables:
      - $REGRESS_T2_CHASSIS8

regress:t2:chassis9:
  extends: .regress
  tags:
    - regress_chassis9
  needs:
    - build:sonic:x86_64
  variables:
    RUN_IMAGE: target/sonic-broadcom-dnx.bin
    DELAY_START: 100
    EXTRA_RUN_TEST_ARGS: --suite masic
  only:
    variables:
      - $REGRESS_T2_CHASSIS9

regress:t2:chassis10:
  extends: .regress
  tags:
    - regress_chassis10
  needs:
    - build:sonic:x86_64
  variables:
    RUN_IMAGE: target/sonic-broadcom-dnx.bin
    DELAY_START: 200
    EXTRA_RUN_TEST_ARGS: --suite masic
  only:
    variables:
      - $REGRESS_T2_CHASSIS10

regress:t2:chassis11:
  extends: .regress
  tags:
    - regress_chassis11
  needs:
    - build:sonic:x86_64
  variables:
    RUN_IMAGE: target/sonic-broadcom-dnx.bin
    DELAY_START: 300
    EXTRA_RUN_TEST_ARGS: --suite masic
  only:
    variables:
      - $REGRESS_T2_CHASSIS11

regress:t2:chassis12:
  extends: .regress
  tags:
    - regress_chassis12
  needs:
    - build:sonic:x86_64
  variables:
    RUN_IMAGE: target/sonic-broadcom-dnx.bin
    DELAY_START: 300
    EXTRA_RUN_TEST_ARGS: --suite masic
  only:
    variables:
      - $REGRESS_T2_CHASSIS12

regress:t2:chassis19:
  extends: .regress
  tags:
    - regress_tb29
  needs:
    - build:sonic:x86_64
  variables:
    RUN_IMAGE: target/sonic-broadcom-dnx.bin
    DELAY_START: 300
    EXTRA_RUN_TEST_ARGS: --suite masic
  only:
    variables:
      - $REGRESS_T2_CHASSIS19

regress:tb3:
  extends: .regress
  tags:
    - regress_tb3
  needs:
    - build:sonic:armhf
  variables:
    REGRESS_SONIC_MGMT_BRANCH: nokia-master-M0
    RUN_IMAGE: target/sonic-marvell-armhf.bin
    DELAY_START: 0
    EXTRA_RUN_TEST_ARGS:
  only:
    variables:
      - $REGRESS_TB3

regress:tb7:
  extends: .regress
  tags:
    - regress_tb7
  needs:
    - build:sonic:armhf
  variables:
    REGRESS_SONIC_MGMT_BRANCH: nokia-master-M0
    RUN_IMAGE: target/sonic-marvell-armhf.bin
    DELAY_START: 0
    EXTRA_RUN_TEST_ARGS:
  only:
    variables:
      - $REGRESS_TB7

regress:tb13:
  extends: .regress
  tags:
    - regress_tb13
  needs:
    - build:sonic:aarch64
  variables:
    REGRESS_SONIC_MGMT_BRANCH: nokia-master-M0
    RUN_IMAGE: target/sonic-marvell-arm64.bin
    DELAY_START: 0
    EXTRA_RUN_TEST_ARGS:
  only:
    variables:
      - $REGRESS_TB13

regress:tb20:
  extends: .regress
  tags:
    - regress_tb20
  needs:
    - build:sonic:aarch64
  variables:
    REGRESS_SONIC_MGMT_BRANCH: nokia-master-M0
    RUN_IMAGE: target/sonic-marvell-arm64.bin
    DELAY_START: 0
    EXTRA_RUN_TEST_ARGS:
  only:
    variables:
      - $REGRESS_TB20

regress:tb21:
  extends: .regress
  tags:
    - regress_tb21
  needs:
    - build:sonic:armhf
  variables:
    REGRESS_SONIC_MGMT_BRANCH: nokia-master-M0
    RUN_IMAGE: target/sonic-marvell-armhf.bin
    DELAY_START: 0
    EXTRA_RUN_TEST_ARGS:
  only:
    variables:
      - $REGRESS_TB21

regress:tb23:
  extends: .regress
  tags:
    - regress_tb23
  needs:
    - build:sonic:armhf
  variables:
    REGRESS_SONIC_MGMT_BRANCH: nokia-master-M0
    RUN_IMAGE: target/sonic-marvell-armhf.bin
    DELAY_START: 0
    EXTRA_RUN_TEST_ARGS:
  only:
    variables:
      - $REGRESS_TB23

regress:tb24:
  extends: .regress
  tags:
    - regress_tb24
  needs:
    - build:sonic:x86_64
  variables:
    REGRESS_SONIC_MGMT_BRANCH: nokia-master-M0
    RUN_IMAGE: target/sonic-broadcom.bin
    DELAY_START: 0
    EXTRA_RUN_TEST_ARGS:
  only:
    variables:
      - $REGRESS_TB24

regress:tb25:
  extends: .regress
  tags:
    - regress_tb25
  needs:
    - build:sonic:armhf
  variables:
    REGRESS_SONIC_MGMT_BRANCH: nokia-master-M0
    RUN_IMAGE: target/sonic-marvell-armhf.bin
    DELAY_START: 0
    EXTRA_RUN_TEST_ARGS:
  only:
    variables:
      - $REGRESS_TB25

regress:tb26:
  extends: .regress
  tags:
    - regress_tb26
  needs:
    - build:sonic:aarch64
  variables:
    REGRESS_SONIC_MGMT_BRANCH: nokia-master-M0
    RUN_IMAGE: target/sonic-marvell-arm64.bin
    DELAY_START: 0
    EXTRA_RUN_TEST_ARGS:
  only:
    variables:
      - $REGRESS_TB26

regress:tb28:
  extends: .regress
  tags:
    - regress_tb28
  needs:
    - build:sonic:aarch64
  variables:
    REGRESS_SONIC_MGMT_BRANCH: nokia-master-M0
    RUN_IMAGE: target/sonic-marvell-arm64.bin
    DELAY_START: 0
    EXTRA_RUN_TEST_ARGS:
  only:
    variables:
      - $REGRESS_TB28

regress:tb44:
  extends: .regress
  tags:
    - regress_tb44
  needs:
    - build:sonic:x86_64
  variables:
    REGRESS_SONIC_MGMT_BRANCH: nokia-master-M0
    RUN_IMAGE: target/sonic-broadcom.bin
    DELAY_START: 0
    EXTRA_RUN_TEST_ARGS:
  only:
    variables:
      - $REGRESS_TB44

regress:tb45:
  extends: .regress
  tags:
    - regress_tb45
  needs:
    - build:sonic:armhf
  variables:
    REGRESS_SONIC_MGMT_BRANCH: nokia-master-M0
    RUN_IMAGE: target/sonic-marvell-armhf.bin
    DELAY_START: 0
    EXTRA_RUN_TEST_ARGS:
  only:
    variables:
      - $REGRESS_TB45

regress:t2:chassis20:
  extends: .regress
  tags:
    - regress_tb39
  needs:
    - build:sonic:x86_64
  variables:
    RUN_IMAGE: target/sonic-broadcom-dnx.bin
    DELAY_START: 300
    EXTRA_RUN_TEST_ARGS: --suite masic
  only:
    variables:
      - $REGRESS_T2_CHASSIS20

.post:
  stage: post
  only:
    - branches
  tags:
    - post
  before_script:
    - !reference [.global_script, git_config]
  script: |
    . .ci-env
    case "$LEAN" in true) echo LEAN ; exit 0 ; esac
    if [ "$skip_build" = "1" ] && [ -z "${NO_SKIP_BUILD}" ]; then
      exit 0
    fi
    # with all express passed, we post images and update the symlink latest
    mkdir -p /var/www/html/${PLUTO_COMMIT_DIR}
    for f in `ls target/sonic-*.bin` ; do \
      cp -a --no-preserve=mode $f /var/www/html/${PLUTO_COMMIT_DIR}/ ; done
    for f in `ls target/docker-syncd-*rpc.gz` ; do \
      cp -a --no-preserve=mode $f /var/www/html/${PLUTO_COMMIT_DIR}/ ; done
    echo "sonic_commitid=${CI_COMMIT_SHORT_SHA}" > /var/www/html/${PLUTO_COMMIT_DIR}/build-info.txt
    # make latest link and remove anything older than a week
    cd /var/www/html/${PLUTO_BRANCH_DIR} && \
      rm -f latest && ln -sf ${CI_PIPELINE_ID} latest && \
      find . -maxdepth 1 -type d -ctime +7 -exec rm -fr {} \+

post:brcm-rpc:x86_64:
  extends: .post
  needs:
    - build:brcm-rpc:x86_64

post:brcm-rpc-dnx:x86_64:
  extends: .post
  needs:
    - build:brcm-rpc-dnx:x86_64

post:sonic-gbsyncd:x86_64:
  extends: .post
  needs:
    - build:sonic-gbsyncd:x86_64

post:sonic:x86_64:
  extends: .post
  needs:
    - build:sonic:x86_64

post:sonic:armhf:
  extends: .post
  needs:
    - build:sonic:armhf

post:sonic:aarch64:
  extends: .post
  needs:
    - build:sonic:aarch64

post:sonic:features:x86_64:
  extends: .post
  needs:
    - build:sonic:features:x86_64

post:sonic:features:aarch64:
  extends: .post
  needs:
    - build:sonic:features:aarch64
