module(name = "sonic-buildimage")

bazel_dep(name = "rules_python", version = "1.7.0")
bazel_dep(name = "aspect_rules_py", version = "1.11.7")
bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "tar.bzl", version = "0.8.1")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    is_default = True,
    python_version = "3.13.4",
)

bazel_dep(name = "sonic-build-infra", version = "0.0.0", repo_name = "sonic_build_infra")
local_path_override(
    module_name = "sonic-build-infra",
    path = "sonic-build-infra",
)

bazel_dep(name = "sonic-frr-mgmt-framework", version = "1.0")
local_path_override(
    module_name = "sonic-frr-mgmt-framework",
    path = "src/sonic-frr-mgmt-framework",
)