/*************************************************************************************
 *                                                                                   *
 * Copyright: (c) 2021 Broadcom.                                                     *
 * Broadcom Proprietary and Confidential. All rights reserved.                       *
 *                                                                                   *
 *************************************************************************************/

/*************************************************************************************
 *************************************************************************************
 *                                                                                   *
 *  Revision      :  Id                                                              *
 *                                                                                   *
 *  Description   :  Defines and externed arrays used for register dump              *
 *                                                                                   *
 *************************************************************************************
 *************************************************************************************/

/** \@file plp_barchetta_blackhawk_barchetta_reg_dump.h 
 *  
 */

/* THIS FILE IS GENERATED USING AN AUTOMATED SCRIPT... PLEASE DO NOT EDIT THIS FILE DIRECTLY !!! */

#ifndef BLACKHAWK_BARCHETTA_API_REG_DUMP_H
#define BLACKHAWK_BARCHETTA_API_REG_DUMP_H

#include "common/srds_api_types.h"
#include "common/srds_api_err_code.h"

#define BLACKHAWK_BARCHETTA_REG_DUMP_SECTIONS  (12)
#define BLACKHAWK_BARCHETTA_REG_PLL_START      (0xd110)
#define BLACKHAWK_BARCHETTA_REG_UC_START       (0xd240)
extern const uint16_t plp_barchetta_blackhawk_barchetta_reg_dump_arr[BLACKHAWK_BARCHETTA_REG_DUMP_SECTIONS][2];

#endif /* SERDES_API_REG_DUMP_H */

