module(load="imfile" mode="inotify") # Ensure "inotify" mode is used
$WorkDirectory /run/uncaught-logs
# Start Monitoring the file
input(type="imfile"
      File="/run/uncaught-logs/current"
      Tag="s6-overlay"
      Severity="info"
      Facility="local0"
      PersistStateInterval="1")
