# name       lanes         alias     inde   speed     mtu    admin_statu   fec
Ethernet0    2             Eth1/1    1      10000     9216   up            none
Ethernet1    1             Eth2/1    2      10000     9216   up            none
Ethernet2    4             Eth3/1    3      10000     9216   up            none
Ethernet3    3             Eth4/1    4      10000     9216   up            none
Ethernet4    18            Eth5/1    5      10000     9216   up            none
Ethernet5    17            Eth6/1    6      10000     9216   up            none
Ethernet6    20            Eth7/1    7      10000     9216   up            none
Ethernet7    19            Eth8/1    8      10000     9216   up            none
Ethernet8    34            Eth9/1    9      10000     9216   up            none
Ethernet9    33            Eth10/1   10     10000     9216   up            none
Ethernet10   36            Eth11/1   11     10000     9216   up            none
Ethernet11   35            Eth12/1   12     10000     9216   up            none
Ethernet12   50            Eth13/1   13     10000     9216   up            none
Ethernet13   49            Eth14/1   14     10000     9216   up            none
Ethernet14   52            Eth15/1   15     10000     9216   up            none
Ethernet15   51            Eth16/1   16     10000     9216   up            none
Ethernet16   54            Eth17/1   17     10000     9216   up            none
Ethernet17   53            Eth18/1   18     10000     9216   up            none
Ethernet18   56            Eth19/1   19     10000     9216   up            none
Ethernet19   55            Eth20/1   20     10000     9216   up            none
Ethernet20   58            Eth21/1   21     10000     9216   up            none
Ethernet21   57            Eth22/1   22     10000     9216   up            none
Ethernet22   60            Eth23/1   23     10000     9216   up            none
Ethernet23   59            Eth24/1   24     10000     9216   up            none
Ethernet24   69,70,71,72   Eth25/1   25     10000     9216   up            none
Ethernet28   65,66,67,68   Eth26/1   26     10000     9216   up            none
