#!/bin/bash

# platform_utils

# Determine platform and is smartswitch
PLATFORM="$(sonic-cfggen -d -v DEVICE_METADATA.localhost.platform)"
SMARTSWITCH=false
PLATFORM_JSON=/usr/share/sonic/device/$PLATFORM/platform.json

if [ -f "$PLATFORM_JSON" ]; then
    NUM_DPU=$(jq -r '.DPUS | length' $PLATFORM_JSON 2>/dev/null)
    if [[ $NUM_DPU -gt 0 ]]; then
        SMARTSWITCH=true
    fi
fi

# Export SMARTSWITCH for other scripts
export SMARTSWITCH

IS_SUPERVISOR=false
ETC_SONIC_CHASSISDB_CONF_FILE=/etc/sonic/chassisdb.conf
PLATFORM_ENV_CONF_FILE=/usr/share/sonic/device/$PLATFORM/platform_env.conf
# if /etc/sonic/cbassisdb.conf exists without platform_env.con file, it is a Supervisor
# if /etc/sonic/chassisdb.conf and with supervisor=1 is defined in plaftorm_env.confm it is a Supervisor,
#   else it is not a Supervisor 
if [ -f "$ETC_SONIC_CHASSISDB_CONF_FILE" ]; then
    # if etc/sonci/chassisdb.con exists, it coule be a Supervisor or a Pizzabox with database-chassis support
    if [ -f "$PLATFORM_ENV_CONF_FILE" ]; then
        # check if platform_env.conf is present with supervisor=1 defined. 
        source $PLATFORM_ENV_CONF_FILE
        if [ -v supervisor ]; then
            if [ $supervisor -eq 1 ]; then
                IS_SUPERVISOR=true
            else
                IS_SUPERVISOR=false
            fi
        else 
            IS_SUPERVISOR=false
        fi
    else
        # true when there is /etc/sonic/chassisdb.conf and no platform_env.conf
        IS_SUPERVISOR=true
    fi
fi

# Export IS_SUPERVISOR for other scripts
export IS_SUPERVISOR

# Export IS_CHASSIS_MODULE for other scripts
IS_CHASSIS_MODULE=false
PLATFORM_CHASSISDB_CONF_FILE=/usr/share/sonic/device/$PLATFORM/chassisdb.conf
ETC_SONIC_CHASSISDB_CONF_FILE=/etc/sonic/chassisdb.conf
if [ -f "$PLATFORM_CHASSISDB_CONF_FILE" ]; then
    if [ -f "$ETC_SONIC_CHASSISDB_CONF_FILE" ]; then
        if [ "$IS_SUPERVISOR" = true ]; then
            IS_CHASSIS_MODULE=true
        else
            IS_CHASSIS_MODULE=false
        fi
    else
        # true if there is /etc/sonic/chassisdb.conf and 
        IS_CHASSIS_MODULE=true
    fi
fi

# Export IS_CHASSIS_MODULE for other scripts
export IS_CHASSIS_MODULE
