#!/bin/bash

# platform_utils

# Determine platform and is smartswitch
PLATFORM="$(sonic-cfggen -d -v DEVICE_METADATA.localhost.platform)"
SMARTSWITCH=false
PLATFORM_JSON=/usr/share/sonic/device/$PLATFORM/platform.json

if [ -f "$PLATFORM_JSON" ]; then
    NUM_DPU=$(jq -r '.DPUS | length' $PLATFORM_JSON 2>/dev/null)
    if [[ $NUM_DPU -gt 0 ]]; then
        SMARTSWITCH=true
    fi
fi

# Export SMARTSWITCH for other scripts
export SMARTSWITCH

IS_SUPERVISOR=false
PLATFORM_ENV_CONF_FILE=/usr/share/sonic/device/$PLATFORM/platform_env.conf
if [ -f "$PLATFORM_ENV_CONF_FILE" ]; then
    source $PLATFORM_ENV_CONF_FILE
    if [ -v supervisor ]; then
        if [ $supervisor -eq 1 ]; then
            IS_SUPERVISOR=true
        else
            IS_SUPERVISOR=false
        fi
    else 
        IS_SUPERVISOR=false
    fi
fi

# Export IS_SUPERVISOR for other scripts
export IS_SUPERVISOR

# Export IS_CHASSIS_MODULE for other scripts
IS_CHASSIS_MODULE=false
PLATFORM_CHASSISDB_CONF_FILE=/usr/share/sonic/device/$PLATFORM/chassisdb.conf
ETC_SONIC_CHASSISDB_CONF_FILE=/etc/sonic/chassisdb.conf
if [ -f "$PLATFORM_CHASSISDB_CONF_FILE" ]; then
    if [ -f "$ETC_SONIC_CHASSISDB_CONF_FILE" ]; then
        if [ "$IS_SUPERVISOR" = true ]; then
            IS_CHASSIS_MODULE=true
        else
            IS_CHASSIS_MODULE=false
        fi
    else
        IS_CHASSIS_MODULE=true
    fi
fi

# Export IS_CHASSIS_MODULE for other scripts
export IS_CHASSIS_MODULE
