#!/bin/bash

# Restrict command to sudo users
if [ "$EUID" -ne 0 ] ; then
  echo "Root priveleges are needed for this operation"
  exit 1
fi

PLATFORM="$(sonic-cfggen -d -v DEVICE_METADATA.localhost.platform)"
PLATFORM_ENV_CONF=/usr/share/sonic/device/$PLATFORM/platform_env.conf
SMARTSWITCH=false
if [ -f "$PLATFORM_ENV_CONF" ]; then
    if grep -Fxq "SMARTSWITCH=1" $PLATFORM_ENV_CONF; then
        SMARTSWITCH=true
    fi
fi

if [ -f /etc/sonic/chassisdb.conf ] && [ "$SMARTSWITCH" = false ] ; then
  if [[ $1 == "no-stats" ]]; then
    rexec all -c "sudo TSC no-stats"
  else
    rexec all -c "sudo TSC"
  fi
  exit 0
fi

/usr/bin/TS TSC
[[ $1 != "no-stats" ]] && portstat -p 5

if [[ "$(sonic-cfggen -d -v DEVICE_METADATA.localhost.subtype | tr [:upper:] [:lower:])" == *"dualtor"* ]]
then
  echo
  show mux status
fi
