{% from "dockers/dockerfile-macros.j2" import install_debian_packages, copy_files, rsync_from_builder_stage %}
ARG BASE=docker-config-engine-trixie-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

FROM $BASE AS base

ARG docker_container_name

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update

RUN apt-get install -f -y iproute2 libcap2-bin

{% if docker_gbsyncd_mrvl_debs.strip() -%}
# Copy MRVL_SAI (libsai.so) Debian package dependency
{{ copy_files("debs/", docker_gbsyncd_mrvl_debs.split(' '), "/debs/") }}

# Install MRVL_SAI and implicitly install its dependencies
{{ install_debian_packages(docker_gbsyncd_mrvl_debs.split(' ')) }}
{%- endif %}

COPY ["docker-init.sh", "/usr/bin/"]
COPY ["start.sh", "/usr/bin/"]

COPY ["critical_processes.j2", "/usr/share/sonic/templates"]
COPY ["supervisord.conf.j2", "/usr/share/sonic/templates"]


FROM $BASE

{{ rsync_from_builder_stage() }}

ENV DEBIAN_FRONTEND=noninteractive
ENTRYPOINT ["/usr/bin/docker-init.sh"]
