onie_arch=x86_64
onie_bin=
onie_boot_reason=install
onie_build_date=2019-11-05T13:30-05:00
onie_build_machine=nokia_ixr7250
onie_build_platform=x86_64-kvm_x86_64-r0
onie_cli_static_parms=
onie_cli_static_url=sonic-broadcom.bin
onie_config_version=1
onie_dev=/dev/sdc2
onie_exec_url=sonic-broadcom.bin
onie_firmware=auto
onie_grub_image_name=grubx64.efi
onie_initrd_tmp=/
onie_installer=/var/tmp/installer
onie_kernel_version=4.9.95
onie_machine=nokia_ixr7250
onie_machine_rev=0
onie_partition_type=gpt
onie_platform=x86_64-kvm_x86_64-r0
onie_root_dir=/mnt/onie-boot/onie
onie_skip_ethmgmt_macs=no
onie_switch_asic=bcm
onie_uefi_arch=x64
onie_uefi_boot_loader=grubx64.efi
onie_vendor_id=7483
onie_version=2019.08onie_version_1.0
