SUBDIR_CFG = cfg
wb_switch_driver-objs := switch_driver.o wb_module.o \
wb_fan_driver.o \
wb_eeprom_driver.o \
wb_cpld_driver.o \
wb_fpga_driver.o \
wb_led_driver.o \
wb_slot_driver.o \
wb_sensors_driver.o \
wb_psu_driver.o \
wb_sff_driver.o \
wb_watchdog_driver.o \
wb_system_driver.o \
wb_cabletray_driver.o\
wb_misc_fw_driver.o\
$(SUBDIR_CFG)/dfd_cfg.o \
$(SUBDIR_CFG)/dfd_cfg_adapter.o \
$(SUBDIR_CFG)/dfd_cfg_file.o \
$(SUBDIR_CFG)/dfd_cfg_info.o \
$(SUBDIR_CFG)/dfd_cfg_listnode.o \
$(SUBDIR_CFG)/dfd_frueeprom.o \
$(SUBDIR_CFG)/dfd_wbtlv_eeprom.o \
$(SUBDIR_CFG)/dfd_tlveeprom.o \

obj-m := wb_switch_driver.o
