#!/bin/sh

mr_reboot() {

    sudo rmmod x86-64-asterfusion-cx532p-n
    sudo i2cset -y 0 0x30 0xa1 0  

}

if [ $# -eq 0 ] || [ $@ = "--halt" ] || [ $@ = "-f" ] || [ $@ = "--force" ]; then
    sudo /sbin/halt
elif [ $@ = "-p" ] || [ $@ = "--reboot" ] || [ $@ = "--poweroff" ]; then
    mr_reboot
else
    echo "unsupported option"
fi

