from setuptools import setup

setup(
    name="sonic-platform",
    version="1.0",
    description='SONiC platform API implementation',
    license='Apache 2.0',
    author='SONiC Team',
    author_email='support',
    url='',
    maintainer='support',
    maintainer_email='',
    packages=[
        "sonic_platform",
        "algorithm",
        "eepromutil",
        "plat_hal",
        "public",
        "tech_support",
        "wbutil",
    ],
    package_dir={
        "sonic_platform": "common/sonic_platform",
        "algorithm": "common/lib/algorithm",
        "eepromutil": "common/lib/eepromutil",
        "plat_hal": "common/lib/plat_hal",
        "public": "common/lib/public",
        "tech_support": "common/lib/tech_support",
        "wbutil": "common/lib/wbutil",
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Environment :: Plugins",
        "Intended Audience :: Developers",
        "Intended Audience :: Information Technology",
        "Intended Audience :: System Administrators",
        "License :: OSI Approved :: Apache Software License",
        "Natural Language :: English",
        "Operating System :: POSIX :: Linux",
        "Programming Language :: Python :: 3.11",
        "Topic :: Utilities",
    ],
    keywords="sonic SONiC platform PLATFORM aspeed bmc micas",
)
