#ifndef BALD_EAGLE_H
#define BALD_EAGLE_H

#include "be_fw_config.h"

#include "canary/canary_regmap.h"

extern const RegHive_t Top[], TopPLL[], FecA[], FecB[], TopSensor[];

#define HAL_SUPPORT_ANLT           1
#define HAL_SUPPORT_FEC_ANA        1
#define HAL_SUPPORT_FW_ADAPT_COUNT 1
#define HAL_SUPPORT_FW_DFE         1
#define HAL_SUPPORT_FW_EYE         1
#define HAL_SUPPORT_FW_ISI         1
#define HAL_SUPPORT_FW_RATIO       1
#define HAL_SUPPORT_FW_OF          1
#define HAL_SUPPORT_FW_HF          1
#define HAL_SUPPORT_PARAMS_SERDES  1

#define FW_SPEED_INFO       TOP_DEBUG, TOP_DEBUG_SPEED
#define FW_LINK_LOST_COUNT  TOP_INFO, TOP_INFO_LINK_LOST_COUNT
#define FW_ADAPT_COUNT_NRZ  NRZ_DEBUG, NRZ_DEBUG_RESTART_COUNT
#define FW_ADAPT_COUNT_PAM4 PAM4_DEBUG, PAM4_DEBUG_RESTART_COUNT
#define FW_READAPT_COUNT    TOP_INFO, TOP_INFO_READAPT_COUNT
#define FW_RX_RATIO_NRZ     NRZ_DEBUG, NRZ_DEBUG_RX_RATIO
#define FW_RX_RATIO_PAM4    PAM4_DEBUG, PAM4_DEBUG_RX_RATIO
#define FW_RX_OF_NRZ        NRZ_DEBUG, NRZ_DEBUG_RX_OF
#define FW_RX_OF_PAM4       PAM4_DEBUG, PAM4_DEBUG_RX_OF
#define FW_RX_HF_NRZ        NRZ_DEBUG, NRZ_DEBUG_RX_HF
#define FW_RX_HF_PAM4       PAM4_DEBUG, PAM4_DEBUG_RX_HF
#define FW_DFE_PAM4         PAM4_INFO, PAM4_INFO_THRESHOLD
#define FW_EYE_PAM4         PAM4_INFO, PAM4_INFO_EYE
#define FW_ISI_PAM4         PAM4_INFO, PAM4_INFO_ISI

/* Other registers of BaldEagle specific */
#define HOST_LANES 8
#define LINE_LANES 8
#define CHIP_LANES (HOST_LANES + LINE_LANES)
#define TOP        HIVE(Top)
#define TOPPLL     HIVE(TopPLL)
#define FECA       HIVE(FecA)
#define FECB       HIVE(FecB)
#define TOPSENSOR  HIVE(TopSensor)

#define REG_DATA             0x9F00
#define REG_MDIO_MAGIC_NUMER 0x985A
#define REG_CHIP_RST         REGBITR(TOP, 0x0002, 15, 0)
#define CHIP_SOFT_RST_VAL    0x888
#define CHIP_LOGIC_RST_VAL   0x777
#define CHIP_CPU_RST_VAL     0xAAA
#define CHIP_REG_RST_VAL     0x999

#define REG_LANE_REGISTER_RST 0x980E
#define REG_LANE_LOGIC_RST    0x980F

#define REG_MAGIC          REGBITR(TOP, 0x0005, 15, 0)
#define REG_CMD            REGBITR(TOP, 0x0006, 15, 0)
#define REG_CMD_DETAIL     REGBITR(TOP, 0x0007, 15, 0)
#define REG_MCU_CLK_SEL    REGBITR(TOP, 0x000B, 15)
#define REG_FW_REG_VALUE   REGBITR(TOP, 0x00C7, 15, 0)
#define REG_CMD_DETAIL2    REG_FW_REG_VALUE
#define FW_LOAD_MAGIC_WORD 0x6A6A
#define FW_UNLOAD_WORD     0xFFF0
#define FW_LOAD_TIMEOUT    100000
#define FW_UNLOAD_DONE     0x0
#define FW_CMD_TIMEOUT     50000
#define REG_FW_PHY_READY   REGBITR(TOP, 0x00C9, 15, 0)

#define REG_FW_WATCHDOG_TIMER REGBITR(TOP, 0x00C6, 15, 0)

#define REG_OUI_LSB         REGBITR(TOP, 0x08, 15, 0)
#define REG_OUI_MSB         REGBITR(TOP, 0x09, 15, 8)
#define REG_MODEL_NUMBER    REGBITR(TOP, 0x0A, 9, 4)
#define REG_REVISION_NUMBER REGBITR(TOP, 0x0A, 3, 0)

#define REG_ADR_DIFF_A0(LN) REGBITR(TOP, 0x0013 + ((LN % 8) * 8), 15, 13)
#define REG_ADR_DIFF_A1(LN) REGBITR(TOP, 0x0013 + ((LN % 8) * 8), 12, 10)
#define REG_ADR_DIFF_B0(LN) REGBITR(TOP, 0x0013 + ((LN % 8) * 8), 9, 7)
#define REG_ADR_DIFF_B1(LN) REGBITR(TOP, 0x0013 + ((LN % 8) * 8), 6, 4)

#define REG_BM_CTRL_S        REGBITR(TOP, 0x0059, 15, 0)
#define REG_BM_BUF_SEL_LANE  REGBITR(TOP, 0x004D, 14, 12)
#define REG_BM_BUF_SEL_SLICE REGBITR(TOP, 0x004D, 10, 8)
#define REG_BM_BUF_SEL_READ  REGBITR(TOP, 0x004E, 15, 4)

// SW loopback
#define REG_PLL_SOURCE     0x98D1
#define PLL_LOOPBACK_MAGIC 8

#define REG_LOOPBACK_ENABLE 0x9811
#define REG_W_ADJUST        0x9812
#define REG_ADR_DIFF        0x9813
#define REG_ADR_DIFF_LB     0x9814
#define LOOPBACK_MASK       0x000A

#define ADR_DIFF_A_SHIFT 10
#define ADR_DIFF_B_SHIFT 4

#define A0_DEC_MASK 0x8000
#define B0_DEC_MASK 0x2000
#define A0_INC_MASK 0x0800
#define B0_INC_MASK 0x0200

/* Top PLL */
#define REG_TOP_PLL_EN_REFCLK         REGBITR(TOPPLL, 0x000, 7)
#define REG_TOP_PLL_DIV4              REGBITR(TOPPLL, 0x000, 6)
#define REG_TOP_PLL_PU                REGBITR(TOPPLL, 0x001, 2)
#define REG_TOP_PLL_LCVCOCAP          REGBITR(TOPPLL, 0x001, 12, 6)
#define REG_TOP_PLL_N                 REGBITR(TOPPLL, 0x007, 12, 4)
#define REG_TOP_PLL_FCAL_START        REGBITR(TOPPLL, 0x00D, 15)
#define REG_TOP_PLL_FCAL_TIMER_WINDOW REGBITR(TOPPLL, 0x00D, 14, 0)
#define REG_TOP_PLL_FCAL_DONE         REGBITR(TOPPLL, 0x000F, 15)
#define REG_TOP_PLL_FCAL_CNT_OP       REGBITR(TOPPLL, 0x00E, 15, 0)
#define REG_TOP_PLL_LO_OPEN           REGBITR(TOPPLL, 0x010, 7)
#define REG_TOP_PLL_VCTRL_LOOPEN_SEL  REGBITR(TOPPLL, 0x010, 6, 4)
#define REG_TOP_PLL_PD_FCAL           REGBITR(TOPPLL, 0x012, 3)
#define REG_TOP_PLL_REFCLK_DIV        REGBITR(TOPPLL, 0x013, 15, 7)
#define REG_TOP_PLL_DIV2              REGBITR(TOPPLL, 0x013, 6)
#define REG_FEC_EN                    REGBITR(TOP, 0x057, 7, 0)
#define REG_FEC_RX_ALIGNED_A          REGBITR(FECA, 0x00C9, 14)
#define REG_FEC_CORR_ERROR_LOWER_A    REGBITR(FECA, 0x00CA, 15, 0)
#define REG_FEC_CORR_ERROR_UPPER_A    REGBITR(FECA, 0x00CB, 15, 0)
#define REG_FEC_UNCORR_ERROR_LOWER_A  REGBITR(FECA, 0x00CC, 15, 0)
#define REG_FEC_UNCORR_ERROR_UPPER_A  REGBITR(FECA, 0x00CD, 15, 0)
#define REG_FEC_RX_FIFO_CUR_A         REGBITR(FECA, 0x089F, 10, 0)
#define REG_FEC_RX_FIFO_MIN_A         REGBITR(FECA, 0x08A0, 10, 0)
#define REG_FEC_RX_FIFO_MAX_A         REGBITR(FECA, 0x08A1, 10, 0)
#define REG_FEC_TX_FIFO_CUR_A         REGBITR(FECA, 0x089C, 10, 0)
#define REG_FEC_TX_FIFO_MIN_A         REGBITR(FECA, 0x089D, 10, 0)
#define REG_FEC_TX_FIFO_MAX_A         REGBITR(FECA, 0x089E, 10, 0)
#define REG_FEC_RX_ALIGNED_B          REGBITR(FECB, 0x00C9, 14)
#define REG_FEC_CORR_ERROR_LOWER_B    REGBITR(FECB, 0x00CA, 15, 0)
#define REG_FEC_CORR_ERROR_UPPER_B    REGBITR(FECB, 0x00CB, 15, 0)
#define REG_FEC_UNCORR_ERROR_LOWER_B  REGBITR(FECB, 0x00CC, 15, 0)
#define REG_FEC_UNCORR_ERROR_UPPER_B  REGBITR(FECB, 0x00CD, 15, 0)
#define REG_FEC_RX_FIFO_CUR_B         REGBITR(FECB, 0x089F, 10, 0)
#define REG_FEC_RX_FIFO_MIN_B         REGBITR(FECB, 0x08A0, 10, 0)
#define REG_FEC_RX_FIFO_MAX_B         REGBITR(FECB, 0x08A1, 10, 0)
#define REG_FEC_TX_FIFO_CUR_B         REGBITR(FECB, 0x089C, 10, 0)
#define REG_FEC_TX_FIFO_MIN_B         REGBITR(FECB, 0x089D, 10, 0)
#define REG_FEC_TX_FIFO_MAX_B         REGBITR(FECB, 0x089E, 10, 0)

/* SENSOR REG */
#define REG_TOP_SENSOR_CLK_SEL_VS REGBITR(TOPSENSOR, 0x3F, 15)
#define REG_TOP_SENSOR_CLK_CNT_VS REGBITR(TOPSENSOR, 0x3F, 14, 0)
#define REG_TOP_SENSOR_VS_RUN     REGBITR(TOPSENSOR, 0xF6, 11)
#define REG_TOP_SENSOR_VS_RSTN    REGBITR(TOPSENSOR, 0xF6, 10)
#define REG_TOP_SENSOR_VS_SDE     REGBITR(TOPSENSOR, 0xF6, 7)
#define REG_TOP_SENSOR_VS_SEL_VIN REGBITR(TOPSENSOR, 0xF6, 6, 3)
#define REG_TOP_SENSOR_VS_PD      REGBITR(TOPSENSOR, 0xF6, 12)
#define REG_TOP_SENSOR_VS_DOUT    REGBITR(TOPSENSOR, 0xF5, 11, 0)

/* ECC */
#define REG_ECC_TEST   REGBITR(TOPPLL, 0x200, 14, 13)
#define REG_ECC_STATUS REGBITR(TOPPLL, 0x201, 15, 0)

// EFUSE
#define EFUSE_BASE_REG 0xB000

#ifndef __EMSCRIPTEN__
void hal_register_sdk(void) __attribute__((constructor));
#else
void hal_register_sdk(void) __attribute__((visibility("default")));
#endif

#endif
