/*
 *
 * $Id: phymod.xml,v 1.1.2.5 2013/09/12 10:43:06 nirf Exp $
 *
 * $Copyright:
 * All Rights Reserved.$
 *
 *
 * DO NOT EDIT THIS FILE!
 *
 */

#include <phymod/phymod.h>
#include <phymod/phymod_diagnostics.h>
#include <phymod/phymod_diagnostics_dispatch.h>

#ifdef PHYMOD_APERTA_SUPPORT

#include <blackhawk_diagnostics.h>


__phymod_diagnostics__dispatch__t__ plp_aperta_phymod_diagnostics_blackhawk_diagnostics_driver = {

    plp_aperta_blackhawk_phy_rx_slicer_position_set,
    plp_aperta_blackhawk_phy_rx_slicer_position_get,
    plp_aperta_blackhawk_phy_rx_slicer_position_max_get,
    plp_aperta_blackhawk_phy_prbs_config_set,
    plp_aperta_blackhawk_phy_prbs_config_get,
    plp_aperta_blackhawk_phy_prbs_enable_set,
    plp_aperta_blackhawk_phy_prbs_enable_get,
    plp_aperta_blackhawk_phy_prbs_status_get,
    plp_aperta_blackhawk_phy_pattern_config_set,
    plp_aperta_blackhawk_phy_pattern_config_get,
    plp_aperta_blackhawk_phy_pattern_enable_set,
    plp_aperta_blackhawk_phy_pattern_enable_get,
    plp_aperta_blackhawk_core_diagnostics_get,
    plp_aperta_blackhawk_phy_diagnostics_get,
    NULL,
    plp_aperta_blackhawk_phy_pmd_info_dump,
    NULL, /* plp_aperta_phymod_phy_pcs_info_dump */
    plp_aperta_blackhawk_phy_eyescan_run,
    NULL, /* plp_aperta_phymod_phy_link_mon_enable_set */
    NULL, /* plp_aperta_phymod_phy_link_mon_enable_get */
    NULL, /* plp_aperta_phymod_phy_link_mon_status_get */
    NULL, /* plp_aperta_phymod_phy_fec_correctable_counter_get */
    NULL, /* plp_aperta_phymod_phy_fec_uncorrectable_counter_get */
    NULL, /* plp_aperta_phymod_phy_prbs_error_inject_set  */
    NULL, /* plp_aperta_phymod_phy_prbs_error_analyzer_proj */
};

#endif /* PHYMOD_BLACKHAWK_SUPPORT */
