{% from "dockers/dockerfile-macros.j2" import install_debian_packages, copy_files %}

FROM docker-config-engine-bookworm-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

ARG docker_container_name
ARG image_version

ENV DEBIAN_FRONTEND=noninteractive
ENV IMAGE_VERSION=$image_version

RUN [ -f /etc/rsyslog.conf ] && sed -ri "s/%syslogtag%/$docker_container_name#%syslogtag%/;" /etc/rsyslog.conf

RUN apt-get update && apt-get install -y \
    libdbus-1-3 \
    libdaemon0 \
    libjansson4 \
    libpython3.8 \
    libjemalloc2 \
    libevent-dev

{% if docker_l2mcd_debs.strip() -%}

{{ copy_files("debs/", docker_l2mcd_debs.split(' '), "/debs/") }}

{{ install_debian_packages(docker_l2mcd_debs.split(' ')) }}
{%- endif %}

RUN apt-get clean -y && \
    apt-get autoclean -y && \
    apt-get autoremove -y && \
    rm -rf /debs

COPY ["start.sh", "/usr/bin/"]
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]
COPY ["critical_processes", "/etc/supervisor/"]

{%- if CONFIGURED_ARCH == "amd64" %}
RUN echo "deb [arch=amd64] http://deb.debian.org/debian bookworm main contrib non-free non-free-firmware" > /etc/apt/sources.list && \
    echo "deb [arch=amd64] http://deb.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware" >> /etc/apt/sources.list && \
    echo "deb [arch=amd64] http://deb.debian.org/debian-updates bookworm-updates main contrib non-free non-free-firmware" >> /etc/apt/sources.list && \
    echo "deb [arch=amd64] http://deb.debian.org/debian-backports bookworm-backports main contrib non-free non-free-firmware" >> /etc/apt/sources.list
{%- elif CONFIGURED_ARCH == "arm64" %}
RUN echo "deb [arch=arm64] http://deb.debian.org/debian bookworm main contrib non-free non-free-firmware" > /etc/apt/sources.list && \
    echo "deb [arch=arm64] http://deb.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware" >> /etc/apt/sources.list && \
    echo "deb [arch=arm64] http://deb.debian.org/debian-updates bookworm-updates main contrib non-free non-free-firmware" >> /etc/apt/sources.list && \
    echo "deb [arch=arm64] http://deb.debian.org/debian-backports bookworm-backports main contrib non-free non-free-firmware" >> /etc/apt/sources.list
{%- endif %}

RUN rm -f ~/.pip/pip.conf
RUN rm -f /usr/local/lib/python3.9/dist-packages/netaddr/eui/oui.txt

ENTRYPOINT ["/usr/local/bin/supervisord"]
