{% from "dockers/dockerfile-macros.j2" import install_debian_packages, copy_files %}

ARG BASE=docker-config-engine-bookworm-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

FROM $BASE AS base

ARG docker_container_name
ARG image_version

ENV DEBIAN_FRONTEND=noninteractive
ENV IMAGE_VERSION=$image_version

RUN [ -f /etc/rsyslog.conf ] && sed -ri "s/%syslogtag%/$docker_container_name#%syslogtag%/;" /etc/rsyslog.conf

RUN apt-get update && apt-get install -f -y \
    libdbus-1-3 \
    libdaemon0 \
    libjansson4 \
    libpython3.11 \
    libjemalloc2 \
    libevent-dev

{% if docker_l2mcd_debs.strip() -%}

{{ copy_files("debs/", docker_l2mcd_debs.split(' '), "/debs/") }}

{{ install_debian_packages(docker_l2mcd_debs.split(' ')) }}
{%- endif %}

RUN apt-get clean -y && \
    apt-get autoclean -y && \
    apt-get autoremove -y && \
    rm -rf /debs

COPY ["start.sh", "/usr/bin/"]
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]
COPY ["critical_processes", "/etc/supervisor/"]
RUN chmod +x /usr/bin/start.sh

FROM $BASE

RUN --mount=type=bind,from=base,target=/changes-to-image rsync -axAX --no-D --exclude=/sys --exclude=/proc --exclude=/dev --exclude=resolv.conf /changes-to-image/ /


ENTRYPOINT ["/usr/local/bin/supervisord"]
