# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meta/meta.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gogo_pb2 as gogo__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

from gogo_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmeta/meta.proto\x12\x04meta\x1a\ngogo.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\"\n\x08TypeMeta\x12\x16\n\x04Kind\x18\x01 \x01(\tB\x08\xea\xde\x1f\x04kind\";\n\tTimestamp\x12.\n\x04Time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x04\xd0\xde\x1f\x01\"\xc1\x01\n\x07ObjMeta\x12\x16\n\x04Name\x18\x01 \x01(\tB\x08\xea\xde\x1f\x04name\x12 \n\x04UUID\x18\x02 \x01(\tB\x12\xea\xde\x1f\x0euuid,omitempty\x12\x42\n\x0c\x43reationTime\x18\x03 \x01(\x0b\x32\x0f.meta.TimestampB\x1b\xea\xde\x1f\x17\x63reation-time,omitempty\x12\x38\n\x07ModTime\x18\x04 \x01(\x0b\x32\x0f.meta.TimestampB\x16\xea\xde\x1f\x12mod-time,omitemptyB\nZ\x08meta/pdsP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meta.meta_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010meta/pds'
  _TYPEMETA.fields_by_name['Kind']._options = None
  _TYPEMETA.fields_by_name['Kind']._serialized_options = b'\352\336\037\004kind'
  _TIMESTAMP.fields_by_name['Time']._options = None
  _TIMESTAMP.fields_by_name['Time']._serialized_options = b'\320\336\037\001'
  _OBJMETA.fields_by_name['Name']._options = None
  _OBJMETA.fields_by_name['Name']._serialized_options = b'\352\336\037\004name'
  _OBJMETA.fields_by_name['UUID']._options = None
  _OBJMETA.fields_by_name['UUID']._serialized_options = b'\352\336\037\016uuid,omitempty'
  _OBJMETA.fields_by_name['CreationTime']._options = None
  _OBJMETA.fields_by_name['CreationTime']._serialized_options = b'\352\336\037\027creation-time,omitempty'
  _OBJMETA.fields_by_name['ModTime']._options = None
  _OBJMETA.fields_by_name['ModTime']._serialized_options = b'\352\336\037\022mod-time,omitempty'
  _globals['_TYPEMETA']._serialized_start=70
  _globals['_TYPEMETA']._serialized_end=104
  _globals['_TIMESTAMP']._serialized_start=106
  _globals['_TIMESTAMP']._serialized_end=165
  _globals['_OBJMETA']._serialized_start=168
  _globals['_OBJMETA']._serialized_end=361
# @@protoc_insertion_point(module_scope)
