/*
 *         
 * $Id: phymod.xml,v 1.1.2.5 Broadcom SDK $
 * 
 * $Copyright: (c) 2020 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *         
 *     
 * DO NOT EDIT THIS FILE!
 *
 */

#ifndef _BARCHETTA_H__H_
#define _BARCHETTA_H__H_

#include <phymod/phymod_definitions.h>
/*Initialize phymod module*/
int plp_barchetta_core_identify(const plp_barchetta_phymod_core_access_t* core, uint32_t core_id, uint32_t* is_identified);

/*Retrive core information*/
int plp_barchetta_core_info_get(const plp_barchetta_phymod_core_access_t* core, plp_barchetta_phymod_core_info_t* info);

/*Reset Core*/
int plp_barchetta_core_reset_set(const plp_barchetta_phymod_core_access_t* core, plp_barchetta_phymod_reset_mode_t reset_mode, plp_barchetta_phymod_reset_direction_t direction);
int plp_barchetta_core_reset_get(const plp_barchetta_phymod_core_access_t* core, plp_barchetta_phymod_reset_mode_t reset_mode, plp_barchetta_phymod_reset_direction_t* direction);

/*Retrive firmware information*/
int plp_barchetta_core_firmware_info_get(const plp_barchetta_phymod_core_access_t* core, plp_barchetta_phymod_core_firmware_info_t* fw_info);

/*Set\get firmware operation mode*/
int plp_barchetta_phy_firmware_lane_config_set(const plp_barchetta_phymod_phy_access_t* phy, phymod_firmware_lane_config_t fw_lane_config);
int plp_barchetta_phy_firmware_lane_config_get(const plp_barchetta_phymod_phy_access_t* phy, phymod_firmware_lane_config_t* fw_lane_config);

/*Start\Stop the sequencer*/
int plp_barchetta_core_pll_sequencer_restart(const plp_barchetta_phymod_core_access_t* core, uint32_t flags, plp_barchetta_phymod_sequencer_operation_t operation);

/*Set phy polarity*/
int plp_barchetta_phy_polarity_set(const plp_barchetta_phymod_phy_access_t* phy, const plp_barchetta_phymod_polarity_t* polarity);
int plp_barchetta_phy_polarity_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_polarity_t* polarity);

/*Set\Get TX Parameters*/
int plp_barchetta_phy_tx_set(const plp_barchetta_phymod_phy_access_t* phy, const plp_barchetta_phymod_tx_t* tx);
int plp_barchetta_phy_tx_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_tx_t* tx);

/*Set\Get PAM4 TX Parameters*/
int plp_barchetta_phy_pam4_tx_set(const plp_barchetta_phymod_phy_access_t* phy, const phymod_pam4_tx_t* tx);
int plp_barchetta_phy_pam4_tx_get(const plp_barchetta_phymod_phy_access_t* phy, phymod_pam4_tx_t* tx);

/*Set\Get RX Parameters*/
int plp_barchetta_phy_rx_set(const plp_barchetta_phymod_phy_access_t* phy, const plp_barchetta_phymod_rx_t* rx);
int plp_barchetta_phy_rx_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_rx_t* rx);

/*PHY Rx adaptation resume*/
int plp_barchetta_phy_rx_adaptation_resume(const plp_barchetta_phymod_phy_access_t* phy);

/*Reset phy*/
int plp_barchetta_phy_reset_set(const plp_barchetta_phymod_phy_access_t* phy, const plp_barchetta_phymod_phy_reset_t* reset);
int plp_barchetta_phy_reset_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_phy_reset_t* reset);

/*Control phy power*/
int plp_barchetta_phy_power_set(const plp_barchetta_phymod_phy_access_t* phy, const plp_barchetta_phymod_phy_power_t* power);
int plp_barchetta_phy_power_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_phy_power_t* power);

/*TX transmission control*/
int plp_barchetta_phy_tx_lane_control_set(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_phy_tx_lane_control_t tx_control);
int plp_barchetta_phy_tx_lane_control_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_phy_tx_lane_control_t* tx_control);

/*Rx control*/
int plp_barchetta_phy_rx_lane_control_set(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_phy_rx_lane_control_t rx_control);
int plp_barchetta_phy_rx_lane_control_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_phy_rx_lane_control_t* rx_control);

/*forced speed FEC control*/
int plp_barchetta_phy_fec_enable_set(const plp_barchetta_phymod_phy_access_t* phy, uint32_t enable);
int plp_barchetta_phy_fec_enable_get(const plp_barchetta_phymod_phy_access_t* phy, uint32_t* enable);

/*Set the interface mode, speed and other configuration related to interface.*/
int plp_barchetta_phy_interface_config_set(const plp_barchetta_phymod_phy_access_t* phy, uint32_t flags, const plp_barchetta_phymod_phy_inf_config_t* config);
int plp_barchetta_phy_interface_config_get(const plp_barchetta_phymod_phy_access_t* phy, uint32_t flags, plp_barchetta_phymod_ref_clk_t ref_clock, plp_barchetta_phymod_phy_inf_config_t* config);

/*Set\Get CL72*/
int plp_barchetta_phy_cl72_set(const plp_barchetta_phymod_phy_access_t* phy, uint32_t cl72_en);
int plp_barchetta_phy_cl72_get(const plp_barchetta_phymod_phy_access_t* phy, uint32_t* cl72_en);

/*Get CL72 status*/
int plp_barchetta_phy_cl72_status_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_cl72_status_t* status);

/*Set\Get autoneg*/
int plp_barchetta_phy_autoneg_ability_set(const plp_barchetta_phymod_phy_access_t* phy, const plp_barchetta_phymod_autoneg_ability_t* an_ability_set_type);
int plp_barchetta_phy_autoneg_ability_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_autoneg_ability_t* an_ability_get_type);

/*Get  remote link autoneg*/
int plp_barchetta_phy_autoneg_remote_ability_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_autoneg_ability_t* an_ability_get_type);

/*Set\Get autoneg*/
int plp_barchetta_phy_autoneg_set(const plp_barchetta_phymod_phy_access_t* phy, const plp_barchetta_phymod_autoneg_control_t* an);
int plp_barchetta_phy_autoneg_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_autoneg_control_t* an, uint32_t* an_done);

/*Core Initialization*/
int plp_barchetta_core_init(const plp_barchetta_phymod_core_access_t* core, const plp_barchetta_phymod_core_init_config_t* init_config, const plp_barchetta_phymod_core_status_t* core_status);

/*Phy Initialization*/
int plp_barchetta_phy_init(const plp_barchetta_phymod_phy_access_t* phy, const plp_barchetta_phymod_phy_init_config_t* init_config);

/*Set\get loopback mode*/
int plp_barchetta_phy_loopback_set(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_loopback_mode_t loopback, uint32_t enable);
int plp_barchetta_phy_loopback_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_loopback_mode_t loopback, uint32_t* enable);

/*Get rx pmd locked indication*/
int plp_barchetta_phy_rx_pmd_locked_get(const plp_barchetta_phymod_phy_access_t* phy, uint32_t* rx_pmd_locked);

/*Get link up status indication*/
int plp_barchetta_phy_link_status_get(const plp_barchetta_phymod_phy_access_t* phy, uint32_t* link_status);

/*Get the serdes status*/
int plp_barchetta_phy_status_dump(const plp_barchetta_phymod_phy_access_t* phy);

/*Read phymod register*/
int plp_barchetta_phy_reg_read(const plp_barchetta_phymod_phy_access_t* phy, uint32_t reg_addr, uint32_t* val);

/*Write phymod register*/
int plp_barchetta_phy_reg_write(const plp_barchetta_phymod_phy_access_t* phy, uint32_t reg_addr, uint32_t val);

/*Read Revision id*/
int plp_barchetta_phy_rev_id(const plp_barchetta_phymod_phy_access_t* phy, uint32_t* rev_id);

/*Get/Set PHY interrupt enable mask*/
int plp_barchetta_phy_intr_enable_set(const plp_barchetta_phymod_phy_access_t* phy, uint32_t enable);
int plp_barchetta_phy_intr_enable_get(const plp_barchetta_phymod_phy_access_t* phy, uint32_t* enable);

/*PHY interrupt status get*/
int plp_barchetta_phy_intr_status_get(const plp_barchetta_phymod_phy_access_t* phy, uint32_t* intr_status);

/*Clear PHY interrupt status */
int plp_barchetta_phy_intr_status_clear(const plp_barchetta_phymod_phy_access_t* phy, uint32_t intr_clr);

/*Read data from I2C device attached to PHY*/
int plp_barchetta_phy_i2c_read(const plp_barchetta_phymod_phy_access_t* phy, uint32_t flags, uint32_t addr, uint32_t offset, uint32_t size, uint8_t* data);

/*Write data to I2C device attached to PHY*/
int plp_barchetta_phy_i2c_write(const plp_barchetta_phymod_phy_access_t* phy, uint32_t flags, uint32_t addr, uint32_t offset, uint32_t size, const uint8_t* data);

/*Set/Get the configuration of a PHY GPIO pin*/
int plp_barchetta_phy_gpio_config_set(const plp_barchetta_phymod_phy_access_t* phy, int pin_no, plp_barchetta_phymod_gpio_mode_t gpio_mode);
int plp_barchetta_phy_gpio_config_get(const plp_barchetta_phymod_phy_access_t* phy, int pin_no, plp_barchetta_phymod_gpio_mode_t* gpio_mode);

/*Set/Get the output/input value of a PHY GPIO pin*/
int plp_barchetta_phy_gpio_pin_value_set(const plp_barchetta_phymod_phy_access_t* phy, int pin_no, int value);
int plp_barchetta_phy_gpio_pin_value_get(const plp_barchetta_phymod_phy_access_t* phy, int pin_no, int* value);

/*Set/get failover mode */
int plp_barchetta_failover_mode_set(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_failover_mode_t failover_mode);
int plp_barchetta_failover_mode_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_failover_mode_t* failover_mode);

/*Initialization for Warmboot*/
int plp_barchetta_warmboot_init(const plp_barchetta_phymod_core_access_t* core, void* init_data);

/*Set\get logical lane mapping*/
int plp_barchetta_logical_lane_set(const plp_barchetta_phymod_core_access_t* core, const phymod_logical_lane_map_t* lane_map);
int plp_barchetta_logical_lane_get(const plp_barchetta_phymod_core_access_t* core, phymod_logical_lane_map_t* lane_map);

/*Get/Set SyncE configuration*/
int plp_barchetta_synce_config_set(const plp_barchetta_phymod_phy_access_t* phy, const phymod_synce_cfg_t* synce_cfg);
int plp_barchetta_synce_config_get(const plp_barchetta_phymod_phy_access_t* phy, phymod_synce_cfg_t* synce_cfg);

/* Dump/Configure SerDes Diagnostics access.*/
int plp_barchetta_srds_diag_access_enable(const plp_barchetta_phymod_phy_access_t* phy, const phymod_srds_diag_access_cfg_t* diag_access_cfg);

/* converts PAI to PHY data and vice versa.*/
int plp_barchetta_phy_pai_info_get(const plp_barchetta_phymod_phy_access_t* phy, phymod_pai_phy_op_t operation, phymod_pai_phy_config_t* pai_phy_config, void* epdm_data);

#endif /*_BARCHETTA_H_*/
