/*
 *         
 * $Id: phymod.xml,v 1.1.2.5 Broadcom SDK $
 * 
 * $Copyright: (c) 2020 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *         
 *     
 * DO NOT EDIT THIS FILE!
 *
 */

#ifndef _BARCHETTA2_H__H_
#define _BARCHETTA2_H__H_

#include <phymod/phymod_definitions.h>
/*Initialize phymod module*/
int barchetta2_core_identify(const plp_barchetta_phymod_core_access_t* core, uint32_t core_id, uint32_t* is_identified);

/*Retrive core information*/
int barchetta2_core_info_get(const plp_barchetta_phymod_core_access_t* core, plp_barchetta_phymod_core_info_t* info);

/*Reset Core*/
int barchetta2_core_reset_set(const plp_barchetta_phymod_core_access_t* core, plp_barchetta_phymod_reset_mode_t reset_mode, plp_barchetta_phymod_reset_direction_t direction);
int barchetta2_core_reset_get(const plp_barchetta_phymod_core_access_t* core, plp_barchetta_phymod_reset_mode_t reset_mode, plp_barchetta_phymod_reset_direction_t* direction);

/*Retrive firmware information*/
int barchetta2_core_firmware_info_get(const plp_barchetta_phymod_core_access_t* core, plp_barchetta_phymod_core_firmware_info_t* fw_info);

/*Set\get firmware operation mode*/
int barchetta2_phy_firmware_lane_config_set(const plp_barchetta_phymod_phy_access_t* phy, phymod_firmware_lane_config_t fw_lane_config);
int barchetta2_phy_firmware_lane_config_get(const plp_barchetta_phymod_phy_access_t* phy, phymod_firmware_lane_config_t* fw_lane_config);

/*Set phy polarity*/
int barchetta2_phy_polarity_set(const plp_barchetta_phymod_phy_access_t* phy, const plp_barchetta_phymod_polarity_t* polarity);
int barchetta2_phy_polarity_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_polarity_t* polarity);

/*Set\Get PAM4 TX Parameters*/
int barchetta2_phy_pam4_tx_set(const plp_barchetta_phymod_phy_access_t* phy, const phymod_pam4_tx_t* tx);
int barchetta2_phy_pam4_tx_get(const plp_barchetta_phymod_phy_access_t* phy, phymod_pam4_tx_t* tx);

/*Set\Get RX Parameters*/
int barchetta2_phy_rx_set(const plp_barchetta_phymod_phy_access_t* phy, const plp_barchetta_phymod_rx_t* rx);
int barchetta2_phy_rx_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_rx_t* rx);

/*Reset phy*/
int barchetta2_phy_reset_set(const plp_barchetta_phymod_phy_access_t* phy, const plp_barchetta_phymod_phy_reset_t* reset);
int barchetta2_phy_reset_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_phy_reset_t* reset);

/*Control phy power*/
int barchetta2_phy_power_set(const plp_barchetta_phymod_phy_access_t* phy, const plp_barchetta_phymod_phy_power_t* power);
int barchetta2_phy_power_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_phy_power_t* power);

/*TX transmission control*/
int barchetta2_phy_tx_lane_control_set(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_phy_tx_lane_control_t tx_control);
int barchetta2_phy_tx_lane_control_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_phy_tx_lane_control_t* tx_control);

/*Rx control*/
int barchetta2_phy_rx_lane_control_set(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_phy_rx_lane_control_t rx_control);
int barchetta2_phy_rx_lane_control_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_phy_rx_lane_control_t* rx_control);

/*Set the interface mode, speed and other configuration related to interface.*/
int barchetta2_phy_interface_config_set(const plp_barchetta_phymod_phy_access_t* phy, uint32_t flags, const plp_barchetta_phymod_phy_inf_config_t* config);
int barchetta2_phy_interface_config_get(const plp_barchetta_phymod_phy_access_t* phy, uint32_t flags, plp_barchetta_phymod_ref_clk_t ref_clock, plp_barchetta_phymod_phy_inf_config_t* config);

/*Set\Get CL72*/
int barchetta2_phy_cl72_set(const plp_barchetta_phymod_phy_access_t* phy, uint32_t cl72_en);
int barchetta2_phy_cl72_get(const plp_barchetta_phymod_phy_access_t* phy, uint32_t* cl72_en);

/*Get CL72 status*/
int barchetta2_phy_cl72_status_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_cl72_status_t* status);

/*Set\Get autoneg*/
int barchetta2_phy_autoneg_ability_set(const plp_barchetta_phymod_phy_access_t* phy, const plp_barchetta_phymod_autoneg_ability_t* an_ability_set_type);
int barchetta2_phy_autoneg_ability_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_autoneg_ability_t* an_ability_get_type);

/*Get  remote link autoneg*/
int barchetta2_phy_autoneg_remote_ability_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_autoneg_ability_t* an_ability_get_type);

/*Set\Get autoneg*/
int barchetta2_phy_autoneg_set(const plp_barchetta_phymod_phy_access_t* phy, const plp_barchetta_phymod_autoneg_control_t* an);
int barchetta2_phy_autoneg_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_autoneg_control_t* an, uint32_t* an_done);

/*Set\Get autoneg restart*/
int barchetta2_phy_autoneg_restart_set(const plp_barchetta_phymod_phy_access_t* phy, const plp_barchetta_phymod_autoneg_control_t* an);

/*Core Initialization*/
int barchetta2_core_init(const plp_barchetta_phymod_core_access_t* core, const plp_barchetta_phymod_core_init_config_t* init_config, const plp_barchetta_phymod_core_status_t* core_status);

/*Phy Initialization*/
int barchetta2_phy_init(const plp_barchetta_phymod_phy_access_t* phy, const plp_barchetta_phymod_phy_init_config_t* init_config);

/*Set\get loopback mode*/
int barchetta2_phy_loopback_set(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_loopback_mode_t loopback, uint32_t enable);
int barchetta2_phy_loopback_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_loopback_mode_t loopback, uint32_t* enable);

/*Get rx pmd locked indication*/
int barchetta2_phy_rx_pmd_locked_get(const plp_barchetta_phymod_phy_access_t* phy, uint32_t* rx_pmd_locked);

/*Get link up status indication*/
int barchetta2_phy_link_status_get(const plp_barchetta_phymod_phy_access_t* phy, uint32_t* link_status);

/*Get the serdes status*/
int barchetta2_phy_status_dump(const plp_barchetta_phymod_phy_access_t* phy);

/*Read phymod register*/
int barchetta2_phy_reg_read(const plp_barchetta_phymod_phy_access_t* phy, uint32_t reg_addr, uint32_t* val);

/*Write phymod register*/
int barchetta2_phy_reg_write(const plp_barchetta_phymod_phy_access_t* phy, uint32_t reg_addr, uint32_t val);

/*Read Revision id*/
int barchetta2_phy_rev_id(const plp_barchetta_phymod_phy_access_t* phy, uint32_t* rev_id);

/*Get/Set PHY interrupt enable mask*/
int barchetta2_phy_intr_enable_set(const plp_barchetta_phymod_phy_access_t* phy, uint32_t enable);
int barchetta2_phy_intr_enable_get(const plp_barchetta_phymod_phy_access_t* phy, uint32_t* enable);

/*PHY interrupt status get*/
int barchetta2_phy_intr_status_get(const plp_barchetta_phymod_phy_access_t* phy, uint32_t* intr_status);

/*Clear PHY interrupt status */
int barchetta2_phy_intr_status_clear(const plp_barchetta_phymod_phy_access_t* phy, uint32_t intr_clr);

/*Set/Get the configuration of a PHY GPIO pin*/
int barchetta2_phy_gpio_config_set(const plp_barchetta_phymod_phy_access_t* phy, int pin_no, plp_barchetta_phymod_gpio_mode_t gpio_mode);
int barchetta2_phy_gpio_config_get(const plp_barchetta_phymod_phy_access_t* phy, int pin_no, plp_barchetta_phymod_gpio_mode_t* gpio_mode);

/*Set/Get the output/input value of a PHY GPIO pin*/
int barchetta2_phy_gpio_pin_value_set(const plp_barchetta_phymod_phy_access_t* phy, int pin_no, int value);
int barchetta2_phy_gpio_pin_value_get(const plp_barchetta_phymod_phy_access_t* phy, int pin_no, int* value);

/*FEC status*/
int barchetta2_phy_pam4_fec_status_get(const plp_barchetta_phymod_phy_access_t* phy, phymod_phy_fec_dump_status_t* fec_sts);

/*AVS configuration*/
int barchetta2_phy_avs_config_set(const plp_barchetta_phymod_phy_access_t* phy, phymod_avs_config_t avs_config);
int barchetta2_phy_avs_config_get(const plp_barchetta_phymod_phy_access_t* phy, phymod_avs_config_t* avs_config);

/*AVS configuration*/
int barchetta2_phy_avs_status_get(const plp_barchetta_phymod_phy_access_t* phy, phymod_avs_config_status_t* avs_status);

/*Initialization for Warmboot*/
int barchetta2_warmboot_init(const plp_barchetta_phymod_core_access_t* core, void* init_data);

/*Set\get logical lane mapping*/
int barchetta2_logical_lane_set(const plp_barchetta_phymod_core_access_t* core, const phymod_logical_lane_map_t* lane_map);
int barchetta2_logical_lane_get(const plp_barchetta_phymod_core_access_t* core, phymod_logical_lane_map_t* lane_map);

/*Get/Set SyncE configuration*/
int barchetta2_synce_config_set(const plp_barchetta_phymod_phy_access_t* phy, const phymod_synce_cfg_t* synce_cfg);
int barchetta2_synce_config_get(const plp_barchetta_phymod_phy_access_t* phy, phymod_synce_cfg_t* synce_cfg);

/*Get pcs status */
int barchetta2_phy_pcs_status_get(const plp_barchetta_phymod_phy_access_t* phy, phymod_pcs_status_t* pcs_status);

/* converts PAI to PHY data and vice versa.*/
int barchetta2_phy_pai_info_get(const plp_barchetta_phymod_phy_access_t* phy, phymod_pai_phy_op_t operation, phymod_pai_phy_config_t* pai_phy_config, void* epdm_data);

#endif /*_BARCHETTA2_H_*/
