/*
 *         
 * $Id: phymod.xml,v 1.1.2.5 Broadcom SDK $
 * 
 * $Copyright: (c) 2020 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *         
 *     
 * DO NOT EDIT THIS FILE!
 *
 */

#ifndef _BARCHETTA_DIAGNOSTICS_H__H_
#define _BARCHETTA_DIAGNOSTICS_H__H_

#include <phymod/phymod_definitions.h>
/*set\get PRBS configuration*/
int plp_barchetta_phy_prbs_config_set(const plp_barchetta_phymod_phy_access_t* phy, uint32_t flags , const plp_barchetta_phymod_prbs_t* prbs);
int plp_barchetta_phy_prbs_config_get(const plp_barchetta_phymod_phy_access_t* phy, uint32_t flags , plp_barchetta_phymod_prbs_t* prbs);

/*Set\get PRBS enable state*/
int plp_barchetta_phy_prbs_enable_set(const plp_barchetta_phymod_phy_access_t* phy, uint32_t flags , uint32_t enable);
int plp_barchetta_phy_prbs_enable_get(const plp_barchetta_phymod_phy_access_t* phy, uint32_t flags , uint32_t* enable);

/*Get PRBS Status*/
int plp_barchetta_phy_prbs_status_get(const plp_barchetta_phymod_phy_access_t* phy, uint32_t flags, plp_barchetta_phymod_prbs_status_t* prbs_status);

/*Set\get pattern state*/
int plp_barchetta_phy_pattern_enable_set(const plp_barchetta_phymod_phy_access_t* phy, uint32_t enable, const plp_barchetta_phymod_pattern_t* pattern);
int plp_barchetta_phy_pattern_enable_get(const plp_barchetta_phymod_phy_access_t* phy, uint32_t* enable, const plp_barchetta_phymod_pattern_t* pattern);

/*Get phy diagnostics information*/
int plp_barchetta_phy_diagnostics_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_phy_diagnostics_t* diag);

/*Display eyescan information*/
int plp_barchetta_phy_eyescan_run(const plp_barchetta_phymod_phy_access_t* phy, uint32_t flags, plp_barchetta_phymod_eyescan_mode_t mode, const plp_barchetta_phymod_phy_eyescan_options_t* eyescan_options);

/*Get/Set link monitor enable/disable*/
int plp_barchetta_phy_link_mon_enable_set(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_link_monitor_mode_t link_mon_mode, uint32_t enable);
int plp_barchetta_phy_link_mon_enable_get(const plp_barchetta_phymod_phy_access_t* phy, plp_barchetta_phymod_link_monitor_mode_t link_mon_mode, uint32_t* enable);

/*Get link monitor Status*/
int plp_barchetta_phy_link_mon_status_get(const plp_barchetta_phymod_phy_access_t* phy, uint32_t* lock_status, uint32_t* lock_lost_lh, uint32_t* error_count);

/*Get FEC Corrected Codeword Counter*/
int plp_barchetta_phy_fec_correctable_counter_get(const plp_barchetta_phymod_phy_access_t* phy, phymod_fec_type_t fec_type, uint32_t* count);

/*Get FEC Uncorrected Codeword Counter*/
int plp_barchetta_phy_fec_uncorrectable_counter_get(const plp_barchetta_phymod_phy_access_t* phy, phymod_fec_type_t fec_type, uint32_t* count);

/*Display PRBS Error Analyzer Projection*/
int plp_barchetta_phy_prbs_error_analyzer_proj(const plp_barchetta_phymod_phy_access_t* phy, uint16_t prbs_error_fec_size, uint8_t hist_errcnt_thresh, uint32_t timeout_s);

#endif /*_BARCHETTA_DIAGNOSTICS_H_*/
