{% from "dockers/dockerfile-macros.j2" import install_debian_packages, install_python_wheels, copy_files %}
FROM docker-config-engine-bookworm-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update

RUN apt-get install iputils-ping

{% if docker_swss_layer_bookworm_debs.strip() -%}
# Copy locally-built Debian package dependencies
{{ copy_files("debs/", docker_swss_layer_bookworm_debs.split(' '), "/debs/") }}

# Install locally-built Debian packages and implicitly install their dependencies
{{ install_debian_packages(docker_swss_layer_bookworm_debs.split(' ')) }}
{%- endif %}

RUN apt-get update && apt-get install -y \
    git cmake build-essential autoconf libtool pkg-config \
    libcurl4-openssl-dev protobuf-compiler libprotobuf-dev \
    libssl-dev zlib1g-dev

WORKDIR /opt
RUN git clone --recurse-submodules https://github.com/open-telemetry/opentelemetry-cpp && \
    cd opentelemetry-cpp && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release && \
    make -j$(nproc) && make install

RUN apt-get clean -y      && \
    apt-get autoclean -y  && \
    apt-get autoremove -y && \
    rm -rf /debs

ENTRYPOINT ["/usr/local/bin/supervisord"]
