# $Id$
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# PHYMOD_EPIL make rules and definitions
#

#
# Provide reasonable defaults for configuration variables
#

# Default build directory
ifndef PHYMOD_EPIL_BLDDIR
PHYMOD_EPIL_BLDDIR = $(PHYMOD_EPIL)/build
endif

# Location to build objects in
ifndef PHYMOD_EPIL_OBJDIR
PHYMOD_EPIL_OBJDIR = $(PHYMOD_EPIL_BLDDIR)/obj
endif
override BLDDIR := $(PHYMOD_EPIL_OBJDIR)

# Location to place libraries
ifndef PHYMOD_EPIL_LIBDIR
PHYMOD_EPIL_LIBDIR = $(PHYMOD_EPIL_BLDDIR)
endif
LIBDIR := $(PHYMOD_EPIL_LIBDIR)

# Option to retrieve compiler version
ifndef PHYMOD_EPIL_CC_VERFLAGS
PHYMOD_EPIL_CC_VERFLAGS := -v
endif
CC_VERFLAGS = $(PHYMOD_EPIL_CC_VERFLAGS); 

# Default suffix for object files
ifndef PHYMOD_EPIL_OBJSUFFIX
PHYMOD_EPIL_OBJSUFFIX = o
endif
OBJSUFFIX = $(PHYMOD_EPIL_OBJSUFFIX)

# Default suffix for library files
ifndef PHYMOD_EPIL_LIBSUFFIX
PHYMOD_EPIL_LIBSUFFIX = a
endif
LIBSUFFIX = $(PHYMOD_EPIL_LIBSUFFIX)

#
# Set up compiler options, etc.
#

# Default include path
PHYMOD_EPIL_INCLUDE_PATH += -I$(PHYMOD_EPIL)/phymod/include

# Import preprocessor flags avoiding include duplicates
TMP_PHYMOD_EPIL_CPPFLAGS := $(filter-out $(PHYMOD_EPIL_INCLUDE_PATH),$(PHYMOD_EPIL_CPPFLAGS))

# Convenience Makefile flags for building specific chips
ifdef PHYMOD_EPIL_CHIPS
PHYMOD_EPIL_DSYM_CPPFLAGS := -DPHYMOD_EPIL_CONFIG_INCLUDE_CHIP_DEFAULT=0
PHYMOD_EPIL_DSYM_CPPFLAGS += $(foreach chip,$(PHYMOD_EPIL_CHIPS),-DPHYMOD_EPIL_CONFIG_INCLUDE_${chip}=1) 
endif
ifdef PHYMOD_EPIL_NCHIPS
PHYMOD_EPIL_DSYM_CPPFLAGS += $(foreach chip,$(PHYMOD_EPIL_NCHIPS),-DPHYMOD_EPIL_CONFIG_INCLUDE_${chip}=0)
endif

TMP_PHYMOD_EPIL_CPPFLAGS += $(PHYMOD_EPIL_DSYM_CPPFLAGS)
TMP_PHYMOD_EPIL_CPPFLAGS += -DPHYMOD_INCLUDE_CUSTOM_CONFIG
TMP_PHYMOD_EPIL_CPPFLAGS += -DBCM_PLP_MAC_SUPPORT
#TMP_PHYMOD_EPIL_CPPFLAGS += -DBCM_PLP_BASE_T_MAC_SUPPORT
#TMP_PHYMOD_EPIL_CPPFLAGS += -DINCLUDE_PLP_MACSEC
#TMP_PHYMOD_EPIL_CPPFLAGS += -DINCLUDE_PLP_IMACSEC
#TMP_PHYMOD_EPIL_CPPFLAGS +=  -DINCLUDE_PLP_UNIMAC
TMP_PHYMOD_EPIL_CPPFLAGS += -DSA_PLP_SUPPORT
TMP_PHYMOD_EPIL_CPPFLAGS += -DEXCLUDE_STD_HEADERS
TMP_PHYMOD_EPIL_CPPFLAGS += -DMACSEC_FW_MSG_INTF
#TMP_PHYMOD_EPIL_CPPFLAGS += -DPHYMOD_DEBUG_BUS_WRITE -DPHYMOD_DEBUG_BUS_READ
#TMP_PHYMOD_EPIL_CPPFLAGS += -DBCM_PLP_WARM_BOOT_SUPPORT -DBCM_WARM_BOOT_SUPPORT
#TMP_PHYMOD_EPIL_CPPFLAGS += -DBCM_PLP_MACSEC_WARM_BOOT_SUPPORT
#TMP_PHYMOD_EPIL_CPPFLAGS += -DBCM_PLP_CFYE_UNINT_BYPASS
#TMP_PHYMOD_EPIL_CPPFLAGS += -DUSE_EPDM_COMMON_DEFINES
TMP_PHYMOD_EPIL_CPPFLAGS += -DSERDES_API_FLOATING_POINT
TMP_PHYMOD_EPIL_CPPFLAGS += -DBCM_PLP_32BIT_TECH_ABILITY
#TMP_PHYMOD_EPIL_CPPFLAGS += -DBARCHETTA_DEBUG_SUPPORT
#TMP_PHYMOD_EPIL_CPPFLAGS += -DBCM_PLP_RMT_PHY_CAPABILITY
TMP_PHYMOD_EPIL_CPPFLAGS += -DBCM_PLP_TIMESYNC_SUPPORT
#TMP_PHYMOD_EPIL_CPPFLAGS += -DBCM_PLP_TIMESYNC_V2_1_SUPPORT
#TMP_PHYMOD_EPIL_CPPFLAGS += -DBCM_PLP_INCREMENTAL_MDIO
#TMP_PHYMOD_EPIL_CPPFLAGS += -DMACSEC_V2_1
TMP_PHYMOD_EPIL_CPPFLAGS += -DMACSEC_V3_2
#TMP_PHYMOD_EPIL_CPPFLAGS += -DMACSEC_BASET_V2_1_1
#TMP_PHYMOD_EPIL_CPPFLAGS += -DMACSEC_BASET_V2_2
#TMP_PHYMOD_EPIL_CPPFLAGS += -DBE_HOST
#TMP_PHYMOD_EPIL_CPPFLAGS += -DPLP_LMI_BUS_LOCK
#TMP_PHYMOD_EPIL_CPPFLAGS += -DPLP_BASE_T_FIRMWARE_DOWNLOAD_LEGACY
TMP_PHYMOD_EPIL_CPPFLAGS += -DMACSEC_FW_MSG_SECY_INIT
#TMP_PHYMOD_EPIL_CPPFLAGS += -DMACSEC_FW_MSG_SECY_STATS
TMP_PHYMOD_EPIL_CPPFLAGS += -DBCM_FIRMWARE_LANE_CONFIG_FIRMWARE_MODE
#TMP_PHYMOD_EPIL_CPPFLAGS += -DAPERTA_ABILITY_WO_CLEAR
#TMP_PHYMOD_EPIL_CPPFLAGS += -DAPERTA_MULTI_SPEED_AN_SUPPORT
#TMP_PHYMOD_EPIL_CPPFLAGS += -DBCM_PLP_PORT_DEFAULT_DISABLE
#EPDM_HOME =
TMP_PHYMOD_EPIL_CPPFLAGS += -DEPIL_UTIL_PATH='"$(CURDIR)/phymod/util/"'
TMP_PHYMOD_EPIL_CPPFLAGS += -DOCTAL_CROSSING_SUPPORT

ifneq (,$(findstring -DINCLUDE_PLP_MACSEC,$(CPPFLAGS)))
#MACSECHOME =
endif

export PHYMOD_EPIL_DSYM_CPPFLAGS

ifdef DSYMS
TMP_PHYMOD_EPIL_CPPFLAGS += -DPHYMOD_EPIL_CONFIG_CHIP_SYMBOLS_USE_DSYMS=1
endif
override CPPFLAGS = $(TMP_PHYMOD_EPIL_CPPFLAGS) $(PHYMOD_EPIL_INCLUDE_PATH)

#Building library as shared object
#PHYMOD_CFLAGS += -fPIC
# Import compiler flags
#PHYMOD_CFLAGS += -O2 -m32 -fstack-protector-strong -Wformat -Werror=format-security
#PHYMOD_CFLAGS += -Wno-misleading-indentation
override CFLAGS = $(PHYMOD_CFLAGS) -Wall -Werror

#
# Define standard targets, etc.
#

ifdef LOCALDIR
override BLDDIR := $(BLDDIR)/$(LOCALDIR)
endif

ifndef LSRCS
LSRCS = $(wildcard *.c)
endif
ifndef LOBJS
LOBJS = $(addsuffix .$(OBJSUFFIX), $(basename $(LSRCS)))
endif
ifndef BOBJS
BOBJS = $(addprefix $(BLDDIR)/,$(LOBJS))
endif

# Use PHYMOD_EPIL_QUIET=1 to control printing of compilation lines.
ifdef PHYMOD_EPIL_QUIET
Q = @
endif

#
# Define rules for creating object directories
#

.PRECIOUS: $(BLDDIR)/.tree

%/.tree:
	@$(ECHO) 'Creating build directory $(dir $@)'
	$(Q)$(MKDIR) $(dir $@)
	@$(ECHO) "Build Directory for $(LOCALDIR) created" > $@

#
# Configure build tools
#
include $(PHYMOD_EPIL)/make/maketools.mk
