#!/bin/bash

set -e

# Restore cipher_pass file from persistent storage
if [ -f /host/security_cipher/cipher_pass ]; then
    cp /host/security_cipher/cipher_pass.json /etc/cipher_pass.json
    chmod 640 /etc/cipher_pass.json
    echo "Restored /host/security_cipher/cipher_pass.json  to /etc/"
fi

