/*
** $Id: lua.c $
** Lua stand-alone interpreter
** See Copyright Notice in lua.h
*/

#include "crlua.h"
#include "lauxlib.h"
#include "lprefix.h"
#include "lua.h"
#include "lualib.h"
#include "shell.h"

#include "credo.h"
#include "sdk.h"

#include <setjmp.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define LUA_PROGNAME "lua"

#define LUA_INIT_VAR "CREDO_LUA_INIT"

static lua_State *globalL = NULL;

static const char *progname = LUA_PROGNAME;

typedef void (*sighandler_t)(int);
/*
** Hook set by signal function to stop the interpreter.
*/
static void lstop(lua_State *L, lua_Debug *ar) {
    (void)ar;                   /* unused arg. */
    lua_sethook(L, NULL, 0, 0); /* reset hook */
    luaL_error(L, "interrupted!");
}

/*
** Function to be called at a C signal. Because a C signal cannot
** just change a Lua state (as there is no proper synchronization),
** this function only sets a hook that, when called, will stop the
** interpreter.
*/
static void laction(int i) {
    (void)i;
    int flag = LUA_MASKCALL | LUA_MASKRET | LUA_MASKLINE | LUA_MASKCOUNT;
    lua_sethook(globalL, lstop, flag, 1);
}

#define LUA_USAGE_DESC                                             \
    "usage: lua [options] [script [args]]\n"                       \
    "Available options are:\n"                                     \
    "  -h       show this help text\n"                             \
    "  -i       enter interactive mode after executing 'script'\n" \
    "  -v       show version information\n"                        \
    "  -E       ignore environment variables\n"                    \
    "  -W       turn warnings on\n"                                \
    "  --       stop handling options\n"

static void print_usage(lua_State *L, const char *badoption) {
    if (badoption == NULL) {
        lua_writestring(L, LUA_USAGE_DESC, strlen(LUA_USAGE_DESC));
        return;
    }
    lua_writestringerror(L, "%s: ", progname);
    if (badoption[1] == 'e' || badoption[1] == 'l')
        lua_writestringerror(L, "'%s' needs argument\n", badoption);
    else
        lua_writestringerror(L, "unrecognized option '%s'\n", badoption);
    lua_writestringerror(L, LUA_USAGE_DESC, progname);
}

/*
** Prints an error message, adding the program name in front of it
** (if present)
*/
static void l_message(lua_State *L, const char *pname, const char *msg) {
    if (pname) lua_writestringerror(L, "%s: ", pname);
    lua_writestringerror(L, "%s\n", msg);
}

/*
** Check whether 'status' is not OK and, if so, prints the error
** message on the top of the stack. It assumes that the error object
** is a string, as it was either generated by Lua or by 'msghandler'.
*/
static int report(lua_State *L, int status) {
    if (status != LUA_OK) {
        const char *msg = lua_tostring(L, -1);
        l_message(L, progname, msg);
        lua_pop(L, 1); /* remove message */
    }
    return status;
}

/*
** Message handler used to run all chunks
*/
static int msghandler(lua_State *L) {
    const char *msg = lua_tostring(L, 1);
    if (msg == NULL) {                           /* is error object not a string? */
        if (luaL_callmeta(L, 1, "__tostring") && /* does it have a metamethod */
            lua_type(L, -1) == LUA_TSTRING)      /* that produces a string? */
            return 1;                            /* that is the message */
        else
            msg = lua_pushfstring(L, "(error object is a %s value)", luaL_typename(L, 1));
    }
    luaL_traceback(L, L, msg, 1); /* append a standard traceback */
    return 1;                     /* return the traceback */
}

/*
** Interface to 'lua_pcall', which sets appropriate message function
** and C-signal handler. Used to run all chunks.
*/
static int docall(lua_State *L, int narg, int nres, bool G) {
    int status;
    int base = lua_gettop(L) - narg; /* function index */
    if (!G) {
        lua_getglobal(L, "SHELLENV"); /* push environment onto stack */
        lua_setupvalue(L, -2 - narg, 1);
    }
    lua_pushcfunction(L, msghandler);           /* push message handler */
    lua_insert(L, base);                        /* put it under function and args */
    globalL = L;                                /* to be available to 'laction' */
    sighandler_t old = signal(SIGINT, laction); /* set C-signal handler */
    status = lua_pcall(L, narg, nres, base);
    signal(SIGINT, old); /* reset C-signal handler */
    lua_remove(L, base); /* remove message handler from the stack */
    return status;
}

static void print_version(lua_State *L) {
    lua_writestring(L, LUA_COPYRIGHT, strlen(LUA_COPYRIGHT));
    lua_writeline(L);
}
#define CR_LUA_WELCOME_NAME "Crlua Shell "
#define CR_LUA_WELCOME_HELP " - Type and run \"%desc\" for more information."

static void print_crlua_banner(lua_State *L) {
    const char *sdk_version = cr_sdk_version_str();
    lua_writestring(L, CR_LUA_WELCOME_NAME, strlen(CR_LUA_WELCOME_NAME));
    lua_writestring(L, sdk_version, (int)strlen(sdk_version));
    lua_writestring(L, CR_LUA_WELCOME_HELP, strlen(CR_LUA_WELCOME_HELP));
    lua_writeline(L);
}

/*
** Create the 'arg' table, which stores all arguments from the
** command line ('argv'). It should be aligned so that, at index 0,
** it has 'argv[script]', which is the script name. The arguments
** to the script (everything after 'script') go to positive indices;
** other arguments (before the script name) go to negative indices.
** If there is no script name, assume interpreter's name as base.
*/
static void createargtable(lua_State *L, char **argv, int argc, int script) {
    int i, narg;
    if (script == argc) script = 0; /* no script name? */
    narg = argc - (script + 1);     /* number of positive indices */
    lua_createtable(L, narg, script + 1);
    for (i = 0; i < argc; i++) {
        lua_pushstring(L, argv[i]);
        lua_rawseti(L, -2, i - script);
    }
    lua_setglobal(L, "arg");
    // copy arg table to shellenv
    lua_getglobal(L, "SHELLENV");
    lua_pushliteral(L, "arg");
    lua_getglobal(L, "arg");
    lua_settable(L, -3);
    lua_pop(L, 1);
}

static int dochunk(lua_State *L, int status, bool user) {
    if (status == LUA_OK) status = docall(L, 0, 0, user);
    return report(L, status);
}

static int dofile(lua_State *L, const char *name, bool user) {
    return dochunk(L, luaL_loadfile(L, name), user);
}

static int dostring(lua_State *L, const char *s, const char *name, bool user) {
    return dochunk(L, luaL_loadbuffer(L, s, strlen(s), name), user);
}

/*
** Calls 'require(name)' and stores the result in a global variable
** with the given name.
*/
static int dolibrary(lua_State *L, const char *name) {
    int status;
    lua_getglobal(L, "require");
    lua_pushstring(L, name);
    status = docall(L, 1, 1, false);              /* call 'require(name)' */
    if (status == LUA_OK) lua_setglobal(L, name); /* global[name] = require return */
    return report(L, status);
}

/*
** Push on the stack the contents of table 'arg' from 1 to #arg
*/
static int pushargs(lua_State *L) {
    int i, n;
    if (lua_getglobal(L, "arg") != LUA_TTABLE) luaL_error(L, "'arg' is not a table");
    n = (int)luaL_len(L, -1);
    luaL_checkstack(L, n + 3, "too many arguments to script");
    for (i = 1; i <= n; i++) lua_rawgeti(L, -i, i);
    lua_remove(L, -i); /* remove table from the stack */
    return n;
}

static int handle_script(lua_State *L, char **argv) {
    int status;
    const char *fname = argv[0];
    if (strcmp(fname, "-") == 0 && strcmp(argv[-1], "--") != 0) fname = NULL; /* stdin */
    status = luaL_loadfile(L, fname);
    if (status == LUA_OK) {
        int n = pushargs(L); /* push arguments to script */
        status = docall(L, n, LUA_MULTRET, false);
    }
    return report(L, status);
}

/* bits of various argument indicators in 'args' */
#define has_error 1  /* bad option */
#define has_i     2  /* -i */
#define has_v     4  /* -v */
#define has_e     8  /* -e */
#define has_E     16 /* -E */
#define has_h     32 /* -h */
/*
** Traverses all arguments from 'argv', returning a mask with those
** needed before running any Lua code (or an error code if it finds
** any invalid argument). 'first' returns the first not-handled argument
** (either the script name or a bad argument in case of error).
*/
static int collectargs(char **argv, int *first) {
    int args = 0;
    int i;
    for (i = 1; argv[i] != NULL; i++) {
        *first = i;
        if (argv[i][0] != '-') /* not an option? */
            return args;       /* stop handling options */
        switch (argv[i][1]) {  /* else check option */
            case 'h':
                return has_h;
            case '-':                   /* '--' */
                if (argv[i][2] != '\0') /* extra characters after '--'? */
                    return has_error;   /* invalid option */
                *first = i + 1;
                return args;
            case '\0':       /* '-' */
                return args; /* script "name" is '-' */
            case 'E':
                if (argv[i][2] != '\0') /* extra characters? */
                    return has_error;   /* invalid option */
                args |= has_E;
                break;
            case 'W':
                if (argv[i][2] != '\0') /* extra characters? */
                    return has_error;   /* invalid option */
                break;
            case 'i':
                args |= has_i; /* (-i implies -v) */ /* FALLTHROUGH */
            case 'v':
                if (argv[i][2] != '\0') /* extra characters? */
                    return has_error;   /* invalid option */
                args |= has_v;
                break;
            case 'e':
                args |= has_e;            /* FALLTHROUGH */
            case 'l':                     /* both options need an argument */
                if (argv[i][2] == '\0') { /* no concatenated argument? */
                    i++;                  /* try next 'argv' */
                    if (argv[i] == NULL || argv[i][0] == '-')
                        return has_error; /* no next argument or it is another option */
                }
                break;
            default: /* invalid option */
                return has_error;
        }
    }
    *first = i; /* no script name */
    return args;
}

/*
** Processes options 'e' and 'l', which involve running Lua code, and
** 'W', which also affects the state.
** Returns 0 if some code raises an error.
*/
static int runargs(lua_State *L, char **argv, int n) {
    int i;
    for (i = 1; i < n; i++) {
        int option = argv[i][1];
        lua_assert(argv[i][0] == '-'); /* already checked */
        switch (option) {
            case 'e':
            case 'l': {
                int status;
                const char *extra = argv[i] + 2; /* both options need an argument */
                if (*extra == '\0') extra = argv[++i];
                lua_assert(extra != NULL);
                status = (option == 'e') ? dostring(L, extra, "=(command line)", false) : dolibrary(L, extra);
                if (status != LUA_OK) return 0;
                break;
            }
            case 'W':
                lua_warning(L, "@on", 0); /* warnings on */
                break;
        }
    }
    return 1;
}

static int handle_luainit(lua_State *L) {
    const char *name = "=" LUA_INIT_VAR;
    const char *init = getenv(name + 1);
    if (init == NULL)
        return LUA_OK;
    else if (init[0] == '@')
        return dofile(L, init + 1, false);
    else
        return dostring(L, init, name, false);
}

/*
** {==================================================================
** Read-Eval-Print Loop (REPL)
** ===================================================================
*/

#define LUA_PROMPT  "crlua > "
#define LUA_PROMPT2 "crlua >> "

#if !defined(LUA_MAXINPUT)
#define LUA_MAXINPUT 1024
#endif

static inline int lua_readline(lua_State *L, char *buffer, const char *prompt) {
    CredoReadLine_t func = crsh.readline;
    if (func != NULL) {
        return func(prompt, buffer) == CR_OK;
    }

    (void)(L);  // following readline api call, prevent unused
    fputs(prompt, stdout);
    fflush(stdout);
    return fgets(buffer, LUA_MAXINPUT, stdin) != NULL;
}
#define lua_initreadline(L) ((void)(L))
#define lua_saveline(L, line) \
    {                         \
        (void)(L);            \
        (void)(line);         \
    }
#define lua_freeline(L, b) \
    {                      \
        (void)(L);         \
        (void)(b);         \
    }

/*
** Return the string to be used as a prompt by the interpreter. Leave
** the string (or nil, if using the default value) on the stack, to keep
** it anchored.
*/
static const char *get_prompt(lua_State *L, int firstline) {
    if (lua_getglobal(L, firstline ? "_PROMPT" : "_PROMPT2") != LUA_TNIL) {
        /* apply 'tostring' over the value */
        const char *p = luaL_tolstring(L, -1, NULL);
        lua_remove(L, -2); /* remove original value */
        return p;
    }
    // try and use custom shell prompt function
    lua_pushstring(L, CR_REGISTRY_SHELL_PROMPT);
    lua_gettable(L, LUA_REGISTRYINDEX);
    lua_pushboolean(L, firstline);
    if (lua_pcall(L, 1, 1, 0) == 0) {
        const char *p = lua_tostring(L, -1);
        lua_remove(L, -2);
        return p;
    }
    lua_pushstring(L, (firstline ? LUA_PROMPT : LUA_PROMPT2));
    lua_remove(L, -2);
    lua_remove(L, -3);
    return firstline ? LUA_PROMPT : LUA_PROMPT2;
}

/* mark in error messages for incomplete statements */
#define EOFMARK "<eof>"
#define marklen (sizeof(EOFMARK) / sizeof(char) - 1)

/*
** Check whether 'status' signals a syntax error and the error
** message at the top of the stack ends with the above mark for
** incomplete statements.
*/
static int incomplete(lua_State *L, int status) {
    if (status == LUA_ERRSYNTAX) {
        size_t lmsg;
        const char *msg = lua_tolstring(L, -1, &lmsg);
        if (lmsg >= marklen && strcmp(msg + lmsg - marklen, EOFMARK) == 0) {
            lua_pop(L, 1);
            return 1;
        }
    }
    return 0; /* else... */
}

#define LUA_RESTART_STMT "Restarting the Shell"

/*
** Prompt the user, read a line, and push it into the Lua stack.
*/

static int pushline(lua_State *L, int firstline, bool *G) {
    char buffer[LUA_MAXINPUT];
    char *b = buffer;
    size_t l;
    const char *prmt = get_prompt(L, firstline);
    int readstatus = lua_readline(L, b, prmt);

    if (readstatus == 0) return 0; /* no input (prompt will be popped by caller) */
    lua_pop(L, 1);                 /* remove prompt */
    l = strlen(b);
    if (l > 0 && b[l - 1] == '\n')              /* line ends with newline? */
        b[--l] = '\0';                          /* remove it */
    if (firstline && b[0] == '=')               /* for compatibility with 5.2, ... */
        lua_pushfstring(L, "return %s", b + 1); /* change '=' to 'return' */
    else if ((firstline && (strcmp(b, "quit") == 0 || strcmp(b, "exit") == 0))) {
        return 0;  // user wants to exit
    } else if (strcmp(b, "%restart") == 0) {
        crsh.restart = true;
        lua_writestring(L, LUA_RESTART_STMT, strlen(LUA_RESTART_STMT));
        lua_writeline(L);
        return 0;
    } else {
        lua_pushstring(L, CR_REGISTRY_MUI);
        int ltype = lua_gettable(L, LUA_REGISTRYINDEX);
        if (ltype == LUA_TFUNCTION) {
            lua_pushboolean(L, firstline);
            lua_pushstring(L, b);
            int status = lua_pcall(L, 2, 2, 0);
            report(L, status);
            if (status != LUA_OK) {
                lua_pushliteral(L, "");
            }
            *G |= lua_toboolean(L, -1);
            lua_pop(L, 1);
        } else {
            lua_pop(L, 1);
            lua_pushstring(L, b);
            *G = false;
        }
    }
    lua_freeline(L, b);
    return 1;
}

/*
** Try to compile line on the stack as 'return <line>;'; on return, stack
** has either compiled chunk or original line (if compilation failed).
*/
static int addreturn(lua_State *L) {
    const char *line = lua_tostring(L, -1); /* original line */
    const char *retline = lua_pushfstring(L, "return %s;", line);
    int status = luaL_loadbuffer(L, retline, strlen(retline), "=stdin");
    if (status == LUA_OK) {
        lua_remove(L, -2);         /* remove modified line */
        if (line[0] != '\0')       /* non empty? */
            lua_saveline(L, line); /* keep history */
    } else
        lua_pop(L, 2); /* pop result from 'luaL_loadbuffer' and modified line */
    return status;
}

/*
** Read multiple lines until a complete Lua statement
*/
static int multiline(lua_State *L, bool *G) {
    for (;;) { /* repeat until gets a complete statement */
        size_t len;
        const char *line = lua_tolstring(L, 1, &len);         /* get what it has */
        int status = luaL_loadbuffer(L, line, len, "=stdin"); /* try it */
        if (!incomplete(L, status) || !pushline(L, 0, G)) {
            lua_saveline(L, line); /* keep history */
            return status;         /* cannot or should not try to add continuation line */
        }
        lua_pushliteral(L, "\n"); /* add newline... */
        lua_insert(L, -2);        /* ...between the two lines */
        lua_concat(L, 3);         /* join them */
    }
}

/*
** Read a line and try to load (compile) it first as an expression (by
** adding "return " in front of it) and second as a statement. Return
** the final status of load/call with the resulting function (if any)
** in the top of the stack.
*/
static int loadline(lua_State *L, bool *G) {
    int status;
    lua_settop(L, 0);
    if (!pushline(L, 1, G)) return -1;     /* no input */
    if ((status = addreturn(L)) != LUA_OK) /* 'return ...' did not work? */
        status = multiline(L, G);          /* try as command, maybe with continuation lines */
    lua_remove(L, 1);                      /* remove line from the stack */
    lua_assert(lua_gettop(L) == 1);
    return status;
}

/*
** Prints (calling the Lua 'print' function) any values on the stack
*/
static void l_print(lua_State *L) {
    int n = lua_gettop(L);
    if (n > 0) { /* any result to be printed? */
        luaL_checkstack(L, LUA_MINSTACK, "too many results to pprint");
        lua_getglobal(L, "pprint");
        lua_insert(L, 1);
        if (lua_pcall(L, n, 0, 0) != LUA_OK)
            l_message(L, progname, lua_pushfstring(L, "error calling 'pprint' (%s)", lua_tostring(L, -1)));
    }
}

/*
** Do the REPL: repeatedly read (load) a line, evaluate (call) it, and
** print any results.
*/

static void doREPL(lua_State *L) {
    int status;
    lua_initreadline(L);
    bool use_G = false;
    while ((status = loadline(L, &use_G)) != -1) {
        if (status == LUA_OK) status = docall(L, 0, LUA_MULTRET, use_G);
        if (status == LUA_OK)
            l_print(L);
        else
            report(L, status);
        use_G = false;
    }
    lua_settop(L, 0); /* clear stack */
    lua_writeline(L);
}

/* }================================================================== */

/*
** Main body of stand-alone interpreter (to be called in protected mode).
** Reads the options and handles them all.
*/
static int pmain(lua_State *L) {
    int argc = (int)lua_tointeger(L, 1);
    char **argv = (char **)lua_touserdata(L, 2);
    int script;
    int args = collectargs(argv, &script);
    luaL_checkversion(L); /* check that interpreter has correct version */
    if (args == has_h) {
        print_usage(L, NULL);
        lua_pushboolean(L, 1); /* signal no errors */
        return 1;
    }
    if (args == has_error) {          /* bad arg? */
        print_usage(L, argv[script]); /* 'script' has index of bad arg. */
        return 0;
    }
    if (args & has_v) /* option '-v'? */
        print_version(L);
    if (args & has_E) {        /* option '-E'? */
        lua_pushboolean(L, 1); /* signal for libraries to ignore env. vars. */
        lua_setfield(L, LUA_REGISTRYINDEX, "LUA_NOENV");
    }
    luaL_openlibs(L);                      /* open standard libraries */
    crluaL_openlibs(L);                    /* open custom libraries */
    createargtable(L, argv, argc, script); /* create table 'arg' */
    lua_gc(L, LUA_GCGEN, 0, 0);            /* GC in generational mode */
    if (!(args & has_E)) {                 /* no option '-E'? */
        if (handle_luainit(L) != LUA_OK)   /* run LUA_INIT */
            return 0;                      /* error running LUA_INIT */
    }
    if (!runargs(L, argv, script)) /* execute arguments -e and -l */
        return 0;                  /* something failed */
    if (script < argc &&           /* execute main script (if there is one) */
        handle_script(L, argv + script) != LUA_OK)
        return 0;
    if (args & has_i)                                       /* -i option? */
        doREPL(L);                                          /* do read-eval-print loop */
    else if (script == argc && !(args & (has_e | has_v))) { /* no arguments? */
        print_version(L);
        print_crlua_banner(L);
        doREPL(L); /* do read-eval-print loop */
    }
    lua_pushboolean(L, 1); /* signal no errors */
    return 1;
}

// add in custom bindings for printing

size_t lua_writestring(lua_State *L, const char *str, int length) {
    if (L != NULL) {
        lua_pushstring(L, "credo_writer");
        lua_gettable(L, LUA_REGISTRYINDEX);
        CredoShellWriter_t writer = lua_touserdata(L, -1);
        lua_pop(L, 1);

        lua_pushstring(L, "credo_ud");
        lua_gettable(L, LUA_REGISTRYINDEX);
        void *ud = lua_touserdata(L, -1);
        lua_pop(L, 1);

        if (writer != NULL) {
            writer(ud, CR_SHELL_STDOUT, str);
            return length;
        }
    }
    if (crsh.writer != NULL) {
        crsh.writer(crsh.writer_ud, CR_SHELL_STDOUT, str);
    } else {
        fwrite(str, sizeof(char), length, stdout);
    }
    return length;
}

int lua_writestringerror(lua_State *L, const char *format, const char *p) {
    char buff[1024];

    if (L != NULL) {
        lua_pushstring(L, "credo_writer");
        lua_gettable(L, LUA_REGISTRYINDEX);
        CredoShellWriter_t writer = lua_touserdata(L, -1);
        lua_pop(L, 1);

        lua_pushstring(L, "credo_ud");
        lua_gettable(L, LUA_REGISTRYINDEX);
        void *ud = lua_touserdata(L, -1);
        lua_pop(L, 1);

        if (writer != NULL) {
            snprintf(buff, sizeof(buff), format, p);
            writer(ud, CR_SHELL_STDERR, buff);
            return 0;
        }
    }

    if (crsh.writer != NULL) {
        char *b = buff;
        char *mb = NULL;
        int len = snprintf(b, sizeof(buff), format, p);
        if ((size_t)len >= sizeof(buff)) {
            mb = malloc(len);
            if (mb != NULL) {
                snprintf(mb, len, format, p);
                b = mb;
            }
        }
        crsh.writer(crsh.writer_ud, CR_SHELL_STDERR, b);
        free(mb);
    } else {
        fprintf(stderr, format, p);
    }
    return 0;
}

static lua_State *CL = NULL;

void cr_lua_get_completions(const char *buf, void *lc, size_t pos) {
    if (CL == NULL) return;
    lua_pushstring(CL, CR_REGISTRY_COMPLETER);
    int ltype = lua_gettable(CL, LUA_REGISTRYINDEX);
    if (ltype != LUA_TFUNCTION) {
        lua_pop(CL, 1);
        return;
    }
    lua_pushstring(CL, buf);
    lua_pushlightuserdata(CL, lc);
    lua_pushinteger(CL, (lua_Integer)pos);
    int status = lua_pcall(CL, 3, 0, 0);
    report(CL, status);
}

static int crlua_panic(lua_State *L) {
    const char *msg = lua_tostring(L, -1);
    lua_pushliteral(L, "credo_jmpbuf");
    lua_gettable(L, LUA_REGISTRYINDEX);
    jmp_buf *buf = lua_touserdata(L, -1);
    if (msg == NULL) msg = "error object is not a string";
    lua_writestringerror(L, "PANIC: unprotected error in call to Lua API (%s)\n", msg);
    longjmp(*buf, 1);
    return 0;
}

static inline void lregister_cmd_slices(lua_State *L, CredoSlice_t **slices, size_t slice_count) {
    lua_newtable(L);
    lua_newtable(L);
    if (slices != NULL && *slices != NULL) {
        for (size_t i = 0; i < slice_count; i++) {
            // add slice list
            lua_pushinteger(L, (lua_Integer)i + 1);
            lua_pushinteger(L, slices[i]->slice_id);
            lua_settable(L, -4);
            // add slice map
            lua_pushinteger(L, slices[i]->slice_id);
            lua_pushlightuserdata(L, slices[i]);
            lua_settable(L, -3);
        }
    }
    lua_pushstring(L, CR_REGISTRY_CMD_SLICES);
    lua_pushvalue(L, -3);
    lua_settable(L, LUA_REGISTRYINDEX);

    lua_pushstring(L, CR_REGISTRY_CMD_SLICES_MAP);
    lua_pushvalue(L, -2);
    lua_settable(L, LUA_REGISTRYINDEX);
    lua_pop(L, 2);
}

static inline void lregister_panic(lua_State *L, jmp_buf *buf) {
    lua_pushliteral(L, "credo_jmpbuf");
    lua_pushlightuserdata(L, buf);
    lua_settable(L, LUA_REGISTRYINDEX);
    lua_atpanic(L, crlua_panic);
}

static inline void lregister_writer(lua_State *L, CredoShellWriter_t writer, void *ud) {
    if (writer == NULL) {
        return;
    }
    lua_pushliteral(L, "credo_writer");
    lua_pushlightuserdata(L, writer);
    lua_settable(L, LUA_REGISTRYINDEX);

    lua_pushliteral(L, "credo_ud");
    lua_pushlightuserdata(L, ud);
    lua_settable(L, LUA_REGISTRYINDEX);
}

CredoError_t cr_lua_exec(int argc, char *argv[]) {
    SHELL_LOCK();
    CredoError_t err = cr_lua_exec_full(argc, argv, crsh.slices, crsh.slice_count);
    SHELL_UNLOCK();
    return err;
}

CredoError_t cr_lua_exec_full(int argc, char *argv[], CredoSlice_t *slices[], size_t slice_count) {
    int status, result;
    lua_State *L = luaL_newstate(); /* create state */
    if (L == NULL) {
        l_message(NULL, argv[0], "cannot create state: not enough memory");
        return CR_FAIL;
    }
    lua_State *old_state = CL;
    CL = L;
    // prevent lua from aborting
    jmp_buf jbuf;
    lregister_panic(L, &jbuf);
    if (setjmp(jbuf) != 0) {
        status = LUA_ERRRUN;
        result = false;
        goto cleanup;
    }
    lregister_cmd_slices(L, slices, slice_count);
    lua_pushliteral(L, "credo_in_shell");
    lua_pushboolean(L, true);
    lua_settable(L, LUA_REGISTRYINDEX);

    lua_pushcfunction(L, &pmain);   /* to call 'pmain' in protected mode */
    lua_pushinteger(L, argc);       /* 1st argument */
    lua_pushlightuserdata(L, argv); /* 2nd argument */
    status = lua_pcall(L, 2, 1, 0); /* do the call */
    result = lua_toboolean(L, -1);  /* get result */
    report(L, status);
cleanup:
    lua_close(L);
    CL = old_state;
    clearerr(stdin);  // clear the EOF error to allow the user to re-enter
    return (result && status == LUA_OK) ? CR_OK : CR_FAIL;
}

static int prun_command(lua_State *L) {
    const char *command = luaL_checkstring(L, 1);
    luaL_openlibs(L);           /* open standard libraries */
    crluaL_openlibs(L);         /* open custom libraries */
    lua_gc(L, LUA_GCGEN, 0, 0); /* GC in generational mode */
    lua_getglobal(L, "slash");
    lua_pushstring(L, command);
    lua_call(L, 1, 0);
    return 0;
}

CredoError_t crlua_run_command(CredoSlice_t *slices[], size_t slice_count, const char *command,
                               CredoShellWriter_t writer, void *ud) {
    lua_State *L = luaL_newstate(); /* create state */
    if (L == NULL) {
        l_message(NULL, "lua", "cannot create state: not enough memory");
        return CR_FAIL;
    }
    // prevent lua from aborting
    jmp_buf jbuf;
    lregister_panic(L, &jbuf);
    if (setjmp(jbuf) != 0) {
        lua_close(L);
        return CR_FAIL;
    }
    lregister_cmd_slices(L, slices, slice_count);
    lregister_writer(L, writer, ud);
    lua_pushcfunction(L, &prun_command);
    lua_pushstring(L, command);
    int status = lua_pcall(L, 1, 0, 0); /* do the call */
    report(L, status);
    lua_close(L);
    return (status == LUA_OK) ? CR_OK : CR_FAIL;
}

void cr_lua_strfree(char **retstr) {
    free(*retstr);
}
