/*
 *         
 * $Id: phymod.xml,v 1.1.2.5 Broadcom SDK $
 * 
 * $Copyright: (c) 2020 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *         
 *     
 * DO NOT EDIT THIS FILE!
 *
 */

#include <phymod/phymod.h>
#include <phymod/phymod_diagnostics.h>
#include <phymod/phymod_diagnostics_dispatch.h>

#ifdef PHYMOD_APERTA2_SUPPORT

#include <phymod/chip/aperta2_diagnostics.h>


__phymod_diagnostics__dispatch__t__ plp_aperta2_phymod_diagnostics_aperta2_diagnostics_driver = {

    NULL, /* plp_aperta2_phymod_phy_rx_slicer_position_set */
    NULL, /* plp_aperta2_phymod_phy_rx_slicer_position_get */
    NULL, /* plp_aperta2_phymod_phy_rx_slicer_position_max_get */
    plp_aperta2_phy_prbs_config_set,
    plp_aperta2_phy_prbs_config_get,
    plp_aperta2_phy_prbs_enable_set,
    plp_aperta2_phy_prbs_enable_get,
    plp_aperta2_phy_prbs_status_get,
    NULL, /* plp_aperta2_phymod_phy_pattern_config_set */
    NULL, /* plp_aperta2_phymod_phy_pattern_config_get */
    plp_aperta2_phy_pattern_enable_set,
    plp_aperta2_phy_pattern_enable_get,
    plp_aperta2_core_diagnostics_get,
    plp_aperta2_phy_diagnostics_get,
    plp_aperta2_phy_pam4_diagnostics_get,
    plp_aperta2_phy_pmd_info_dump,
    NULL, /* plp_aperta2_phymod_phy_pcs_info_dump */
    plp_aperta2_phy_eyescan_run,
    plp_aperta2_phy_link_mon_enable_set,
    plp_aperta2_phy_link_mon_enable_get,
    plp_aperta2_phy_link_mon_status_get,
    plp_aperta2_phy_fec_correctable_counter_get,
    plp_aperta2_phy_fec_uncorrectable_counter_get,
    NULL, /* plp_aperta2_phymod_phy_prbs_error_inject_set */
    plp_aperta2_phy_prbs_error_analyzer_proj,
};

#endif /* PHYMOD_APERTA2_SUPPORT */
