/*
 *
 * $Id:$
 *
 * $Copyright: (c) 2020 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *
 *
 * DO NOT EDIT THIS FILE!
 *
 */

#ifndef _aperta_pm8x50_H__H_
#define _aperta_pm8x50_H__H_

#include <phymod/phymod.h>
#include <phymod/phymod_diagnostics.h>
#include <phymod/phymod_reg.h>
#include <include/portmod_defs.h>
/**/
int plp_aperta_pm8x50_port_speed_ability_local_get(int unit, int port, int max_num_abilities, portmod_port_speed_ability_t* abilities, int* num_abilities);

/*Get whether the inerface type is supported by PM */
int plp_aperta_pm8x50_pm_interface_type_is_supported(int unit, soc_port_if_t interface_t, int* is_supported);

/*Add new pm.*/
int plp_aperta_pm8x50_pm_init(int unit, const portmod_pm_create_info_internal_t* pm_add_info, int wb_buffer_index, pm_info_t pm_info);

/*Release PM resources*/
int plp_aperta_pm8x50_pm_destroy(int unit, pm_info_t pm_info);

/*Add new port*/
int plp_aperta_pm8x50_port_attach(int unit, int port, pm_info_t pm_info, const portmod_port_add_info_t* add_info);

/*Set PM in bypass mode. should be called in the aggregator code.*/
int plp_aperta_pm8x50_pm_bypass_set(int unit, pm_info_t pm_info, int enable);

/*get port cores' phymod access*/
int plp_aperta_pm8x50_pm_core_info_get(int unit, pm_info_t pm_info, int phyn, portmod_pm_core_info_t* core_info);

/*Get PM phys.*/
int plp_aperta_pm8x50_pm_phys_get(int unit, pm_info_t pm_info, int* phys);

/*Port remove in PM level*/
int plp_aperta_pm8x50_port_detach(int unit, int port, pm_info_t pm_info);

/*Port replace in PM level*/
int plp_aperta_pm8x50_port_replace(int unit, int port, pm_info_t pm_info, int new_port);

/*Port enable*/
int plp_aperta_pm8x50_port_enable_set(int unit, int port, pm_info_t pm_info, int flags, int enable);
int plp_aperta_pm8x50_port_enable_get(int unit, int port, pm_info_t pm_info, int flags, int* enable);

/* set/get the interface_t, speed and encapsulation for the specified port.
            For the First port within core this function initialize the PM, MAC and PHY before configure the port.*/
int plp_aperta_pm8x50_port_interface_config_set(int unit, int port, pm_info_t pm_info, const portmod_port_interface_config_t* config, int phy_init_flags);
int plp_aperta_pm8x50_port_interface_config_get(int unit, int port, pm_info_t pm_info, portmod_port_interface_config_t* config, int phy_init_flags);

/*Port cl72 set\get*/
int plp_aperta_pm8x50_port_cl72_set(int unit, int port, pm_info_t pm_info, uint32_t enable);
int plp_aperta_pm8x50_port_cl72_get(int unit, int port, pm_info_t pm_info, uint32_t* enable);

/*Get port cl72 status*/
int plp_aperta_pm8x50_port_cl72_status_get(int unit, int port, pm_info_t pm_info, plp_aperta_phymod_cl72_status_t* status);

/*Port speed set\get*/
int plp_aperta_pm8x50_port_loopback_set(int unit, int port, pm_info_t pm_info, portmod_loopback_mode_t loopback_type, int enable);
int plp_aperta_pm8x50_port_loopback_get(int unit, int port, pm_info_t pm_info, portmod_loopback_mode_t loopback_type, int* enable);

/*Port RX MAC ENABLE set\get*/
int plp_aperta_pm8x50_port_rx_mac_enable_set(int unit, int port, pm_info_t pm_info, int enable);
int plp_aperta_pm8x50_port_rx_mac_enable_get(int unit, int port, pm_info_t pm_info, int* enable);

/*Port TX MAC ENABLE set\get*/
int plp_aperta_pm8x50_port_tx_mac_enable_set(int unit, int port, pm_info_t pm_info, int enable);
int plp_aperta_pm8x50_port_tx_mac_enable_get(int unit, int port, pm_info_t pm_info, int* enable);

/*Set\Get autoneg*/
int plp_aperta_pm8x50_port_autoneg_set(int unit, int port, pm_info_t pm_info, uint32_t phy_flags, const plp_aperta_phymod_autoneg_control_t* an);
int plp_aperta_pm8x50_port_autoneg_get(int unit, int port, pm_info_t pm_info, uint32_t phy_flags, plp_aperta_phymod_autoneg_control_t* an);

/*Get autoneg status*/
int plp_aperta_pm8x50_port_autoneg_status_get(int unit, int port, pm_info_t pm_info, plp_aperta_phymod_autoneg_status_t* an_status);

/*get link status*/
int plp_aperta_pm8x50_port_link_get(int unit, int port, pm_info_t pm_info, int flags, int* link);

/*get latch down link status (whether link was ever down since last clear)*/
int plp_aperta_pm8x50_port_link_latch_down_get(int unit, int port, pm_info_t pm_info, uint32_t flags, int* link);

/* link up event */
int plp_aperta_pm8x50_port_phy_link_up_event(int unit, int port, pm_info_t pm_info);

/* link down event */
int plp_aperta_pm8x50_port_phy_link_down_event(int unit, int port, pm_info_t pm_info);

/*PRBS configuration set/get*/
int plp_aperta_pm8x50_port_prbs_config_set(int unit, int port, pm_info_t pm_info, portmod_prbs_mode_t mode, int flags, const plp_aperta_phymod_prbs_t* config);
int plp_aperta_pm8x50_port_prbs_config_get(int unit, int port, pm_info_t pm_info, portmod_prbs_mode_t mode, int flags, plp_aperta_phymod_prbs_t* config);

/*PRBS enable set/get*/
int plp_aperta_pm8x50_port_prbs_enable_set(int unit, int port, pm_info_t pm_info, portmod_prbs_mode_t mode, int flags, int enable);
int plp_aperta_pm8x50_port_prbs_enable_get(int unit, int port, pm_info_t pm_info, portmod_prbs_mode_t mode, int flags, int* enable);

/*PRBS status get*/
int plp_aperta_pm8x50_port_prbs_status_get(int unit, int port, pm_info_t pm_info, portmod_prbs_mode_t mode, int flags, plp_aperta_phymod_prbs_status_t* status);

/*Number of lanes get*/
int plp_aperta_pm8x50_port_nof_lanes_get(int unit, int port, int* nof_lanes);

/*Set port PHYs' firmware mode*/
int plp_aperta_pm8x50_port_firmware_mode_set(int unit, int port, pm_info_t pm_info, phymod_firmware_mode_t fw_mode);
int plp_aperta_pm8x50_port_firmware_mode_get(int unit, int port, pm_info_t pm_info, phymod_firmware_mode_t* fw_mode);

/*Filter packets smaller than the specified threshold*/
int plp_aperta_pm8x50_port_runt_threshold_set(int unit, int port, pm_info_t pm_info, int value);
int plp_aperta_pm8x50_port_runt_threshold_get(int unit, int port, pm_info_t pm_info, int* value);

/*Filter packets bigger than the specified value*/
int plp_aperta_pm8x50_port_max_packet_size_set(int unit, int port, pm_info_t pm_info, int value);
int plp_aperta_pm8x50_port_max_packet_size_get(int unit, int port, pm_info_t pm_info, int* value);

/*TX pad packets to the specified size. values smaller than 17 means pad is disabled.*/
int plp_aperta_pm8x50_port_pad_size_set(int unit, int port, pm_info_t pm_info, int value);
int plp_aperta_pm8x50_port_pad_size_get(int unit, int port, pm_info_t pm_info, int* value);

/*set/get the MAC source address that will be sent in case of Pause/LLFC*/
int plp_aperta_pm8x50_port_tx_mac_sa_set(int unit, int port, pm_info_t pm_info, pm_mac_addr_t mac_sa);
int plp_aperta_pm8x50_port_tx_mac_sa_get(int unit, int port, pm_info_t pm_info, pm_mac_addr_t mac_sa);

/*set/get SA recognized for MAC control packets in addition to the standard 0x0180C2000001*/
int plp_aperta_pm8x50_port_rx_mac_sa_set(int unit, int port, pm_info_t pm_info, pm_mac_addr_t mac_sa);
int plp_aperta_pm8x50_port_rx_mac_sa_get(int unit, int port, pm_info_t pm_info, pm_mac_addr_t mac_sa);

/*set/get Average inter-packet gap*/
int plp_aperta_pm8x50_port_tx_average_ipg_set(int unit, int port, pm_info_t pm_info, int value);
int plp_aperta_pm8x50_port_tx_average_ipg_get(int unit, int port, pm_info_t pm_info, int* value);

/*local fault set/get*/
int plp_aperta_pm8x50_port_local_fault_control_set(int unit, int port, pm_info_t pm_info, const portmod_local_fault_control_t* control);
int plp_aperta_pm8x50_port_local_fault_control_get(int unit, int port, pm_info_t pm_info, portmod_local_fault_control_t* control);

/*remote fault set/get*/
int plp_aperta_pm8x50_port_remote_fault_control_set(int unit, int port, pm_info_t pm_info, const portmod_remote_fault_control_t* control);
int plp_aperta_pm8x50_port_remote_fault_control_get(int unit, int port, pm_info_t pm_info, portmod_remote_fault_control_t* control);

/*local fault steatus get*/
int plp_aperta_pm8x50_port_local_fault_status_get(int unit, int port, pm_info_t pm_info, int* value);

/*remote fault status get*/
int plp_aperta_pm8x50_port_remote_fault_status_get(int unit, int port, pm_info_t pm_info, int* value);

/*local fault steatus clear*/
int plp_aperta_pm8x50_port_local_fault_status_clear(int unit, int port, pm_info_t pm_info);

/*remote fault status clear*/
int plp_aperta_pm8x50_port_remote_fault_status_clear(int unit, int port, pm_info_t pm_info);

/*set/get Pause FC configuration*/
int plp_aperta_pm8x50_port_pause_control_set(int unit, int port, pm_info_t pm_info, const portmod_pause_control_t* control);
int plp_aperta_pm8x50_port_pause_control_get(int unit, int port, pm_info_t pm_info, portmod_pause_control_t* control);

/*set/get PFC FC configuration*/
int plp_aperta_pm8x50_port_pfc_control_set(int unit, int port, pm_info_t pm_info, const portmod_pfc_control_t* control);
int plp_aperta_pm8x50_port_pfc_control_get(int unit, int port, pm_info_t pm_info, portmod_pfc_control_t* control);

/*Routine for MAC\PHY sync.*/
int plp_aperta_pm8x50_port_update(int unit, int port, pm_info_t pm_info, const portmod_port_update_control_t* update_control);

/*get port cores' phymod access*/
int plp_aperta_pm8x50_port_core_access_get(int unit, int port, pm_info_t pm_info, int phyn, int max_cores, plp_aperta_phymod_core_access_t* core_access_arr, int* nof_cores, int* is_most_ext);

/*Get lane phymod access structure. can be used for per lane operations*/
int plp_aperta_pm8x50_port_phy_lane_access_get(int unit, int port, pm_info_t pm_info, const portmod_access_get_params_t* params, int max_phys, plp_aperta_phymod_phy_access_t* access, int* nof_phys, int* is_most_ext);

/*Port duplex set\get*/
int plp_aperta_pm8x50_port_duplex_set(int unit, int port, pm_info_t pm_info, int enable);
int plp_aperta_pm8x50_port_duplex_get(int unit, int port, pm_info_t pm_info, int* enable);

/*Port PHY Control register read*/
int plp_aperta_pm8x50_port_phy_reg_read(int unit, int port, pm_info_t pm_info, int flags, int reg_addr, uint32_t* value);

/*Port PHY Control register write*/
int plp_aperta_pm8x50_port_phy_reg_write(int unit, int port, pm_info_t pm_info, int flags, int reg_addr, uint32_t value);

/*Port Reset set\get*/
int plp_aperta_pm8x50_port_reset_set(int unit, int port, pm_info_t pm_info, int mode, int opcode, int value);
int plp_aperta_pm8x50_port_reset_get(int unit, int port, pm_info_t pm_info, int mode, int opcode, int* value);

/*Drv Name Get*/
int plp_aperta_pm8x50_port_drv_name_get(int unit, int port, pm_info_t pm_info, char* name, int len);

/*set/get port fec enable according to local/remote FEC ability*/
int plp_aperta_pm8x50_port_fec_enable_set(int unit, int port, pm_info_t pm_info, uint32_t enable);
int plp_aperta_pm8x50_port_fec_enable_get(int unit, int port, pm_info_t pm_info, uint32_t* enable);

/*get port auto negotiation local ability*/
int plp_aperta_pm8x50_port_ability_advert_set(int unit, int port, pm_info_t pm_info, portmod_port_ability_t* ability);
int plp_aperta_pm8x50_port_ability_advert_get(int unit, int port, pm_info_t pm_info, portmod_port_ability_t* ability);

/*Port ability remote Adv get*/
int plp_aperta_pm8x50_port_ability_remote_get(int unit, int port, pm_info_t pm_info, portmod_port_ability_t* ability);

/*Port Mac Control Spacing Stretch*/
int plp_aperta_pm8x50_port_frame_spacing_stretch_set(int unit, int port, pm_info_t pm_info, int spacing);
int plp_aperta_pm8x50_port_frame_spacing_stretch_get(int unit, int port, pm_info_t pm_info, const int* spacing);

/*get port timestamps in fifo*/
int plp_aperta_pm8x50_port_diag_fifo_status_get(int unit, int port, pm_info_t pm_info, const portmod_fifo_status_t* diag_info);

/*set/get pass control frames.*/
int plp_aperta_pm8x50_port_rx_control_set(int unit, int port, pm_info_t pm_info, const portmod_rx_control_t* rx_ctrl);
int plp_aperta_pm8x50_port_rx_control_get(int unit, int port, pm_info_t pm_info, portmod_rx_control_t* rx_ctrl);

/*set PFC config registers.*/
int plp_aperta_pm8x50_port_pfc_config_set(int unit, int port, pm_info_t pm_info, const portmod_pfc_config_t* pfc_cfg);
int plp_aperta_pm8x50_port_pfc_config_get(int unit, int port, pm_info_t pm_info, portmod_pfc_config_t* pfc_cfg);

/*set EEE Config.*/
int plp_aperta_pm8x50_port_eee_set(int unit, int port, pm_info_t pm_info, const portmod_eee_t* eee);
int plp_aperta_pm8x50_port_eee_get(int unit, int port, pm_info_t pm_info, portmod_eee_t* eee);

/*set EEE Config.*/
int plp_aperta_pm8x50_port_eee_clock_set(int unit, int port, pm_info_t pm_info, const portmod_eee_clock_t* eee_clk);
int plp_aperta_pm8x50_port_eee_clock_get(int unit, int port, pm_info_t pm_info, portmod_eee_clock_t* eee_clk);

/*set Vlan Inner/Outer tag.*/
int plp_aperta_pm8x50_port_vlan_tag_set(int unit, int port, pm_info_t pm_info, const portmod_vlan_tag_t* vlan_tag);
int plp_aperta_pm8x50_port_vlan_tag_get(int unit, int port, pm_info_t pm_info, portmod_vlan_tag_t* vlan_tag);

/*set modid field.*/
int plp_aperta_pm8x50_port_modid_set(int unit, int port, pm_info_t pm_info, int value);

/*set modid field.*/
int plp_aperta_pm8x50_port_led_chain_config(int unit, int port, pm_info_t pm_info, int value);

/*set modid field.*/
int plp_aperta_pm8x50_port_clear_rx_lss_status_set(int unit, int port, pm_info_t pm_info, int lcl_fault, int rmt_fault);
int plp_aperta_pm8x50_port_clear_rx_lss_status_get(int unit, int port, pm_info_t pm_info, int* lcl_fault, int* rmt_fault);

/*Attaches an external phy lane to a specific port macro*/
int plp_aperta_pm8x50_xphy_lane_attach_to_pm(int unit, pm_info_t pm_info, int iphy, int phyn, const portmod_xphy_lane_connection_t* lane_connection);

/*Attaches an external phy lane to a specific port macro*/
int plp_aperta_pm8x50_xphy_lane_detach_from_pm(int unit, pm_info_t pm_info, int iphy, int phyn, portmod_xphy_lane_connection_t* lane_connection);

/*Toggle Lag Failover Status.*/
int plp_aperta_pm8x50_port_lag_failover_status_toggle(int unit, int port, pm_info_t pm_info);

/*Toggle Lag Failover loopback set / get.*/
int plp_aperta_pm8x50_port_lag_failover_loopback_set(int unit, int port, pm_info_t pm_info, int value);
int plp_aperta_pm8x50_port_lag_failover_loopback_get(int unit, int port, pm_info_t pm_info, int* value);

/*set port mode.*/
int plp_aperta_pm8x50_port_mode_set(int unit, int port, pm_info_t pm_info, const portmod_port_mode_info_t* mode);
int plp_aperta_pm8x50_port_mode_get(int unit, int port, pm_info_t pm_info, portmod_port_mode_info_t* mode);

/*set port encap.*/
int plp_aperta_pm8x50_port_encap_set(int unit, int port, pm_info_t pm_info, int flags, portmod_encap_t encap);
int plp_aperta_pm8x50_port_encap_get(int unit, int port, pm_info_t pm_info, int* flags, portmod_encap_t* encap);

/*set port register higig field.*/
int plp_aperta_pm8x50_port_higig_mode_set(int unit, int port, pm_info_t pm_info, int mode);
int plp_aperta_pm8x50_port_higig_mode_get(int unit, int port, pm_info_t pm_info, int* mode);

/*set port register higig field.*/
int plp_aperta_pm8x50_port_higig2_mode_set(int unit, int port, pm_info_t pm_info, int mode);
int plp_aperta_pm8x50_port_higig2_mode_get(int unit, int port, pm_info_t pm_info, int* mode);

/*set port register port type field.*/
int plp_aperta_pm8x50_port_config_port_type_set(int unit, int port, pm_info_t pm_info, int type);
int plp_aperta_pm8x50_port_config_port_type_get(int unit, int port, pm_info_t pm_info, int* type);

/*set/get hwfailover for trident.*/
int plp_aperta_pm8x50_port_trunk_hwfailover_config_set(int unit, int port, pm_info_t pm_info, int hw_count);
int plp_aperta_pm8x50_port_trunk_hwfailover_config_get(int unit, int port, pm_info_t pm_info, int* enable);

/*set/get hwfailover for trident.*/
int plp_aperta_pm8x50_port_trunk_hwfailover_status_get(int unit, int port, pm_info_t pm_info, int* loopback);

/*port diagnostics control.*/
int plp_aperta_pm8x50_port_diag_ctrl(int unit, int port, pm_info_t pm_info, uint32_t inst, int op_type, int op_cmd, const void* arg);

/*Get the reference clock value 156 or 125.*/
int plp_aperta_pm8x50_port_ref_clk_get(int unit, int port, pm_info_t pm_info, int* ref_clk);

/*Disable lag failover.*/
int plp_aperta_pm8x50_port_lag_failover_disable(int unit, int port, pm_info_t pm_info);

/*Disable lag failover.*/
int plp_aperta_pm8x50_port_lag_remove_failover_lpbk_set(int unit, int port, pm_info_t pm_info, int val);
int plp_aperta_pm8x50_port_lag_remove_failover_lpbk_get(int unit, int port, pm_info_t pm_info, int* val);

/*Disable lag failover.*/
int plp_aperta_pm8x50_port_cntmaxsize_set(int unit, int port, pm_info_t pm_info, int val);
int plp_aperta_pm8x50_port_cntmaxsize_get(int unit, int port, pm_info_t pm_info, int* val);

/*Get Info needed to restore after drain cells.*/
int plp_aperta_pm8x50_port_drain_cell_get(int unit, int port, pm_info_t pm_info, portmod_drain_cells_t* drain_cells);

/*Restore informaation after drain cells.*/
int plp_aperta_pm8x50_port_drain_cell_stop(int unit, int port, pm_info_t pm_info, const portmod_drain_cells_t* drain_cells);

/*Restore informaation after drain cells.*/
int plp_aperta_pm8x50_port_drain_cell_start(int unit, int port, pm_info_t pm_info);

/**/
int plp_aperta_pm8x50_port_drain_cells_rx_enable(int unit, int port, pm_info_t pm_info, int rx_en);

/**/
int plp_aperta_pm8x50_port_egress_queue_drain_rx_en(int unit, int port, pm_info_t pm_info, int rx_en);

/**/
int plp_aperta_pm8x50_port_mac_ctrl_set(int unit, int port, pm_info_t pm_info, uint64_t ctrl);

/**/
int plp_aperta_pm8x50_port_txfifo_cell_cnt_get(int unit, int port, pm_info_t pm_info, uint32_t* cnt);

/**/
int plp_aperta_pm8x50_port_egress_queue_drain_get(int unit, int port, pm_info_t pm_info, uint64_t* ctrl, int* rxen);

/**/
int plp_aperta_pm8x50_port_mac_reset_set(int unit, int port, pm_info_t pm_info, int val);

/**/
int plp_aperta_pm8x50_port_soft_reset_toggle(int unit, int port, pm_info_t pm_info, int idx);

/*Check if MAC needs to be reset.*/
int plp_aperta_pm8x50_port_mac_reset_check(int unit, int port, pm_info_t pm_info, int enable, int* reset);

/**/
int plp_aperta_pm8x50_port_core_num_get(int unit, int port, pm_info_t pm_info, int* core_num);

/**/
int plp_aperta_pm8x50_port_e2ecc_hdr_set(int unit, int port, pm_info_t pm_info, const portmod_port_higig_e2ecc_hdr_t* e2ecc_hdr);
int plp_aperta_pm8x50_port_e2ecc_hdr_get(int unit, int port, pm_info_t pm_info, portmod_port_higig_e2ecc_hdr_t* e2ecc_hdr);

/**/
int plp_aperta_pm8x50_port_e2e_enable_set(int unit, int port, pm_info_t pm_info, int enable);
int plp_aperta_pm8x50_port_e2e_enable_get(int unit, int port, pm_info_t pm_info, int* enable);

/*get the speed for the specified port*/
int plp_aperta_pm8x50_port_speed_get(int unit, int port, pm_info_t pm_info, int* speed);

/*TSC refere clock input and output set/get*/
int plp_aperta_pm8x50_port_tsc_refclock_set(int unit, int port, pm_info_t pm_info, int ref_in, int ref_out);
int plp_aperta_pm8x50_port_tsc_refclock_get(int unit, int port, pm_info_t pm_info, int* ref_in, int* ref_out);

/*Port discard set*/
int plp_aperta_pm8x50_port_discard_set(int unit, int port, pm_info_t pm_info, int discard);

/*Port soft reset set set*/
int plp_aperta_pm8x50_port_soft_reset_set(int unit, int port, pm_info_t pm_info, int idx, int val, int flags);

/*Port tx_en=0 and softreset mac*/
int plp_aperta_pm8x50_port_tx_down(int unit, int port, pm_info_t pm_info);

/*reconfig pgw.*/
int plp_aperta_pm8x50_port_pgw_reconfig(int unit, int port, pm_info_t pm_info, const portmod_port_mode_info_t* pmode, int phy_port, int flags);

/*Routine to notify internal phy of external phy link state.*/
int plp_aperta_pm8x50_port_notify(int unit, int port, pm_info_t pm_info, int link);

/*"port control phy timesync config set/get"*/
int plp_aperta_pm8x50_port_control_phy_timesync_set(int unit, int port, pm_info_t pm_info, portmod_port_control_phy_timesync_t config, uint64_t value);
int plp_aperta_pm8x50_port_control_phy_timesync_get(int unit, int port, pm_info_t pm_info, portmod_port_control_phy_timesync_t config, uint64_t* value);

/*"port timesync config set/get"*/
int plp_aperta_pm8x50_port_timesync_config_set(int unit, int port, pm_info_t pm_info, const portmod_phy_timesync_config_t* config);
int plp_aperta_pm8x50_port_timesync_config_get(int unit, int port, pm_info_t pm_info, portmod_phy_timesync_config_t* config);

/*"port timesync enable set/get"*/
int plp_aperta_pm8x50_port_timesync_enable_set(int unit, int port, pm_info_t pm_info, uint32_t enable);
int plp_aperta_pm8x50_port_timesync_enable_get(int unit, int port, pm_info_t pm_info, uint32_t* enable);

/*"port timesync nco addend  set/get"*/
int plp_aperta_pm8x50_port_timesync_nco_addend_set(int unit, int port, pm_info_t pm_info, uint32_t freq_step);
int plp_aperta_pm8x50_port_timesync_nco_addend_get(int unit, int port, pm_info_t pm_info, uint32_t* freq_step);

/*"port timesync framesync info  set/get"*/
int plp_aperta_pm8x50_port_timesync_framesync_mode_set(int unit, int port, pm_info_t pm_info, const portmod_timesync_framesync_t* framesync);
int plp_aperta_pm8x50_port_timesync_framesync_mode_get(int unit, int port, pm_info_t pm_info, portmod_timesync_framesync_t* framesync);

/*"port timesync local time  set/get"*/
int plp_aperta_pm8x50_port_timesync_local_time_set(int unit, int port, pm_info_t pm_info, uint64_t local_time);
int plp_aperta_pm8x50_port_timesync_local_time_get(int unit, int port, pm_info_t pm_info, uint64_t* local_time);

/*"port timesync framesync info  set/get"*/
int plp_aperta_pm8x50_port_timesync_load_ctrl_set(int unit, int port, pm_info_t pm_info, uint32_t load_once, uint32_t load_always);
int plp_aperta_pm8x50_port_timesync_load_ctrl_get(int unit, int port, pm_info_t pm_info, uint32_t* load_once, uint32_t* load_always);

/*"port timesync tx timestamp offset set/get"*/
int plp_aperta_pm8x50_port_timesync_tx_timestamp_offset_set(int unit, int port, pm_info_t pm_info, uint32_t ts_offset);
int plp_aperta_pm8x50_port_timesync_tx_timestamp_offset_get(int unit, int port, pm_info_t pm_info, uint32_t* ts_offset);

/*"port timesync rx timestamp offset set/get"*/
int plp_aperta_pm8x50_port_timesync_rx_timestamp_offset_set(int unit, int port, pm_info_t pm_info, uint32_t ts_offset);
int plp_aperta_pm8x50_port_timesync_rx_timestamp_offset_get(int unit, int port, pm_info_t pm_info, uint32_t* ts_offset);

/*set/get interrupt enable value. */
int plp_aperta_pm8x50_port_interrupt_enable_set(int unit, int port, pm_info_t pm_info, int intr_type, uint32_t val);
int plp_aperta_pm8x50_port_interrupt_enable_get(int unit, int port, pm_info_t pm_info, int intr_type, uint32_t* val);

/*get interrupt status value. */
int plp_aperta_pm8x50_port_interrupt_get(int unit, int port, pm_info_t pm_info, int intr_type, uint32_t* val);

/*get interrupt value array. */
int plp_aperta_pm8x50_port_interrupts_get(int unit, int port, pm_info_t pm_info, int arr_max_size, uint32_t* intr_arr, uint32_t* size);

/* portmod check if external phy is legacy*/
int plp_aperta_pm8x50_port_check_legacy_phy(int unit, int port, pm_info_t pm_info, int* legacy_phy);

/* portmod phy failover mode*/
int plp_aperta_pm8x50_port_failover_mode_set(int unit, int port, pm_info_t pm_info, plp_aperta_phymod_failover_mode_t failover);
int plp_aperta_pm8x50_port_failover_mode_get(int unit, int port, pm_info_t pm_info, plp_aperta_phymod_failover_mode_t* failover);

/* portmod port rsv mask set*/
int plp_aperta_pm8x50_port_mac_rsv_mask_set(int unit, int port, pm_info_t pm_info, uint32_t rsv_mask);

/* portmod port mib reset toggle*/
int plp_aperta_pm8x50_port_mib_reset_toggle(int unit, int port, pm_info_t pm_info, int port_index);

/* portmod restore information after warmboot*/
int plp_aperta_pm8x50_port_warmboot_db_restore(int unit, int port, pm_info_t pm_info, const portmod_port_interface_config_t* intf_config, const portmod_port_init_config_t* init_config, plp_aperta_phymod_operation_mode_t phy_op_mode);

/* portmod port flow control config*/
int plp_aperta_pm8x50_port_flow_control_set(int unit, int port, pm_info_t pm_info, int merge_mode_en, int parallel_fc_en);

/*Portmod state for any logical port dynamixc settings*/
int plp_aperta_pm8x50_port_update_dynamic_state(int unit, int port, pm_info_t pm_info, uint32_t port_dynamic_state);

/*get phy operation mode. */
int plp_aperta_pm8x50_port_phy_op_mode_get(int unit, int port, pm_info_t pm_info, plp_aperta_phymod_operation_mode_t* val);

/*PM Core init routine for DNX devices; XGS does not call this API but calls plp_aperta_portmod_pm_serdes_core_init() directly*/
int plp_aperta_pm8x50_core_add(int unit, int pm_id, pm_info_t pm_info, const portmod_port_add_info_t* add_info);

/*PM Core init routine*/
int plp_aperta_pm8x50_pm_serdes_core_init(int unit, int pm_id, pm_info_t pm_info, const portmod_port_add_info_t* add_info);

/*Returns if the PortMacro associated with the port is initialized or not*/
int plp_aperta_pm8x50_pm_is_initialized(int unit, int pm_id, pm_info_t pm_info, int* is_initialized);

/*Port speed validation.*/
int plp_aperta_pm8x50_port_speed_config_validate(int unit, int port, pm_info_t pm_info, const portmod_speed_config_t* speed_config, int* affected_pbmp);

/*Enable port macro.*/
int plp_aperta_pm8x50_pm_enable(int unit, int pm_id, pm_info_t pm_info, int enable);

/*Get the logical port bitmap based on the input PM ID*/
int plp_aperta_pm8x50_pm_logical_pbmp_get(int unit, int pm_id, pm_info_t pm_info, int* logical_pbmp);

/*Reconfigure the vco rate for pm core.*/
int plp_aperta_pm8x50_pm_vco_reconfig(int unit, int pm_id, pm_info_t pm_info, const portmod_vco_type_t* vco);

/* set/get the speed config for the specified port.*/
int plp_aperta_pm8x50_port_speed_config_set(int unit, int port, pm_info_t pm_info, const portmod_speed_config_t* speed_config);
int plp_aperta_pm8x50_port_speed_config_get(int unit, int port, pm_info_t pm_info, portmod_speed_config_t* speed_config);

/*Validate a set of speed config within a port macro.*/
int plp_aperta_pm8x50_pm_speed_config_validate(int unit, int pm_id, pm_info_t pm_info, const int* ports, int flag, portmod_pm_vco_setting_t* vco_setting);

/*Get the suggested VCO values based on the speed config list of a PM*/
int plp_aperta_pm8x50_pm_vcos_get(int unit, portmod_dispatch_type_t pm_type, portmod_pm_vco_setting_t* vco_select);

/*Set/get port auto negotiation ability*/
int plp_aperta_pm8x50_port_autoneg_ability_advert_set(int unit, int port, pm_info_t pm_info, int num_abilities, const portmod_port_speed_ability_t* abilities);
int plp_aperta_pm8x50_port_autoneg_ability_advert_get(int unit, int port, pm_info_t pm_info, int max_num_abilities, portmod_port_speed_ability_t* abilities, int* actual_num_abilities);

/*Port ability remote Adv get*/
int plp_aperta_pm8x50_port_autoneg_ability_remote_get(int unit, int port, pm_info_t pm_info, int max_num_abilities, portmod_port_speed_ability_t* abilities, int* actual_num_abilities);

/*Port tx taps set\get*/
int plp_aperta_pm8x50_port_tx_set(int unit, int port, pm_info_t pm_info, const plp_aperta_phymod_tx_t* tx);
int plp_aperta_pm8x50_port_tx_get(int unit, int port, pm_info_t pm_info, plp_aperta_phymod_tx_t* tx);

int _plp_aperta_pm8x50_port_phy_to_port_ability(phymod_autoneg_advert_abilities_t* an_advert_abilities,
                                     int* num_abilities,
                                     portmod_port_speed_ability_t* abilities);
int _plp_aperta_pm8x50_port_port_to_phy_ability(int num_abilities,
                                     const portmod_port_speed_ability_t* abilities,
                                     phymod_autoneg_advert_abilities_t* an_advert_abilities);


#endif /*_aperta_pm8x50_H_*/
