#ifndef SE_CONFIG_MODE_H
#define SE_CONFIG_MODE_H

#include <stdint.h>

#define FW_FEATURE_ENABLE                          0xFFFFFF
#define FW_FEATURE_SUPPORT_40B_DATA                (1 << 0)
#define FW_FEATURE_SUPPORT_SWITCHOVER_RETIMER_MODE (1 << 1)
#define FW_FEATURE_SUPPORT_READ_VSENSOR            (1 << 2)
#define FW_FEATURE_SUPPORT_FLEXSPEED               (1 << 3)

/* detail 1*/
#define FW_OPTION_OPT_MODE     (1 << 12)
#define FW_OPTION_ISC_ENABLE   (1 << 13)
#define FW_OPTION_AN_OVERRIDE  (1 << 14)
#define FW_OPTION_ISC_AN_AGENT (1 << 15)

/* detail 2 */
#define FW_LINE_ARBITRARY_MAIN_OFFSET 0
#define FW_SYS_ARBITRARY_MAIN_OFFSET  6
#define FW_OPTION_LINE_ARBITRARY_MAIN (1 << 3)
#define FW_OPTION_LINE_SIDE_AN        (1 << 4)
#define FW_OPTION_LINE_SIDE_LT        (1 << 5)
#define FW_OPTION_SYS_ARBITRARY_MAIN  (1 << 9)
#define FW_OPTION_SYS_SIDE_AN         (1 << 10)
#define FW_OPTION_SYS_SIDE_LT         (1 << 11)

// detail3

#define FW_OPTION_ISC_SYS_MAIN_OFFSET  3
#define FW_OPTION_ISC_LINE_MAIN_OFFSET 0

#define FW_ISI_TIMEOUT_PER_PHASE 20000  // ms

#define FW_RATE_FULL    0
#define FW_RATE_HALF    1
#define FW_RATE_QUARTER 2

#define FW_LOAD_MAGIC_WORD 0x5A5A
#define FW_LOADING_SPI     0x2000
#define FW_LOAD_FROM_SPI   0xFFF0
#define FW_UNLOAD_WORD     0xFFF1
#define FW_UNLOAD_DONE     0x4000

#define FW_EM_HSTEP_SIDE      16
#define FW_EM_VSTEP_SIDE_PAM4 63
#define FW_EM_VSTEP_SIDE_NRZ  48
#define FW_EM_VSTEP_SEPARATOR 0x7FFF

#define FW_RT_STATE_START       1
#define FW_RT_STATE_WAIT_PHY    2
#define FW_RT_STATE_WAIT_LT     3
#define FW_RT_STATE_ADJUST_FIFO 4
#define FW_RT_STATE_TRACK       5
#define FW_RT_STATE_RESET_FIFO  6

#define FW_BM_STATE_START        0
#define FW_BM_STATE_WAIT_PHY     1
#define FW_BM_STATE_WAIT_LT      2
#define FW_BM_STATE_RELEASE_FIFO 3
#define FW_BM_STATE_CHECK_FIFO   4
#define FW_BM_STATE_FUNCTIONAL   5
#define FW_BM_STATE_DONE         6

/* TX Control */
#define TX_CONTROL_STATE_MASK          (3 << 0)
#define TX_CONTROL_FORCED_SOURCE_SHIFT 2
#define TX_CONTROL_FORCED_SOURCE_MASK  (3 << TX_CONTROL_FORCED_SOURCE_SHIFT)
#define TX_CONTROL_NORMAL_SOURCE_SHIFT 4
#define TX_CONTROL_NORMAL_SOURCE_MASK  (3 << TX_CONTROL_NORMAL_SOURCE_SHIFT)

#define TX_CONTROL_SOURCE_QUIET     0
#define TX_CONTROL_SOURCE_PRBS_PAM4 1
#define TX_CONTROL_SOURCE_PRBS_NRZ  2
#define TX_CONTROL_SOURCE_DATA      3

#define TX_CONTROL_STATE_UNKNOWN   0
#define TX_CONTROL_STATE_FORCED    1
#define TX_CONTROL_STATE_NORMAL    2
#define TX_CONTROL_STATE_LOW_POWER 3

#define FW_TIME_UNIT           0.08589934592                  // 195.3125 / (2^24)
#define FW_STATE_TIME_UNIT     ((FW_TIME_UNIT * 1000) / 256)  // ms
#define FW_CONFIG_MODE_DELAY   20                             // ms, wait rx clk ready
#define FW_DECONFIG_MODE_DELAY 100                            // ms, wait firmware deconfig task
#define FW_STATE_RECORD_LEN    50

/* Firmware commands */
// TODO, change all enums to define
#define FW_CMD_FREEZE   0xD000
#define FW_CMD_UNFREEZE 0xD001

/* Load top param*/
#define LOAD_SRAM_CLK_EN 0x8000

/* Load serdes param*/
#define LOAD_FFE_PRE            0x8000
#define LOAD_FFE_PST            0x8001
#define LOAD_FFE_FLT            0x8002
#define LOAD_DFE_F0             0x8003
#define LOAD_DFE_F1             0x8004
#define LOAD_VGA                0x8005
#define LOAD_FFE_FLT_SEL        0x8008
#define LOAD_AGCGAIN            0x800A
#define LOAD_RECOVER_SD_TIMEOUT 0x8100
#define LOAD_SD_DELAY           0x8101

/* vsensor */
#define FW_VSENSOR_DEFAULT_RESOLUTION 3  // 0, 14-bit; 1, 12-bit; 2, 10-bit, 3, 8-bit
#define FW_VSENSOR_READ               (1 << 15)
#define FW_VSENSOR_RES_OFFSET         13
#define FW_VSENSOR_GROUP_OFFSET       9
#define FW_VSENSOR_INDEX_OFFSET       4
#define FW_VSENSOR_MODE_OFFSET        1

typedef union {
    uint32_t state;
    struct {
        uint32_t min_state : 8;
        uint32_t maj_state : 4;
        uint32_t mode : 4;
    } s;
} FirmwareState_t;

typedef enum {
    FW_CMD_SPI_WRITE = 0x1000,
    FW_CMD_SPI_READ = 0x1008,
    FW_CMD_SPI_STATUS = 0x100A,
    FW_CMD_SPI_ERASE = 0x100B,
    FW_CMD_EYE_MON_START = 0x5000,
    FW_CMD_EYE_MON_STOP = 0x5100,
    FW_CMD_EYE_MON_READ = 0x5200,
    FW_CMD_EYE_MON_PROG = 0x5300,
    FW_CMD_OPT = 0x6000,
    FW_CMD_TX_CONTROL = 0x7010,
    FW_CMD_LANE_RESET = 0x7040,
    FW_CMD_TRF_CONTROL = 0x7050,
    FW_CMD_TX_PI_CONTROL = 0x7060,
    FW_CMD_FORCE_LOOPBACK = 0x7070,
    FW_CMD_T2R_FORCE_LOOPBACK = 0x7080,
    FW_CMD_SWITCHOVER_RETIMER_SWITCH = 0x70C0,
    FW_CMD_VSENSOR_TESTPOINT_SEL_READ = 0x70D0,
    FW_CMD_LANE_DISABLE = 0x70B0,

    FW_CMD_CONFIG_MODE = 0x8000,
    FW_CMD_DESTROY_MODE = 0x9000,
    FW_CMD_PORT_REGISTER = 0xA000,
    FW_CMD_PORT_QUERY = 0xA010,
    FW_CMD_PORT_FP_CONTROL = 0xA020,
    FW_CMD_INFO = 0xB000,
    FW_CMD_STATE_LOAD_TOP = 0xC000,
    FW_CMD_STATE_LOAD_SERDES = 0xC001,
    FW_CMD_INTERNAL_REG_READ = 0xE010,
    FW_CMD_INTERNAL_REG_WRITE = 0xE020,

    FW_CMD_HASH_READ = 0xF000,
    FW_CMD_CRC_READ = 0xF001,
    FW_CMD_DATE_READ = 0xF002,
    FW_CMD_VER_READ = 0xF003,
    FW_CMD_FEATURE_EN = 0xF005,
    FW_CMD_FEATURE = 0xF006,
} FwCommand_t;

typedef enum {
    FW_MODE_RETIMER = 0,
    FW_MODE_BITMUX_A1B2 = 1,
    FW_MODE_BITMUX_A2B1 = 2,
    FW_MODE_FAR_LOOPBACK = 3,
    FW_MODE_UNI_RETIMER = 4,
    FW_MODE_SWITCHOVER_RETIMER = 5,
    FW_MODE_PHY = 7,
    FW_MODE_LOOPBACK = 8,
    FW_MODE_UNI_BITMUX_A1B2 = 9,
    FW_MODE_UNI_BITMUX_A2B1 = 10,
    FW_MODE_OFF = 0xFF,
} FirmwareMode_t;

typedef enum {
    SPEED_UNKNOWN = -1,
    SPEED_OFF = 0,
    SPEED_10G = 1,
    SPEED_20G = 2,
    SPEED_25G = 3,
    SPEED_26G = 4,
    SPEED_1G = 5,
    SPEED_51G = 7,
    SPEED_53G = 8,
    SPEED_56G = 10,
    SPEED_55G = 11,
    SPEED_106G = 12,
    SPEED_98G = 13,
    SPEED_90G = 14,
    SPEED_112G = 15,
} FirmwareSpeed_t;

typedef enum {
    CONFIG_1G = 1000,
    CONFIG_1P25G = 1250,
    CONFIG_10G = 10000,
    CONFIG_20G = 20000,
    CONFIG_25G = 25000,
    CONFIG_26G = 26000,
    CONFIG_50G = 50000,
    CONFIG_51G = 51000,
    CONFIG_53G = 53000,
    CONFIG_56G = 56000,
    CONFIG_90G = 90000,
    CONFIG_98G = 98000,
    CONFIG_100G = 100000,
    CONFIG_106G = 106000,
    CONFIG_112G = 112000,
    CONFIG_200G = 200000,
    CONFIG_400G = 400000,
} Speed_t;

typedef enum {
    OPT_CMD_LR = 0,
    OPT_CMD_BER = 1,
    OPT_CMD_EYE = 2,
    OPT_CMD_ISI = 3,
    OPT_CMD_FFE_FORCE_CM1 = 4,
    OPT_CMD_VULTURE_OPT = 5,
    OPT_CMD_VULTURE_PARAM_SEARCH = 6,
    OPT_CMD_VULTURE_OPT_VREF = 7,
    OPT_CMD_VULTURE_DFE_TO_VREF = 8,
    OPT_CMD_VULTURE_ENVELOPE = 9,
    OPT_CMD_VULTURE_AGCGAIN_SEARCH = 10,
    OPT_CMD_VULTURE_CDFLE = 11,
    OPT_CMD_AGC_GAIN = 12,
    OPT_CMD_AGC_DEGEN = 13,
    OPT_CMD_LOSS = 14,
    OPT_CMD_FFE = 15,
    OPT_CMD_DFE = 16,
    OPT_CMD_CHANNEL_EST = 17,
} OptCode_t;

typedef enum {
    OPT_DEBUG = 1,
    OPT_DEBUG_NRZ = 2,
    OPT_DEBUG_PAM4 = 3,
    OPT_DEBUG_RETIMER = 4,
    OPT_DEBUG_BITMUX = 5,
    OPT_DEBUG_LOOPBACK = 6,
    TOP_INFO = 8,
    ANLT_DEBUG = 13,
    SE_INFO = 15,
} InfoSection_t;

typedef enum {
    OPT_DEBUG_STATE = 0,
    OPT_DEBUG_IS_FULL_RATE = 3,
    OPT_DEBUG_RX_PPM_SHIFT = 4,
    OPT_DEBUG_RATE_MODE = 7,
    OPT_DEBUG_SD_DELAY = 8,
    OPT_DEBUG_SDT_SIGNAL = 57,
    OPT_DEBUG_SDT_P = 60,
    OPT_DEBUG_SDT_N = 61,
    OPT_DEBUG_AMP_P = 62,
    OPT_DEBUG_AMP_N = 63,
    OPT_DEBUG_SD_COUNT = 70,
    OPT_DEBUG_SD_TIMEOUT = 71,
    OPT_DEBUG_CHANNEL_LOSS_PSD0 = 90,
    OPT_DEBUG_CHANNEL_LOSS_PSD1 = 91,
    OPT_DEBUG_PRESET_INDEX = 93,
    OPT_DEBUG_CHANNEL_LOSS_HEX_HIGH = 94,
    OPT_DEBUG_CHANNEL_LOSS_HEX_LOW = 95,
    OPT_DEBUG_CHANNEL_LOSS = 97,
    OPT_DEBUG_LOG_DUMP_STAGE = 200,
    OPT_DEBUG_LOG_DUMP_LOG_TYPE = 201,       // read clear
    OPT_DEBUG_LOG_DUMP_LOG_WAIT_READ = 202,  // read clear
    OPT_DEBUG_LOG_DUMP_LOG_BREAK = 203,
    OPT_DEBUG_LOG_DUMP_PARAM_ID = 205,
    OPT_DEBUG_LOG_DUMP_PARAM_DATA = 215,
    OPT_DEBUG_LOG_DUMP_METRIC_ID = 225,
    OPT_DEBUG_LOG_DUMP_METRIC_DATA = 235,
    OPT_DEBUG_RX_PLL_CLK = 348,
    OPT_DEBUG_TX_PLL_CLK = 348,
    OPT_DEBUG_VCOCAP_RX_FINAL = 350,
    OPT_DEBUG_VCOCAP_TX_FINAL = 351,
    OPT_DEBUG_VCOCAP_RX_RESULT = 352,
    OPT_DEBUG_VCOCAP_TX_RESULT = 353,
    OPT_DEBUG_VCOCAP_RX_MIN = 354,
    OPT_DEBUG_VCOCAP_TX_MIN = 355,
    OPT_DEBUG_VCOCAP_RX_MARGIN_CNT = 356,
    OPT_DEBUG_VCOCAP_RX_TRGT_CNT = 357,
    OPT_DEBUG_VCOCAP_RX_DEBUG = 370,
    OPT_DEBUG_VCOCAP_TX_DEBUG = 500,
    OPT_DEBUG_VCOCAP_TX_MARGIN_CNT = 632,
    OPT_DEBUG_VCOCAP_TX_TRGT_CNT = 633,
    OPT_DEBUG_ISI_READY_OLD = 635,
    OPT_DEBUG_ISI_READY_CLEAR_OLD = 636,
    OPT_DEBUG_ISI_PHASE_OLD = 637,
    OPT_DEBUG_ISI_OLD = 638,
    OPT_DEBUG_EYE_ALL = 700,
    OPT_DEBUG_FFE_ALL = 1000,
    OPT_DEBUG_FFE_CM = 1000,
    OPT_DEBUG_FFE_CP = 1064,
    OPT_DEBUG_FFE_CF = 1192,
    OPT_DEBUG_FLT_SEL = 1320,
    OPT_DEBUG_DFE_ALL = 1400,
    OPT_DEBUG_DFE_F0 = 1400,
    OPT_DEBUG_DFE_F1 = 1416,
    OPT_DEBUG_DC_SAR = 1500,
    OPT_DEBUG_GAIN_SAR = 1600,
    OPT_DEBUG_VGA = 1700,
    OPT_DEBUG_DC_CMN = 1701,
    OPT_DEBUG_ISI_READY = 1800,
    OPT_DEBUG_ISI_READY_NEXT_PHS = 1801,
    OPT_DEBUG_ISI_PHASE = 1802,
    OPT_DEBUG_ISI_READ_INIT = 1803,  // start from phase 0 to read
    OPT_DEBUG_ISI = 1810,
    OPT_DEBUG_STATE_CNT = 2000,
    OPT_DEBUG_STATE_REC = 2001,
    OPT_DEBUG_STATE_MAX_CNT = 2099,
    OPT_DEBUG_STATE_TIMESTAMP = 2100,
    OPT_DEBUG_RX_PLL_SEARCH_RANGE = 3010,
    OPT_DEBUG_TX_PLL_SEARCH_RANGE = 3025,
    OPT_DEBUG_CMIS_SNR = 4052,
    OPT_DEBUG_STATE_CLEAR = 5002,
} OptDebugCode_t;

typedef enum {
    OPT_DEBUG_NRZ_EYE = 100,
} OptDebugNRZCode_t;

typedef enum {
    OPT_DEBUG_PAM4_EYE = 100,
} OptDebugPAM4Code_t;

typedef enum {
    RETIMER_DEBUG_STATE = 0,
} RetimerDebugCode_t;

typedef enum {
    BITMUX_DEBUG_STATE = 0,
} BitmuxDebugCode_t;

typedef enum {
    TOP_INFO_RX_STATE = 0,
    TOP_INFO_ERROR_STATE = 1,
    TOP_INFO_RESTART_COUNT = 2,
    TOP_INFO_READAPT_COUNT = 3,
    TOP_INFO_OPT_MODE = 4,
    TOP_INFO_SPEED = 6,

    TOP_INFO_LINK_LOST_COUNT = 9,
    TOP_INFO_STARTUP_TIME = 10,
    TOP_INFO_LOS_COUNT = 11,

    TOP_INFO_AGC_ATT = 65,
    TOP_INFO_CHANNEL_LOSS = 74,
    TOP_INFO_CHANNEL_POWER = 75,
    TOP_INFO_UP_TIME = 76,
    TOP_INFO_DOWN_TIME = 78,
    TOP_INFO_AGC_GAIN = 106,
    TOP_INFO_AGC_DEGEN = 110,
    TOP_INFO_CDFL_ENV = 112,
    TOP_INFO_LOSS = 127,

    TOP_INFO_EYE_ALL = 240,
    TOP_INFO_EYE = 396,
    TOP_INFO_SKEF = 410,
    TOP_INFO_TX_FFE = 414,
} TopInfoCode_t;

typedef enum {
    ANLT_DEBUG_AN_STATE = 0,
    ANLT_DEBUG_ANLT_STATE = 1,
    ANLT_DEBUG_AN_MODE = 2,
    ANLT_DEBUG_AN_HW_STATE = 3,
    ANLT_DEBUG_AN_RESTART_COUNT = 14,
    ANLT_DEBUG_LT_RESTART_COUNT = 15,
    ANLT_DEBUG_LT_STATE = 16,
    ANLT_DEBUG_LD_PAGES = 300,
    ANLT_DEBUG_LP_PAGES = 330,
} ANLTDebugCode_t;

typedef enum {
    SE_INFO_PLL_VCOCAP = 0,
    SE_INFO_OPT_MODE = 1,
    SE_INFO_SPEED_MODE = 3,
    SE_INFO_ANLT_ON = 4,
    SE_INFO_CONFIG_SEL = 5,
    SE_INFO_TX_STATUS = 9,
    SE_INFO_PLL_SEARCH_RANGE = 10,
    SE_INFO_RESTART_COUNT = 51,
    SE_INFO_LINK_LOST_COUNT = 52,
    SE_INFO_READAPT_COUNT = 53,
    SE_INFO_LOS_COUNT = 54,
    SE_INFO_LANE_UP_TIME = 55,
    SE_INFO_LANE_UP_TIME_MSB = 55,
    SE_INFO_LANE_UP_TIME_LSB = 56,
    SE_INFO_LANE_DOWN_TIME = 57,
    SE_INFO_LANE_DOWN_TIME_MSB = 57,
    SE_INFO_LANE_DOWN_TIME_LSB = 58,
    SE_INFO_SYS_TIME = 59,
    SE_INFO_ISC_ENABLE = 60,
    SE_INFO_ALL_EXIT_CODES = 100,
    SE_INFO_ALL_ERROR_CODES = 120,
    SE_INFO_TOP_PLL_TARGET_MARGIN = 352,
    SE_INFO_TOP_PLL_VCOCAP_TOP_DEBUG = 200,
    SE_INFO_TOP_AP_ACTIVE_LANES = 600,
    SE_INFO_INTERNAL_VER = 999,
    SE_INFO_CMD_LOG_CNT = 5000,
    SE_INFO_CMD_LOG = 5001,
} SeInfoCode_t;

#define SE_TOP_VCOCAP_LENGTH  64
#define SE_LANE_VCOCAP_LENGTH 32

typedef enum {
    FW_TX_SOURCE_QUIET = 0,
    FW_TX_SOURCE_PRBS_PAM4 = 1,
    FW_TX_SOURCE_PRBS_NRZ = 2,
    FW_TX_SOURCE_DATA = 3,
    FW_TX_SOURCE_NOFORCE = 0xFF,
} FwTxSource_t;

typedef enum {
    FW_RX_CONTROL_RESET = 0,
    FW_RX_CONTROL_ENABLE = 1,
    FW_RX_CONTROL_DISABLE = 5,
} FwRxControl_t;

typedef enum {
    TRF_Off = 0,
    TRF_OnetoOne = 1,
    TRF_GearBox = 2,
    TRF_NOFORCE = 0xFF,
} TRF_t;

typedef enum {
    FW_EM_SUCCESS = 0,
    FW_EM_PROG_REPORT = 1,
    FW_EM_DATA_RETURN = 2,
    FW_EM_ERROR = 3,  // fw command error too
    FW_EM_ERROR_NOT_READY = 4,
    FW_EM_ERROR_GOING_ON = 5,
    FW_EM_ERROR_CANCELL = 6,
    FW_EM_ERROR_NOT_START = 7,
} FirmwareEMState_t;

/* Firmware internal regs */
// Refer: https://stackoverflow.com/a/11314760/9174589
#define TOP_BIT_SET -2147483648  // ISO C standard doesnt support (1 << 31) as enum treated as int

#define FWREG(SECTION, OFFSET)   (((SECTION) << 16) + (OFFSET))
#define FWREG32(SECTION, OFFSET) ((SECTION) << 16) + (OFFSET) + TOP_BIT_SET

typedef enum {
    FW_REG_SECTION_TOP = 0,
    FW_REG_SECTION_SWIFT_TOP = 1,
    FW_REG_SECTION_AUTONEG = 3,
} FirmwareRegSection_t;

#define FWREG_TOP_OPTIONS           FWREG(FW_REG_SECTION_TOP, 6)
#define FWREG_TOP_TEMPERATURE       FWREG(FW_REG_SECTION_TOP, 9)
#define FWREG_TOP_VCOCAP_STATE      FWREG(FW_REG_SECTION_TOP, 10)
#define FWREG_TOP_TRACE_OPT         FWREG(FW_REG_SECTION_TOP, 17)
#define FWREG_TOP_ISC_SLICE_ID      FWREG(FW_REG_SECTION_TOP, 25)
#define FWREG_TOP_VSENSOR           FWREG(FW_REG_SECTION_TOP, 31)
#define FWREG_TOP_VCO_LOCK_CRITERIA FWREG(FW_REG_SECTION_SWIFT_TOP, 28)
#define FWREG_TOP_ACTIVE_LANE_MAP   FWREG(FW_REG_SECTION_SWIFT_TOP, 178)

#define FWREG_TOP_FLEXSPEED_EN_TX               FWREG(FW_REG_SECTION_SWIFT_TOP, 179)
#define FWREG_TOP_FLEXSPEED_EN_RX               FWREG(FW_REG_SECTION_SWIFT_TOP, 180)
#define FWREG_TOP_FLEXSPEED_PLL_N_TX_A          FWREG(FW_REG_SECTION_SWIFT_TOP, 181)
#define FWREG_TOP_FLEXSPEED_PLL_N_TX_B          FWREG(FW_REG_SECTION_SWIFT_TOP, 182)
#define FWREG_TOP_FLEXSPEED_PLL_N_RX_A          FWREG(FW_REG_SECTION_SWIFT_TOP, 183)
#define FWREG_TOP_FLEXSPEED_PLL_N_RX_B          FWREG(FW_REG_SECTION_SWIFT_TOP, 184)
#define FWREG_TOP_FLEXSPEED_PLL_N_TX_FRAC_A     FWREG(FW_REG_SECTION_SWIFT_TOP, 185)
#define FWREG_TOP_FLEXSPEED_PLL_N_TX_FRAC_B     FWREG(FW_REG_SECTION_SWIFT_TOP, 186)
#define FWREG_TOP_FLEXSPEED_PLL_N_RX_FRAC_A     FWREG(FW_REG_SECTION_SWIFT_TOP, 187)
#define FWREG_TOP_FLEXSPEED_PLL_N_RX_FRAC_B     FWREG(FW_REG_SECTION_SWIFT_TOP, 188)
#define FWREG_TOP_FLEXSPEED_PLL_TX_TARGET_MSB_A FWREG(FW_REG_SECTION_SWIFT_TOP, 190)
#define FWREG_TOP_FLEXSPEED_PLL_TX_TARGET_LSB_A FWREG(FW_REG_SECTION_SWIFT_TOP, 191)
#define FWREG_TOP_FLEXSPEED_PLL_TX_TARGET_MSB_B FWREG(FW_REG_SECTION_SWIFT_TOP, 192)
#define FWREG_TOP_FLEXSPEED_PLL_TX_TARGET_LSB_B FWREG(FW_REG_SECTION_SWIFT_TOP, 193)
#define FWREG_TOP_FLEXSPEED_PLL_RX_TARGET_MSB_A FWREG(FW_REG_SECTION_SWIFT_TOP, 194)
#define FWREG_TOP_FLEXSPEED_PLL_RX_TARGET_LSB_A FWREG(FW_REG_SECTION_SWIFT_TOP, 195)
#define FWREG_TOP_FLEXSPEED_PLL_RX_TARGET_MSB_B FWREG(FW_REG_SECTION_SWIFT_TOP, 196)
#define FWREG_TOP_FLEXSPEED_PLL_RX_TARGET_LSB_B FWREG(FW_REG_SECTION_SWIFT_TOP, 197)

#define TOP_OPTION_TOPPLL_MODE_OFFSET           9
#define TOP_OPTION_TOPPLL_MODE_MASK             0x7
#define TOP_OPTION_BYPASS_TOPLL_AND_DIV2        (1 << 9)
#define TOP_OPTION_BYPASS_TOPLL_AND_ENABLE_DIV2 (1 << 10)
#define TOP_OPTION_ENABLE_TOPLL_AND_BYPASS_DIV2 (1 << 11)

#define DEFSPEED(...)      EXPAND__(DEFSPEED_n, NUM_ARGS(__VA_ARGS__), __VA_ARGS__)
#define DEFSPEED_n(N, ...) DEFSPEED_##N(__VA_ARGS__)
#define DEFSPEED_1(A)      DEFSPEED_2(A, A)
#define DEFSPEED_2(A, B)   (GLUE__(SPEED_, A) << 4 | GLUE__(SPEED_, B))
#define DEFLANE_INDEX(A, LANE) \
    (((LANE) > 11) ? ((A & 0xF000) | (LANE & 0x003F)) : ((A & 0xF000) | ((LANE << 6) & 0x0FC0)))

#define DEFLANE_INDEX_n(N, ...) DEFLANE_INDEX_##N(__VA_ARGS__)
#define DEFLANE_INDEX_1(LANE)   (((LANE) > 11) ? ((LANE & 0x003F)) : ((LANE << 6) & 0x0FC0))
#define DEFLANE_INDEX_2(A, B)   ((A << 6) | B)

// exit_codes
#define ALL_EXIT_CODES_START                          (SE_INFO_ALL_EXIT_CODES)
#define ALL_EXIT_CODES_END                            (ALL_EXIT_CODES_START + 16)
#define GET_FW_EXIT_CODES(slice, lane, index, pvalue) hal_fw_debug_cmd(slice, lane, SE_INFO, index, pvalue)

// error codes
#define ALL_ERROR_CODES_START                          (SE_INFO_ALL_ERROR_CODES)
#define ALL_ERROR_CODES_END                            (ALL_ERROR_CODES_START + 16)
#define GET_FW_ERROR_CODES(slice, lane, index, pvalue) hal_fw_debug_cmd(slice, lane, SE_INFO, index, pvalue)

#endif
