#ifndef SE_FW_STATE_H
#define SE_FW_STATE_H

#define FW_STATE_MODE_PAM4 0x8
#define FW_STATE_MODE_NRZ  0x9

// Major
#define FW_STATE_TOP          0x0
#define FW_STATE_OPT_STARTUP  0x1
#define FW_STATE_OPT_PRESET   0x2
#define FW_STATE_OPT_FFE_FLT  0x3
#define FW_STATE_OPT_CTLE_CP2 0x4
#define FW_STATE_OPT_F1_EYE   0x5
#define FW_STATE_OPT_CM1_EYE  0x6
#define FW_STATE_OPT_F0_EYE   0x7
#define FW_STATE_OPT_SKEF_EYE 0x8
#define FW_STATE_OPT_GAIN     0x9
#define FW_STATE_ANLT         0xA
#define FW_STATE_LT           0xB
#define FW_STATE_THDLY_ADAPT  0xC
#define FW_STATE_OPT_LINKUP   0xF

// Minor
#define FW_STATE_MODE_QUIET    0x01
#define FW_STATE_MODE_SQUELCH  0x02
#define FW_STATE_INIT_MODE     0x03
#define FW_STATE_INIT_NRZ      0x04
#define FW_STATE_INIT_PAM4     0x05
#define FW_STATE_INIT_AN       0x06
#define FW_STATE_START_PLL_CAL 0x07
#define FW_STATE_RX_DISABLE    0x08
#define FW_STATE_PLL_CAL_DONE  0x09
#define FW_STATE_DESTROYING    0x0A

#define FW_STATE_OPT_START_NRZ     0x10
#define FW_STATE_OPT_START_PAM4    0x11
#define FW_STATE_OPT_START_AN      0x12
#define FW_STATE_OPT_START_NRZ_LT  0x13
#define FW_STATE_OPT_START_PAM4_LT 0x14
#define FW_STATE_OPT_SINGAL_DETECT 0x15
#define FW_STATE_OPT_CHECK_CDR     0x16
#define FW_STATE_OPT_SD_RESET      0x17

#define FW_STATE_OPT_PRESET_CH_EST            0x20
#define FW_STATE_OPT_PRESET_INIT              0x21
#define FW_STATE_OPT_PRESET_CAL_TABLE_RANGE   0x22
#define FW_STATE_OPT_PRESET_ATTN_SEARCH       0x23
#define FW_STATE_OPT_PRESET_DSP_STARTUP       0x24
#define FW_STATE_OPT_PRESET_OPT_F0_ENV        0x25
#define FW_STATE_OPT_PRESET_OPT_F0_VGA        0x26
#define FW_STATE_OPT_PRESET_THDLY_ADAPT       0x27
#define FW_STATE_OPT_PRESET_OPT_CM1           0x28
#define FW_STATE_OPT_PRESET_CHECK_EYE_BALC    0x29
#define FW_STATE_OPT_PRESET_CHECK_CDR         0x2A
#define FW_STATE_OPT_PRESET_CHECK_ANA_FE      0x2B
#define FW_STATE_OPT_PRESET_CHECK_GAIN        0x2C
#define FW_STATE_OPT_PRESET_GET_CANDIDATE     0x2D
#define FW_STATE_OPT_PRESET_BEST_INDEX_BROKEN 0x2E
#define FW_STATE_OPT_PRESET_OW                0x2F

#define FW_STATE_OPT_PRESET_ENTRY_SHORT_CH       0x30
#define FW_STATE_OPT_PRESET_ENTRY_MIDDLE_CH      0x31
#define FW_STATE_OPT_PRESET_ENTRY_LONG_CH        0x32
#define FW_STATE_OPT_PRESET_CS_ADJ_PLUS          0x33
#define FW_STATE_OPT_PRESET_CS_ADJ_MINUS         0x34
#define FW_STATE_OPT_PRESET_THDLY_OW             0x35
#define FW_STATE_OPT_PRESET_CS_GRP_SHRT_2_LNG    0x36
#define FW_STATE_OPT_PRESET_CS_GRP_LNG_2_SHRT    0x37
#define FW_STATE_OPT_PRESET_PPM_PATCH            0x38
#define FW_STATE_OPT_PRESET_PPM_PATCH_CDR_UNLOCK 0x39
#define FW_STATE_OPT_PRESET_INIT_DONE            0x3A
#define FW_STATE_OPT_PRESET_OFF_CTEL_IND         0x3B
#define FW_STATE_OPT_PRESET_DO_LOAD              0x3C

#define FW_STATE_OPT_CTLE_FIND_CUR_IDX            0x40
#define FW_STATE_OPT_CTLE_START_OPT               0x41
#define FW_STATE_OPT_CTLE_OPT_F1_BY_CP1           0x42
#define FW_STATE_OPT_CTLE_CP2_HIT_BOUNDARY        0x43
#define FW_STATE_OPT_CTLE_CP2_DIR_CHANGE          0x44
#define FW_STATE_OPT_CTLE_CP2_OUT_OF_RANGE        0x45
#define FW_STATE_OPT_CTLE_F1_SATURATED            0x46
#define FW_STATE_OPT_CTLE_GET_CANDIDATE           0x47
#define FW_STATE_OPT_PRESET_PPM_PATCH_DONE        0x48
#define FW_STATE_OPT_PRESET_PPM_PATCH_SIGNAL_LOST 0x49

#define FW_STATE_OPT_CM1_EYE_CHECK_RANGE       0x60
#define FW_STATE_OPT_CM1_EYE_START             0x61
#define FW_STATE_OPT_CM1_EYE_CAL_AVG           0x62
#define FW_STATE_OPT_CM1_EYE_CAL_MOVING_WINDOW 0x63
#define FW_STATE_OPT_CM1_EYE_DATA_ERROR        0x64
#define FW_STATE_OPT_CM1_EYE_BAD_RESULT        0x65

#define FW_STATE_OPT_F0_EYE_ENV_ADJ_1      0x70
#define FW_STATE_OPT_F0_EYE_ENV_ADJ_2      0x71
#define FW_STATE_OPT_F0_EYE_VGA_PROTECTION 0x72
#define FW_STATE_OPT_F0_EYE_CS_BY_ENV      0x73
#define FW_STATE_OPT_F0_EYE_FIN_ADJ        0x7F

// LT
#define FW_STATE_LT_IDLE                 0x00
#define FW_STATE_LT_START                0xB0
#define FW_STATE_LT_WAIT_FRAME_LOCK      0xB1
#define FW_STATE_LT_WAIT_REMOTE_LOCK     0xB2
#define FW_STATE_LT_WAIT_INITIAL_CMD     0xB3
#define FW_STATE_LT_CHECK_FRAME_LOCK     0xB4
#define FW_STATE_LT_TX_ADJUST            0xB5
#define FW_STATE_LT_SWITCH_TO_PAM4       0xB6
#define FW_STATE_LT_PAM4_WAIT_FRAME_LOCK 0xB7
#define FW_STATE_LT_PAM4_TX_ADJUST       0xB8
#define FW_STATE_LT_RX_ADAPT             0xB9
#define FW_STATE_LT_WAIT_DATA_READY      0xBA
#define FW_STATE_LT_LOCAL_READY          0xBB
#define FW_STATE_LT_SWITCH_TO_PRBS       0xBE
#define FW_STATE_LT_END                  0xBF

// Background
#define FW_STATE_OPT_BG_INIT                  0xF0
#define FW_STATE_OPT_BG_READ_EYE              0xF1
#define FW_STATE_OPT_BG_READ_ISI              0xF2
#define FW_STATE_OPT_BG_GET_FE_INFO           0xF3
#define FW_STATE_OPT_BG_CHECK_SMALL_EYE       0xF4
#define FW_STATE_OPT_BG_CHECK_EYE             0xF5
#define FW_STATE_OPT_BG_TOP_RESET             0xF6
#define FW_STATE_OPT_BG_COMP_VGA_CS_ATT_ICTRL 0xF7
#define FW_STATE_OPT_BG_COMP_CS_VGA_REF_CTL   0xF8
#define FW_STATE_OPT_BG_COMP_GAIN_PROTECT     0xF9

#define FW_STATE_RETIMER_FIFO_ADJUST 0xA0
#define FW_STATE_RETIMER_TX_EANBLE   0xA1

// log state
#define FW_LOG_NO_USE      0xABAB
#define FW_LOG_TYPE_HEADER 1
#define FW_LOG_TYPE_DATA   2
#define FW_LOG_TYPE_END    3
#define FW_LOG_PARAM_LEN   10
#define FW_LOG_METRIC_LEN  10

#endif
