/***********************************************************************************
 ***********************************************************************************
 *  File Name     :  serdes_api_dependencies.c                                     *
 *  Created On    :  23/09/2013                                                    *
 *  Created By    :  Kiran Divakar                                                 *
 *  Description   :  Version of Dependency APIs used in Eval                       *
 * $Copyright: (c) 2021 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *                                                                                 *
 ***********************************************************************************
 ***********************************************************************************/
/*  Blackhawk memory map */

#include "blackhawk_barchetta_dependencies.h"
#include "common/srds_api_err_code.h"
#include "common/srds_api_uc_common.h"
#include "common/srds_api_types.h"
#include <bcmi_barchetta_defs.h>
#include <barchetta_cfg_seq.h>

/** Read a register from the currently selected Serdes IP Lane.
 * @param sa__ is an opaque state vector passed through to device access functions.
 * @param address Address of register to be read
 * @param *val value read out from the register
 * @return Error code generated by read function (returns ERR_CODE_NONE if no errors)
 */
err_code_t plp_barchetta_blackhawk_barchetta_pmd_rdt_reg(srds_access_t *sa__, uint16_t address, uint16_t *val)
{
    uint32_t data = 0, addr = 0;
    addr = (address) | (1 << 16);
    PHYMOD_IF_ERR_RETURN(
        _plp_barchetta_reg_read(sa__, addr, &data));
    *val = (uint16_t)data;
    return ( ERR_CODE_NONE );
}

/** Write to a register from the currently selected Serdes IP Lane.
 * @param sa__ is an opaque state vector passed through to device access functions.
 * @param address Address of register to be written
 * @param val Value to be written to the register
 * @return Error code generated by write function (returns ERR_CODE_NONE if no errors)
 */
err_code_t plp_barchetta_blackhawk_barchetta_pmd_wr_reg(srds_access_t *sa__, uint16_t address, uint16_t val)
{
    uint32_t data = 0xffff & val;
    uint32_t addr = 0;
    addr = (address) | (1 << 16);

    PHYMOD_IF_ERR_RETURN(
       _plp_barchetta_reg_write(sa__, addr, data));

    return (ERR_CODE_NONE);
}

/** Masked Register Write to the currently selected Serdes IP core/lane.
 * If using Serdes MDIO controller to access the registers, implement this function using blackhawk_barchetta_pmd_mdio_mwr_reg(..)
 *
 * If NOT using a Serdes MDIO controller or the Serdes PMI Masked write feature, please use the following code to
 * implement this function
 *
 *    plp_barchetta_blackhawk_barchetta_pmd_wr_reg(addr, ((blackhawk_barchetta_pmd_rd_reg(addr) & ~mask) | (mask & (val << lsb))));
 *
 * @param sa__ is an opaque state vector passed through to device access functions.
 * @param addr Address of register to be written
 * @param mask 16-bit mask indicating the position of the field with bits of 1s
 * @param lsb  LSB of the field
 * @param val  16bit value to be written
 * @return Error code generated by write function (returns ERR_CODE_NONE if no errors)
 */
err_code_t plp_barchetta_blackhawk_barchetta_pmd_mwr_reg(srds_access_t *sa__, uint16_t addr, uint16_t mask, uint8_t lsb, uint16_t val)
{
    uint16_t tmp, otmp;
    uint32_t reg_val;
    val = val << lsb;

    val = val & mask ;
    /* Use clause 45 access if supported */
    PHYMOD_IF_ERR_RETURN(
        _plp_barchetta_reg_read(sa__, (addr | (1 << 16)), &reg_val));
    tmp = (uint16_t) (reg_val & 0xffff);
    otmp = tmp;
    tmp &= ~(mask);
    tmp |= val;

    if (otmp != tmp) {
        PHYMOD_IF_ERR_RETURN(
            _plp_barchetta_reg_write(sa__, (addr | (1 << 16)), tmp));
    }

    return (ERR_CODE_NONE);
}

/** Write to a PRAM location for the currently selected Serdes IP Core.
 *  The address is auto-incrementing, per the PRAM interface specification.
 * @param sa__ is an opaque state vector passed through to device access functions.
 * @param val Value to be written
 * @return Error code generated by write function (returns ERR_CODE_NONE if no errors)
 */
/*  No need for this call, don't change BH PRAM */
err_code_t plp_barchetta_blackhawk_barchetta_pmd_wr_pram(srds_access_t *sa__, uint8_t val)
{
    return (ERR_CODE_NONE);
}

/** Write message to the logger with the designated verbose level.
 * Output is sent to stdout and a logfile
 * @param message_verbose_level   Verbose level for the current message
 * @param *format Format string as in printf
 * @param ... Additional variables used as in printf
 * @return Error code generated by function (returns ERR_CODE_NONE if no errors)
 */
/*int logger_write(int message_verbose_level, const char *format, ...)
{
    int n = 0;
    {
        va_list args;
        PHYMOD_MEMSET(&args, 0x00, sizeof(va_list));

        va_start(args, format);
        n = vprintf(format, args);
        va_end(args);
    }
    return n;
}*/

/** Delay the execution of the code for atleast specified amount of time in nanoseconds.
 * This function is used ONLY for delays less than 1 microsecond, non-zero error code may be returned otherwise.
 * The user can implement this as an empty function if their register access latency exceeds 1 microsecond.
 * @param delay_ns Delay in nanoseconds
 * @return Error code generated by delay function (returns ERR_CODE_NONE if no errors)
 */
err_code_t plp_barchetta_blackhawk_barchetta_delay_ns(uint16_t delay_ns)
{
    PHYMOD_USLEEP(1);
    return(ERR_CODE_NONE);
}


/** Delay the execution of the code for atleast specified amount of time in microseconds.
 * For longer delays, accuracy is required. When requested delay is > 100ms, the implemented delay is assumed
 * to be < 10% bigger than requested.
 * This function is used ONLY for delays greater than or equal to 1 microsecond.
 * @param delay_us Delay in microseconds
 * @return Error code generated by delay function (returns ERR_CODE_NONE if no errors)
 */
err_code_t plp_barchetta_blackhawk_barchetta_delay_us(uint32_t delay_usec)
{
    PHYMOD_USLEEP(1);
    return(ERR_CODE_NONE);
}


/** Delay the execution of the code for atleast specified amount of time in milliseconds.
 * For longer delays, accuracy is required. When requested delay is > 100ms, the implemented delay is assumed
 * to be < 10% bigger than requested.
 * This function is used ONLY for delays greater than or equal to 1 millisecond.
 * @param delay_ms Delay in milliseconds
 * @return Error code generated by delay function (returns ERR_CODE_NONE if no errors)
 */
err_code_t plp_barchetta_blackhawk_barchetta_delay_ms(uint32_t delay_msec)
{
    PHYMOD_USLEEP(delay_msec*1000);
    return(ERR_CODE_NONE);
}


/** Return the address of current selected Serdes IP Core.
 * @param sa__ is an opaque state vector passed through to device access functions.
 * @return the IP level address of the current core.
 */
uint8_t plp_barchetta_blackhawk_barchetta_get_core(srds_access_t *sa__)
{
    return 0;
}

/** Return the address of current selected Serdes IP lane.
 * @param sa__ is an opaque state vector passed through to device access functions.
 * @return the IP level address of the current lane. 0 to N-1, for an N lane IP
 */
uint8_t plp_barchetta_blackhawk_barchetta_get_lane(srds_access_t *sa__)
{
    int lane_map = 0, lane_idx=0;
    BCMI_BARCHETTA_SLICE_SLICE0r_t slice0;

    PHYMOD_IF_ERR_RETURN(
        BCMI_BARCHETTA_READ_SLICE_SLICE0r(sa__, &slice0));
	lane_map = BCMI_BARCHETTA_SLICE_SLICE0r_LANE_SELf_GET(slice0);
	for (lane_idx = 0; lane_idx < 8; lane_idx ++) {
	    if (lane_map & (1 << lane_idx)) {
			return lane_idx;
		}
	}
	/* default return 0*/
    return 0 ;


}

/** Set the address of current selected Serdes IP lane.  Used in diagnostic
 * and core-level management functions.
 * @param sa__ is an opaque state vector passed through to device access functions.
 * @param lane_index is the lane index
 * @return Any error code generated during execution; ERR_CODE NONE otherwise.
 */
err_code_t plp_barchetta_blackhawk_barchetta_set_lane(srds_access_t *sa__, uint8_t lane_index)
{
    BCMI_BARCHETTA_SLICE_SLICE0r_t slice0;
    PHYMOD_IF_ERR_RETURN(
        BCMI_BARCHETTA_READ_SLICE_SLICE0r(sa__, &slice0));
    BCMI_BARCHETTA_SLICE_SLICE0r_LANE_SELf_SET(slice0, (1 << lane_index));
    PHYMOD_IF_ERR_RETURN(
        BCMI_BARCHETTA_WRITE_SLICE_SLICE0r(sa__, slice0));
    return(ERR_CODE_NONE);
}


/** Return the address of current selected Serdes IP PLL.
 * @param sa__ is an opaque state vector passed through to device access functions.
 * @return the IP level address of the current PLL. 0 to N-1, for an N-PLL IP
 */
uint8_t plp_barchetta_blackhawk_barchetta_get_pll_idx(srds_access_t *sa__)
{
    BCMI_BARCHETTA_SLICE_SLICE1r_t slice1;
    PHYMOD_IF_ERR_RETURN(
        BCMI_BARCHETTA_READ_SLICE_SLICE1r(sa__, &slice1));

    return BCMI_BARCHETTA_SLICE_SLICE1r_PLL_MICRO_SELf_GET(slice1);
}

/** Set the address of current selected Serdes IP PLL.  Used in disgnoztic
 * and core-level management functions.
 * @param sa__ is an opaque state vector passed through to device access functions.
 * @param pll_index is the PLL index
 * @return Any error code generated during execution; ERR_CODE NONE otherwise.
 */
err_code_t plp_barchetta_blackhawk_barchetta_set_pll_idx(srds_access_t *sa__, uint8_t pll_index)
{
    BCMI_BARCHETTA_SLICE_SLICE1r_t slice1;
    PHYMOD_IF_ERR_RETURN(
        BCMI_BARCHETTA_READ_SLICE_SLICE1r(sa__, &slice1));

    /*  Select pll_base_address */
    if(pll_index == 0) {
        BCMI_BARCHETTA_SLICE_SLICE1r_PLL_MICRO_SELf_SET(slice1, 0);
    } else {
        BCMI_BARCHETTA_SLICE_SLICE1r_PLL_MICRO_SELf_SET(slice1, 1);
    }
    PHYMOD_IF_ERR_RETURN(
        BCMI_BARCHETTA_WRITE_SLICE_SLICE1r(sa__, slice1));

    return(ERR_CODE_NONE);
}
uint8_t plp_barchetta_blackhawk_barchetta_get_micro_idx(srds_access_t *sa__)
{
    BCMI_BARCHETTA_SLICE_SLICE1r_t slice1;
    PHYMOD_IF_ERR_RETURN(
        BCMI_BARCHETTA_READ_SLICE_SLICE1r(sa__, &slice1));

    return BCMI_BARCHETTA_SLICE_SLICE1r_PLL_MICRO_SELf_GET(slice1);

}
err_code_t plp_barchetta_blackhawk_barchetta_set_micro_idx(srds_access_t *sa__, uint8_t micro_index)
{
    BCMI_BARCHETTA_SLICE_SLICE1r_t slice1;
    PHYMOD_IF_ERR_RETURN(
        BCMI_BARCHETTA_READ_SLICE_SLICE1r(sa__, &slice1));

    /*  Select micro */
    BCMI_BARCHETTA_SLICE_SLICE1r_PLL_MICRO_SELf_SET(slice1, micro_index);

    PHYMOD_IF_ERR_RETURN(
        BCMI_BARCHETTA_WRITE_SLICE_SLICE1r(sa__, slice1));

    return(ERR_CODE_NONE);
}

