# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interrupt.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gogo_pb2 as gogo__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import types_pb2 as types__pb2
try:
  gogo__pb2 = types__pb2.gogo__pb2
except AttributeError:
  gogo__pb2 = types__pb2.gogo_pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finterrupt.proto\x12\x03pds\x1a\ngogo.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0btypes.proto\"\xae\x02\n\tInterrupt\x12.\n\x04Time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x04\x90\xdf\x1f\x01\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12&\n\x08Severity\x18\x03 \x01(\x0e\x32\x14.pds.Interrupt.Level\x12\r\n\x05\x43ount\x18\x04 \x01(\x04\x12\x13\n\x0b\x44\x65scription\x18\x05 \x01(\t\x12\x12\n\nIgnoreOnce\x18\x06 \x01(\x08\x12\x11\n\tIgnoreAll\x18\x07 \x01(\x08\x12\x13\n\x0bZeroToClear\x18\x08 \x01(\x08\"[\n\x05Level\x12\x0e\n\nLEVEL_NONE\x10\x00\x12\x0f\n\x0bLEVEL_FATAL\x10\x01\x12\x10\n\x0cLEVEL_HW_RMA\x10\x02\x12\x0f\n\x0bLEVEL_ERROR\x10\x03\x12\x0e\n\nLEVEL_INFO\x10\x04\"\"\n\x13InterruptGetRequest\x12\x0b\n\x03\x41ll\x18\x01 \x01(\x08\"^\n\x14InterruptGetResponse\x12#\n\tApiStatus\x18\x01 \x01(\x0e\x32\x10.types.ApiStatus\x12!\n\tInterrupt\x18\x02 \x03(\x0b\x32\x0e.pds.Interrupt2T\n\tSystemSvc\x12G\n\x0cInterruptGet\x12\x18.pds.InterruptGetRequest\x1a\x19.pds.InterruptGetResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interrupt_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INTERRUPT.fields_by_name['Time']._options = None
  _INTERRUPT.fields_by_name['Time']._serialized_options = b'\220\337\037\001'
  _globals['_INTERRUPT']._serialized_start=83
  _globals['_INTERRUPT']._serialized_end=385
  _globals['_INTERRUPT_LEVEL']._serialized_start=294
  _globals['_INTERRUPT_LEVEL']._serialized_end=385
  _globals['_INTERRUPTGETREQUEST']._serialized_start=387
  _globals['_INTERRUPTGETREQUEST']._serialized_end=421
  _globals['_INTERRUPTGETRESPONSE']._serialized_start=423
  _globals['_INTERRUPTGETRESPONSE']._serialized_end=517
  _globals['_SYSTEMSVC']._serialized_start=519
  _globals['_SYSTEMSVC']._serialized_end=603
# @@protoc_insertion_point(module_scope)
