/*
 * $Id 
 * 
 * $Copyright: (c) 2020 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *         
 *     
 * DO NOT EDIT THIS FILE!
 *
 */
    
#ifdef PLP_EUROPA_SUPPORT
#ifdef PLP_MACSEC_SUPPORT
#include "epdm_sec.h"

/* CFYE */

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_device_init(bcm_plp_sec_phy_access_t *pa,
                                               const bcm_plp_cfye_init_t *init_p)EPDM_WEAK;
extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_device_uninit(bcm_plp_sec_phy_access_t *pa)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_vport_add(bcm_plp_sec_phy_access_t *pa,
                                             bcm_plp_cfye_vport_handle_t *vport_handle_p,
                                             const bcm_plp_cfye_vport_t *vport_p)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_vport_remove(bcm_plp_sec_phy_access_t *pa,
                                                const bcm_plp_cfye_vport_handle_t vport_handle)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_vport_update(bcm_plp_sec_phy_access_t *pa,
                                                const bcm_plp_cfye_vport_handle_t vport_handle,
                                                const bcm_plp_cfye_vport_t *vport_p)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_rule_add(bcm_plp_sec_phy_access_t *pa,
                                            const bcm_plp_cfye_vport_handle_t vport_handle,
                                            bcm_plp_cfye_rule_handle_t *rule_handle_p,
                                            const bcm_plp_cfye_rule_t *rule_p)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_rule_remove(bcm_plp_sec_phy_access_t *pa,
                                               const bcm_plp_cfye_rule_handle_t rule_handle)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_rule_update(bcm_plp_sec_phy_access_t *pa,
                                               const bcm_plp_cfye_rule_handle_t rule_handle,
                                               const bcm_plp_cfye_rule_t *rule_p)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_rule_enable(bcm_plp_sec_phy_access_t *pa,
                                               const bcm_plp_cfye_rule_handle_t rule_handle,
                                               const unsigned char fsync)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_rule_disable(bcm_plp_sec_phy_access_t *pa,
                                                const bcm_plp_cfye_rule_handle_t rule_handle,
                                                const unsigned char fsync)EPDM_WEAK;

extern unsigned int bcm_plp_europa_cfye_vport_id_get(bcm_plp_sec_phy_access_t *pa,
                                    const bcm_plp_cfye_vport_handle_t vport_handle)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_rule_enable_disable(bcm_plp_sec_phy_access_t *pa,
                                                      const bcm_plp_cfye_rule_handle_t rule_handle_disable,
                                                      const bcm_plp_cfye_rule_handle_t rule_handle_enable,
                                                      const unsigned char enable_all,
                                                      const unsigned char disable_all,
                                                      const unsigned char fsync)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_device_limits(bcm_plp_sec_phy_access_t *pa,
                                                 unsigned int *max_channel_count_p,
                                                 unsigned int *maxv_port_count_p,
                                                 unsigned int *max_rule_count_p)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_device_update(bcm_plp_sec_phy_access_t *pa,
                                                 const bcm_plp_cfye_device_t *control_p)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_statistics_read(bcm_plp_sec_phy_access_t *pa,
                                                   const unsigned int stat_index,
                                                   bcm_plp_cfye_statistics_t *stat_p,
                                                   const unsigned char fsync)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_statistics_summary_read(bcm_plp_sec_phy_access_t *pa,
                                                           const unsigned int start_offset,
                                                           unsigned int *summary_p,
                                                           const unsigned int Count)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_statistics_summary_channel_read(bcm_plp_sec_phy_access_t *pa,
                                                                   bcm_plp_cfye_statistics_channel_summary_t *ch_summary_p)EPDM_WEAK;


extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_vport_handle_issame(bcm_plp_sec_phy_access_t *pa,
                                      const bcm_plp_cfye_vport_handle_t handle1_p,
                                      const bcm_plp_cfye_vport_handle_t handle2_p)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_rule_handle_issame(bcm_plp_sec_phy_access_t *pa,
                                     const bcm_plp_cfye_rule_handle_t handle1_p,
                                     const bcm_plp_cfye_rule_handle_t handle2_p)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_channel_bypass_set(bcm_plp_sec_phy_access_t *pa, const unsigned char fbypass) EPDM_WEAK;
extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_intr_enable_set(bcm_plp_sec_phy_access_t *pa, const bcm_plp_cfye_intr_t *cfye_intr)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_intr_enable_get(bcm_plp_sec_phy_access_t *pa, bcm_plp_cfye_intr_t *cfye_intr)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_intr_status_get(bcm_plp_sec_phy_access_t *pa, bcm_plp_cfye_intr_t *cfye_intr_sts)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_intr_status_clear(bcm_plp_sec_phy_access_t *pa, bcm_plp_cfye_intr_t *cfye_intr_clear)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_event_status_get(bcm_plp_sec_phy_access_t *pa, bcm_plp_cfye_intr_t *cfye_event_sts)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_rule_handle_get(bcm_plp_sec_phy_access_t *pa, const unsigned int rule_index, bcm_plp_cfye_rule_handle_t * const rule_handle_p)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_rule_index_get(bcm_plp_sec_phy_access_t *pa, const bcm_plp_cfye_rule_handle_t rule_handle, unsigned int * const rule_index_p)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_vport_handle_get(bcm_plp_sec_phy_access_t *pa, const unsigned int vport_index, bcm_plp_cfye_vport_handle_t * const vport_handle_p)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_vport_index_get(bcm_plp_sec_phy_access_t *pa, const bcm_plp_cfye_vport_handle_t vport_handle, unsigned int * const vport_index_p)EPDM_WEAK;

extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_vport_next_get(bcm_plp_sec_phy_access_t *pa, const bcm_plp_cfye_vport_handle_t current_vport_handle, bcm_plp_cfye_vport_handle_t *next_vport_handle_p) EPDM_WEAK;
extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_rule_next_get(bcm_plp_sec_phy_access_t *pa, const bcm_plp_cfye_rule_handle_t current_rule_handle, bcm_plp_cfye_rule_handle_t * next_rule_handle_p) EPDM_WEAK;
extern bcm_plp_cfye_status_t bcm_plp_europa_cfye_rule_vport_next_get(bcm_plp_sec_phy_access_t *pa, const bcm_plp_cfye_vport_handle_t vport_handle,  const bcm_plp_cfye_rule_handle_t current_rule_handle, bcm_plp_cfye_rule_handle_t *next_rule_handle_p) EPDM_WEAK;

/* SECY */

extern bcm_plp_secy_status_t bcm_plp_europa_secy_device_init(bcm_plp_sec_phy_access_t *pa,
                         const bcm_plp_secy_settings_t * const settings_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_device_uninit(bcm_plp_sec_phy_access_t *pa)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_sa_add(bcm_plp_sec_phy_access_t *pa,
                    const unsigned int vport,
                    bcm_plp_secy_sa_handle_t * const sa_handle_p,
                    const bcm_plp_secy_sa_t * const sa_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_sa_update(bcm_plp_sec_phy_access_t *pa,
                       const bcm_plp_secy_sa_handle_t sa_handle,
                       const bcm_plp_secy_sa_t * const sa_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_sa_read(bcm_plp_sec_phy_access_t *pa,
                     const bcm_plp_secy_sa_handle_t sa_handle,
                     const unsigned int word_offset,
                     const unsigned int word_count,
                     unsigned int * transform_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_sa_remove(bcm_plp_sec_phy_access_t *pa,
                       const bcm_plp_secy_sa_handle_t sa_handle)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_rules_sectag_update(bcm_plp_sec_phy_access_t *pa,
                                 const bcm_plp_secy_rule_sectag_t * const sec_tag_rules_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_bypass_get(bcm_plp_sec_phy_access_t *pa,
                                unsigned char * const fbypass)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_bypass_set(bcm_plp_sec_phy_access_t *pa,
                                const unsigned char fbypass)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_config_set(bcm_plp_sec_phy_access_t *pa)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_device_limits(bcm_plp_sec_phy_access_t *pa,
                           unsigned int * const max_channel_count_p,
                           unsigned int * const maxv_port_count_p,
                           unsigned int * const max_sa_count_p,
                           unsigned int * const max_sc_count_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_device_count_summary_secy_checkandclear(bcm_plp_sec_phy_access_t *pa,
                                                            const unsigned int secy_index,
                                                            unsigned int * const count_summary_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_device_count_summary_pifc_checkandclear(bcm_plp_sec_phy_access_t *pa,
                                                    unsigned int ** const ifc_indexes_pp,
                                                    unsigned int * const num_ifc_indexes_p)EPDM_WEAK;
extern bcm_plp_secy_status_t bcm_plp_europa_secy_device_count_summary_ifc_checkandclear(bcm_plp_sec_phy_access_t *pa,
                                                   const unsigned int ifc_index,
                                                   unsigned int * const count_summary_ifc_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_device_count_summary_pifc1_checkandclear(bcm_plp_sec_phy_access_t *pa,
                                                     unsigned int ** const ifc_indexes_pp,
                                                     unsigned int * const num_ifc_indexes_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_device_count_summary_ifc1_checkandclear(bcm_plp_sec_phy_access_t *pa,
                                                    const unsigned int ifc_index,
                                                    unsigned int * const count_summary_ifc_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_device_count_summary_prxcam_checkandclear(bcm_plp_sec_phy_access_t *pa,
                                                      unsigned int ** const rxcam_indexes_pp,
                                                      unsigned int * const num_rxcam_indexes_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_device_count_summary_psa_checkandclear(bcm_plp_sec_phy_access_t *pa,
                                                   unsigned int ** const sa_indexes_pp,
                                                   unsigned int * const num_sa_indexes_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_device_count_summary_sa_checkandclear(bcm_plp_sec_phy_access_t *pa,
                                                  const unsigned int sa_index,
                                                  unsigned int * const count_summary_sa_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_device_count_summary_channel_checkandclear(bcm_plp_sec_phy_access_t *pa,
                                                       unsigned int ** const channel_summary_pp,
                                                       unsigned int * const num_channel_summaries_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_sa_handle_issame(bcm_plp_sec_phy_access_t *pa,
                                   const bcm_plp_secy_sa_handle_t * const handle1_p,
                                   const bcm_plp_secy_sa_handle_t * const handle2_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_sa_handle_sa_index_issame(bcm_plp_sec_phy_access_t *pa,
                                           const bcm_plp_secy_sa_handle_t sa_handle,
                                           const unsigned int sa_index)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_crypt_auth_bypass_len_update(bcm_plp_sec_phy_access_t *pa,
                                        const unsigned int bypass_length)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_sa_nextpn_update(bcm_plp_sec_phy_access_t *pa,
                              const bcm_plp_secy_sa_handle_t sa_handle,
                              const unsigned int next_pn_lo,
                              const unsigned int next_pn_hi,
                              unsigned char * const fnext_pn_written_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_sa_chain(bcm_plp_sec_phy_access_t *pa,
                      const bcm_plp_secy_sa_handle_t active_sa_handle,
                      bcm_plp_secy_sa_handle_t * const new_sa_handle_p,
                      const bcm_plp_secy_sa_t * const new_sa_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_sa_switch(bcm_plp_sec_phy_access_t *pa,
                       const bcm_plp_secy_sa_handle_t active_sa_handle,
                       const bcm_plp_secy_sa_handle_t new_sa_handle,
                       const bcm_plp_secy_sa_t * const new_sa_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_sa_statistics_e_get(bcm_plp_sec_phy_access_t *pa,
                                 const bcm_plp_secy_sa_handle_t sa_handle,
                                 bcm_plp_secy_sa_stat_e_t * const stat_p,
                                 const unsigned char fsync)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_sa_statistics_i_get(bcm_plp_sec_phy_access_t *pa,
                                 const bcm_plp_secy_sa_handle_t sa_handle,
                                 bcm_plp_secy_sa_stat_i_t * const stats_p,
                                 const unsigned char fsync)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_ifc_statistics_e_get(bcm_plp_sec_phy_access_t *pa,
                                  const unsigned int vport,
                                  bcm_plp_secy_ifc_stat_e_t * const stat_p,
                                  const unsigned char fsync)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_ifc_statistics_i_get(bcm_plp_sec_phy_access_t *pa,
                                  unsigned int vport,
                                  bcm_plp_secy_ifc_stat_i_t * const stat_p,
                                  const unsigned char fsync)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_rxcam_statistics_get(bcm_plp_sec_phy_access_t *pa,
                                  const unsigned int scindex,
                                  bcm_plp_secy_rxcam_stat_t * const stats_p,
                                  const unsigned char fsync)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_sa_pnthr_summary_checkandclear(bcm_plp_sec_phy_access_t *pa,
                                           unsigned int ** const sa_indexes_pp,
                                           unsigned int * const num_sa_indexes_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_sa_expired_summary_checkandclear(bcm_plp_sec_phy_access_t *pa,
                                             unsigned int ** const sa_indexes_pp,
                                             unsigned int * const num_sa_indexes_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_rules_mtucheck_update(bcm_plp_sec_phy_access_t *pa,
                                   const unsigned int scindex,
                                   const bcm_plp_secy_sc_rule_mtu_check_t * const mtu_check_rule_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_channel_statistics_get(bcm_plp_sec_phy_access_t *pa,
                                    bcm_plp_secy_channel_stat_t * const stats_p,
                                    const unsigned char fsync)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_channel_packets_inflight_get(bcm_plp_sec_phy_access_t *pa,
                                         unsigned int * const in_flight_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_secy_statistics_e_get(bcm_plp_sec_phy_access_t *pa,
                              const unsigned int vport,
                              bcm_plp_secy_secy_stat_e_t *stats_p,
                              const unsigned char fsync)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_secy_statistics_i_get(bcm_plp_sec_phy_access_t *pa,
                              unsigned int vport,
                              bcm_plp_secy_secy_stat_i_t *stats_p,
                              const unsigned char fsync)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_device_count_summary_psecy_checkandclear(bcm_plp_sec_phy_access_t *pa,
                                                             unsigned int **secy_indexes_pp,
                                                             unsigned int *num_secy_indexes_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_intr_enable_set(bcm_plp_sec_phy_access_t *pa, const bcm_plp_secy_intr_t *secy_intr)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_intr_enable_get(bcm_plp_sec_phy_access_t *pa, bcm_plp_secy_intr_t *secy_intr)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_intr_status_get(bcm_plp_sec_phy_access_t *pa, bcm_plp_secy_intr_t *secy_intr_status)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_intr_status_clear(bcm_plp_sec_phy_access_t *pa, bcm_plp_secy_intr_t *secy_intr_clear)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_event_status_get(bcm_plp_sec_phy_access_t *pa, bcm_plp_secy_intr_t *secy_event_status)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_sa_handle_get(bcm_plp_sec_phy_access_t *pa, const unsigned int sa_index, bcm_plp_secy_sa_handle_t * const sa_handle_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_sa_index_get(bcm_plp_sec_phy_access_t *pa, const bcm_plp_secy_sa_handle_t sa_handle, unsigned int * const sa_index_p, unsigned int * const sc_index_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_device_update(bcm_plp_sec_phy_access_t *pa, const bcm_plp_secy_device_params_t * const control_p)EPDM_WEAK;

extern bcm_plp_sa_builder_status_t bcm_plp_europa_secy_build_transform_record(bcm_plp_sec_phy_access_t *pa, bcm_plp_sa_builder_params_t *params, unsigned int *sa_buffer_p)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_sa_window_size_update(bcm_plp_sec_phy_access_t *pa, const bcm_plp_secy_sa_handle_t sa_handle, const unsigned int window_size)EPDM_WEAK;
extern bcm_plp_secy_status_t bcm_plp_europa_secy_sa_nextpn_get(bcm_plp_sec_phy_access_t *pa, const bcm_plp_secy_sa_handle_t sa_handle, unsigned int *next_pn_lo_p, unsigned int *next_pn_hi_p, unsigned char *fext_pn_p) EPDM_WEAK;
extern int bcm_plp_europa_mac_sec_burst_reg_value_get(bcm_plp_sec_phy_access_t *pa, bcm_plp_sec_reg_access_t *reg_acc)EPDM_WEAK;

extern bcm_plp_secy_status_t bcm_plp_europa_secy_sa_next_get(bcm_plp_sec_phy_access_t *pa, const bcm_plp_secy_sa_handle_t current_sa_handle, bcm_plp_secy_sa_handle_t *next_sa_handle_p) EPDM_WEAK;
extern bcm_plp_secy_status_t bcm_plp_europa_secy_sci_next_get(bcm_plp_sec_phy_access_t *pa, unsigned int vport, const void **tmp_handle_p, unsigned char *next_sci_p, unsigned int *scindex_p) EPDM_WEAK;

extern int bcm_plp_europa_mac_sec_burst_reg_value_set(bcm_plp_sec_phy_access_t *pa, bcm_plp_sec_reg_access_t *reg_acc)EPDM_WEAK;
extern bcm_plp_secy_status_t bcm_plp_europa_secy_sa_active_e_get(bcm_plp_sec_phy_access_t *pa1, unsigned int vport, bcm_plp_secy_sa_handle_t * const active_sa_handle_p) EPDM_WEAK;

/* MAC */

extern int bcm_plp_europa_mac_loopback_set(bcm_plp_mac_access_t mac_info, bcm_plp_mac_lb_type_t lb_type, unsigned int enable)EPDM_WEAK;
extern int bcm_plp_europa_mac_loopback_get(bcm_plp_mac_access_t mac_info, bcm_plp_mac_lb_type_t lb_type, unsigned int *enable)EPDM_WEAK;
extern int bcm_plp_europa_mac_fault_option_set(bcm_plp_mac_access_t mac_info, bcm_plp_mac_fault_option_t fault_option)EPDM_WEAK;
extern int bcm_plp_europa_mac_fault_option_get(bcm_plp_mac_access_t mac_info, bcm_plp_mac_fault_option_t *fault_option)EPDM_WEAK;
extern int bcm_plp_europa_mac_flow_control_set(bcm_plp_mac_access_t mac_info, bcm_plp_mac_flow_control_t flow_option)EPDM_WEAK;
extern int bcm_plp_europa_mac_flow_control_get(bcm_plp_mac_access_t mac_info, bcm_plp_mac_flow_control_t *flow_option)EPDM_WEAK;
extern int bcm_plp_europa_mac_store_and_forward_mode_set(bcm_plp_mac_access_t mac_info, int enable)EPDM_WEAK;
extern int bcm_plp_europa_mac_store_and_forward_mode_get(bcm_plp_mac_access_t mac_info, int *is_enable)EPDM_WEAK;
extern int bcm_plp_europa_reg64_value_set(bcm_plp_access_t phy_info, unsigned int devaddr, unsigned int regaddr, plp_uint64_t data)EPDM_WEAK;
extern int bcm_plp_europa_reg64_value_get(bcm_plp_access_t phy_info, unsigned int devaddr, unsigned int regaddr, plp_uint64_t *data)EPDM_WEAK;
extern int bcm_plp_europa_mac_cleanup(bcm_plp_mac_access_t mac_info)EPDM_WEAK;
extern int bcm_plp_europa_mac_max_packet_size_set(bcm_plp_mac_access_t mac_info, int pkt_size)EPDM_WEAK;
extern int bcm_plp_europa_mac_max_packet_size_get(bcm_plp_mac_access_t mac_info, int *pkt_size)EPDM_WEAK;
extern int bcm_plp_europa_mac_runt_threshold_set(bcm_plp_mac_access_t mac_info, int threshold)EPDM_WEAK;
extern int bcm_plp_europa_mac_runt_threshold_get(bcm_plp_mac_access_t mac_info, int *threshold)EPDM_WEAK;
extern int bcm_plp_europa_mac_pad_size_set(bcm_plp_mac_access_t mac_info, int pad_size)EPDM_WEAK;
extern int bcm_plp_europa_mac_pad_size_get(bcm_plp_mac_access_t mac_info, int *pad_size)EPDM_WEAK;
extern int bcm_plp_europa_tx_mac_sa_set(bcm_plp_mac_access_t mac_info, unsigned char mac_sa[6])EPDM_WEAK;
extern int bcm_plp_europa_tx_mac_sa_get(bcm_plp_mac_access_t mac_info, unsigned char mac_sa[6])EPDM_WEAK;
extern int bcm_plp_europa_rx_mac_sa_set(bcm_plp_mac_access_t mac_info, unsigned char mac_sa[6])EPDM_WEAK;
extern int bcm_plp_europa_rx_mac_sa_get(bcm_plp_mac_access_t mac_info, unsigned char mac_sa[6])EPDM_WEAK;
extern int bcm_plp_europa_mac_tx_avg_ipg_set(bcm_plp_mac_access_t mac_info, int avg_ipg)EPDM_WEAK;
extern int bcm_plp_europa_mac_tx_avg_ipg_get(bcm_plp_mac_access_t mac_info, int *avg_ipg)EPDM_WEAK;
extern int bcm_plp_europa_mac_tx_preamble_length_set(bcm_plp_mac_access_t mac_info, int preamble_length)EPDM_WEAK;
extern int bcm_plp_europa_mac_tx_preamble_length_get(bcm_plp_mac_access_t mac_info, int *preamble_length)EPDM_WEAK;
extern int bcm_plp_europa_mac_pause_control_set(bcm_plp_mac_access_t mac_info, bcm_plp_mac_pause_control_t pause_control)EPDM_WEAK;
extern int bcm_plp_europa_mac_pause_control_get(bcm_plp_mac_access_t mac_info, bcm_plp_mac_pause_control_t *pause_control)EPDM_WEAK;
extern int bcm_plp_europa_mac_pfc_control_set(bcm_plp_mac_access_t mac_info, bcm_plp_mac_pfc_control_t pfc_ctrl)EPDM_WEAK;
extern int bcm_plp_europa_mac_pfc_control_get(bcm_plp_mac_access_t mac_info, bcm_plp_mac_pfc_control_t *pfc_ctrl)EPDM_WEAK;
extern int bcm_plp_europa_mac_diagnostic_dump(bcm_plp_mac_access_t mac_info)EPDM_WEAK;
extern int bcm_plp_europa_datapath_flush(bcm_plp_mac_access_t mac_info)EPDM_WEAK;
extern int bcm_plp_europa_port_enable_set(bcm_plp_mac_access_t mac_info, int tx_rx, int enable_disable)EPDM_WEAK;
extern int bcm_plp_europa_port_enable_get(bcm_plp_mac_access_t mac_info, int tx_rx, int *enable_disable)EPDM_WEAK;
extern int bcm_plp_europa_pcs_diagnostic_dump(bcm_plp_mac_access_t mac_info)EPDM_WEAK;
extern bcm_plp_warmboot_status_t bcm_plp_europa_macsec_warmboot_register(bcm_plp_sec_phy_access_t *pa, bcm_plp_macsec_warmboot_callbacks_t *ops) EPDM_WEAK;
extern bcm_plp_warmboot_status_t bcm_plp_europa_macsec_warmboot_shutdown(bcm_plp_sec_phy_access_t *pa, const unsigned int area_id) EPDM_WEAK;
extern bcm_plp_warmboot_status_t bcm_plp_europa_macsec_warmboot_restore(bcm_plp_sec_phy_access_t *pa, const unsigned int area_id) EPDM_WEAK;
extern bcm_plp_warmboot_status_t bcm_plp_europa_macsec_warmboot_maxsize_get(bcm_plp_sec_phy_access_t *pa,
                                                                            const bcm_plp_macsec_warmboot_device_type_t device_type,
                                                                            unsigned int * const maxbyte_count_p) EPDM_WEAK;

__plp__sec__dispatch__t__ plp_europa_sec_dispatch = {
    bcm_plp_europa_cfye_device_init,
    bcm_plp_europa_cfye_device_uninit,
    bcm_plp_europa_cfye_vport_add,
    bcm_plp_europa_cfye_vport_remove,
    bcm_plp_europa_cfye_vport_update,
    bcm_plp_europa_cfye_rule_add,
    bcm_plp_europa_cfye_rule_remove,
    bcm_plp_europa_cfye_rule_update,
    bcm_plp_europa_cfye_rule_enable,
    bcm_plp_europa_cfye_rule_disable,
    bcm_plp_europa_cfye_rule_enable_disable,
    bcm_plp_europa_cfye_vport_id_get,
    bcm_plp_europa_cfye_device_limits,
    bcm_plp_europa_cfye_device_update,
    bcm_plp_europa_cfye_statistics_read,
    bcm_plp_europa_cfye_statistics_summary_read,
    bcm_plp_europa_cfye_statistics_summary_channel_read,
    bcm_plp_europa_cfye_vport_handle_issame,
    bcm_plp_europa_cfye_rule_handle_issame,
    bcm_plp_europa_cfye_intr_enable_set,
    bcm_plp_europa_cfye_intr_enable_get,
    bcm_plp_europa_cfye_intr_status_get,
    bcm_plp_europa_cfye_intr_status_clear,
    bcm_plp_europa_cfye_event_status_get,
    bcm_plp_europa_cfye_rule_handle_get,
    bcm_plp_europa_cfye_rule_index_get,
    bcm_plp_europa_cfye_vport_handle_get,
    bcm_plp_europa_cfye_vport_index_get,
    __PLP_NOT_USED, /* bcm_plp_cfye_intr_set */
    __PLP_NOT_USED, /* bcm_plp_cfye_intr_get */
    __PLP_NOT_USED, /* bcm_plp_cfye_statistics_tcam_get */
    __PLP_NOT_USED, /* bcm_plp_cfye_statistics_summary_tcam_get */
    __PLP_NOT_USED, /* bcm_plp_cfye_statistics_channel_get */
    bcm_plp_europa_secy_device_init,
    bcm_plp_europa_secy_device_uninit,
    bcm_plp_europa_secy_sa_add,
    bcm_plp_europa_secy_sa_update,
    bcm_plp_europa_secy_sa_read,
    bcm_plp_europa_secy_sa_remove,
    bcm_plp_europa_secy_rules_sectag_update,
    bcm_plp_europa_secy_bypass_get,
    bcm_plp_europa_secy_bypass_set,
    bcm_plp_europa_secy_config_set,
    bcm_plp_europa_secy_device_limits,
    bcm_plp_europa_secy_device_count_summary_secy_checkandclear,
    bcm_plp_europa_secy_device_count_summary_pifc_checkandclear,
    bcm_plp_europa_secy_device_count_summary_ifc_checkandclear,
    bcm_plp_europa_secy_device_count_summary_pifc1_checkandclear,
    bcm_plp_europa_secy_device_count_summary_ifc1_checkandclear,
    bcm_plp_europa_secy_device_count_summary_prxcam_checkandclear,
    bcm_plp_europa_secy_device_count_summary_psa_checkandclear,
    bcm_plp_europa_secy_device_count_summary_sa_checkandclear,
    bcm_plp_europa_secy_device_count_summary_channel_checkandclear,
    bcm_plp_europa_secy_sa_handle_issame,
    bcm_plp_europa_secy_sa_handle_sa_index_issame,
    bcm_plp_europa_secy_crypt_auth_bypass_len_update,
    bcm_plp_europa_secy_sa_nextpn_update,
    bcm_plp_europa_secy_sa_chain,
    bcm_plp_europa_secy_sa_switch,
    bcm_plp_europa_secy_sa_statistics_e_get,
    bcm_plp_europa_secy_sa_statistics_i_get,
    bcm_plp_europa_secy_ifc_statistics_e_get,
    bcm_plp_europa_secy_ifc_statistics_i_get,
    bcm_plp_europa_secy_rxcam_statistics_get,
    bcm_plp_europa_secy_sa_pnthr_summary_checkandclear,
    bcm_plp_europa_secy_sa_expired_summary_checkandclear,
    bcm_plp_europa_secy_rules_mtucheck_update,
    bcm_plp_europa_secy_channel_statistics_get,
    bcm_plp_europa_secy_channel_packets_inflight_get,
    bcm_plp_europa_secy_secy_statistics_e_get,
    bcm_plp_europa_secy_secy_statistics_i_get,
    bcm_plp_europa_secy_device_count_summary_psecy_checkandclear,
    bcm_plp_europa_secy_intr_enable_set,
    bcm_plp_europa_secy_intr_enable_get,
    bcm_plp_europa_secy_intr_status_get,
    bcm_plp_europa_secy_intr_status_clear,
    bcm_plp_europa_secy_event_status_get,
    bcm_plp_europa_secy_sa_handle_get,
    bcm_plp_europa_secy_sa_index_get,
    bcm_plp_europa_secy_device_update,
    bcm_plp_europa_secy_build_transform_record,
    bcm_plp_europa_mac_sec_burst_reg_value_get,
    bcm_plp_europa_mac_sec_burst_reg_value_set,
    bcm_plp_europa_secy_sa_window_size_update,
    __PLP_NOT_USED, /* bcm_plp_secy_intr_set */
    __PLP_NOT_USED, /* bcm_plp_secy_intr_get */
    bcm_plp_europa_secy_sa_nextpn_get,
    __PLP_NOT_USED, /* bcm_plp_secy_crypt_auth_bypass_len_get */
    __PLP_NOT_USED, /* bcm_plp_secy_rules_mtucheck_get */
    bcm_plp_europa_secy_sci_next_get,
    bcm_plp_europa_mac_loopback_set,
    bcm_plp_europa_mac_loopback_get,
    bcm_plp_europa_mac_fault_option_set,
    bcm_plp_europa_mac_fault_option_get,
    bcm_plp_europa_mac_flow_control_set,
    bcm_plp_europa_mac_flow_control_get,
    bcm_plp_europa_mac_store_and_forward_mode_set,
    bcm_plp_europa_mac_store_and_forward_mode_get,
    bcm_plp_europa_mac_cleanup,
    bcm_plp_europa_mac_max_packet_size_set,
    bcm_plp_europa_mac_max_packet_size_get,
    bcm_plp_europa_mac_runt_threshold_set,
    bcm_plp_europa_mac_runt_threshold_get,
    bcm_plp_europa_mac_pad_size_set,
    bcm_plp_europa_mac_pad_size_get,
    bcm_plp_europa_tx_mac_sa_set,
    bcm_plp_europa_tx_mac_sa_get,
    bcm_plp_europa_rx_mac_sa_set,
    bcm_plp_europa_rx_mac_sa_get,
    bcm_plp_europa_mac_tx_avg_ipg_set,
    bcm_plp_europa_mac_tx_avg_ipg_get,
    bcm_plp_europa_mac_tx_preamble_length_set,
    bcm_plp_europa_mac_tx_preamble_length_get,
    bcm_plp_europa_mac_pause_control_set,
    bcm_plp_europa_mac_pause_control_get,
    bcm_plp_europa_mac_pfc_control_set,
    bcm_plp_europa_mac_pfc_control_get,
    bcm_plp_europa_reg64_value_set,
    bcm_plp_europa_reg64_value_get,
    bcm_plp_europa_mac_diagnostic_dump,
    bcm_plp_europa_datapath_flush,
    bcm_plp_europa_port_enable_set,
    bcm_plp_europa_port_enable_get,
    bcm_plp_europa_pcs_diagnostic_dump,
    __PLP_NOT_USED, /* bcm_plp_cfye_device_config_get */
    __PLP_NOT_USED, /* bcm_plp_cfye_device_status_get */
    __PLP_NOT_USED, /* bcm_plp_cfye_channel_bypass_get */
    bcm_plp_europa_cfye_channel_bypass_set,
    __PLP_NOT_USED, /* bcm_plp_cfye_rule_get */
    bcm_plp_europa_cfye_rule_next_get,
    bcm_plp_europa_cfye_rule_vport_next_get,
    __PLP_NOT_USED, /* bcm_plp_cfye_diag_device_dump */
    __PLP_NOT_USED, /* bcm_plp_cfye_diag_channel_dump */
    __PLP_NOT_USED, /* bcm_plp_cfye_diag_vport_dump */
    __PLP_NOT_USED, /* bcm_plp_cfye_diag_rule_dump */
    __PLP_NOT_USED, /* bcm_plp_cfye_vport_get */
    bcm_plp_europa_cfye_vport_next_get,
    __PLP_NOT_USED, /* bcm_plp_cfye_diag_insert_sop */
    __PLP_NOT_USED, /* bcm_plp_cfye_diag_insert_eop */
    __PLP_NOT_USED, /* bcm_plp_secy_device_status_get */
    __PLP_NOT_USED, /* bcm_plp_secy_device_config_get */
    __PLP_NOT_USED, /* bcm_plp_secy_device_role_get */
    __PLP_NOT_USED, /* bcm_plp_secy_diag_device_dump */
    __PLP_NOT_USED, /* bcm_plp_secy_diag_channel_dump */
    __PLP_NOT_USED, /* bcm_plp_secy_diag_vport_dump */
    __PLP_NOT_USED, /* bcm_plp_secy_diag_sa_dump */
    __PLP_NOT_USED, /* bcm_plp_secy_vport_statistics_clear */
    __PLP_NOT_USED, /* bcm_plp_secy_vport_params_get */
    __PLP_NOT_USED, /* bcm_plp_secy_diag_insert_sop */
    __PLP_NOT_USED, /* bcm_plp_secy_diag_insert_eop */
    __PLP_NOT_USED, /* bcm_plp_secy_sa_params_get */
    __PLP_NOT_USED, /* bcm_plp_secy_sa_vport_index_get */
    bcm_plp_europa_secy_sa_next_get,
    __PLP_NOT_USED, /* bcm_plp_secy_sa_chained_get */
    __PLP_NOT_USED, /* bcm_plp_secy_sa_windowsize_get */
    __PLP_NOT_USED, /* bcm_plp_mac_configure_frame_drop_set */
    __PLP_NOT_USED, /* bcm_plp_mac_configure_frame_drop_get */
    __PLP_NOT_USED, /* bcm_plp_secy_channel_config_set */
    bcm_plp_europa_secy_sa_active_e_get, /* bcm_plp_secy_sa_active_e_get */
    __PLP_NOT_USED, /* bcm_plp_secy_sa_active_i_get */
    __PLP_NOT_USED, /* bcm_plp_secy_channel_config_get */
    bcm_plp_europa_macsec_warmboot_register,
    bcm_plp_europa_macsec_warmboot_shutdown,
    bcm_plp_europa_macsec_warmboot_restore,
    bcm_plp_europa_macsec_warmboot_maxsize_get,
    __PLP_NOT_USED, /* bcm_plp_timesync_enable_set*/
    __PLP_NOT_USED, /* bcm_plp_timesync_enable_get */
    __PLP_NOT_USED, /* bcm_plp_tx_info_get */
    __PLP_NOT_USED, /* bcm_plp_mac_mib_stat_get */
    __PLP_NOT_USED, /* bcm_plp_update_port_config */
    __PLP_NOT_USED, /* bcm_plp_cfye_channel_vport_add */
    __PLP_NOT_USED, /* bcm_plp_cfye_device_limits_get */
    __PLP_NOT_USED, /* bcm_plp_cfye_statistics_mtt_get */
    __PLP_NOT_USED, /* bcm_plp_cfye_statistics_summary_mtt_read */
    __PLP_NOT_USED, /* bcm_plp_cfye_rule_add_index */
    __PLP_NOT_USED, /* bcm_plp_cfye_mtt_update */
    __PLP_NOT_USED, /* bcm_plp_cfye_mtt_entry_enable_disable */
    __PLP_NOT_USED, /* bcm_plp_cfye_mtt_enable_disable */
    __PLP_NOT_USED, /* bcm_plp_cfye_mtt_read */
    __PLP_NOT_USED, /* bcm_plp_cfye_diag_mtt_dump */
    __PLP_NOT_USED, /* bcm_plp_secy_sa_statistics_ipsec_i_get */
    __PLP_NOT_USED, /* bcm_plp_secy_secy_statistics_ipsec_e_get */
    __PLP_NOT_USED, /* bcm_plp_secy_secy_statistics_ipsec_i_get */
    __PLP_NOT_USED  /* bcm_plp_secy_channel_config_update */
};

#endif /* PLP_MACSEC_SUPPORT */
#endif /* PLP_EUROPA_SUPPORT */
