/*
 * $Id
 *
 * $Copyright: (c) 2023 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *
 * DO NOT EDIT THIS FILE!
 *
 */

#ifdef PLP_LANAI_SUPPORT
#include "epdm.h"

extern int bcm_plp_lanai_init(bcm_plp_access_t phy_info, int (*read)(void* user_acc,
            unsigned int core_addr, unsigned int reg_addr, unsigned int* val),
            int (*write)(void* user_acc, unsigned int core_addr, unsigned int reg_addr,
            unsigned int val), bcm_pm_firmware_load_method_t firmware_load_method) EPDM_WEAK;
extern int bcm_plp_lanai_init_fw_bcast(bcm_plp_access_t phy_info,
                  int (*read)(void* user_acc, unsigned int core_addr, unsigned int reg_addr, unsigned int* val),
                  int (*write)(void* user_acc, unsigned int core_addr, unsigned int reg_addr, unsigned int val),
                  bcm_plp_firmware_load_type_t *firmware_load_type,
                  bcm_pm_firmware_broadcast_method_t broadcast_method) EPDM_WEAK;
extern int bcm_plp_lanai_core_diagnostics_get(bcm_plp_access_t phy_info, bcm_plp_core_diagnostics_t *core_diag) EPDM_WEAK;
extern int bcm_plp_lanai_cleanup(bcm_plp_access_t phy_info) EPDM_WEAK;
extern int bcm_plp_lanai_link_status_get(bcm_plp_access_t phy_info, unsigned int *link_status) EPDM_WEAK;
extern int bcm_plp_lanai_mode_config_set(bcm_plp_access_t phy_info, int speed, int if_type,
                            int ref_clk, int interface_mode, void* device_aux_modes) EPDM_WEAK;
extern int bcm_plp_lanai_mode_config_get(bcm_plp_access_t phy_info, int *speed,
                            int *if_type, int *ref_clk, int *interface_mode,
                            void *device_aux_modes) EPDM_WEAK;
extern int bcm_plp_lanai_driver_version_get(bcm_plp_access_t phy_info, char *phy_chip_name, unsigned short *major_ver,
                         unsigned short *minor_ver) EPDM_WEAK;
extern int bcm_plp_lanai_prbs_set(bcm_plp_access_t phy_info, unsigned int tx_rx,
                     unsigned int poly, unsigned int invert,
                     unsigned int loopback, unsigned int ena_dis) EPDM_WEAK;
extern int bcm_plp_lanai_prbs_get(bcm_plp_access_t phy_info, unsigned int tx_rx,
                     unsigned int *poly, unsigned int *invert,
                     unsigned int *loopback, unsigned int *ena_dis) EPDM_WEAK;
extern int bcm_plp_lanai_prbs_rx_stat(bcm_plp_access_t phy_info, unsigned int time) EPDM_WEAK;
extern int bcm_plp_lanai_prbs_clear(bcm_plp_access_t phy_info, unsigned int tx_rx) EPDM_WEAK;
extern int bcm_plp_lanai_prbs_config_get(bcm_plp_access_t phy_info, unsigned int tx_rx,
                            unsigned int *poly, unsigned int *invert) EPDM_WEAK;
extern int bcm_plp_lanai_prbs_status_get(bcm_plp_access_t phy_info, unsigned int *prbs_lock,
                            unsigned int *prbs_lock_loss, unsigned int *error_count) EPDM_WEAK;
extern int bcm_plp_lanai_reg_value_set(bcm_plp_access_t phy_info, unsigned int devaddr,
                          unsigned int regaddr, unsigned int data) EPDM_WEAK;
extern int bcm_plp_lanai_reg_value_get(bcm_plp_access_t phy_info, unsigned int devaddr,
                          unsigned int regaddr, unsigned int *data) EPDM_WEAK;
extern int bcm_plp_lanai_polarity_set(bcm_plp_access_t phy_info, unsigned int tx_pol,
                         unsigned int rx_pol) EPDM_WEAK;
extern int bcm_plp_lanai_polarity_get(bcm_plp_access_t phy_info, unsigned int *tx_pol,
                         unsigned int *rx_pol) EPDM_WEAK;
extern int bcm_plp_lanai_tx_set(bcm_plp_access_t phy_info,  bcm_plp_tx_t* tx) EPDM_WEAK;
extern int bcm_plp_lanai_tx_get(bcm_plp_access_t phy_info,  bcm_plp_tx_t* tx) EPDM_WEAK;
extern int bcm_plp_lanai_rev_id(bcm_plp_access_t phy_info, unsigned int* rev_id) EPDM_WEAK;
extern int bcm_plp_lanai_loopback_set(bcm_plp_access_t phy_info, unsigned int lb_mode,
                         unsigned int enable) EPDM_WEAK;
extern int bcm_plp_lanai_loopback_get(bcm_plp_access_t phy_info, unsigned int lb_mode,
                         unsigned int *enable) EPDM_WEAK;
extern int bcm_plp_lanai_reset_set(bcm_plp_access_t phy_info, unsigned int reset_mode,
                      unsigned int reset_val) EPDM_WEAK;
extern int bcm_plp_lanai_firmware_info_get(bcm_plp_access_t phy_info, unsigned int *fw_version,
                              unsigned int *fw_crc) EPDM_WEAK;
extern int bcm_plp_lanai_firmware_set(bcm_plp_access_t phy_info) EPDM_WEAK;
extern int bcm_plp_lanai_rxtx_laneswap_set(bcm_plp_access_t phy_info, bcm_laneswap_map_t* laneswap_map) EPDM_WEAK;
extern int bcm_plp_lanai_rxtx_laneswap_get(bcm_plp_access_t phy_info, bcm_laneswap_map_t* laneswap_map) EPDM_WEAK;
extern int bcm_plp_lanai_phy_status_dump(bcm_plp_access_t phy_info) EPDM_WEAK;
extern int bcm_plp_lanai_phy_diagnostics_get(bcm_plp_access_t phy_info, bcm_plp_pm_phy_diagnostics_t* diag) EPDM_WEAK;
extern int bcm_plp_lanai_power_set(bcm_plp_access_t phy_info,  unsigned int power_rx, unsigned int power_tx) EPDM_WEAK;
extern int bcm_plp_lanai_power_get(bcm_plp_access_t phy_info,  unsigned int *power_rx, unsigned int *power_tx) EPDM_WEAK;
extern int bcm_plp_lanai_base_t_autoneg_ability_set(bcm_plp_access_t phy_info, bcm_plp_base_t_ability_t *ability) EPDM_WEAK;
extern int bcm_plp_lanai_base_t_autoneg_ability_get(bcm_plp_access_t phy_info, bcm_plp_base_t_ability_t *ability) EPDM_WEAK;
extern int bcm_plp_lanai_base_t_autoneg_set(bcm_plp_access_t phy_info, int  enable) EPDM_WEAK;
extern int bcm_plp_lanai_base_t_autoneg_get(bcm_plp_access_t phy_info, int *enable, int *an_done) EPDM_WEAK;
extern int bcm_plp_lanai_base_t_eee_set(bcm_plp_access_t phy_info, bcm_plp_base_t_eee_t *eee_conf) EPDM_WEAK;
extern int bcm_plp_lanai_base_t_eee_get(bcm_plp_access_t phy_info, bcm_plp_base_t_eee_t *eee_conf) EPDM_WEAK;
extern int bcm_plp_lanai_base_t_power_mode_set(bcm_plp_access_t phy_info, bcm_plp_base_t_power_mode_t  power_mode) EPDM_WEAK;
extern int bcm_plp_lanai_base_t_power_mode_get(bcm_plp_access_t phy_info, bcm_plp_base_t_power_mode_t *power_mode) EPDM_WEAK;
extern int bcm_plp_lanai_base_t_cable_diag(bcm_plp_access_t phy_info, bcm_plp_base_t_cable_diag_t *cdiag) EPDM_WEAK;
extern int bcm_plp_lanai_base_t_state_mfg_diag(bcm_plp_access_t phy_info, unsigned int inst,
                      bcm_plp_base_t_diag_ctrl_type_t op_type, bcm_plp_base_t_diag_ctrl_cmd_t  op_cmd, void *arg) EPDM_WEAK;
extern int bcm_plp_lanai_mutex_info_set(bcm_plp_access_t phy_info, bcm_plp_mutex_info_t *mutex_info) EPDM_WEAK;

extern int bcm_plp_lanai_intr_status_get(bcm_plp_access_t phy_info, unsigned int intr_type, unsigned int* intr_status) EPDM_WEAK;
extern int bcm_plp_lanai_intr_enable_set(bcm_plp_access_t phy_info, unsigned int intr_type, unsigned int enable) EPDM_WEAK;
extern int bcm_plp_lanai_intr_enable_get(bcm_plp_access_t phy_info, unsigned int intr_type, unsigned int* enable) EPDM_WEAK;
extern int bcm_plp_lanai_intr_status_clear(bcm_plp_access_t phy_info, unsigned int intr_type) EPDM_WEAK;

extern int bcm_plp_lanai_timesync_config_set(bcm_plp_access_t phy_info, bcm_plp_timesync_config_t* config) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_config_get(bcm_plp_access_t phy_info, bcm_plp_timesync_config_t* config) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_enable_set(bcm_plp_access_t phy_info, unsigned int flags, unsigned int enable) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_enable_get(bcm_plp_access_t phy_info, unsigned int flags, unsigned int* enable) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_mpls_set(bcm_plp_access_t phy_info, unsigned int flags, int  enable, bcm_plp_timesync_mpls_ctrl_t *mpls_ctrl) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_mpls_get(bcm_plp_access_t phy_info, unsigned int flags, int* enable, bcm_plp_timesync_mpls_ctrl_t *mpls_ctrl) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_nco_addend_set(bcm_plp_access_t phy_info, unsigned int flags,  unsigned int freq_step) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_nco_addend_get(bcm_plp_access_t phy_info, unsigned int flags, unsigned int* freq_step) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_framesync_mode_set(bcm_plp_access_t phy_info, unsigned int flags, bcm_plp_timesync_framesync_t* framesync) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_framesync_mode_get(bcm_plp_access_t phy_info, unsigned int flags, bcm_plp_timesync_framesync_t* framesync) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_local_time_set(bcm_plp_access_t phy_info, unsigned int flags, plp_uint64_t local_time) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_local_time_get(bcm_plp_access_t phy_info, unsigned int flags, plp_uint64_t* local_time) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_load_ctrl_set(bcm_plp_access_t phy_info, unsigned int flags, unsigned int load_once, unsigned int load_always) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_load_ctrl_get(bcm_plp_access_t phy_info, unsigned int flags, unsigned int* load_once, unsigned int* load_always) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_timing_control_set(bcm_plp_access_t phy_info, unsigned int flags, bcm_plp_timesync_time_value_t *time_ctrl) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_timing_control_get(bcm_plp_access_t phy_info, unsigned int flags, bcm_plp_timesync_time_value_t *time_ctrl) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_link_delay_set(bcm_plp_access_t phy_info, unsigned int flags, bcm_plp_timesync_time_value_t *linkdelay) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_link_delay_get(bcm_plp_access_t phy_info, unsigned int flags, bcm_plp_timesync_time_value_t *linkdelay) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_timestamp_offset_set(bcm_plp_access_t phy_info, unsigned int flags, bcm_plp_timesync_time_value_t *ts_offset) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_timestamp_offset_get(bcm_plp_access_t phy_info, unsigned int flags, bcm_plp_timesync_time_value_t *ts_offset) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_tx_timestamp_offset_set(bcm_plp_access_t phy_info, unsigned int flags, unsigned int ts_offset) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_tx_timestamp_offset_get(bcm_plp_access_t phy_info, unsigned int flags, unsigned int* ts_offset) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_rx_timestamp_offset_set(bcm_plp_access_t phy_info, unsigned int flags, unsigned int ts_offset) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_rx_timestamp_offset_get(bcm_plp_access_t phy_info, unsigned int flags, unsigned int* ts_offset) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_time_code_set(bcm_plp_access_t phy_info, unsigned int flags, bcm_plp_timesync_timespec_t *timecode) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_time_code_get(bcm_plp_access_t phy_info, unsigned int flags, bcm_plp_timesync_timespec_t *timecode) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_capture_timestamp_get(bcm_plp_access_t phy_info, unsigned int flags, plp_uint64_t* cap_ts) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_heartbeat_timestamp_get(bcm_plp_access_t phy_info, unsigned int flags, plp_uint64_t* hb_ts) EPDM_WEAK;
extern int bcm_plp_lanai_timestamp_univ_get(bcm_plp_access_t phy_info, unsigned int flags, int index, bcm_plp_timestamp_univ_t *sopentry) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_do_sync(bcm_plp_access_t phy_info) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_sopmem_get(bcm_plp_access_t phy_info, unsigned int flags, int index, bcm_plp_timesync_sopmem_t *sopentry) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_ptp_action_set(bcm_plp_access_t phy_info, unsigned int flags, bcm_plp_timesync_txrx_t direction, bcm_plp_timesync_ptp_action_mode_t  mode, void *user_def) EPDM_WEAK;
extern int bcm_plp_lanai_timesync_ptp_action_get(bcm_plp_access_t phy_info, unsigned int flags, bcm_plp_timesync_txrx_t direction, bcm_plp_timesync_ptp_action_mode_t *mode, void *user_def) EPDM_WEAK;
extern int bcm_plp_lanai_synce_config_set(bcm_plp_access_t phy_info, bcm_plp_synce_cfg_t* synce_cfg) EPDM_WEAK;
extern int bcm_plp_lanai_synce_config_get(bcm_plp_access_t phy_info, bcm_plp_synce_cfg_t* synce_cfg) EPDM_WEAK;
extern int bcm_plp_lanai_phy_pai_info_get(bcm_plp_access_t phy_info, bcm_plp_pai_info_t *epdm_pai_info) EPDM_WEAK;

__plp__dispatch__t__ plp_lanai_dispatch = {
    __PLP_NOT_USED, /* bcm_plp_lanai_static_config_set */
    __PLP_NOT_USED, /* bcm_plp_lanai_static_config_get */
    bcm_plp_lanai_init,
    bcm_plp_lanai_cleanup,
    bcm_plp_lanai_link_status_get,
    bcm_plp_lanai_mode_config_set,
    bcm_plp_lanai_mode_config_get,
    bcm_plp_lanai_driver_version_get,
    bcm_plp_lanai_prbs_set,
    bcm_plp_lanai_prbs_get,
    bcm_plp_lanai_prbs_rx_stat,
    bcm_plp_lanai_prbs_clear,
    bcm_plp_lanai_prbs_config_get,
    bcm_plp_lanai_prbs_status_get,
    bcm_plp_lanai_reg_value_set,
    bcm_plp_lanai_reg_value_get,
    bcm_plp_lanai_polarity_set,
    bcm_plp_lanai_polarity_get,
    __PLP_NOT_USED, /* bcm_plp_lanai_rx_pmd_lock_get */
    bcm_plp_lanai_rev_id,
    bcm_plp_lanai_loopback_set,
    bcm_plp_lanai_loopback_get,
    bcm_plp_lanai_tx_set,
    bcm_plp_lanai_tx_get,
    __PLP_NOT_USED, /* bcm_plp_lanai_rx_set */
    __PLP_NOT_USED, /* bcm_plp_lanai_rx_get */
    bcm_plp_lanai_reset_set,
    __PLP_NOT_USED, /* bcm_plp_lanai_phy_lane_reset_set */
    __PLP_NOT_USED, /* bcm_plp_lanai_phy_lane_reset_get */
    __PLP_NOT_USED, /* bcm_plp_lanai_tx_lane_control_set */
    __PLP_NOT_USED, /* bcm_plp_lanai_rx_lane_control_set */
    __PLP_NOT_USED, /* bcm_plp_lanai_tx_lane_control_get */
    __PLP_NOT_USED, /* bcm_plp_lanai_rx_lane_control_get */
    __PLP_NOT_USED, /* bcm_plp_lanai_lane_cross_switch_map_set */
    __PLP_NOT_USED, /* bcm_plp_lanai_lane_cross_switch_map_get */
    __PLP_NOT_USED, /* bcm_plp_lanai_force_tx_training_set */
    __PLP_NOT_USED, /* bcm_plp_lanai_force_tx_training_get */
    __PLP_NOT_USED, /* bcm_plp_lanai_force_tx_training_status_get */
    __PLP_NOT_USED, /* bcm_plp_lanai_cl73_ability_set */
    __PLP_NOT_USED, /* bcm_plp_lanai_cl73_ability_get */
    __PLP_NOT_USED, /* bcm_plp_lanai_cl73_set */
    __PLP_NOT_USED, /* bcm_plp_lanai_cl73_get */
    __PLP_NOT_USED, /* bcm_plp_lanai_display_eye_scan */
    bcm_plp_lanai_firmware_info_get,
    bcm_plp_lanai_firmware_set,
    bcm_plp_lanai_rxtx_laneswap_set,
    bcm_plp_lanai_rxtx_laneswap_get,
    __PLP_NOT_USED, /* bcm_plp_lanai_pll_sequencer_restart */
    __PLP_NOT_USED, /* bcm_plp_lanai_fec_enable_set */
    __PLP_NOT_USED, /* bcm_plp_lanai_fec_enable_get */
    bcm_plp_lanai_phy_status_dump,
    bcm_plp_lanai_phy_diagnostics_get,
    bcm_plp_lanai_intr_status_get,
    bcm_plp_lanai_intr_enable_set,
    bcm_plp_lanai_intr_enable_get,
    bcm_plp_lanai_intr_status_clear,
    __PLP_NOT_USED, /* bcm_plp_lanai_fc_pcs_chkr_enable_set */
    __PLP_NOT_USED, /* bcm_plp_lanai_fc_pcs_chkr_enable_get */
    __PLP_NOT_USED, /* bcm_plp_lanai_fc_pcs_chkr_status_get */
    __PLP_NOT_USED, /* bcm_plp_lanai_eye_margin_proj */
    __PLP_NOT_USED, /* bcm_plp_lanai_repeater_mode_get */
    __PLP_NOT_USED, /* bcm_plp_lanai_repeater_mode_set */
    __PLP_NOT_USED, /* bcm_plp_lanai_module_read */
    __PLP_NOT_USED, /* bcm_plp_lanai_module_write */
    __PLP_NOT_USED, /* bcm_plp_lanai_cfg_gpio_pin_set */
    __PLP_NOT_USED, /* bcm_plp_lanai_cfg_gpio_pin_get */
    bcm_plp_lanai_power_set,
    bcm_plp_lanai_power_get,
    __PLP_NOT_USED, /* bcm_plp_lanai_firmware_lane_config_set */
    __PLP_NOT_USED, /* bcm_plp_lanai_firmware_lane_config_get */
    bcm_plp_lanai_init_fw_bcast,
    __PLP_NOT_USED, /* bcm_plp_lanai_failover_mode_set */
    __PLP_NOT_USED, /* bcm_plp_lanai_failover_mode_get */
    __PLP_NOT_USED, /* bcm_plp_lanai_edc_config_set */
    __PLP_NOT_USED, /* bcm_plp_lanai_edc_config_get */
    __PLP_NOT_USED, /* bcm_plp_lanai_fec_corrected_counter_get */
    __PLP_NOT_USED, /* bcm_plp_lanai_fec_uncorrected_counter_get */
    __PLP_NOT_USED, /* bcm_plp_lanai_event_status_get */
    bcm_plp_lanai_base_t_autoneg_ability_set,
    bcm_plp_lanai_base_t_autoneg_ability_get,
    bcm_plp_lanai_base_t_autoneg_set,
    bcm_plp_lanai_base_t_autoneg_get,
    bcm_plp_lanai_base_t_eee_set,
    bcm_plp_lanai_base_t_eee_get,
    bcm_plp_lanai_base_t_power_mode_set,
    bcm_plp_lanai_base_t_power_mode_get,
    bcm_plp_lanai_timesync_config_set,
    bcm_plp_lanai_timesync_config_get,
    bcm_plp_lanai_timesync_enable_set,
    bcm_plp_lanai_timesync_enable_get,
    bcm_plp_lanai_timesync_nco_addend_set,
    bcm_plp_lanai_timesync_nco_addend_get,
    bcm_plp_lanai_timesync_framesync_mode_set,
    bcm_plp_lanai_timesync_framesync_mode_get,
    bcm_plp_lanai_timesync_local_time_set,
    bcm_plp_lanai_timesync_local_time_get,
    bcm_plp_lanai_timesync_load_ctrl_set,
    bcm_plp_lanai_timesync_load_ctrl_get,
    __PLP_NOT_USED,  /* bcm_plp_timesync_tx_timestamp_offset_set*/
    __PLP_NOT_USED,  /* bcm_plp_timesync_tx_timestamp_offset_get*/
    __PLP_NOT_USED,  /* bcm_plp_timesync_rx_timestamp_offset_set*/
    __PLP_NOT_USED,  /* bcm_plp_timesync_rx_timestamp_offset_get*/
    bcm_plp_lanai_timesync_capture_timestamp_get,
    bcm_plp_lanai_timesync_heartbeat_timestamp_get,
    bcm_plp_lanai_timesync_do_sync,
    bcm_plp_lanai_mutex_info_set,
    __PLP_NOT_USED, /*bcm_plp_l1_intr_status_get*/
    bcm_plp_lanai_base_t_cable_diag,
    bcm_plp_lanai_base_t_state_mfg_diag,
    __PLP_NOT_USED,  /* bcm_plp_pam4_tx_set */
    __PLP_NOT_USED,  /* bcm_plp_pam4_tx_get */
    __PLP_NOT_USED,  /* bcm_plp_phy_pam4_diagnostics_get */
    __PLP_NOT_USED,  /* bcm_plp_jfec_config_set */
    __PLP_NOT_USED,  /* bcm_plp_jfec_config_get */
    __PLP_NOT_USED,  /* bcm_plp_fec_status_get */
    __PLP_NOT_USED,  /* bcm_plp_kp4_fec_config_set */
    __PLP_NOT_USED,  /* bcm_plp_kp4_fec_config_get */
    bcm_plp_lanai_core_diagnostics_get,
    __PLP_NOT_USED,  /* bcm_plp_avs_config_set */
    __PLP_NOT_USED,  /* bcm_plp_avs_config_get */
    __PLP_NOT_USED,  /* bcm_plp_avs_status_get */
    __PLP_NOT_USED,  /* bcm_plp_prbs_error_inject_set */
    __PLP_NOT_USED,  /* bcm_plp_logical_lane_set */
    __PLP_NOT_USED,  /* bcm_plp_logical_lane_get */
    __PLP_NOT_USED,  /* bcm_plp_prbs_error_analyzer_proj */
    __PLP_NOT_USED,  /* bcm_plp_dsrds_firmware_lane_config_set */
    __PLP_NOT_USED,  /* bcm_plp_dsrds_firmware_lane_config_get */
    bcm_plp_lanai_synce_config_set,
    bcm_plp_lanai_synce_config_get,
    __PLP_NOT_USED,  /* bcm_plp_autoneg_remote_ability_get */
    bcm_plp_lanai_timesync_time_code_set,
    bcm_plp_lanai_timesync_time_code_get,
    bcm_plp_lanai_timesync_link_delay_set,
    bcm_plp_lanai_timesync_link_delay_get,
    bcm_plp_lanai_timesync_timestamp_offset_set,
    bcm_plp_lanai_timesync_timestamp_offset_get,
    bcm_plp_lanai_timesync_timing_control_set,
    bcm_plp_lanai_timesync_timing_control_get,
    __PLP_NOT_USED,  /* bcm_plp_pcs_status_get */
    bcm_plp_lanai_timesync_sopmem_get,
    __PLP_NOT_USED,  /* bcm_plp_pattern_enable_get*/
    __PLP_NOT_USED,  /* bcm_plp_pattern_enable_get*/
    __PLP_NOT_USED,  /* bcm_plp_fw_init_params_get*/
    __PLP_NOT_USED,  /* bcm_plp_srds_diag_access_enable*/
    bcm_plp_lanai_timesync_mpls_set,
    bcm_plp_lanai_timesync_mpls_get,
    __PLP_NOT_USED,  /* bcm_plp_lanai_timesync_inband_filter_set */
    __PLP_NOT_USED,  /* bcm_plp_lanai_timesync_inband_filter_get */
    bcm_plp_lanai_phy_pai_info_get,
    __PLP_NOT_USED,  /* bcm_plp_failover_config_set */
    __PLP_NOT_USED,  /* bcm_plp_failover_config_get */
    __PLP_NOT_USED,  /* bcm_plp_timesync_sopmem_set, */
    __PLP_NOT_USED,  /* bcm_plp_timesync_pch_set, */
    __PLP_NOT_USED,  /* bcm_plp_timesync_pch_get, */
    __PLP_NOT_USED,  /* bcm_plp_timestamp_univ_set, */
    bcm_plp_lanai_timestamp_univ_get,
    __PLP_NOT_USED,  /* bcm_plp_peripheral_device_control, */
    __PLP_NOT_USED,  /* bcm_plp_phy_stats */
    bcm_plp_lanai_timesync_ptp_action_set,
    bcm_plp_lanai_timesync_ptp_action_get,
}; /* plp_dispatch */

#endif /* PLP_LANAI_SUPPORT */
