/*
 * $Id: longfin_sec_dispatch.c $
 *
 * $Copyright: (c) 2020 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *
 *
 * DO NOT EDIT THIS FILE!
 *
 */

#ifdef PLP_LONGFIN_SUPPORT
#ifdef PLP_MACSEC_SUPPORT
#include "epdm_base_t_sec.h"

/* SECY */
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_device_init(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const bcm_plp_base_t_secy_settings_t * const settings_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_device_uninit(bcm_plp_base_t_sec_phy_access_t *pa) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_device_limits(bcm_plp_base_t_sec_phy_access_t *pa,
                                 unsigned int * const max_vport_count_p,
                                 unsigned int * const max_rule_count_p,
                                 unsigned int * const max_sa_count_p,
                                 unsigned int * const max_sc_count_p) EPDM_WEAK;

unsigned char bcm_plp_longfin_base_t_secy_vport_handle_issame(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const bcm_plp_base_t_secy_vport_handle_t * const handle1_p,
                                 const bcm_plp_base_t_secy_vport_handle_t * const handle2_p) EPDM_WEAK;

unsigned char bcm_plp_longfin_base_t_secy_sa_handle_issame(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const bcm_plp_base_t_secy_sa_handle_t * const handle1_p,
                                 const bcm_plp_base_t_secy_sa_handle_t * const handle2_p) EPDM_WEAK;

unsigned char bcm_plp_longfin_base_t_secy_sa_handle_sa_index_issame(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const bcm_plp_base_t_secy_sa_handle_t sa_handle,
                                 const unsigned int sa_index) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sa_add(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const bcm_plp_base_t_secy_vport_handle_t vport_handle,
                                 bcm_plp_base_t_secy_sa_handle_t * const sa_handle_p,
                                 const bcm_plp_base_t_secy_sa_t * const sa_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sa_update(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const bcm_plp_base_t_secy_sa_handle_t sa_handle,
                                 const bcm_plp_base_t_secy_sa_t * const sa_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sa_read(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const bcm_plp_base_t_secy_sa_handle_t sa_handle,
                                 const unsigned int word_offset,
                                 const unsigned int word_count,
                                 unsigned int * transform_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sa_remove(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const bcm_plp_base_t_secy_sa_handle_t sa_handle) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sa_nextpn_update(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const bcm_plp_base_t_secy_sa_handle_t sa_handle,
                                 const unsigned int nextpn_lo,
                                 const unsigned int nextpn_hi,
                                 unsigned char * const fnextpn_written_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sa_chain(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const bcm_plp_base_t_secy_sa_handle_t active_sa_handle,
                                 bcm_plp_base_t_secy_sa_handle_t * const new_sa_handle_p,
                                 const bcm_plp_base_t_secy_sa_t * const new_sa_p) EPDM_WEAK;


bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sa_switch(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const bcm_plp_base_t_secy_sa_handle_t active_sa_handle,
                                 const bcm_plp_base_t_secy_sa_handle_t new_sa_handle,
                                 const bcm_plp_base_t_secy_sa_t * const new_sa_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_vport_add(bcm_plp_base_t_sec_phy_access_t *pa,
                                 bcm_plp_base_t_secy_vport_handle_t *vport_handle_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_vport_remove(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const bcm_plp_base_t_secy_vport_handle_t vport_handle) EPDM_WEAK;

unsigned char bcm_plp_longfin_base_t_secy_rule_handle_issame(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const bcm_plp_base_t_secy_rule_handle_t * const handle1_p,
                                 const bcm_plp_base_t_secy_rule_handle_t * const handle2_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_rule_add(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const bcm_plp_base_t_secy_vport_handle_t vport_handle,
                                 bcm_plp_base_t_secy_rule_handle_t *rule_handle_p,
                                 const bcm_plp_base_t_secy_rule_t *rule_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_rule_remove(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const bcm_plp_base_t_secy_rule_handle_t rule_handle) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_rule_update(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const bcm_plp_base_t_secy_rule_handle_t rule_handle,
                                 const bcm_plp_base_t_secy_rule_t *rule_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_rule_enable(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const bcm_plp_base_t_secy_rule_handle_t rule_handle,
                                 const unsigned char fsync) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_rule_disable(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const bcm_plp_base_t_secy_rule_handle_t rule_handle,
                                 const unsigned char fsync) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_rule_enable_disable(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const bcm_plp_base_t_secy_rule_handle_t rule_handle_disable,
                                 const bcm_plp_base_t_secy_rule_handle_t rule_handle_enable,
                                 const unsigned char enable_all,
                                 const unsigned char disable_all,
                                 const unsigned char fsync) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sa_index_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const bcm_plp_base_t_secy_sa_handle_t sa_handle,
                                 unsigned int * const sa_index_p,
                                 unsigned int * const sc_index_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_rule_index_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const bcm_plp_base_t_secy_rule_handle_t rule_handle,
                                 unsigned int * const rule_index_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_vport_index_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const bcm_plp_base_t_secy_vport_handle_t vport_handle,
                                 unsigned int * const vport_index_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sa_handle_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const unsigned int sa_index,
                                 bcm_plp_base_t_secy_sa_handle_t * const sa_handle_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_rule_handle_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const unsigned int rule_index,
                                 bcm_plp_base_t_secy_rule_handle_t * const rule_handle_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_vport_handle_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                 const unsigned int vport_index,
                                 bcm_plp_base_t_secy_vport_handle_t * const vport_handle_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_device_update(bcm_plp_base_t_sec_phy_access_t *pa,
                                                              const bcm_plp_base_t_secy_device_params_t  * const device_p ) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_crypt_auth_bypass_len_update(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                                              const unsigned int bypass_length) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_rules_mtu_check_update(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                    const unsigned int sci_index,
                                                                    const bcm_plp_base_t_secy_sc_rule_mtu_check_t * const mtucheck_rule_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_tcam_statistics_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                                const bcm_plp_base_t_secy_rule_handle_t rule_handle,
                                                                                bcm_plp_base_t_secy_tcam_stat_t * const stat_p,
                                                                                const unsigned char fsync) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_rxcam_statistics_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                                 const unsigned int scindex,
                                                                                 bcm_plp_base_t_secy_rxcam_stat_t* const stats_p,
                                                                                 const unsigned char fsync) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_secy_statistics_i_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                                 bcm_plp_base_t_secy_vport_handle_t vport_handle,
                                                                                 bcm_plp_base_t_secy_secy_stat_i_t * const stats_p,
                                                                                 const unsigned char fsync) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_secy_statistics_e_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                                 bcm_plp_base_t_secy_vport_handle_t vport_handle,
                                                                                 bcm_plp_base_t_secy_secy_stat_e_t * const stats_p,
                                                                                 const unsigned char fsync) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sa_statistics_i_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                           const bcm_plp_base_t_secy_sa_handle_t sa_handle,
                                                                           bcm_plp_base_t_secy_sa_stat_i_t * const stats_p,
                                                                           const unsigned char fsync) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sa_statistics_e_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                            const bcm_plp_base_t_secy_sa_handle_t sa_handle,
                                                                            bcm_plp_base_t_secy_sa_stat_e_t * const stats_p,
                                                                            const unsigned char fsync) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_global_statistics_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                                 bcm_plp_base_t_secy_global_stat_t * const stat_p,
                                                                                 const unsigned char fsync) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_ifc_statistics_e_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                    bcm_plp_base_t_secy_vport_handle_t vport_handle,
                                                                    bcm_plp_base_t_secy_ifc_stat_e_t * const stats_p,
                                                                    const unsigned char fsync) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_ifc_statistics_i_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                        bcm_plp_base_t_secy_vport_handle_t vport_handle,
                                                                        bcm_plp_base_t_secy_ifc_stat_i_t * const stats_p,
                                                                        const unsigned char fsync) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_device_count_summary_pifc_checkandclear(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                                                           bcm_plp_base_t_secy_vport_handle_t ** const vport_handle_pp,
                                                                                                           unsigned int * const num_ifc_indexes_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_device_count_summary_prxcam_checkandclear(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                                                         unsigned int ** const rx_cam_indexes_pp,
                                                                                                         unsigned int * const num_rx_cam_indexes_p) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_device_count_summary_psa_checkandclear(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                                           bcm_plp_base_t_secy_sa_handle_t ** const sa_handle_pp,
                                                                                           unsigned int * const num_sa_indexes_p) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_device_count_summary_psecy_checkandclear(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                                                                bcm_plp_base_t_secy_vport_handle_t ** const vport_handle_pp,
                                                                                                                unsigned int * const nm_secy_indexes_p) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_device_count_summary_ptcam_checkandclear(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                                 bcm_plp_base_t_secy_rule_handle_t ** const rule_handle_pp,
                                                                                 unsigned int * const num_tcam_indexes_p) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_device_count_summary_sa_checkandclear(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                                    bcm_plp_base_t_secy_sa_handle_t sa_handle,
                                                                                    unsigned int * const count_summary_sa_p) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_device_count_summary_secy_checkandclear(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                                                 bcm_plp_base_t_secy_vport_handle_t vport_handle,
                                                                                                 unsigned int * const count_summary_secy_p) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_device_count_summary_tcam_global_checkandclear(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                                                          unsigned int * const count_summary_tcam_global_p) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_device_count_summary_ifc_checkandclear(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                                           bcm_plp_base_t_secy_vport_handle_t vport_handle,
                                                                                           unsigned int * const count_summary_ifc_p) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sa_expired_summary_checkandclear(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                                      bcm_plp_base_t_secy_sa_handle_t ** const sa_handle_pp,
                                                                                      unsigned int * const num_sa_indexes_p) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sa_pnthr_summary_checkandclear(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                                       bcm_plp_base_t_secy_sa_handle_t ** const sa_handle_pp,
                                                                                       unsigned int * const num_sa_indexes_p) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_intr_enable_set(bcm_plp_base_t_sec_phy_access_t *pa, const bcm_plp_base_t_secy_intr_t *secy_intr_p) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_intr_enable_get(bcm_plp_base_t_sec_phy_access_t *pa, bcm_plp_base_t_secy_intr_t *secy_intr_p) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_intr_status_get(bcm_plp_base_t_sec_phy_access_t *pa, bcm_plp_base_t_secy_intr_t *secy_intr_p) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_intr_status_clear(bcm_plp_base_t_sec_phy_access_t *pa, const bcm_plp_base_t_secy_intr_t *secy_intr_p) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_event_status_get(bcm_plp_base_t_sec_phy_access_t *pa, bcm_plp_base_t_secy_intr_t *secy_intr_p) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_intr_set(bcm_plp_base_t_sec_phy_access_t *pa, const bcm_plp_base_t_secy_intr_t *secy_intr, const unsigned int enable) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_intr_get(bcm_plp_base_t_sec_phy_access_t *pa, bcm_plp_base_t_secy_intr_t *secy_intr, unsigned int *enable) EPDM_WEAK;
bcm_plp_base_t_sa_builder_status_t bcm_plp_longfin_base_t_secy_build_transform_record(bcm_plp_base_t_sec_phy_access_t *pa, bcm_plp_base_t_sa_builder_params_t *params, unsigned int *sa_buffer_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sa_active_e_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                  const unsigned int vport,
                                  bcm_plp_base_t_secy_sa_handle_t * const active_sa_handle_p) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sa_active_i_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                  const unsigned int vport,
                                  const unsigned char * const sci_p,
                                  bcm_plp_base_t_secy_sa_handle_t * const active_sa_handle_p) EPDM_WEAK;

int bcm_plp_longfin_base_t_imacsec_version_get(bcm_plp_base_t_sec_phy_access_t *pa, bcm_plp_base_t_version_t* version_info) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sa_window_size_update(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                                      const bcm_plp_base_t_secy_sa_handle_t sa_handle,
                                                                                      const unsigned int window_size) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_bypass_set(bcm_plp_base_t_sec_phy_access_t *pa, const unsigned char fbypass) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_bypass_get(bcm_plp_base_t_sec_phy_access_t *pa, unsigned char *fbypass) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_vport_params_get( bcm_plp_base_t_sec_phy_access_t *pa,
                                                                    const bcm_plp_base_t_secy_vport_handle_t vport_handle,
                                                                    bcm_plp_base_t_secy_sa_t * const sa_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sa_params_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                           const bcm_plp_base_t_secy_sa_handle_t sa_handle,
                                           bcm_plp_base_t_secy_sa_t * const sa_p,
                                           unsigned char * const sci_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sa_next_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                        const bcm_plp_base_t_secy_sa_handle_t current_sa_handle,
                                        bcm_plp_base_t_secy_sa_handle_t * const next_sa_handle_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sa_window_size_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                         const bcm_plp_base_t_secy_sa_handle_t sa_handle,
                                         unsigned int * const  window_size_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sa_next_pn_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                            const bcm_plp_base_t_secy_sa_handle_t sa_handle,
                                            unsigned int * const next_pn_lo_p,
                                            unsigned int * const next_pn_hi_p,
                                            unsigned char * const fext_pn_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_vport_next_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                              const bcm_plp_base_t_secy_vport_handle_t current_vport_handle,
                                              bcm_plp_base_t_secy_vport_handle_t * const next_vport_handle_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_rule_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                             const bcm_plp_base_t_secy_rule_handle_t rule_handle,
                                             bcm_plp_base_t_secy_rule_t * const rule_p,
                                             unsigned char * const f_enabled_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_rule_next_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                    const bcm_plp_base_t_secy_rule_handle_t current_rule_handle,
                                    bcm_plp_base_t_secy_rule_handle_t * const next_rule_handle_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_rule_vport_next_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                        const bcm_plp_base_t_secy_vport_handle_t vport_handle,
                                        const bcm_plp_base_t_secy_rule_handle_t current_rule_handle,
                                        bcm_plp_base_t_secy_rule_handle_t * const next_rule_handle_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sa_chained_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                            const bcm_plp_base_t_secy_sa_handle_t current_sa_handle,
                                            bcm_plp_base_t_secy_sa_handle_t * const next_sa_handle_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_rules_mtu_check_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                       unsigned int sci_index,
                                                                       bcm_plp_base_t_secy_sc_rule_mtu_check_t * const mtu_check_rule_p) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_diag_vport_dump(bcm_plp_base_t_sec_phy_access_t *pa,
                                        const bcm_plp_base_t_secy_vport_handle_t vport_handle,
                                        const unsigned char f_all_vports,
                                        const unsigned char f_include_sa) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_diag_sa_dump(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                const bcm_plp_base_t_secy_sa_handle_t sa_handle,
                                                                const unsigned char f_all_sas) EPDM_WEAK;

bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_diag_rule_dump(bcm_plp_base_t_sec_phy_access_t *pa,
                                                      const bcm_plp_base_t_secy_rule_handle_t rule_handle,
                                                      const unsigned char f_all_rules) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sa_vport_handle_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                 const bcm_plp_base_t_secy_sa_handle_t sa_handle,
                                                                 bcm_plp_base_t_secy_vport_handle_t * const vport_handle_p) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_sci_next_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                                          const bcm_plp_base_t_secy_vport_handle_t vport_handle,
                                                          const void ** tmp_handle_p,
                                                          unsigned char * const next_sci_p,
                                                          unsigned int * const sci_index_p) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_diag_device_dump(bcm_plp_base_t_sec_phy_access_t *pa) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_device_config_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                                               bcm_plp_base_t_secy_device_params_t * const control_p) EPDM_WEAK;
bcm_plp_base_t_secy_status_t bcm_plp_longfin_base_t_secy_device_role_get(bcm_plp_base_t_sec_access_t *pa,
                                                bcm_plp_base_t_secy_role_t * const role_p) EPDM_WEAK;
/* 64-bit Register set & get */
extern int bcm_plp_longfin_reg64_value_set(bcm_plp_access_t phy_info, unsigned int devaddr, unsigned int regaddr, plp_uint64_t data) EPDM_WEAK;
extern int bcm_plp_longfin_reg64_value_get(bcm_plp_access_t phy_info, unsigned int devaddr, unsigned int regaddr, plp_uint64_t *data) EPDM_WEAK;

extern bcm_plp_base_t_warmboot_status_t bcm_plp_longfin_base_t_macsec_warmboot_register(bcm_plp_base_t_sec_phy_access_t *pa, bcm_plp_base_t_macsec_warmboot_callbacks_t *ops) EPDM_WEAK;

extern bcm_plp_base_t_warmboot_status_t bcm_plp_longfin_base_t_macsec_warmboot_shutdown(bcm_plp_base_t_sec_phy_access_t *pa, const unsigned int area_id) EPDM_WEAK;

extern bcm_plp_base_t_warmboot_status_t bcm_plp_longfin_base_t_macsec_warmboot_restore(bcm_plp_base_t_sec_phy_access_t *pa, const unsigned int area_id) EPDM_WEAK;

extern bcm_plp_base_t_warmboot_status_t bcm_plp_longfin_base_t_macsec_warmboot_maxsize_get(bcm_plp_base_t_sec_phy_access_t *pa,
                                                                            const bcm_plp_base_t_macsec_warmboot_device_type_t device_type,
                                                                            unsigned int * const maxbyte_count_p) EPDM_WEAK;

/* XLMAC APIs */
extern int bcm_plp_longfin_mac_loopback_set(bcm_plp_mac_access_t mac_info, bcm_plp_mac_lb_type_t lb_type, unsigned int enable) EPDM_WEAK;
extern int bcm_plp_longfin_mac_loopback_get(bcm_plp_mac_access_t mac_info, bcm_plp_mac_lb_type_t lb_type, unsigned int *enable) EPDM_WEAK;
extern int bcm_plp_longfin_mac_fault_option_set(bcm_plp_mac_access_t mac_info, bcm_plp_mac_fault_option_t fault_option) EPDM_WEAK;
extern int bcm_plp_longfin_mac_fault_option_get(bcm_plp_mac_access_t mac_info, bcm_plp_mac_fault_option_t *fault_option) EPDM_WEAK;
extern int bcm_plp_longfin_mac_flow_control_set(bcm_plp_mac_access_t mac_info, bcm_plp_mac_flow_control_t flow_option) EPDM_WEAK;
extern int bcm_plp_longfin_mac_flow_control_get(bcm_plp_mac_access_t mac_info, bcm_plp_mac_flow_control_t *flow_option) EPDM_WEAK;
extern int bcm_plp_longfin_mac_cleanup(bcm_plp_mac_access_t mac_info) EPDM_WEAK;
extern int bcm_plp_longfin_mac_max_packet_size_set(bcm_plp_mac_access_t mac_info, int pkt_size) EPDM_WEAK;
extern int bcm_plp_longfin_mac_max_packet_size_get(bcm_plp_mac_access_t mac_info, int *pkt_size) EPDM_WEAK;
extern int bcm_plp_longfin_mac_runt_threshold_set(bcm_plp_mac_access_t mac_info, int threshold) EPDM_WEAK;
extern int bcm_plp_longfin_mac_runt_threshold_get(bcm_plp_mac_access_t mac_info, int *threshold) EPDM_WEAK;
extern int bcm_plp_longfin_mac_pad_size_set(bcm_plp_mac_access_t mac_info, int pad_size) EPDM_WEAK;
extern int bcm_plp_longfin_mac_pad_size_get(bcm_plp_mac_access_t mac_info, int *pad_size) EPDM_WEAK;
extern int bcm_plp_longfin_tx_mac_sa_set(bcm_plp_mac_access_t mac_info, unsigned char mac_sa[6]) EPDM_WEAK;
extern int bcm_plp_longfin_tx_mac_sa_get(bcm_plp_mac_access_t mac_info, unsigned char mac_sa[6]) EPDM_WEAK;
extern int bcm_plp_longfin_rx_mac_sa_set(bcm_plp_mac_access_t mac_info, unsigned char mac_sa[6]) EPDM_WEAK;
extern int bcm_plp_longfin_rx_mac_sa_get(bcm_plp_mac_access_t mac_info, unsigned char mac_sa[6]) EPDM_WEAK;
extern int bcm_plp_longfin_mac_tx_avg_ipg_set(bcm_plp_mac_access_t mac_info, int avg_ipg) EPDM_WEAK;
extern int bcm_plp_longfin_mac_tx_avg_ipg_get(bcm_plp_mac_access_t mac_info, int *avg_ipg) EPDM_WEAK;
extern int bcm_plp_longfin_mac_tx_preamble_length_set(bcm_plp_mac_access_t mac_info, int preamble_length) EPDM_WEAK;
extern int bcm_plp_longfin_mac_tx_preamble_length_get(bcm_plp_mac_access_t mac_info, int *preamble_length) EPDM_WEAK;
extern int bcm_plp_longfin_mac_pause_control_set(bcm_plp_mac_access_t mac_info, bcm_plp_mac_pause_control_t pause_control) EPDM_WEAK;
extern int bcm_plp_longfin_mac_pause_control_get(bcm_plp_mac_access_t mac_info, bcm_plp_mac_pause_control_t *pause_control) EPDM_WEAK;
extern int bcm_plp_longfin_mac_configure_frame_drop_set(bcm_plp_mac_access_t mac_info, bcm_plp_mac_frame_select_t frame,unsigned int enable) EPDM_WEAK;
extern int bcm_plp_longfin_mac_configure_frame_drop_get(bcm_plp_mac_access_t mac_info, bcm_plp_mac_frame_select_t frame,unsigned int *enable) EPDM_WEAK;
extern int bcm_plp_longfin_mac_pfc_control_set(bcm_plp_mac_access_t mac_info, bcm_plp_mac_pfc_control_t pfc_ctrl) EPDM_WEAK;
extern int bcm_plp_longfin_mac_pfc_control_get(bcm_plp_mac_access_t mac_info, bcm_plp_mac_pfc_control_t *pfc_ctrl) EPDM_WEAK;
extern int bcm_plp_longfin_mac_diagnostic_dump(bcm_plp_mac_access_t mac_info) EPDM_WEAK;
extern int bcm_plp_longfin_port_enable_set(bcm_plp_mac_access_t mac_info, int tx_rx, int enable_disable) EPDM_WEAK;
extern int bcm_plp_longfin_port_enable_get(bcm_plp_mac_access_t mac_info, int tx_rx, int *enable_disable) EPDM_WEAK;
extern int bcm_plp_longfin_datapath_flush(bcm_plp_mac_access_t mac_info) EPDM_WEAK;
extern int bcm_plp_longfin_mac_reset_set(bcm_plp_mac_access_t mac_info, int  reset) EPDM_WEAK;
extern int bcm_plp_longfin_mac_reset_get(bcm_plp_mac_access_t mac_info, int *reset) EPDM_WEAK;


/* BAST_T MACSEC APIs */
__plp__base__t__sec__dispatch__t__  plp_longfin_sec_dispatch = {
    bcm_plp_longfin_base_t_secy_device_init,
    bcm_plp_longfin_base_t_secy_device_uninit,
    bcm_plp_longfin_base_t_secy_device_limits,
    bcm_plp_longfin_base_t_secy_vport_add,
    bcm_plp_longfin_base_t_secy_vport_handle_issame,
    bcm_plp_longfin_base_t_secy_vport_remove,
    bcm_plp_longfin_base_t_secy_sa_add,
    bcm_plp_longfin_base_t_secy_sa_update,
    bcm_plp_longfin_base_t_secy_sa_read,
    bcm_plp_longfin_base_t_secy_sa_handle_issame,
    bcm_plp_longfin_base_t_secy_sa_handle_sa_index_issame,
    bcm_plp_longfin_base_t_secy_sa_remove,
    bcm_plp_longfin_base_t_secy_sa_nextpn_update,
    bcm_plp_longfin_base_t_secy_sa_chain,
    bcm_plp_longfin_base_t_secy_sa_switch,
    bcm_plp_longfin_base_t_secy_rule_add,
    bcm_plp_longfin_base_t_secy_rule_update,
    bcm_plp_longfin_base_t_secy_rule_enable,
    bcm_plp_longfin_base_t_secy_rule_enable_disable,
    bcm_plp_longfin_base_t_secy_rule_handle_issame,
    bcm_plp_longfin_base_t_secy_rule_disable,
    bcm_plp_longfin_base_t_secy_rule_remove,
    bcm_plp_longfin_base_t_secy_sa_index_get,
    bcm_plp_longfin_base_t_secy_rule_index_get,
    bcm_plp_longfin_base_t_secy_vport_index_get,
    bcm_plp_longfin_base_t_secy_sa_handle_get,
    bcm_plp_longfin_base_t_secy_rule_handle_get,
    bcm_plp_longfin_base_t_secy_vport_handle_get,
    bcm_plp_longfin_base_t_secy_device_update,
    bcm_plp_longfin_base_t_secy_crypt_auth_bypass_len_update,
    bcm_plp_longfin_base_t_secy_rules_mtu_check_update,
    bcm_plp_longfin_base_t_secy_tcam_statistics_get,
    bcm_plp_longfin_base_t_secy_rxcam_statistics_get,
    bcm_plp_longfin_base_t_secy_secy_statistics_i_get,
    bcm_plp_longfin_base_t_secy_secy_statistics_e_get,
    bcm_plp_longfin_base_t_secy_sa_statistics_i_get,
    bcm_plp_longfin_base_t_secy_sa_statistics_e_get,
    bcm_plp_longfin_base_t_secy_global_statistics_get,
    bcm_plp_longfin_base_t_secy_ifc_statistics_e_get,
    bcm_plp_longfin_base_t_secy_ifc_statistics_i_get,
    bcm_plp_longfin_base_t_secy_device_count_summary_pifc_checkandclear,
    bcm_plp_longfin_base_t_secy_device_count_summary_prxcam_checkandclear,
    bcm_plp_longfin_base_t_secy_device_count_summary_psa_checkandclear,
    bcm_plp_longfin_base_t_secy_device_count_summary_psecy_checkandclear,
    bcm_plp_longfin_base_t_secy_device_count_summary_ptcam_checkandclear,
    bcm_plp_longfin_base_t_secy_device_count_summary_sa_checkandclear,
    bcm_plp_longfin_base_t_secy_device_count_summary_secy_checkandclear,
    bcm_plp_longfin_base_t_secy_device_count_summary_tcam_global_checkandclear,
    bcm_plp_longfin_base_t_secy_device_count_summary_ifc_checkandclear,
    bcm_plp_longfin_base_t_secy_sa_expired_summary_checkandclear,
    bcm_plp_longfin_base_t_secy_sa_pnthr_summary_checkandclear,
    bcm_plp_longfin_base_t_secy_intr_enable_set,
    bcm_plp_longfin_base_t_secy_intr_enable_get,
    bcm_plp_longfin_base_t_secy_intr_status_get,
    bcm_plp_longfin_base_t_secy_intr_status_clear,
    bcm_plp_longfin_base_t_secy_event_status_get,
    bcm_plp_longfin_base_t_secy_intr_set,
    bcm_plp_longfin_base_t_secy_intr_get,
    bcm_plp_longfin_base_t_secy_build_transform_record,
    bcm_plp_longfin_base_t_secy_sa_active_e_get,
    bcm_plp_longfin_base_t_secy_sa_active_i_get,
    bcm_plp_longfin_base_t_imacsec_version_get,
    bcm_plp_longfin_base_t_secy_sa_window_size_update,
    bcm_plp_longfin_base_t_secy_bypass_set,
    bcm_plp_longfin_base_t_secy_bypass_get,
    bcm_plp_longfin_base_t_secy_vport_params_get,
    bcm_plp_longfin_base_t_secy_sa_params_get,
    bcm_plp_longfin_base_t_secy_sa_next_get,
    bcm_plp_longfin_base_t_secy_sa_window_size_get,
    bcm_plp_longfin_base_t_secy_sa_next_pn_get,
    bcm_plp_longfin_base_t_secy_vport_next_get,
    bcm_plp_longfin_base_t_secy_rule_get,
    bcm_plp_longfin_base_t_secy_rule_next_get,
    bcm_plp_longfin_base_t_secy_rule_vport_next_get,
    bcm_plp_longfin_base_t_secy_sa_chained_get,
    bcm_plp_longfin_base_t_secy_rules_mtu_check_get,
    bcm_plp_longfin_base_t_secy_diag_vport_dump,
    bcm_plp_longfin_base_t_secy_diag_sa_dump,
    bcm_plp_longfin_base_t_secy_diag_rule_dump,
    bcm_plp_longfin_base_t_secy_sa_vport_handle_get,
    bcm_plp_longfin_base_t_secy_sci_next_get,
    bcm_plp_longfin_base_t_secy_diag_device_dump,
    bcm_plp_longfin_base_t_secy_device_config_get,
    bcm_plp_longfin_base_t_secy_device_role_get,
    __PLP_NOT_USED, /* reserved16 */
    __PLP_NOT_USED, /* reserved17 */
    __PLP_NOT_USED, /* reserved18 */
    __PLP_NOT_USED, /* reserved19 */
    __PLP_NOT_USED, /* reserved20 */
    __PLP_NOT_USED, /* bcm_plp_longfin_base_t_mac_reset */
    __PLP_NOT_USED, /* bcm_plp_longfin_base_t_mac_pause_set */
    __PLP_NOT_USED, /* bcm_plp_longfin_base_t_mac_datapath_flush */
    __PLP_NOT_USED, /* bcm_plp_longfin_base_t_mac_port_enable */
    bcm_plp_longfin_mac_loopback_set,
    bcm_plp_longfin_mac_loopback_get,
    bcm_plp_longfin_mac_fault_option_set,
    bcm_plp_longfin_mac_fault_option_get,
    bcm_plp_longfin_mac_flow_control_set,
    bcm_plp_longfin_mac_flow_control_get,
    __PLP_NOT_USED, /* bcm_plp_longfin_mac_store_and_forward_mode_set */
    __PLP_NOT_USED, /* bcm_plp_longfin_mac_store_and_forward_mode_get */
    bcm_plp_longfin_mac_cleanup,
    bcm_plp_longfin_mac_max_packet_size_set,
    bcm_plp_longfin_mac_max_packet_size_get,
    bcm_plp_longfin_mac_runt_threshold_set,
    bcm_plp_longfin_mac_runt_threshold_get,
    bcm_plp_longfin_mac_pad_size_set,
    bcm_plp_longfin_mac_pad_size_get,
    bcm_plp_longfin_tx_mac_sa_set,
    bcm_plp_longfin_tx_mac_sa_get,
    bcm_plp_longfin_rx_mac_sa_set,
    bcm_plp_longfin_rx_mac_sa_get,
    bcm_plp_longfin_mac_tx_avg_ipg_set,
    bcm_plp_longfin_mac_tx_avg_ipg_get,
    bcm_plp_longfin_mac_tx_preamble_length_set,
    bcm_plp_longfin_mac_tx_preamble_length_get,
    bcm_plp_longfin_mac_pause_control_set,
    bcm_plp_longfin_mac_pause_control_get,
    bcm_plp_longfin_mac_pfc_control_set,
    bcm_plp_longfin_mac_pfc_control_get,
    bcm_plp_longfin_reg64_value_set,
    bcm_plp_longfin_reg64_value_get,
    bcm_plp_longfin_mac_diagnostic_dump,
    bcm_plp_longfin_datapath_flush,
    bcm_plp_longfin_port_enable_set,
    bcm_plp_longfin_port_enable_get,
    bcm_plp_longfin_mac_configure_frame_drop_set,
    bcm_plp_longfin_mac_configure_frame_drop_get,
    bcm_plp_longfin_mac_reset_set,
    bcm_plp_longfin_mac_reset_get,
    bcm_plp_longfin_base_t_macsec_warmboot_register,
    bcm_plp_longfin_base_t_macsec_warmboot_shutdown,
    bcm_plp_longfin_base_t_macsec_warmboot_restore,
    bcm_plp_longfin_base_t_macsec_warmboot_maxsize_get

};

#endif /* PLP_MACSEC_SUPPORT */
#endif /* PLP_LONGFIN_SUPPORT */
