/*------------------------------------------------------------------------------
 * $Id: tscpmod_speed_ctrl_defines.h $
 *
 * $Copyright: (c) 2017 Broadcom Corporation All Rights Reserved.$
 *  Broadcom Corporation
 *  Proprietary and Confidential information
 *  All rights reserved
 *  This source file is the property of Broadcom Corporation, and
 *  may not be copied or distributed in any isomorphic form without the
 *  prior written consent of Broadcom Corporation.
 *------------------------------------------------------------------------------
 *  Description: Defines for the Speed Table, AM Table, and UM Table access APIs
 *----------------------------------------------------------------------------*/

#ifndef _TSCPMOD_SPEED_CTRL_DEFINES_H_
#define _TSCPMOD_SPEED_CTRL_DEFINES_H_

/*-------- Defines for table dimensions --------*/
#define SPD_CTRL_SPD_ID_TBL_SIZE 64
#define SPD_CTRL_AM_TBL_SIZE 64
#define SPD_CTRL_UM_TBL_SIZE 64
#define SPD_CTRL_SPD_ID_TBL_ENTRY_WIDTH 127 
#define SPD_CTRL_AM_TBL_ENTRY_WIDTH 78
#define SPD_CTRL_UM_TBL_ENTRY_WIDTH 48

/*-------- Defines for fields of Speed ID Table --------*/
#define TSCPMOD_SPD_ID_TBL_AM_TABLE_INDEX_OFFSET 0
#define TSCPMOD_SPD_ID_TBL_AM_TABLE_INDEX_WIDTH 6
#define TSCPMOD_SPD_ID_TBL_AM_TABLE_INDEX_MASK ((1 << TSCPMOD_SPD_ID_TBL_AM_TABLE_INDEX_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_FEC_ARCH_OFFSET 6
#define TSCPMOD_SPD_ID_TBL_FEC_ARCH_WIDTH 3
#define TSCPMOD_SPD_ID_TBL_FEC_ARCH_MASK ((1 << TSCPMOD_SPD_ID_TBL_FEC_ARCH_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_TC_XOR_CONTROL_OFFSET 9
#define TSCPMOD_SPD_ID_TBL_TC_XOR_CONTROL_WIDTH 1
#define TSCPMOD_SPD_ID_TBL_TC_XOR_CONTROL_MASK ((1 << TSCPMOD_SPD_ID_TBL_TC_XOR_CONTROL_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_RS_FEC_SYNC_HEADER_MODE_OFFSET 10 
#define TSCPMOD_SPD_ID_TBL_RS_FEC_SYNC_HEADER_MODE_WIDTH 2
#define TSCPMOD_SPD_ID_TBL_RS_FEC_SYNC_HEADER_MODE_MASK ((1 << TSCPMOD_SPD_ID_TBL_RS_FEC_SYNC_HEADER_MODE_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_RS_FEC_CWM_NIBBLE_MATCH_COUNT_OFFSET 12 
#define TSCPMOD_SPD_ID_TBL_RS_FEC_CWM_NIBBLE_MATCH_COUNT_WIDTH 4
#define TSCPMOD_SPD_ID_TBL_RS_FEC_CWM_NIBBLE_MATCH_COUNT_MASK ((1 << TSCPMOD_SPD_ID_TBL_RS_FEC_CWM_NIBBLE_MATCH_COUNT_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_WINDOW_MODE_OFFSET 16
#define TSCPMOD_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_WINDOW_MODE_WIDTH 2
#define TSCPMOD_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_WINDOW_MODE_MASK ((1 << TSCPMOD_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_WINDOW_MODE_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_COUNT_THRESHOLD_OFFSET 18 
#define TSCPMOD_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_COUNT_THRESHOLD_WIDTH 17
#define TSCPMOD_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_COUNT_THRESHOLD_MASK ((1 << TSCPMOD_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_COUNT_THRESHOLD_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_2XN_OFFSET 35
#define TSCPMOD_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_2XN_WIDTH 8
#define TSCPMOD_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_2XN_MASK ((1 << TSCPMOD_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_2XN_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_1XN_OFFSET 43
#define TSCPMOD_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_1XN_WIDTH 8
#define TSCPMOD_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_1XN_MASK ((1 << TSCPMOD_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_1XN_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_BIT_MUX_MODE_OFFSET 51
#define TSCPMOD_SPD_ID_TBL_BIT_MUX_MODE_WIDTH 2
#define TSCPMOD_SPD_ID_TBL_BIT_MUX_MODE_MASK ((1 << TSCPMOD_SPD_ID_TBL_BIT_MUX_MODE_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_NUM_LANES_OFFSET 53
#define TSCPMOD_SPD_ID_TBL_NUM_LANES_WIDTH 3
#define TSCPMOD_SPD_ID_TBL_NUM_LANES_MASK ((1 << TSCPMOD_SPD_ID_TBL_NUM_LANES_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_DESKEW_WINDOW_WITHOUT_RS_FEC_OFFSET 56
#define TSCPMOD_SPD_ID_TBL_DESKEW_WINDOW_WITHOUT_RS_FEC_WIDTH 8
#define TSCPMOD_SPD_ID_TBL_DESKEW_WINDOW_WITHOUT_RS_FEC_MASK ((1 << TSCPMOD_SPD_ID_TBL_DESKEW_WINDOW_WITHOUT_RS_FEC_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_DESKEW_WINDOW_WITH_RS_FEC_OFFSET 64
#define TSCPMOD_SPD_ID_TBL_DESKEW_WINDOW_WITH_RS_FEC_WIDTH 8
#define TSCPMOD_SPD_ID_TBL_DESKEW_WINDOW_WITH_RS_FEC_MASK ((1 << TSCPMOD_SPD_ID_TBL_DESKEW_WINDOW_WITH_RS_FEC_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_BER_FSM_DISABLE_WITH_RS_FEC_OFFSET 72
#define TSCPMOD_SPD_ID_TBL_BER_FSM_DISABLE_WITH_RS_FEC_WIDTH 1
#define TSCPMOD_SPD_ID_TBL_BER_FSM_DISABLE_WITH_RS_FEC_MASK ((1 << TSCPMOD_SPD_ID_TBL_BER_FSM_DISABLE_WITH_RS_FEC_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_BER_FSM_DISABLE_WITHOUT_RS_FEC_OFFSET 73
#define TSCPMOD_SPD_ID_TBL_BER_FSM_DISABLE_WITHOUT_RS_FEC_WIDTH 1
#define TSCPMOD_SPD_ID_TBL_BER_FSM_DISABLE_WITHOUT_RS_FEC_MASK ((1 << TSCPMOD_SPD_ID_TBL_BER_FSM_DISABLE_WITHOUT_RS_FEC_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_BER_WINDOW_MODE_OFFSET 74
#define TSCPMOD_SPD_ID_TBL_BER_WINDOW_MODE_WIDTH 2
#define TSCPMOD_SPD_ID_TBL_BER_WINDOW_MODE_MASK ((1 << TSCPMOD_SPD_ID_TBL_BER_WINDOW_MODE_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_BER_TRIGGER_COUNT_OFFSET 76
#define TSCPMOD_SPD_ID_TBL_BER_TRIGGER_COUNT_WIDTH 1
#define TSCPMOD_SPD_ID_TBL_BER_TRIGGER_COUNT_MASK ((1 << TSCPMOD_SPD_ID_TBL_BER_TRIGGER_COUNT_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_CREDIT_QUOTIENT_OFFSET 77
#define TSCPMOD_SPD_ID_TBL_CREDIT_QUOTIENT_WIDTH 7
#define TSCPMOD_SPD_ID_TBL_CREDIT_QUOTIENT_MASK ((1 << TSCPMOD_SPD_ID_TBL_CREDIT_QUOTIENT_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_USE_CL49_BLOCK_SYNC_OFFSET 84 
#define TSCPMOD_SPD_ID_TBL_USE_CL49_BLOCK_SYNC_WIDTH 1
#define TSCPMOD_SPD_ID_TBL_USE_CL49_BLOCK_SYNC_MASK ((1 << TSCPMOD_SPD_ID_TBL_USE_CL49_BLOCK_SYNC_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_SCR_MODE_OFFSET 85 
#define TSCPMOD_SPD_ID_TBL_SCR_MODE_WIDTH 2
#define TSCPMOD_SPD_ID_TBL_SCR_MODE_MASK ((1 << TSCPMOD_SPD_ID_TBL_SCR_MODE_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_CODEC_MODE_OFFSET 87 
#define TSCPMOD_SPD_ID_TBL_CODEC_MODE_WIDTH 2
#define TSCPMOD_SPD_ID_TBL_CODEC_MODE_MASK ((1 << TSCPMOD_SPD_ID_TBL_CODEC_MODE_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_TRAINING_EN_OFFSET 89 
#define TSCPMOD_SPD_ID_TBL_TRAINING_EN_WIDTH 1
#define TSCPMOD_SPD_ID_TBL_TRAINING_EN_MASK ((1 << TSCPMOD_SPD_ID_TBL_TRAINING_EN_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_SCRAMBLER_DIS_OFFSET 90 
#define TSCPMOD_SPD_ID_TBL_SCRAMBLER_DIS_WIDTH 1
#define TSCPMOD_SPD_ID_TBL_SCRAMBLER_DIS_MASK ((1 << TSCPMOD_SPD_ID_TBL_SCRAMBLER_DIS_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_AN_TIMER_SELECT_OFFSET 91 
#define TSCPMOD_SPD_ID_TBL_AN_TIMER_SELECT_WIDTH 1
#define TSCPMOD_SPD_ID_TBL_AN_TIMER_SELECT_MASK ((1 << TSCPMOD_SPD_ID_TBL_AN_TIMER_SELECT_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_T_PMA_WATERMARK_OFFSET 92
#define TSCPMOD_SPD_ID_TBL_T_PMA_WATERMARK_WIDTH 4
#define TSCPMOD_SPD_ID_TBL_T_PMA_WATERMARK_MASK ((1 << TSCPMOD_SPD_ID_TBL_T_PMA_WATERMARK_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_LOOP_BLOCK_COUNT_FOR_TS_OFFSET 94 
#define TSCPMOD_SPD_ID_TBL_LOOP_BLOCK_COUNT_FOR_TS_WIDTH 8
#define TSCPMOD_SPD_ID_TBL_LOOP_BLOCK_COUNT_FOR_TS_MASK ((1 << TSCPMOD_SPD_ID_TBL_LOOP_BLOCK_COUNT_FOR_TS_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_LOOP_BIT_COUNT_FOR_TS_OFFSET 102
#define TSCPMOD_SPD_ID_TBL_LOOP_BIT_COUNT_FOR_TS_WIDTH 14 
#define TSCPMOD_SPD_ID_TBL_LOOP_BIT_COUNT_FOR_TS_MASK ((1 << TSCPMOD_SPD_ID_TBL_LOOP_BIT_COUNT_FOR_TS_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_AM_LOCK_FSM_MODE_OFFSET 116
#define TSCPMOD_SPD_ID_TBL_AM_LOCK_FSM_MODE_WIDTH 1
#define TSCPMOD_SPD_ID_TBL_AM_LOCK_FSM_MODE_MASK ((1 << TSCPMOD_SPD_ID_TBL_AM_LOCK_FSM_MODE_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_T_PMA_START_MODE_OFFSET 117
#define TSCPMOD_SPD_ID_TBL_T_PMA_START_MODE_WIDTH 1
#define TSCPMOD_SPD_ID_TBL_T_PMA_START_MODE_MASK ((1 << TSCPMOD_SPD_ID_TBL_T_PMA_START_MODE_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_HI_SER_ENABLE_OFFSET 118 
#define TSCPMOD_SPD_ID_TBL_HI_SER_ENABLE_WIDTH 1
#define TSCPMOD_SPD_ID_TBL_HI_SER_ENABLE_MASK ((1 << TSCPMOD_SPD_ID_TBL_HI_SER_ENABLE_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_T_PMA_INPUT_WIDTH_MODE_OFFSET 119 
#define TSCPMOD_SPD_ID_TBL_T_PMA_INPUT_WIDTH_MODE_WIDTH 3
#define TSCPMOD_SPD_ID_TBL_T_PMA_INPUT_WIDTH_MODE_MASK ((1 << TSCPMOD_SPD_ID_TBL_T_PMA_INPUT_WIDTH_MODE_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_T_PMA_OUTPUT_WIDTH_MODE_OFFSET 122 
#define TSCPMOD_SPD_ID_TBL_T_PMA_OUTPUT_WIDTH_MODE_WIDTH 2
#define TSCPMOD_SPD_ID_TBL_T_PMA_OUTPUT_WIDTH_MODE_MASK ((1 << TSCPMOD_SPD_ID_TBL_T_PMA_OUTPUT_WIDTH_MODE_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_HI_SER_2_OFFSET 124 
#define TSCPMOD_SPD_ID_TBL_HI_SER_2_WIDTH 1
#define TSCPMOD_SPD_ID_TBL_HI_SER_2_MASK ((1 << TSCPMOD_SPD_ID_TBL_HI_SER_2_WIDTH) - 1)
#define TSCPMOD_SPD_ID_TBL_T_PMA_TDM_OFFSET 125 
#define TSCPMOD_SPD_ID_TBL_T_PMA_TDM_WIDTH 2
#define TSCPMOD_SPD_ID_TBL_T_PMA_TDM_MASK ((1 << TSCPMOD_SPD_ID_TBL_T_PMA_TDM_WIDTH) - 1)

/*-------- Defines for fields of AM Table --------*/
#define TSCPMOD_AM_TBL_UM_MODIFIER_MPP0_OFFSET 77
#define TSCPMOD_AM_TBL_UM_MODIFIER_MPP0_WIDTH 1
#define TSCPMOD_AM_TBL_UM_MODIFIER_MPP0_MASK ((1 << TSCPMOD_AM_TBL_UM_MODIFIER_MPP0_WIDTH) - 1)
#define TSCPMOD_AM_TBL_UM_MODIFIER_MPP1_OFFSET 76
#define TSCPMOD_AM_TBL_UM_MODIFIER_MPP1_WIDTH 1
#define TSCPMOD_AM_TBL_UM_MODIFIER_MPP1_MASK ((1 << TSCPMOD_AM_TBL_UM_MODIFIER_MPP1_WIDTH) - 1)
#define TSCPMOD_AM_TBL_AM_DROP_CONTROL_OFFSET 75
#define TSCPMOD_AM_TBL_AM_DROP_CONTROL_WIDTH 1
#define TSCPMOD_AM_TBL_AM_DROP_CONTROL_MASK ((1 << TSCPMOD_AM_TBL_AM_DROP_CONTROL_WIDTH) - 1)
#define TSCPMOD_AM_TBL_CM_AM_SEL_OFFSET 74
#define TSCPMOD_AM_TBL_CM_AM_SEL_WIDTH 1
#define TSCPMOD_AM_TBL_CM_AM_SEL_MASK ((1 << TSCPMOD_AM_TBL_CM_AM_SEL_WIDTH) - 1)
#define TSCPMOD_AM_TBL_AM_SPACING_CREDITS_OFFSET 66
#define TSCPMOD_AM_TBL_AM_SPACING_CREDITS_WIDTH 8
#define TSCPMOD_AM_TBL_AM_SPACING_CREDITS_MASK ((1 << TSCPMOD_AM_TBL_AM_SPACING_CREDITS_WIDTH) - 1)
#define TSCPMOD_AM_TBL_AM_SPACING_NO_RS_OFFSET 58
#define TSCPMOD_AM_TBL_AM_SPACING_NO_RS_WIDTH 8
#define TSCPMOD_AM_TBL_AM_SPACING_NO_RS_MASK ((1 << TSCPMOD_AM_TBL_AM_SPACING_NO_RS_WIDTH) - 1)
#define TSCPMOD_AM_TBL_AM_SPACING_RS_OFFSET 49
#define TSCPMOD_AM_TBL_AM_SPACING_RS_WIDTH 9
#define TSCPMOD_AM_TBL_AM_SPACING_RS_MASK ((1 << TSCPMOD_AM_TBL_AM_SPACING_RS_WIDTH) - 1)
#define TSCPMOD_AM_TBL_USE_FIXED_OFFSET 45
#define TSCPMOD_AM_TBL_USE_FIXED_WIDTH 4
#define TSCPMOD_AM_TBL_USE_FIXED_MASK ((1 << TSCPMOD_AM_TBL_USE_FIXED_WIDTH) - 1)
#define TSCPMOD_AM_TBL_CM_OFFSET 21
#define TSCPMOD_AM_TBL_CM_WIDTH 24
#define TSCPMOD_AM_TBL_CM_MASK ((1 << TSCPMOD_AM_TBL_CM_WIDTH) - 1)
#define TSCPMOD_AM_TBL_UM_TABLE_INDEX_OFFSET 15
#define TSCPMOD_AM_TBL_UM_TABLE_INDEX_WIDTH 6
#define TSCPMOD_AM_TBL_UM_TABLE_INDEX_MASK ((1 << TSCPMOD_AM_TBL_UM_TABLE_INDEX_WIDTH) - 1)
#define TSCPMOD_AM_TBL_UM_TABLE_COUNT_OFFSET 9
#define TSCPMOD_AM_TBL_UM_TABLE_COUNT_WIDTH 6
#define TSCPMOD_AM_TBL_UM_TABLE_COUNT_MASK ((1 << TSCPMOD_AM_TBL_UM_TABLE_COUNT_WIDTH) - 1)
#define TSCPMOD_AM_TBL_PAD_MODE_OFFSET 7
#define TSCPMOD_AM_TBL_PAD_MODE_WIDTH 2
#define TSCPMOD_AM_TBL_PAD_MODE_MASK ((1 << TSCPMOD_AM_TBL_PAD_MODE_WIDTH) - 1)
#define TSCPMOD_AM_TBL_AM_SIZE_OFFSET 3
#define TSCPMOD_AM_TBL_AM_SIZE_WIDTH 4
#define TSCPMOD_AM_TBL_AM_SIZE_MASK ((1 << TSCPMOD_AM_TBL_AM_SIZE_WIDTH) - 1)
#define TSCPMOD_AM_TBL_AM_COMPRESSION_MODE_OFFSET 0
#define TSCPMOD_AM_TBL_AM_COMPRESSION_MODE_WIDTH 3
#define TSCPMOD_AM_TBL_AM_COMPRESSION_MODE_MASK ((1 << TSCPMOD_AM_TBL_AM_COMPRESSION_MODE_WIDTH) - 1)

/*-------- Defines for fields of UM Table --------*/
#define TSCPMOD_UM_TBL_UM_OFFSET 24
#define TSCPMOD_UM_TBL_UM_WIDTH 24
#define TSCPMOD_UM_TBL_UM_MASK ((1 << TSCPMOD_UM_TBL_UM_WIDTH) - 1)
#define TSCPMOD_UM_TBL_CM_PAD_OFFSET 16
#define TSCPMOD_UM_TBL_CM_PAD_WIDTH 8
#define TSCPMOD_UM_TBL_CM_PAD_MASK ((1 << TSCPMOD_UM_TBL_CM_PAD_WIDTH) - 1)
#define TSCPMOD_UM_TBL_UM_PAD_OFFSET 8
#define TSCPMOD_UM_TBL_UM_PAD_WIDTH 8
#define TSCPMOD_UM_TBL_UM_PAD_MASK ((1 << TSCPMOD_UM_TBL_UM_PAD_WIDTH) - 1)
#define TSCPMOD_UM_TBL_CM_CONTROL_OFFSET 0
#define TSCPMOD_UM_TBL_CM_CONTROL_WIDTH 8
#define TSCPMOD_UM_TBL_CM_CONTROL_MASK ((1 << TSCPMOD_UM_TBL_CM_CONTROL_WIDTH) - 1)


#endif  /* _TBHMOD_SPEED_CTRL_DEFINES_H_ */

