FROM docker-config-engine-bookworm-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

ARG docker_container_name
ARG image_version
RUN [ -f /etc/rsyslog.conf ] && sed -ri "s/%syslogtag%/$docker_container_name#%syslogtag%/;" /etc/rsyslog.conf

# Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

# Pass the image_version to container
ENV IMAGE_VERSION=$image_version

# Update apt's cache of available packages
RUN apt-get update

COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]
COPY ["readiness_probe_hook", "/usr/bin"]
COPY ["start.sh", "/usr/bin"]

RUN chmod +x /usr/bin/readiness_probe_hook
RUN chmod +x /usr/bin/start.sh

ENTRYPOINT ["/usr/local/bin/supervisord"]
