# name          lanes             alias         index  speed
Ethernet0       1                 etp1          1      10000
Ethernet1       2                 etp2          2      10000
Ethernet2       3                 etp3          3      10000
Ethernet3       4                 etp4          4      10000
Ethernet4       5                 etp5          5      10000
Ethernet5       6                 etp6          6      10000
Ethernet6       7                 etp7          7      10000
Ethernet7       8                 etp8          8      10000
Ethernet8       9                 etp9          9      10000
Ethernet9       10                etp10         10     10000
Ethernet10      11                etp11         11     10000
Ethernet11      12                etp12         12     10000
Ethernet12      13                etp13         13     10000
Ethernet13      14                etp14         14     10000
Ethernet14      15                etp15         15     10000
Ethernet15      16                etp16         16     10000
Ethernet16      17                etp17         17     10000
Ethernet17      18                etp18         18     10000
Ethernet18      19                etp19         19     10000
Ethernet19      20                etp20         20     10000
Ethernet20      21                etp21         21     10000
Ethernet21      22                etp22         22     10000
Ethernet22      23                etp23         23     10000
Ethernet23      24                etp24         24     10000
Ethernet24      57                etp25         25     10000
Ethernet25      58                etp26         26     10000
Ethernet26      59                etp27         27     10000
Ethernet27      60                etp28         28     10000
Ethernet28      61                etp29         29     10000
Ethernet29      62                etp30         30     10000
Ethernet30      63                etp31         31     10000
Ethernet31      64                etp32         32     10000
Ethernet32      65                etp33         33     10000
Ethernet33      66                etp34         34     10000
Ethernet34      67                etp35         35     10000
Ethernet35      68                etp36         36     10000
Ethernet36      69                etp37         37     10000
Ethernet37      70                etp38         38     10000
Ethernet38      71                etp39         39     10000
Ethernet39      72                etp40         40     10000
Ethernet40      73                etp41         41     10000
Ethernet41      74                etp42         42     10000
Ethernet42      75                etp43         43     10000
Ethernet43      76                etp44         44     10000
Ethernet44      77                etp45         45     10000
Ethernet45      78                etp46         46     10000
Ethernet46      79                etp47         47     10000
Ethernet47      80                etp48         48     10000
Ethernet48      25,26,27,28       etp49         49     40000
Ethernet52      29,30,31,32       etp50         50     40000
Ethernet56      33,34,35,36       etp51         51     40000
Ethernet60      37,38,39,40       etp52         52     40000
Ethernet64      41,42,43,44       etp53         53     40000
Ethernet68      45,46,47,48       etp54         54     40000
Ethernet72      49,50,51,52       etp55         55     40000
Ethernet76      53,54,55,56       etp56         56     40000
