# Alliedtelesis Platform

ALLIEDTELESIS_X980_32CQ_PLATFORM_MODULE_VERSION = 1.0
export ALLIEDTELESIS_X980_32CQ_PLATFORM_MODULE_VERSION

ifeq ($(CONFIGURED_ARCH),amd64)
ALLIEDTELESIS_X980_32CQ_PLATFORM = sonic-platform-alliedtelesis-x980-32cq_$(ALLIEDTELESIS_X980_32CQ_PLATFORM_MODULE_VERSION)_$(CONFIGURED_ARCH).deb
$(ALLIEDTELESIS_X980_32CQ_PLATFORM)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-alliedtelesis
$(ALLIEDTELESIS_X980_32CQ_PLATFORM)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON) $(PDDF_PLATFORM_MODULE_SYM)
$(ALLIEDTELESIS_X980_32CQ_PLATFORM)_PLATFORM = x86_64-alliedtelesis_x980_32cq-r0
SONIC_DPKG_DEBS += $(ALLIEDTELESIS_X980_32CQ_PLATFORM)

$(eval $(call add_extra_package,$(ALLIEDTELESIS_X980_32CQ_PLATFORM)))
endif
