s3ip_sysfs-objs := switch.o cpld_sysfs.o \
curr_sensor_sysfs.o \
fan_sysfs.o \
fpga_sysfs.o \
psu_sysfs.o \
slot_sysfs.o \
sysled_sysfs.o \
temp_sensor_sysfs.o \
transceiver_sysfs.o \
vol_sensor_sysfs.o \
watchdog_sysfs.o \
system_sysfs.o \
eeprom_sysfs.o \
power_sensor_sysfs.o \
cabletray_sysfs.o \
misc_fw_sysfs.o \

obj-m := s3ip_sysfs.o
