/*
 *         
 * $Id: phymod.xml,v 1.1.2.5 2013/09/12 10:43:06 nirf Exp $
 * 
 * $Copyright: 
 * All Rights Reserved.$
 *         
 *     
 * DO NOT EDIT THIS FILE!
 *
 */

#ifndef _PEREGRINE5_PC_H__H_
#define _PEREGRINE5_PC_H__H_

#include <phymod/phymod_definitions.h>
/*Initialize phymod module*/
int plp_aperta2_peregrine5_pc_core_identify(const plp_aperta2_phymod_core_access_t* core, uint32_t core_id, uint32_t* is_identified);

/*Retrive core information*/
int plp_aperta2_peregrine5_pc_core_info_get(const plp_aperta2_phymod_core_access_t* core, plp_aperta2_phymod_core_info_t* info);

/*Set\get lane mapping*/
int plp_aperta2_peregrine5_pc_core_lane_map_set(const plp_aperta2_phymod_core_access_t* core, const plp_aperta2_phymod_lane_map_t* lane_map);
int plp_aperta2_peregrine5_pc_core_lane_map_get(const plp_aperta2_phymod_core_access_t* core, plp_aperta2_phymod_lane_map_t* lane_map);

/*Reset Core*/
int plp_aperta2_peregrine5_pc_core_reset_set(const plp_aperta2_phymod_core_access_t* core, plp_aperta2_phymod_reset_mode_t reset_mode, plp_aperta2_phymod_reset_direction_t direction);
int plp_aperta2_peregrine5_pc_core_reset_get(const plp_aperta2_phymod_core_access_t* core, plp_aperta2_phymod_reset_mode_t reset_mode, plp_aperta2_phymod_reset_direction_t* direction);

/*Set\get firmware operation mode*/
int plp_aperta2_peregrine5_pc_phy_firmware_lane_config_set(const plp_aperta2_phymod_phy_access_t* phy, phymod_firmware_lane_config_t fw_lane_config);
int plp_aperta2_peregrine5_pc_phy_firmware_lane_config_get(const plp_aperta2_phymod_phy_access_t* phy, phymod_firmware_lane_config_t* fw_lane_config);

/* re-tune rx path*/
int plp_aperta2_peregrine5_pc_phy_rx_restart(const plp_aperta2_phymod_phy_access_t* phy);

/*Set phy polarity*/
int plp_aperta2_peregrine5_pc_phy_polarity_set(const plp_aperta2_phymod_phy_access_t* phy, const plp_aperta2_phymod_polarity_t* polarity);
int plp_aperta2_peregrine5_pc_phy_polarity_get(const plp_aperta2_phymod_phy_access_t* phy, plp_aperta2_phymod_polarity_t* polarity);

/*Set\Get TX Parameters*/
int plp_aperta2_peregrine5_pc_phy_pam4_tx_set(const plp_aperta2_phymod_phy_access_t* phy, const phymod_pam4_tx_t* tx);
int plp_aperta2_peregrine5_pc_phy_pam4_tx_get(const plp_aperta2_phymod_phy_access_t* phy, phymod_pam4_tx_t* tx);

/*Set\Get TX override Parameters*/
int plp_aperta2_peregrine5_pc_phy_tx_override_set(const plp_aperta2_phymod_phy_access_t* phy, const plp_aperta2_phymod_tx_override_t* tx_override);
int plp_aperta2_peregrine5_pc_phy_tx_override_get(const plp_aperta2_phymod_phy_access_t* phy, plp_aperta2_phymod_tx_override_t* tx_override);

/*Set\Get RX Parameters*/
int plp_aperta2_peregrine5_pc_phy_rx_set(const plp_aperta2_phymod_phy_access_t* phy, const plp_aperta2_phymod_rx_t* rx);
int plp_aperta2_peregrine5_pc_phy_rx_get(const plp_aperta2_phymod_phy_access_t* phy, plp_aperta2_phymod_rx_t* rx);

/*PHY Rx adaptation resume*/
int plp_aperta2_peregrine5_pc_phy_rx_adaptation_resume(const plp_aperta2_phymod_phy_access_t* phy);

/*Control phy power*/
int plp_aperta2_peregrine5_pc_phy_power_set(const plp_aperta2_phymod_phy_access_t* phy, const plp_aperta2_phymod_phy_power_t* power);
int plp_aperta2_peregrine5_pc_phy_power_get(const plp_aperta2_phymod_phy_access_t* phy, plp_aperta2_phymod_phy_power_t* power);

/*TX transmission control*/
int plp_aperta2_peregrine5_pc_phy_tx_lane_control_set(const plp_aperta2_phymod_phy_access_t* phy, plp_aperta2_phymod_phy_tx_lane_control_t tx_control);
int plp_aperta2_peregrine5_pc_phy_tx_lane_control_get(const plp_aperta2_phymod_phy_access_t* phy, plp_aperta2_phymod_phy_tx_lane_control_t* tx_control);

/*Rx control*/
int plp_aperta2_peregrine5_pc_phy_rx_lane_control_set(const plp_aperta2_phymod_phy_access_t* phy, plp_aperta2_phymod_phy_rx_lane_control_t rx_control);
int plp_aperta2_peregrine5_pc_phy_rx_lane_control_get(const plp_aperta2_phymod_phy_access_t* phy, plp_aperta2_phymod_phy_rx_lane_control_t* rx_control);

/*Set\Get CL72*/
int plp_aperta2_peregrine5_pc_phy_cl72_set(const plp_aperta2_phymod_phy_access_t* phy, uint32_t cl72_en);
int plp_aperta2_peregrine5_pc_phy_cl72_get(const plp_aperta2_phymod_phy_access_t* phy, uint32_t* cl72_en);

/*Get CL72 status*/
int plp_aperta2_peregrine5_pc_phy_cl72_status_get(const plp_aperta2_phymod_phy_access_t* phy, plp_aperta2_phymod_cl72_status_t* status);

/*Core Initialization*/
int plp_aperta2_peregrine5_pc_core_init(const plp_aperta2_phymod_core_access_t* core, const plp_aperta2_phymod_core_init_config_t* init_config, const plp_aperta2_phymod_core_status_t* core_status);

/*Core vco freq get function*/
int plp_aperta2_peregrine5_pc_phy_pll_multiplier_get(const plp_aperta2_phymod_phy_access_t* phy, uint32_t* core_vco_pll_multiplier);

/*Phy Initialization*/
int plp_aperta2_peregrine5_pc_phy_init(const plp_aperta2_phymod_phy_access_t* phy, const plp_aperta2_phymod_phy_init_config_t* init_config);

/*Set\get loopback mode*/
int plp_aperta2_peregrine5_pc_phy_loopback_set(const plp_aperta2_phymod_phy_access_t* phy, plp_aperta2_phymod_loopback_mode_t loopback, uint32_t enable);
int plp_aperta2_peregrine5_pc_phy_loopback_get(const plp_aperta2_phymod_phy_access_t* phy, plp_aperta2_phymod_loopback_mode_t loopback, uint32_t* enable);

/*Get rx pmd locked indication. This API will clear the pmd_lock_change indication.*/
int plp_aperta2_peregrine5_pc_phy_rx_pmd_locked_get(const plp_aperta2_phymod_phy_access_t* phy, uint32_t* rx_pmd_locked);

/*Get Lane Bit Map of rx pmd lock and pmd lock change indication. */
int plp_aperta2_peregrine5_pc_phy_rx_pmd_lock_status_get(const plp_aperta2_phymod_phy_access_t* phy, uint32_t* rx_pmd_locked, uint32_t* rx_pmd_lock_change);

/*Get rx signal detect indication*/
int plp_aperta2_peregrine5_pc_phy_rx_signal_detect_get(const plp_aperta2_phymod_phy_access_t* phy, uint32_t* rx_signal_detect);

/*Read phymod register*/
int plp_aperta2_peregrine5_pc_phy_reg_read(const plp_aperta2_phymod_phy_access_t* phy, uint32_t reg_addr, uint32_t* val);

/*Write phymod register*/
int plp_aperta2_peregrine5_pc_phy_reg_write(const plp_aperta2_phymod_phy_access_t* phy, uint32_t reg_addr, uint32_t val);

/*eye margin estimate get*/
int plp_aperta2_peregrine5_pc_phy_eye_margin_est_get(const plp_aperta2_phymod_phy_access_t* phy, phymod_eye_margin_mode_t eye_margin_mode, uint32_t* value);

/*Set the interface mode, speed and other configuration related to interface.*/
int plp_aperta2_peregrine5_pc_phy_speed_config_set(const plp_aperta2_phymod_phy_access_t* phy, const phymod_phy_speed_config_t* speed_config, const phymod_phy_pll_state_t* old_pll_state, phymod_phy_pll_state_t* new_pll_state);
int plp_aperta2_peregrine5_pc_phy_speed_config_get(const plp_aperta2_phymod_phy_access_t* phy, phymod_phy_speed_config_t* speed_config);

/* get default tx taps*/
int plp_aperta2_peregrine5_pc_phy_tx_taps_default_get(const plp_aperta2_phymod_phy_access_t* phy, phymod_phy_signalling_method_t mode, phymod_pam4_tx_t* tx);

/* get PMD micro code and length*/
int plp_aperta2_peregrine5_pc_phy_firmware_load_info_get(const plp_aperta2_phymod_phy_access_t* phy, phymod_firmware_load_info_t* info);

/* enable tx pam4 precoder for extended reach channel*/
int plp_aperta2_peregrine5_pc_phy_tx_pam4_precoder_enable_set(const plp_aperta2_phymod_phy_access_t* phy, int enable);
int plp_aperta2_peregrine5_pc_phy_tx_pam4_precoder_enable_get(const plp_aperta2_phymod_phy_access_t* phy, int* enable);

/* reconfig pll on a specific serdes core*/
int plp_aperta2_peregrine5_pc_phy_pll_reconfig(const plp_aperta2_phymod_phy_access_t* phy, uint8_t pll_index, uint32_t pll_div, plp_aperta2_phymod_ref_clk_t ref_clk);

/* Power down PLL*/
int plp_aperta2_peregrine5_pc_phy_pll_pwrdn(const plp_aperta2_phymod_phy_access_t* phy, uint32_t pll_index, uint32_t pwrdn);

/*Get rx ppm*/
int plp_aperta2_peregrine5_pc_phy_rx_ppm_get(const plp_aperta2_phymod_phy_access_t* phy, int16_t* rx_ppm);

/*Set/Get the channel loss hint for PAM4 speed */
int plp_aperta2_peregrine5_pc_phy_channel_loss_hint_set(const plp_aperta2_phymod_phy_access_t* phy, uint32_t channel_loss);
int plp_aperta2_peregrine5_pc_phy_channel_loss_hint_get(const plp_aperta2_phymod_phy_access_t* phy, uint32_t* channel_loss);

/* initialize the PMD info data structure */
int plp_aperta2_peregrine5_pc_phy_pmd_info_init(const plp_aperta2_phymod_phy_access_t* phy);

/*Get PLL power down*/
int plp_aperta2_peregrine5_pc_phy_pll_powerdown_get(const plp_aperta2_phymod_phy_access_t* phy, uint32_t pll_index, uint32_t* powerdown);

#endif /*_PEREGRINE5_PC_H_*/
