# Setting ARP garbage collection threshold values
net.ipv4.neigh.default.gc_thresh1=40000
net.ipv4.neigh.default.gc_thresh2=48000
net.ipv4.neigh.default.gc_thresh3=56000
net.ipv6.neigh.default.gc_thresh1=40000
net.ipv6.neigh.default.gc_thresh2=48000
net.ipv6.neigh.default.gc_thresh3=56000