#!/bin/bash

BMC_PRESENCE_SYS_PATH="/sys/bus/platform/devices/sys_cpld/bmc_present_l"
BMC_PRESENCE=`cat ${BMC_PRESENCE_SYS_PATH}`

DOCKER_EXEC_FLAGS="i"

# Determine whether stdout is on a terminal
if [ -t 1 ] ; then
    DOCKER_EXEC_FLAGS+="t"
fi

docker exec -$DOCKER_EXEC_FLAGS pmon python3 /usr/bin/platform_sensors.py
