/*
 *         
 * $Id: phymod.xml,v 1.1.2.5 2013/09/12 10:43:06 nirf Exp $
 * 
 * $Copyright: 
 * All Rights Reserved.$
 *         
 *     
 * DO NOT EDIT THIS FILE!
 *
 */

#include <phymod/phymod.h>
#include <phymod/phymod_system.h>
#include <phymod/phymod.h>
#include <phymod/phymod_dispatch.h>

#ifdef PHYMOD_APERTA2_SUPPORT

#include <tscp.h>
#include <peregrine5_pc.h>

__phymod__dispatch__t__ plp_aperta2_phymod_tscp_driver = {

    plp_aperta2_tscp_core_identify,
    plp_aperta2_tscp_core_info_get,
    plp_aperta2_tscp_core_lane_map_set,
    plp_aperta2_tscp_core_lane_map_get,
    NULL, /* plp_aperta2_phymod_core_reset_set */
    NULL, /* plp_aperta2_phymod_core_reset_get */
    NULL, /* plp_aperta2_phymod_core_firmware_info_get */
    NULL, /* plp_aperta2_phymod_phy_firmware_core_config_set */
    NULL, /* plp_aperta2_phymod_phy_firmware_core_config_get */
    plp_aperta2_tscp_phy_firmware_lane_config_set,
    plp_aperta2_tscp_phy_firmware_lane_config_get,
    NULL, /* plp_aperta2_phymod_core_pll_sequencer_restart */
    NULL, /* plp_aperta2_phymod_core_wait_event */
    NULL, /* plp_aperta2_phymod_phy_rx_restart */
    plp_aperta2_tscp_phy_polarity_set,
    plp_aperta2_tscp_phy_polarity_get,
    NULL, /* phymod_phy_training_tx_fir_post_set */
    NULL, /* phymod_phy_training_tx_fir_post_get */
    plp_aperta2_tscp_phy_tx_set,
    plp_aperta2_tscp_phy_tx_get,
    NULL, /* plp_aperta2_phymod_phy_media_type_tx_get */
    plp_aperta2_peregrine5_pc_phy_tx_override_set,
    plp_aperta2_peregrine5_pc_phy_tx_override_get,
    plp_aperta2_peregrine5_pc_phy_rx_set,
    plp_aperta2_peregrine5_pc_phy_rx_get,
    plp_aperta2_peregrine5_pc_phy_rx_adaptation_resume,
    NULL, /* plp_aperta2_phymod_phy_reset_set */
    NULL, /* plp_aperta2_phymod_phy_reset_get */
    NULL, /* plp_aperta2_phymod_phy_power_set */
    NULL, /* plp_aperta2_phymod_phy_power_get */
    NULL, /* plp_aperta2_phymod_phy_hg2_codec_control_set */
    NULL, /* plp_aperta2_phymod_phy_hg2_codec_control_get */
    plp_aperta2_tscp_phy_tx_lane_control_set,
    plp_aperta2_tscp_phy_tx_lane_control_get,
    plp_aperta2_tscp_phy_rx_lane_control_set,
    plp_aperta2_tscp_phy_rx_lane_control_get,
    NULL, /* plp_aperta2_phymod_phy_fec_enable_set */
    NULL, /* plp_aperta2_phymod_phy_fec_enable_get */
/*    plp_aperta2_tscp_phy_fec_override_set,
    plp_aperta2_tscp_phy_fec_override_get,*/
    NULL, /* plp_aperta2_phymod_phy_forced_speed_line_side_set */
    NULL, /* plp_aperta2_phymod_phy_forced_speed_line_side_get */
    NULL, /* plp_aperta2_phymod_phy_flow_control_mode_set */
    NULL, /* plp_aperta2_phymod_phy_flow_control_mode_get */
    NULL, /* plp_aperta2_phymod_phy_psm_cos_bmp_set */
    NULL, /* plp_aperta2_phymod_phy_psm_cos_bmp_get */
    NULL, /* plp_aperta2_phymod_phy_autoneg_oui_set */
    NULL, /* plp_aperta2_phymod_phy_autoneg_oui_get */
    NULL, /* plp_aperta2_phymod_phy_eee_set */
    NULL, /* plp_aperta2_phymod_phy_eee_get */
    NULL, /* plp_aperta2_phymod_phy_interface_config_set */
    NULL, /* plp_aperta2_phymod_phy_interface_config_get */
    plp_aperta2_tscp_phy_cl72_set,
    plp_aperta2_tscp_phy_cl72_get,
    plp_aperta2_tscp_phy_cl72_status_get,
    NULL, /* plp_aperta2_phymod_phy_autoneg_ability_set */
    NULL, /* plp_aperta2_phymod_phy_autoneg_ability_get */
    NULL, /* plp_aperta2_phymod_phy_autoneg_remote_ability_get */
    plp_aperta2_tscp_phy_autoneg_set,
    plp_aperta2_tscp_phy_autoneg_get,
    NULL, /* plp_aperta2_phymod_phy_autoneg_restart_set */
    plp_aperta2_tscp_phy_autoneg_status_get,
    plp_aperta2_tscp_core_init,
    plp_aperta2_peregrine5_pc_phy_pll_multiplier_get,
    plp_aperta2_tscp_phy_init,
    plp_aperta2_tscp_phy_loopback_set,
    plp_aperta2_tscp_phy_loopback_get,
    plp_aperta2_peregrine5_pc_phy_rx_pmd_locked_get,
    plp_aperta2_peregrine5_pc_phy_rx_signal_detect_get,
    plp_aperta2_tscp_phy_link_status_get,
    NULL, /* plp_aperta2_phymod_phy_status_dump */
    NULL, /* plp_aperta2_phymod_phy_pcs_userspeed_set */
    NULL, /* plp_aperta2_phymod_phy_pcs_userspeed_get */
    plp_aperta2_tscp_phy_reg_read,
    plp_aperta2_tscp_phy_reg_write,
    NULL, /* plp_aperta2_phymod_phy_private_read */
    NULL, /* plp_aperta2_phymod_phy_private_write */
    NULL, /* plp_aperta2_phymod_phy_rev_id */
    NULL, /* plp_aperta2_phymod_phy_lane_cross_switch_map_set */
    NULL, /* plp_aperta2_phymod_phy_lane_cross_switch_map_get */
    NULL, /* plp_aperta2_phymod_phy_intr_enable_set */
    NULL, /* plp_aperta2_phymod_phy_intr_enable_get */
    NULL, /* plp_aperta2_phymod_phy_intr_status_get */
    NULL, /* plp_aperta2_phymod_phy_intr_status_clear */
    NULL, /* plp_aperta2_phymod_phy_i2c_read */
    NULL, /* plp_aperta2_phymod_phy_i2c_write */
    NULL, /* plp_aperta2_phymod_phy_gpio_config_set */
    NULL, /* plp_aperta2_phymod_phy_gpio_config_get */
    NULL, /* plp_aperta2_phymod_phy_gpio_pin_value_set */
    NULL, /* plp_aperta2_phymod_phy_gpio_pin_value_get */
    NULL, /* plp_aperta2_phymod_timesync_config_set */
    NULL, /* plp_aperta2_phymod_timesync_config_get */
    plp_aperta2_tscp_timesync_enable_set,
    plp_aperta2_tscp_timesync_enable_get,
    NULL, /* plp_aperta2_phymod_timesync_nco_addend_set */
    NULL, /* plp_aperta2_phymod_timesync_nco_addend_get */
    NULL, /* plp_aperta2_phymod_timesync_framesync_mode_set */
    NULL, /* plp_aperta2_phymod_timesync_framesync_mode_get */
    NULL, /* plp_aperta2_phymod_timesync_local_time_set */
    NULL, /* plp_aperta2_phymod_timesync_local_time_get */
    NULL, /* plp_aperta2_phymod_timesync_load_ctrl_set */
    NULL, /* plp_aperta2_phymod_timesync_load_ctrl_get */
    NULL, /* plp_aperta2_phymod_timesync_tx_timestamp_offset_set */
    NULL, /* plp_aperta2_phymod_timesync_tx_timestamp_offset_get */
    NULL, /* plp_aperta2_phymod_timesync_rx_timestamp_offset_set */
    NULL, /* plp_aperta2_phymod_timesync_rx_timestamp_offset_get */
    NULL, /* plp_aperta2_phymod_timesync_capture_timestamp_get */
    NULL, /* plp_aperta2_phymod_timesync_heartbeat_timestamp_get */
    NULL, /* plp_aperta2_phymod_timesync_do_sync */
    /*plp_aperta2_tscp_timesync_offset_set,
    plp_aperta2_tscp_timesync_offset_get,
    plp_aperta2_tscp_timesync_adjust_set,*/
    NULL, /* plp_aperta2_phymod_edc_config_set */
    NULL, /* plp_aperta2_phymod_edc_config_get */
    NULL, /* plp_aperta2_phymod_phy_core_mode_set */
    NULL, /* plp_aperta2_phymod_phy_core_mode_get */
    NULL, /* plp_aperta2_phymod_failover_mode_set */
    NULL, /* plp_aperta2_phymod_failover_mode_get */
    NULL, /* plp_aperta2_phymod_port_init */
    NULL, /* plp_aperta2_phymod_phy_autoneg_try_enable */
    NULL, /* plp_aperta2_phymod_debug_ether */
    NULL, /* plp_aperta2_phymod_phy_short_chn_mode_enable_set */
    NULL, /* plp_aperta2_phymod_phy_short_chn_mode_enable_get */
    plp_aperta2_tscp_port_enable_set,
    plp_aperta2_tscp_port_enable_get,
    NULL, /* plp_aperta2_phymod_phy_eye_margin_est_get */
    NULL, /* plp_aperta2_phymod_phy_multi_get */
    NULL, /* plp_aperta2_phymod_phy_rescal_set */
    NULL, /* plp_aperta2_phymod_phy_rescal_get */
    NULL, /* plp_aperta2_phymod_phy_sw_an_control_status_get */
    NULL, /* plp_aperta2_phymod_phy_sw_an_base_page_exchange_handler */
    NULL, /* plp_aperta2_phymod_phy_sw_an_lp_page_rdy_handler */
    NULL, /* plp_aperta2_phymod_phy_sw_an_advert_set */
    NULL, /* plp_aperta2_phymod_phy_sw_autoneg_enable */
    NULL, /* plp_aperta2_phymod_phy_eee_mode_set*/
    NULL, /* plp_aperta2_phymod_phy_eee_mode_get*/
    NULL, /* plp_aperta2_phymod_phy_power_mode_set*/
    NULL, /* plp_aperta2_phymod_phy_power_mode_get*/
    NULL, /* plp_aperta2_phymod_phy_jfec_config_set*/
    NULL, /* plp_aperta2_phymod_phy_jfec_config_get*/
    NULL, /* plp_aperta2_phymod_phy_kp4_config_set*/
    NULL, /* plp_aperta2_phymod_phy_kp4_config_get*/
    NULL, /* plp_aperta2_phymod_phy_pam4_fec_status_get*/
    NULL, /* plp_aperta2_phymod_phy_avs_config_set*/
    NULL, /* plp_aperta2_phymod_phy_avs_config_get*/
    NULL, /* plp_aperta2_phymod_phy_avs_status_get*/
    NULL, /* plp_aperta2_phymod_warmboot_init*/
    NULL, /* plp_aperta2_phymod_logical_lane_set*/
    NULL, /* plp_aperta2_phymod_logical_lane_get*/
    NULL, /* plp_aperta2_phymod_phy_dsrds_firmware_lane_config_set*/
    NULL, /* plp_aperta2_phymod_phy_dsrds_firmware_lane_config_get*/
    NULL, /* plp_aperta2_phymod_synce_config_set*/
    NULL, /* plp_aperta2_phymod_synce_config_get*/
    NULL, /* plp_aperta2_phymod_timesync_time_code_set*/
    NULL, /* plp_aperta2_phymod_timesync_time_code_get*/
    NULL, /* plp_aperta2_phymod_timesync_link_delay_set*/
    NULL, /* plp_aperta2_phymod_timesync_link_delay_get*/
    NULL, /* plp_aperta2_phymod_timesync_timestamp_offset_set*/
    NULL, /* plp_aperta2_phymod_timesync_timestamp_offset_get*/
    NULL, /* plp_aperta2_phymod_timesync_timing_control_set*/
    NULL, /* plp_aperta2_phymod_timesync_timing_control_get*/
    NULL, /* plp_aperta2_phymod_phy_pcs_status_get*/
    NULL, /* plp_aperta2_phymod_timesync_sopmem_get*/
    plp_aperta2_tscp_phy_speed_config_set,
    plp_aperta2_tscp_phy_speed_config_get,
    NULL, /* plp_aperta2_phymod_phy_op_mode_get */
    NULL,
    plp_aperta2_tscp_phy_lane_config_default_get,
    plp_aperta2_tscp_phy_firmware_load_info_get,
    plp_aperta2_tscp_phy_autoneg_advert_ability_set,
    plp_aperta2_tscp_phy_autoneg_advert_ability_get,
    plp_aperta2_tscp_phy_autoneg_remote_advert_ability_get,
    NULL, /* plp_aperta2_phymod_phy_bond_in_pwrdn_override */
    plp_aperta2_tscp_phy_tx_pam4_precoder_enable_set,
    plp_aperta2_tscp_phy_tx_pam4_precoder_enable_get,
    NULL, /* phymod_phy_tx_phase_lock_rx_set */
    plp_aperta2_tscp_phy_pll_reconfig,
    NULL, /* plp_aperta2_phymod_phy_pll_pwrdn */
    NULL, /* plp_aperta2_phymod_phy_linkdown_transmit_set */
    NULL, /* plp_aperta2_phymod_phy_linkdown_transmit_get */
    NULL, /* plp_aperta2_phymod_phy_fw_init_params_get*/
    NULL, /* plp_aperta2_phymod_srds_diag_access_enable*/
    NULL, /* plp_aperta2_phymod_phy_cleanup*/
    NULL, /* plp_aperta2_phymod_timesync_mpls_set*/
    NULL, /* plp_aperta2_phymod_timesync_mpls_get*/
    NULL, /* plp_aperta2_phymod_timesync_inband_filter_set*/
    NULL, /* plp_aperta2_phymod_timesync_inband_filter_get*/
    NULL, /* plp_aperta2_phymod_phy_pai_info_get*/
    NULL, /* plp_aperta2_phymod_failover_config_set*/
    NULL, /* plp_aperta2_phymod_failover_config_get*/
    NULL, /* plp_aperta2_phymod_timesync_sopmem_set*/
    NULL, /* plp_aperta2_phymod_timesync_pch_set*/
    NULL, /* plp_aperta2_phymod_timesync_pch_get*/
    NULL, /* plp_aperta2_phymod_timestamp_univ_set*/
    NULL, /* plp_aperta2_phymod_timestamp_univ_get*/
    NULL, /* plp_aperta2_phymod_peripheral_dev_control*/
    plp_aperta2_peregrine5_pc_phy_pll_powerdown_get,   
    plp_aperta2_tscp_phy_fec_bypass_indication_set,
    plp_aperta2_tscp_phy_fec_bypass_indication_get,
    plp_aperta2_tscp_phy_autoneg_speed_id_table_reload,
};

#endif /* PHYMOD_APERTA2_SUPPORT */
