/*
 *
 * $Id: phymod.xml,v 1.1.2.5 Broadcom SDK $
 *
 * $Copyright: (c) 2020 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *
 *
 * DO NOT EDIT THIS FILE!
 *
 */

#ifndef _BLACKHAWK_DIAGNOSTICS_H__H_
#define _BLACKHAWK_DIAGNOSTICS_H__H_

#include <phymod/phymod_definitions.h>
/*Set\get slicer position*/
int plp_aperta_blackhawk_phy_rx_slicer_position_set(const plp_aperta_phymod_phy_access_t* phy, uint32_t flags, const plp_aperta_phymod_slicer_position_t* position);
int plp_aperta_blackhawk_phy_rx_slicer_position_get(const plp_aperta_phymod_phy_access_t* phy, uint32_t flags, plp_aperta_phymod_slicer_position_t* position);

/*Get slicer range limitation*/
int plp_aperta_blackhawk_phy_rx_slicer_position_max_get(const plp_aperta_phymod_phy_access_t* phy, uint32_t flags, const plp_aperta_phymod_slicer_position_t* position_min, const plp_aperta_phymod_slicer_position_t* position_max);

/*set\get PRBS configuration*/
int plp_aperta_blackhawk_phy_prbs_config_set(const plp_aperta_phymod_phy_access_t* phy, uint32_t flags , const plp_aperta_phymod_prbs_t* prbs);
int plp_aperta_blackhawk_phy_prbs_config_get(const plp_aperta_phymod_phy_access_t* phy, uint32_t flags , plp_aperta_phymod_prbs_t* prbs);

/*Set\get PRBS enable state*/
int plp_aperta_blackhawk_phy_prbs_enable_set(const plp_aperta_phymod_phy_access_t* phy, uint32_t flags , uint32_t enable);
int plp_aperta_blackhawk_phy_prbs_enable_get(const plp_aperta_phymod_phy_access_t* phy, uint32_t flags , uint32_t* enable);

/*Get PRBS Status*/
int plp_aperta_blackhawk_phy_prbs_status_get(const plp_aperta_phymod_phy_access_t* phy, uint32_t flags, plp_aperta_phymod_prbs_status_t* prbs_status);

/*Set\get pattern state*/
int plp_aperta_blackhawk_phy_pattern_config_set(const plp_aperta_phymod_phy_access_t* phy, const plp_aperta_phymod_pattern_t* pattern);
int plp_aperta_blackhawk_phy_pattern_config_get(const plp_aperta_phymod_phy_access_t* phy, plp_aperta_phymod_pattern_t* pattern);

/*Set\get pattern state*/
int plp_aperta_blackhawk_phy_pattern_enable_set(const plp_aperta_phymod_phy_access_t* phy, uint32_t enable, const plp_aperta_phymod_pattern_t* pattern);
int plp_aperta_blackhawk_phy_pattern_enable_get(const plp_aperta_phymod_phy_access_t* phy, uint32_t* enable, const plp_aperta_phymod_pattern_t* pattern);

/*Get core diagnostics information*/
int plp_aperta_blackhawk_core_diagnostics_get(const plp_aperta_phymod_core_access_t* core, plp_aperta_phymod_core_diagnostics_t* diag);

/*Get phy diagnostics information*/
int plp_aperta_blackhawk_phy_diagnostics_get(const plp_aperta_phymod_phy_access_t* phy, plp_aperta_phymod_phy_diagnostics_t* diag);

/*Get phy diagnostics information*/
int plp_aperta_blackhawk_phy_pmd_info_dump(const plp_aperta_phymod_phy_access_t* phy, char* type);

/*Display eyescan information*/
int plp_aperta_blackhawk_phy_eyescan_run(const plp_aperta_phymod_phy_access_t* phy, uint32_t flags, plp_aperta_phymod_eyescan_mode_t mode, const plp_aperta_phymod_phy_eyescan_options_t* eyescan_options);


#endif /*_BLACKHAWK_DIAGNOSTICS_H_*/
