module sonic-tunnel {
	yang-version 1.1;
	namespace "http://github.com/sonic-net/sonic-tunnel";
	prefix tunnel;

	import ietf-inet-types {
		prefix inet;
	}

	import sonic-peer-switch {
		prefix ps;
	}

	import sonic-dscp-tc-map {
		prefix dtm;
	}

	import sonic-tc-priority-group-map {
		prefix tpgm;
	}

	import sonic-tc-queue-map {
		prefix tqm;
	}

	organization
		"SONiC";

	contact
		"SONiC";

	description
		"SONiC tunnel config";

	revision 2026-06-17 {
		description
			"Initial revision";
	}

	container sonic-tunnel {
		container TUNNEL {
			description "General TUNNEL configuration for SONiC";
			list TUNNEL_LIST {
				key "tunnel_name";

				leaf tunnel_name {
					description "Name of Tunnel";
					type string;
				}

				leaf dscp_mode {
					description "DSCP mode";
					type string {
						pattern "uniform|pipe";
					}
				}

				leaf src_ip {
					description "Source IP address off the tunnel.";
					type inet:ip-address;
				}

				leaf dst_ip {
					description "IPv4 or IPv6 address of this switch.";
					type inet:ip-address;
				}

				leaf ecn_mode {
					description "ECN mode";
					type string {
						pattern "copy_from_outer|standard";
					}
				}

				leaf encap_ecn_mode {
					description "Encap ECN mode";
					type string {
						pattern "standard";
					}
				}

				leaf ttl_mode {
					description "TTL mode";
					type string {
						pattern "uniform|pipe";
					}
				}

				leaf tunnel_type {
					description "Tunnel type";
					type string {
						pattern "IPINIP";
					}
				}

				leaf decap_dscp_to_tc_map {
					description "Decap DSCP to TC map";
					type string;
				}

				leaf decap_tc_to_pg_map {
					description "Decap TC to PG map";
					type string;
				}

				leaf encap_tc_to_dscp_map {
					description "Encap TC to DSCP map";
					type string;
				}

				leaf encap_tc_to_queue_map {
					description "Encap TC to Queue map";
					type string;
				}
			}
		}
	}
}
