# Asterfusion CX532P-N platform modules


ASTERFUSION_CX532P-N_PLATFORM_MODULE_VERSION = 1.0.0
ASTERFUSION_CX664D-N_PLATFORM_MODULE_VERSION = 1.0.0
ASTERFUSION_CX564P-N_PLATFORM_MODULE_VERSION = 1.0.0
ASTERFUSION_CX732Q-N_PLATFORM_MODULE_VERSION = 1.0.0
ASTERFUSION_CX864E-N_PLATFORM_MODULE_VERSION = 1.0.0

export ASTERFUSION_CX532P-N_PLATFORM_MODULE_VERSION
export ASTERFUSION_CX664D-N_PLATFORM_MODULE_VERSION
export ASTERFUSION_CX564P-N_PLATFORM_MODULE_VERSION
export ASTERFUSION_CX732Q-N_PLATFORM_MODULE_VERSION
export ASTERFUSION_CX864E-N_PLATFORM_MODULE_VERSION

ASTERFUSION_CX532P-N_PLATFORM_MODULE = sonic-platform-asterfusion-cx532p-n_$(ASTERFUSION_CX532P-N_PLATFORM_MODULE_VERSION)_amd64.deb
$(ASTERFUSION_CX532P-N_PLATFORM_MODULE)_PLATFORM = x86_64-asterfusion_cx532p_n-r0
$(ASTERFUSION_CX532P-N_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-asterfusion
$(ASTERFUSION_CX532P-N_PLATFORM_MODULE)_DEPENDS +=  $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
SONIC_DPKG_DEBS += $(ASTERFUSION_CX532P-N_PLATFORM_MODULE)

ASTERFUSION_CX664D-N_PLATFORM_MODULE = sonic-platform-asterfusion-cx664d-n_$(ASTERFUSION_CX664D-N_PLATFORM_MODULE_VERSION)_amd64.deb
ASTERFUSION_CX564P-N_PLATFORM_MODULE = sonic-platform-asterfusion-cx564p-n_$(ASTERFUSION_CX564P-N_PLATFORM_MODULE_VERSION)_amd64.deb
ASTERFUSION_CX732Q-N_PLATFORM_MODULE = sonic-platform-asterfusion-cx732q-n_$(ASTERFUSION_CX732Q-N_PLATFORM_MODULE_VERSION)_amd64.deb
ASTERFUSION_CX864E-N_PLATFORM_MODULE = sonic-platform-asterfusion-cx864e-n_$(ASTERFUSION_CX864E-N_PLATFORM_MODULE_VERSION)_amd64.deb

$(ASTERFUSION_CX664D-N_PLATFORM_MODULE)_PLATFORM = x86_64-asterfusion_cx664d_n-r0
$(ASTERFUSION_CX564P-N_PLATFORM_MODULE)_PLATFORM = x86_64-asterfusion_cx564p_n-r0
$(ASTERFUSION_CX732Q-N_PLATFORM_MODULE)_PLATFORM = x86_64-asterfusion_cx732q_n-r0
$(ASTERFUSION_CX864E-N_PLATFORM_MODULE)_PLATFORM = x86_64-asterfusion_cx864e_n-r0

$(ASTERFUSION_CX664D-N_PLATFORM_MODULE)_DEPENDS +=  $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(ASTERFUSION_CX564P-N_PLATFORM_MODULE)_DEPENDS +=  $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(ASTERFUSION_CX732Q-N_PLATFORM_MODULE)_DEPENDS +=  $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(ASTERFUSION_CX864E-N_PLATFORM_MODULE)_DEPENDS +=  $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)

$(eval $(call add_extra_package,$(ASTERFUSION_CX532P-N_PLATFORM_MODULE),$(ASTERFUSION_CX664D-N_PLATFORM_MODULE)))
$(eval $(call add_extra_package,$(ASTERFUSION_CX532P-N_PLATFORM_MODULE),$(ASTERFUSION_CX564P-N_PLATFORM_MODULE)))
$(eval $(call add_extra_package,$(ASTERFUSION_CX532P-N_PLATFORM_MODULE),$(ASTERFUSION_CX732Q-N_PLATFORM_MODULE)))
$(eval $(call add_extra_package,$(ASTERFUSION_CX532P-N_PLATFORM_MODULE),$(ASTERFUSION_CX864E-N_PLATFORM_MODULE)))
