# Celestica DX010 and Haliburton Platform modules

CLS_DX010_PLATFORM_MODULE_VERSION = 1.0
CLS_HALIBURTON_PLATFORM_MODULE_VERSION = 1.0
CLS_QUESTONE2_PLATFORM_MODULE_VERSION = 1.0
CLS_SEASTONE2_PLATFORM_MODULE_VERSION = 1.0
CLS_SILVERSTONE_PLATFORM_MODULE_VERSION = 1.0
CLS_DS1000_PLATFORM_MODULE_VERSION = 1.0
CLS_DS2000_PLATFORM_MODULE_VERSION = 1.0
CLS_DS3000_PLATFORM_MODULE_VERSION = 1.0
CLS_DS4000_PLATFORM_MODULE_VERSION = 1.0

export CLS_DX010_PLATFORM_MODULE_VERSION
export CLS_HALIBURTON_PLATFORM_MODULE_VERSION
export CLS_QUESTONE2_PLATFORM_MODULE_VERSION
export CLS_SEASTONE2_PLATFORM_MODULE_VERSION
export CLS_SILVERSTONE_PLATFORM_MODULE_VERSION
export CLS_DS1000_PLATFORM_MODULE_VERSION
export CLS_DS2000_PLATFORM_MODULE_VERSION
export CLS_DS3000_PLATFORM_MODULE_VERSION
export CLS_DS4000_PLATFORM_MODULE_VERSION

CLS_DX010_PLATFORM_MODULE = platform-modules-dx010_$(CLS_DX010_PLATFORM_MODULE_VERSION)_amd64.deb
$(CLS_DX010_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-cls
$(CLS_DX010_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON) $(PDDF_PLATFORM_MODULE_SYM)
$(CLS_DX010_PLATFORM_MODULE)_PLATFORM = x86_64-cel_seastone-r0
SONIC_DPKG_DEBS += $(CLS_DX010_PLATFORM_MODULE)

CLS_HALIBURTON_PLATFORM_MODULE = platform-modules-haliburton_$(CLS_HALIBURTON_PLATFORM_MODULE_VERSION)_amd64.deb
$(CLS_HALIBURTON_PLATFORM_MODULE)_PLATFORM = x86_64-cel_e1031-r0
$(eval $(call add_extra_package,$(CLS_DX010_PLATFORM_MODULE),$(CLS_HALIBURTON_PLATFORM_MODULE)))

CLS_QUESTONE2_PLATFORM_MODULE = platform-modules-questone2_$(CLS_QUESTONE2_PLATFORM_MODULE_VERSION)_amd64.deb
$(CLS_QUESTONE2_PLATFORM_MODULE)_PLATFORM = x86_64-cel_questone_2-r0
$(eval $(call add_extra_package,$(CLS_DX010_PLATFORM_MODULE),$(CLS_QUESTONE2_PLATFORM_MODULE)))

CLS_SEASTONE2_PLATFORM_MODULE = platform-modules-seastone2_$(CLS_SEASTONE2_PLATFORM_MODULE_VERSION)_amd64.deb
$(CLS_SEASTONE2_PLATFORM_MODULE)_PLATFORM = x86_64-cel_seastone_2-r0
$(eval $(call add_extra_package,$(CLS_DX010_PLATFORM_MODULE),$(CLS_SEASTONE2_PLATFORM_MODULE)))

CLS_SILVERSTONE_PLATFORM_MODULE = platform-modules-silverstone_$(CLS_SILVERSTONE_PLATFORM_MODULE_VERSION)_amd64.deb
$(CLS_SILVERSTONE_PLATFORM_MODULE)_PLATFORM = x86_64-cel_silverstone-r0
$(eval $(call add_extra_package,$(CLS_DX010_PLATFORM_MODULE),$(CLS_SILVERSTONE_PLATFORM_MODULE)))

CLS_PO_DS1000_PLATFORM_MODULE = platform-modules-cel-ds1000_$(CLS_DS1000_PLATFORM_MODULE_VERSION)_amd64.deb
$(CLS_PO_DS1000_PLATFORM_MODULE)_PLATFORM = x86_64-cel_ds1000-r0
$(eval $(call add_extra_package,$(CLS_DX010_PLATFORM_MODULE),$(CLS_PO_DS1000_PLATFORM_MODULE)))

CLS_PO_DS2000_PLATFORM_MODULE = platform-modules-cel-ds2000_$(CLS_DS2000_PLATFORM_MODULE_VERSION)_amd64.deb
$(CLS_PO_DS2000_PLATFORM_MODULE)_PLATFORM = x86_64-cel_ds2000-r0
$(eval $(call add_extra_package,$(CLS_DX010_PLATFORM_MODULE),$(CLS_PO_DS2000_PLATFORM_MODULE)))

CLS_PO_DS3000_PLATFORM_MODULE = platform-modules-cel-ds3000_$(CLS_DS3000_PLATFORM_MODULE_VERSION)_amd64.deb
$(CLS_PO_DS3000_PLATFORM_MODULE)_PLATFORM = x86_64-cel_ds3000-r0
$(eval $(call add_extra_package,$(CLS_DX010_PLATFORM_MODULE),$(CLS_PO_DS3000_PLATFORM_MODULE)))

CLS_PO_SILVERSTONE_V2_PLATFORM_MODULE = platform-modules-cel-silverstone-v2_$(CLS_DS4000_PLATFORM_MODULE_VERSION)_amd64.deb
$(CLS_PO_SILVERSTONE_V2_PLATFORM_MODULE)_PLATFORM = x86_64-cel_silverstone_v2-r0
$(eval $(call add_extra_package,$(CLS_DX010_PLATFORM_MODULE),$(CLS_PO_SILVERSTONE_V2_PLATFORM_MODULE)))

CLS_DS1000_PLATFORM_MODULE = platform-modules-ds1000_$(CLS_DS1000_PLATFORM_MODULE_VERSION)_amd64.deb
$(CLS_DS1000_PLATFORM_MODULE)_PLATFORM = x86_64-cls_ds1000-r0
$(eval $(call add_extra_package,$(CLS_DX010_PLATFORM_MODULE),$(CLS_DS1000_PLATFORM_MODULE)))

CLS_DS2000_PLATFORM_MODULE = platform-modules-ds2000_$(CLS_DS2000_PLATFORM_MODULE_VERSION)_amd64.deb
$(CLS_DS2000_PLATFORM_MODULE)_PLATFORM = x86_64-cls_ds2000-r0
$(eval $(call add_extra_package,$(CLS_DX010_PLATFORM_MODULE),$(CLS_DS2000_PLATFORM_MODULE)))

CLS_DS3000_PLATFORM_MODULE = platform-modules-ds3000_$(CLS_DS3000_PLATFORM_MODULE_VERSION)_amd64.deb
$(CLS_DS3000_PLATFORM_MODULE)_PLATFORM = x86_64-cls_ds3000-r0
$(eval $(call add_extra_package,$(CLS_DX010_PLATFORM_MODULE),$(CLS_DS3000_PLATFORM_MODULE)))

CLS_DS4000_PLATFORM_MODULE = platform-modules-ds4000_$(CLS_DS4000_PLATFORM_MODULE_VERSION)_amd64.deb
$(CLS_DS4000_PLATFORM_MODULE)_PLATFORM = x86_64-cls_ds4000-r0
$(eval $(call add_extra_package,$(CLS_DX010_PLATFORM_MODULE),$(CLS_DS4000_PLATFORM_MODULE)))
