# broadcom sswsyncd package

SSWSYNCD_BCMCMD = sswsyncd-bcmcmd.bin
$(SSWSYNCD_BCMCMD)_SRC_PATH = $(PLATFORM_PATH)/sswsyncd
$(SSWSYNCD_BCMCMD)_DEPENDS += $(LIBC_DEV)
$(SSWSYNCD_BCMCMD)_RDEPENDS += $(LIBC)
$(SSWSYNCD_BCMCMD)_DST_PATH = $(PLATFORM_PATH)/docker-syncd-brcm/files
SONIC_MAKE_FILES += $(SSWSYNCD_BCMCMD)

SSWSYNCD_DSSERVE = sswsyncd-dsserve.bin
$(SSWSYNCD_DSSERVE)_SRC_PATH = $(PLATFORM_PATH)/sswsyncd
$(SSWSYNCD_DSSERVE)_DEPENDS += $(LIBC_DEV)
$(SSWSYNCD_DSSERVE)_RDEPENDS += $(LIBC)
$(SSWSYNCD_DSSERVE)_DST_PATH = $(PLATFORM_PATH)/docker-syncd-brcm/files
SONIC_MAKE_FILES += $(SSWSYNCD_DSSERVE)
