# Arista Platform modules for ARM64

ARISTA_PLATFORM_MODULE_VERSION = 1.0

export ARISTA_PLATFORM_MODULE_VERSION

# Get list of Arista platforms (if any arm64 platforms exist)
ARISTA_PLATFORMS_ARM64 = $(subst device/arista/,, $(wildcard device/arista/arm64-arista_*))

export ARISTA_PLATFORMS_ARM64

# Main arista platform module for arm64
ARISTA_PLATFORM_MODULE_ARM64 = sonic-platform-arista_$(ARISTA_PLATFORM_MODULE_VERSION)_arm64.deb
$(ARISTA_PLATFORM_MODULE_ARM64)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-arista
$(ARISTA_PLATFORM_MODULE_ARM64)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(ARISTA_PLATFORM_MODULE_ARM64)_BUILD_ENV = KVERSION_SHORT=$(KVERSION_SHORT) KVERSION=$(KVERSION) ARCH=$(CONFIGURED_ARCH)
ifneq ($(ARISTA_PLATFORMS_ARM64),)
$(ARISTA_PLATFORM_MODULE_ARM64)_PLATFORM = $(ARISTA_PLATFORMS_ARM64)
endif
SONIC_DPKG_DEBS += $(ARISTA_PLATFORM_MODULE_ARM64)

# Python package (architecture independent)
ARISTA_PLATFORM_MODULE_PYTHON3 = python3-sonic-platform-arista_$(ARISTA_PLATFORM_MODULE_VERSION)_all.deb
ifneq ($(ARISTA_PLATFORMS_ARM64),)
$(ARISTA_PLATFORM_MODULE_PYTHON3)_PLATFORM = $(ARISTA_PLATFORMS_ARM64)
endif
$(eval $(call add_extra_package,$(ARISTA_PLATFORM_MODULE_ARM64),$(ARISTA_PLATFORM_MODULE_PYTHON3)))

export ARISTA_PLATFORM_MODULE_ARM64 \
       ARISTA_PLATFORM_MODULE_PYTHON3
