#ifndef CANARY_FALCONITA_REGMAP_H
#define CANARY_FALCONITA_REGMAP_H

// Phoenix state machine
#define REG_FLR_RX_LANE_RST          REGBITR(FLR, 0x000, 15)
#define REG_FLR_RX_CNTR_TARGET_INIT  REGBITR(FLR, 0x001, 15, 0)
#define REG_FLR_RX_CNTR_TARGET_FINAL REGBITR(FLR, 0x002, 15, 0)
#define REG_FLR_RX_TIMER_MEAS_S6     REGBITR(FLR, 0x007, 6, 3)
#define REG_FLR_RX_FIXED_PATT_B0     REGBITR(FLR, 0x007, 2, 1)
#define REG_FLR_RX_FIXED_PATT_DIR    REGBITR(FLR, 0x007, 0)
#define REG_FLR_RX_ITER_S6           REGBITR(FLR, 0x009, 3, 0)

#define REG_FLR_RX_OF_PERIOD           REGBITR(FLR, 0x00A, 9, 5)
#define REG_FLR_RX_HF_PERIOD           REGBITR(FLR, 0x00A, 4, 0)
#define REG_FLR_RX_OF_THS              REGBITR(FLR, 0x00B, 14, 8)
#define REG_FLR_RX_HF_THS              REGBITR(FLR, 0x00B, 6, 0)
#define REG_FLR_RX_OF_CNTR_UPPER_LIMIT REGBITR(FLR, 0x00C, 15, 0)
#define REG_FLR_RX_OF_CNTR_LOWER_LIMIT REGBITR(FLR, 0x00D, 15, 0)
#define REG_FLR_RX_HF_CNTR_TARGET      REGBITR(FLR, 0x00E, 15, 0)

#define REG_FLR_RX_BP1_EN     REGBITR(FLR, 0x011, 15)
#define REG_FLR_RX_BP1_ST     REGBITR(FLR, 0x011, 12, 8)
#define REG_FLR_RX_BP2_EN     REGBITR(FLR, 0x011, 14)
#define REG_FLR_RX_BP2_ST     REGBITR(FLR, 0x011, 4, 0)
#define REG_FLR_RX_SM_CONT    REGBITR(FLR, 0x011, 13)
#define REG_FLR_RX_DELTA_OWEN REGBITR(FLR, 0x012, 13)
#define REG_FLR_RX_DELTA_OW   REGBITR(FLR, 0x012, 12, 6)
#define REG_FLR_RX_KP_OWEN    REGBITR(FLR, 0x020, 9)
#define REG_FLR_RX_KP_OW      REGBITR(FLR, 0x020, 8, 6)

#define REG_FLR_RX_ACAL_CLK_EN_OWEN REGBITR(FLR, 0x018, 11)
#define REG_FLR_RX_ACAL_CLK_EN_OW   REGBITR(FLR, 0x018, 10)
#define REG_FLR_RX_ACAL_START_OW    REGBITR(FLR, 0x01F, 0)
#define REG_FLR_RX_ACAL_START_OWEN  REGBITR(FLR, 0x01F, 1)
#define REG_FLR_RX_ACAL_DONE_OW     REGBITR(FLR, 0x023, 2)
#define REG_FLR_RX_ACAL_DONE_OWEN   REGBITR(FLR, 0x023, 3)

#define REG_FLR_RX_DAC_OW               REGBITR(FLR, 0x021, 11, 8)
#define REG_FLR_RX_DAC_OWEN             REGBITR(FLR, 0x021, 12)
#define REG_FLR_RX_AGC_OW               REGBITR(FLR, 0x021, 6, 4)
#define REG_FLR_RX_AGC_OWEN             REGBITR(FLR, 0x021, 7)
#define REG_FLR_RX_MARGIN_PATT_DIS_OWEN REGBITR(FLR, 0x021, 3)
#define REG_FLR_RX_MARGIN_PATT_DIS_OW   REGBITR(FLR, 0x021, 2)
#define REG_FLR_RX_BP1_REACHED          REGBITR(FLR, 0x028, 15)
#define REG_FLR_RX_BP2_REACHED          REGBITR(FLR, 0x028, 14)
#define REG_FLR_RX_STATE                REGBITR(FLR, 0x028, 13, 9)
#define REG_FLR_RX_DAC                  REGBITR(FLR, 0x028, 8, 5)

#define REG_FLR_RX_MJ REGBITR(FLR, 0x02E, 1, 0)

#define REG_FLR_RX_CNTR_SEL REGBITR(FLR, 0x030, 7, 4)

#define REG_FLR_RX_PLUS_MARGIN    REGBITR(FLR, 0x032, 15, 4)
#define REG_FLR_RX_MINUS_MARGIN_H REGBITR(FLR, 0x032, 3, 0)
#define REG_FLR_RX_MINUS_MARGIN_L REGBITR(FLR, 0x33, 15, 8)

#define REG_FLR_RX_FIXED_PATT_PLUS_MARGIN_H REGBITR(FLR, 0x036, 7, 0)    // HIGH
#define REG_FLR_RX_FIXED_PATT_PLUS_MARGIN_L REGBITR(FLR, 0x037, 15, 12)  // LOW
#define REG_FLR_RX_FIXED_PATT_MINUS_MARGIN  REGBITR(FLR, 0x037, 11, 0)
#define REG_FLR_RX_EM                       REGBITR(FLR, 0x038, 11, 0)
#define REG_FLR_RX_DELTA                    REGBITR(FLR, 0x040, 13, 7)
#define REG_FLR_RX_PAM4_TAP                 REGBITR(FLR, 0x040, 6, 0)  // PAM4 FM1

#define REG_FLR_RX_MU_OW   REGBITR(FLR, 0x087, 10, 9)
#define REG_FLR_RX_MU_OWEN REGBITR(FLR, 0x087, 11)

#define REG_FLR_RX_PLUS_MARGIN_SEL  REGBITR(FLR, 0x088, 15, 12)
#define REG_FLR_RX_MINUS_MARGIN_SEL REGBITR(FLR, 0x088, 11, 8)
#define REG_FLR_RX_PAM4_DFE_SEL     REGBITR(FLR, 0x088, 7, 4)   // THS_Q_SEL
#define REG_FLR_RX_PAM4_DFE_RD      REGBITR(FLR, 0x02F, 15, 4)  // READ_THS_Q

// Phoenix RX digital top
#define REG_FLR_RX_PAM4_EN           REGBITR(FLR, 0x041, 15)
#define REG_FLR_RX_THETA_UPDATE_MODE REGBITR(FLR, 0x041, 12, 10)  // THETA2,3,4 UPDATE MODE, USED DELTA_SEARCH()

#define REG_FLR_RX_PRECODER_EN REGBITR(FLR, 0x42, 1)
#define REG_FLR_RX_GRAY_EN     REGBITR(FLR, 0x42, 0)
#define REG_FLR_RX_MSB_SWAP    REGBITR(FLR, 0x43, 15)

#define REG_FLR_RX_ERR_CNTR_RST      REGBITR(FLR, 0x43, 0)  // USE SYNC ERR CNTR
#define REG_FLR_RX_PRBS_AUTO_SYNC_EN REGBITR(FLR, 0x43, 1)
#define REG_FLR_RX_POL               REGBITR(FLR, 0x43, 7)  // FIRMWARE FLIP [8], CUSTOMER FLIP [7]
#define REG_FLR_RX_PRBS_CHECKER_PU   REGBITR(FLR, 0x43, 3)  // USE SYNC CHECKER
#define REG_FLR_RX_PRBS_MODE         REGBITR(FLR, 0x43, 6, 5)

#define REG_FLR_RX_DELAY_LOOP_FREEZE REGBITR(FLR, 0x044, 1)  // FREEZE DELAY LOOP, USED DELTA_SEARCH

#define REG_FLR_RX_FIXED_PATT_MODE         REGBITR(FLR, 0x045, 6, 3)
#define REG_FLR_RX_PRBS_PATTERN_PREV       REGBITR(FLR, 0x045, 8, 7)
#define REG_FLR_RX_PRBS_PATTERN_PREV_EN    REGBITR(FLR, 0x045, 9)
#define REG_FLR_RX_PRBS_PATTERN_CNTR_RESET REGBITR(FLR, 0x045, 10)
#define REG_FLR_RX_ERR_CNTR_MSB            REGBITR(FLR, 0x050, 15, 0)
#define REG_FLR_RX_ERR_CNTR_LSB            REGBITR(FLR, 0x051, 15, 0)
#define REG_FLR_RX_PRBS_PATTERN_MSB(X)     REGBITR(FLR, (0x052 + (X * 2)), 15, 0)
#define REG_FLR_RX_PRBS_PATTERN_LSB(X)     REGBITR(FLR, (0x053 + (X * 2)), 15, 0)
#define REG_FLR_RX_AGC_MAP0                REGBITR(FLR, 0x048, 15, 0)  // HIGHEST PEAKING
#define REG_FLR_RX_AGC_MAP1                REGBITR(FLR, 0x049, 15, 0)
#define REG_FLR_RX_AGC_MAP2                REGBITR(FLR, 0x04A, 15, 0)  // LOWEST PEAKING
#define REG_FLR_RX_AGC_ENTRY7              REGBITR(FLR, 0x04A, 5, 0)

#define REG_FLR_RX_SD                 REGBITR(FLR, 0x06A, 7)
#define REG_FLR_RX_RDY                REGBITR(FLR, 0x06A, 15)
#define REG_FLR_RX_PRBS_PATTERN_PHASE REGBITR(FLR, 0x06E, 7, 0)
#define REG_FLR_PRBS_CNT_ATOMIC_READ  REGBITR(FLR, 0x06E, 9, 8)
#define REG_FLR_RX_CNT3               REGBITR(FLR, 0x06F, 15, 0)
#define REG_FLR_RX_CNT0               REGBITR(FLR, 0x070, 15, 0)
#define REG_FLR_RX_HF_CNT             REGBITR(FLR, 0x072, 15, 0)
#define REG_FLR_RX_FREQ_ACCUM         REGBITR(FLR, 0x073, 10, 0)
#define REG_FLR_RX_TED_EN             REGBITR(FLR, 0x079, 13)
#define REG_FLR_PAM4_TRF              REGBITR(FLR, 0x079, 12, 0)
#define REG_FLR_PAM4_TRF_SPEED_SEL    REGBITR(FLR, 0x079, 12, 8)
#define REG_FLR_PAM4_TRF_FREQ         REGBITR(FLR, 0x079, 4, 3)

// RX PAM4 registers
#define REG_FLR_RX_F1OVER3 REGBITR(FLR, 0x004, 11, 5)

#endif
