#ifndef CANARY_REGMAP_H
#define CANARY_REGMAP_H

#include "canary/canary_eagle_regmap.h"
#include "canary/canary_falconita_regmap.h"

#include "sdk.h"

/* Canary requires hive "PHY" defined. */
extern const RegHive_t PHY[];

#define ANA   SUBHIVE(PHY, 0)
#define PLL   SUBHIVE(PHY, 0)
#define FLR   SUBHIVE(PHY, 0)
#define TX    SUBHIVE(PHY, 0)
#define EAGLE SUBHIVE(PHY, 0x100)

// Phoenix3 TX PLL
#define REG_TX_PU_BG              REGBITR(PLL, 0x0FF, 12)
#define REG_TX_PU_RVDD            REGBITR(PLL, 0x0FF, 11)
#define REG_TX_EN_RVDDVCO         REGBITR(PLL, 0x0FF, 10)
#define REG_TX_PU_RVDDLOOP        REGBITR(PLL, 0x0FF, 7)
#define REG_TX_PU_PLL_INTP        REGBITR(PLL, 0x0FF, 4)
#define REG_TX_PLL_DIV2           REGBITR(PLL, 0x0FF, 1)
#define REG_TX_PLL_DIV4           REGBITR(PLL, 0x0FF, 0)
#define REG_TX_PLL_N              REGBITR(PLL, 0x0FE, 15, 7)
#define REG_TX_PLL_PU             REGBITR(PLL, 0x0FE, 0)
#define REG_EN_40T_CLK_TX         REGBITR(PLL, 0x0FB, 0)
#define REG_PU_VDRV_MA            REGBITR(PLL, 0x0FA, 15)
#define REG_TX_PI_EN              REGBITR(PLL, 0x0F4, 0)
#define REG_OWEN_PHASE_ROTATOR    REGBITR(PLL, 0x0F3, 15)
#define REG_OW_PHASE_ROTATOR      REGBITR(PLL, 0x0F3, 14, 8)
#define REG_PHASE_ROTATOR_FLIP_TX REGBITR(PLL, 0x0F3, 2)
#define REG_EN_40T_CLK_RX         REGBITR(PLL, 0x0F1, 3)
#define REG_TX_PU_ADC             REGBITR(PLL, 0x0F1, 2)
#define REG_TX_CLKCOMP            REGBITR(PLL, 0x0F1, 1)
#define REG_TX_CLKCOMPREG         REGBITR(PLL, 0x0F1, 0)
#define REG_PU_VDRV               REGBITR(PLL, 0x0EB, 13)
#define REG_TX_PLL_FRAC_N         REGBITR(PLL, 0x0D8, 15, 0)
#define REG_TX_PLL_LVCOCAP        REGBITR(PLL, 0x0DB, 14, 8)
#define REG_TX_PLL_FRAC_ORDER     REGBITR(PLL, 0x0D7, 15, 14)
#define REG_TX_PLL_FRAC_EN        REGBITR(PLL, 0x0D7, 13)

// Phoenix3 RX PLL
#define REG_RX_PU_PLL           REGBITR(PLL, 0x1FD, 0)
#define REG_RX_PU_BG            REGBITR(ANA, 0x1FF, 12)
#define REG_RX_PU_RVDD          REGBITR(PLL, 0x1FF, 11)
#define REG_RX_EN_RVDDVCO       REGBITR(PLL, 0x1FF, 10)
#define REG_RX_PU_RVDDLOOP      REGBITR(PLL, 0x1FF, 7)
#define REG_RX_PLL_DIV4         REGBITR(PLL, 0x1FF, 6)
#define REG_RX_PU_AGC_MA        REGBITR(PLL, 0x1FF, 5)
#define REG_RX_PU_REFCLKBUF     REGBITR(PLL, 0x1FF, 1)
#define REG_RX_PU_AGC_1_MA      REGBITR(PLL, 0x1FE, 15)
#define REG_RX_PU_AGCDL_MA      REGBITR(PLL, 0x1FE, 14)
#define REG_RX_PLL_N            REGBITR(PLL, 0x1FD, 15, 7)
#define REG_RX_PLL_LVCOCAP      REGBITR(PLL, 0x1F5, 15, 9)
#define REG_RX_PU_ADC_MA        REGBITR(PLL, 0x1F8, 15)
#define REG_RX_PU_CLKCOMPREG_MA REGBITR(PLL, 0x1F8, 14)
#define REG_RX_PU_ADC_1_MA      REGBITR(PLL, 0x1F8, 13)
#define REG_RX_PU_INTP_MA       REGBITR(PLL, 0x1F8, 9)
#define REG_RX_ACOMPVREG        REGBITR(PLL, 0x1F6, 6, 4)
#define REG_RX_PLL_DIV2         REGBITR(PLL, 0x1F5, 8)
#define REG_RX_PU_PLL_INTP      REGBITR(PLL, 0x1F3, 5)
#define REG_RX_PLL_FRAC_N       REGBITR(PLL, 0x1F1, 15, 0)
#define REG_RX_PLL_FRAC_ORDER   REGBITR(PLL, 0x1F0, 15, 14)
#define REG_RX_PLL_FRAC_EN      REGBITR(PLL, 0x1F0, 13)

// Phoenix3 RX analog front end
#define REG_RX_VER_ID_47_32 REGBITR(ANA, 0x0CC, 15, 0)
#define REG_RX_VER_ID_31_16 REGBITR(ANA, 0x0CB, 15, 0)
#define REG_RX_VER_ID_15_00 REGBITR(ANA, 0x0CA, 15, 0)

#define REG_RX_ACOMPNBS1 REGBITR(ANA, 0x0EE, 15, 13)

#define REG_RX_EDGE1 REGBITR(ANA, 0x0ED, 15, 12)
#define REG_RX_EDGE2 REGBITR(ANA, 0x0ED, 11, 8)
#define REG_RX_EDGE3 REGBITR(ANA, 0x0ED, 7, 4)
#define REG_RX_EDGE4 REGBITR(ANA, 0x0ED, 3, 0)
#define REG_RX_EDGE  REGBITR(ANA, 0x0ED, 15, 0)

#define REG_RX_PU_AGC        REGBITR(ANA, 0x1E7, 15)
#define REG_RX_PU_AGCDL      REGBITR(ANA, 0x1E7, 14)
#define REG_RX_EN_VCOMINBUF  REGBITR(ANA, 0x1E7, 11)
#define REG_RX_VAGCCOM       REGBITR(ANA, 0x1E7, 10, 8)
#define REG_RX_VAGCCOM2      REGBITR(ANA, 0x1E7, 7, 5)
#define REG_RX_VGAVDSAT      REGBITR(ANA, 0x1E6, 15, 12)
#define REG_RX_VREFAGCREG    REGBITR(ANA, 0x1E6, 5, 3)
#define REG_RX_VREF2AGCREG   REGBITR(ANA, 0x1E6, 2, 0)
#define REG_RX_VCOMREFSEL_EX REGBITR(ANA, 0x1DD, 9)
#define REG_RX_SKEF_EN       REGBITR(ANA, 0x1DD, 8)
#define REG_RX_SKEF_DEGEN    REGBITR(ANA, 0x1DD, 7, 5)
#define REG_RX_SKEF_ADDCAP   REGBITR(ANA, 0x1DD, 4, 2)
#define REG_RX_PU_INTP       REGBITR(ANA, 0x1DD, 1)
#define REG_RX_AGC_DEGEN     REGBITR(ANA, 0x1D7, 3, 2)
#define REG_RX_AGCGAIN1      REGBITR(ANA, 0x1D4, 15, 9)  // 7-BIT GRAY CODED
#define REG_RX_AGCGAIN2      REGBITR(ANA, 0x1D4, 8, 4)   // 5-BIT GRAY CODED
#define REG_RX_INPUT_MODE    REGBITR(ANA, 0x1E7, 11)

#define REG_RX_FFE_NBIAS_MAIN REGBITR(ANA, 0x1D6, 15, 12)
#define REG_RX_FFE_NBIAS_SUM  REGBITR(ANA, 0x1D6, 11, 8)

#define REG_RX_FFE_K3_MSB REGBITR(ANA, 0x1E4, 15, 12)
#define REG_RX_FFE_K3_LSB REGBITR(ANA, 0x1E4, 11, 8)
#define REG_RX_FFE_K4_MSB REGBITR(ANA, 0x1E4, 7, 4)
#define REG_RX_FFE_K4_LSB REGBITR(ANA, 0x1E4, 3, 0)

#define REG_RX_FFE_K2_MSB REGBITR(ANA, 0x1E3, 15, 12)
#define REG_RX_FFE_K2_LSB REGBITR(ANA, 0x1E3, 11, 8)
#define REG_RX_FFE_S2_MSB REGBITR(ANA, 0x1E3, 7, 4)
#define REG_RX_FFE_S2_LSB REGBITR(ANA, 0x1E3, 3, 0)

#define REG_RX_FFE_K1_MSB REGBITR(ANA, 0x1E2, 15, 12)
#define REG_RX_FFE_K1_LSB REGBITR(ANA, 0x1E2, 11, 8)
#define REG_RX_FFE_S1_MSB REGBITR(ANA, 0x1E2, 7, 4)
#define REG_RX_FFE_S1_LSB REGBITR(ANA, 0x1E2, 3, 0)

#define REG_RX_FFE_SF_MSB REGBITR(ANA, 0x1E1, 15, 12)
#define REG_RX_FFE_SF_LSB REGBITR(ANA, 0x1E1, 7, 4)

#define REG_RX_FFE_K4_PU REGBITR(ANA, 0x1E0, 15)
#define REG_RX_FFE_K3_PU REGBITR(ANA, 0x1E0, 14)
#define REG_RX_FFE_K2_PU REGBITR(ANA, 0x1E0, 13)
#define REG_RX_FFE_K1_PU REGBITR(ANA, 0x1E0, 12)
#define REG_RX_FFE_S2_PU REGBITR(ANA, 0x1E0, 11)
#define REG_RX_FFE_S1_PU REGBITR(ANA, 0x1E0, 10)

#define REG_RX_FFE_POL1 REGBITR(ANA, 0x1E0, 9)
#define REG_RX_FFE_POL2 REGBITR(ANA, 0x1E0, 8)
#define REG_RX_FFE_POL3 REGBITR(ANA, 0x1E0, 7)
#define REG_RX_FFE_POL4 REGBITR(ANA, 0x1E0, 6)
// Phoenix + Eagle tx digital top (00A0-00B4)
#define REG_TX_PATTERN           REGBITR(TX, 0x0A0, 15)
#define REG_TX_PRBS_GENERATOR_EN REGBITR(TX, 0x0A0, 14)
#define REG_TX_TEST_PATT_EN      REGBITR(TX, 0x0A0, 13)
#define REG_TX_PRBS_EN           REGBITR(TX, 0x0A0, 11)
#define REG_TX_PRBS_1B_ERR       REGBITR(TX, 0x0A0, 10)
#define REG_TX_PRBS_PATT_SEL \
    REGBITR(TX, 0x0A0, 9, 8)  // NRZ:00=CR_PRBS9, 01=CR_PRBS15, 10=CR_PRBS23, 11=CR_PRBS31 # PAM4:00=CR_PRBS9,
                              // 01=CR_PRBS13, 10=CR_PRBS15, 11=CR_PRBS31
#define REG_TX_POL               REGBITR(TX, 0x0A0, 5)  // ANALOG OUTPUT FLIP
#define REG_TX_COEF_KR_TRAINING  REGBITR(TX, 0x0A0, 4)
#define REG_TX_PATT_MODE         REGBITR(TX, 0x0A0, 3, 2)
#define REG_TX_PATTERN_MEM_63_48 REGBITR(TX, 0x0A1, 15, 0)
#define REG_TX_PATTERN_MEM_47_32 REGBITR(TX, 0x0A2, 15, 0)
#define REG_TX_PATTERN_MEM_31_16 REGBITR(TX, 0x0A3, 15, 0)
#define REG_TX_PATTERN_MEM_15_00 REGBITR(TX, 0x0A4, 15, 0)
#define REG_TX_TAP1              REGBITR(TX, 0x0A5, 15, 8)
#define REG_TX_TAP2              REGBITR(TX, 0x0A7, 15, 8)
#define REG_TX_TAP3              REGBITR(TX, 0x0A9, 15, 8)
#define REG_TX_TAP4              REGBITR(TX, 0x0AB, 15, 8)
#define REG_TX_TAP5              REGBITR(TX, 0x0AD, 15, 8)
#define REG_TX_TAP6              REGBITR(TX, 0x0B1, 15, 12)
#define REG_TX_TAP7              REGBITR(TX, 0x0B1, 11, 8)
#define REG_TX_TAP8              REGBITR(TX, 0x0B1, 7, 4)
#define REG_TX_TAP9              REGBITR(TX, 0x0B1, 3, 0)
#define REG_TX_TAP10             REGBITR(TX, 0x0B2, 15, 12)
#define REG_TX_TAP11             REGBITR(TX, 0x0B2, 11, 8)
#define REG_TX_KR_TAP1           REGBITR(TX, 0x0B4, 5, 0)
#define REG_TX_KR_TAP2           REGBITR(TX, 0x0B4, 13, 8)
#define REG_TX_KR_TAP3           REGBITR(TX, 0x0B3, 5, 0)
#define REG_TX_KR_TAP4           REGBITR(TX, 0x0B3, 13, 8)
#define REG_TX_TAPS_SUM_LIMIT    31.5
#define REG_TX_MSB_SWAP          REGBITR(TX, 0x0AF, 10)
#define REG_TX_GRAY_EN           REGBITR(TX, 0x0AF, 9)
#define REG_TX_PRECODER_EN       REGBITR(TX, 0x0AF, 8)
#define REG_TX_TAPS_HF           REGBITR(TX, 0x0AF, 5, 1)
#define REG_TX_PRBS_1B_ERR_NRZ   REGBITR(TX, 0x0B0, 10)
#define REG_TX_PRBS_CLK_EN_NRZ   REGBITR(TX, 0x0B0, 14)
#define REG_TX_PRBS_EN_NRZ       REGBITR(TX, 0x0B0, 11)
#define REG_TX_NRZ_MODE          REGBITR(TX, 0x0B0, 1)
#define REG_TX_MODE10G_EN        REGBITR(TX, 0x0B0, 0)

#endif
