/*
 *         
 * $Id:$
 * 
 * $Copyright: (c) 2013 Broadcom Corp. All Rights Reserved.$
 *         
 *     
 * DO NOT EDIT THIS FILE!
 *
 */

#ifndef _APERTA2_PM8X100_GEN2_H__H_
#define _APERTA2_PM8X100_GEN2_H__H_

#include <phymod/phymod.h>
#include <phymod/phymod_diagnostics.h>
#include <phymod/phymod_reg.h>
#include <include/portmod_defs.h>
#include <include/portmod_internal.h>
/**/
int plp_aperta2_pm8x100_gen2_port_speed_ability_local_get(int unit, int port, pm_info_t pm_info, int max_num_abilities, portmod_port_speed_ability_t* abilities, int* num_abilities);

/*Get whether the inerface type is supported by PM */
int plp_aperta2_pm8x100_gen2_pm_interface_type_is_supported(int unit, soc_port_if_t interface, int* is_supported);

/*Add new pm.*/
int plp_aperta2_pm8x100_gen2_pm_init(int unit, const portmod_pm_create_info_internal_t* pm_add_info, int wb_buffer_index, pm_info_t pm_info);

/*Release PM resources*/
int plp_aperta2_pm8x100_gen2_pm_destroy(int unit, pm_info_t pm_info);

/*Add new port*/
int plp_aperta2_pm8x100_gen2_port_attach(int unit, int port, pm_info_t pm_info, const portmod_port_add_info_t* add_info);

/*get port cores' phymod access*/
int plp_aperta2_pm8x100_gen2_pm_core_info_get(int unit, pm_info_t pm_info, int phyn, portmod_pm_core_info_t* core_info);

/*Get PM phys.*/
int plp_aperta2_pm8x100_gen2_pm_phys_get(int unit, pm_info_t pm_info, portmod_pbmp_t* phys);

/*Port remove in PM level*/
int plp_aperta2_pm8x100_gen2_port_detach(int unit, int port, pm_info_t pm_info);

/*Port replace in PM level*/
int plp_aperta2_pm8x100_gen2_port_replace(int unit, int port, pm_info_t pm_info, int new_port);

/*Port enable*/
int plp_aperta2_pm8x100_gen2_port_enable_set(int unit, int port, pm_info_t pm_info, int flags, int enable);
int plp_aperta2_pm8x100_gen2_port_enable_get(int unit, int port, pm_info_t pm_info, int flags, int* enable);

/*Port cl72 set\get*/
int plp_aperta2_pm8x100_gen2_port_cl72_set(int unit, int port, pm_info_t pm_info, uint32 enable);
int plp_aperta2_pm8x100_gen2_port_cl72_get(int unit, int port, pm_info_t pm_info, uint32* enable);

/*Get port cl72 status*/
int plp_aperta2_pm8x100_gen2_port_cl72_status_get(int unit, int port, pm_info_t pm_info, plp_aperta2_phymod_cl72_status_t* status);

/*Port loopback set\get*/
int plp_aperta2_pm8x100_gen2_port_loopback_set(int unit, int port, pm_info_t pm_info, portmod_loopback_mode_t loopback_type, int enable);
int plp_aperta2_pm8x100_gen2_port_loopback_get(int unit, int port, pm_info_t pm_info, portmod_loopback_mode_t loopback_type, int* enable);

/*Port RX MAC ENABLE set\get*/
int plp_aperta2_pm8x100_gen2_port_rx_mac_enable_set(int unit, int port, pm_info_t pm_info, int enable);
int plp_aperta2_pm8x100_gen2_port_rx_mac_enable_get(int unit, int port, pm_info_t pm_info, int* enable);

/*Port TX MAC ENABLE set\get*/
int plp_aperta2_pm8x100_gen2_port_tx_mac_enable_set(int unit, int port, pm_info_t pm_info, int enable);
int plp_aperta2_pm8x100_gen2_port_tx_mac_enable_get(int unit, int port, pm_info_t pm_info, int* enable);

/*Set\Get autoneg*/
int plp_aperta2_pm8x100_gen2_port_autoneg_set(int unit, int port, pm_info_t pm_info, uint32 phy_flags, const plp_aperta2_phymod_autoneg_control_t* an);
int plp_aperta2_pm8x100_gen2_port_autoneg_get(int unit, int port, pm_info_t pm_info, uint32 phy_flags, plp_aperta2_phymod_autoneg_control_t* an);

/*Get autoneg status*/
int plp_aperta2_pm8x100_gen2_port_autoneg_status_get(int unit, int port, pm_info_t pm_info, plp_aperta2_phymod_autoneg_status_t* an_status);

/*PRBS configuration set/get*/
int plp_aperta2_pm8x100_gen2_port_prbs_config_set(int unit, int port, pm_info_t pm_info, portmod_prbs_mode_t mode, int flags, const plp_aperta2_phymod_prbs_t* config);
int plp_aperta2_pm8x100_gen2_port_prbs_config_get(int unit, int port, pm_info_t pm_info, portmod_prbs_mode_t mode, int flags, plp_aperta2_phymod_prbs_t* config);

/*PRBS enable set/get*/
int plp_aperta2_pm8x100_gen2_port_prbs_enable_set(int unit, int port, pm_info_t pm_info, portmod_prbs_mode_t mode, int flags, int enable);
int plp_aperta2_pm8x100_gen2_port_prbs_enable_get(int unit, int port, pm_info_t pm_info, portmod_prbs_mode_t mode, int flags, int* enable);

/*PRBS status get*/
int plp_aperta2_pm8x100_gen2_port_prbs_status_get(int unit, int port, pm_info_t pm_info, portmod_prbs_mode_t mode, int flags, plp_aperta2_phymod_prbs_status_t* status);

/*Number of lanes get*/
int plp_aperta2_pm8x100_gen2_port_nof_lanes_get(int unit, int port, pm_info_t pm_info, int* nof_lanes);

/*Filter packets smaller than the specified threshold*/
int plp_aperta2_pm8x100_gen2_port_runt_threshold_set(int unit, int port, pm_info_t pm_info, int value);
int plp_aperta2_pm8x100_gen2_port_runt_threshold_get(int unit, int port, pm_info_t pm_info, int* value);

/*Configure TX threshold*/
int plp_aperta2_pm8x100_gen2_port_tx_threshold_set(int unit, int port, pm_info_t pm_info, int value);
int plp_aperta2_pm8x100_gen2_port_tx_threshold_get(int unit, int port, pm_info_t pm_info, int* value);

/*Filter packets bigger than the specified value*/
int plp_aperta2_pm8x100_gen2_port_max_packet_size_set(int unit, int port, pm_info_t pm_info, int value);
int plp_aperta2_pm8x100_gen2_port_max_packet_size_get(int unit, int port, pm_info_t pm_info, int* value);

/*set/get the MAC source address that will be sent in case of Pause/LLFC*/
int plp_aperta2_pm8x100_gen2_port_tx_mac_sa_set(int unit, int port, pm_info_t pm_info, pm_mac_addr_t mac_sa);
int plp_aperta2_pm8x100_gen2_port_tx_mac_sa_get(int unit, int port, pm_info_t pm_info, pm_mac_addr_t mac_sa);

/*set/get SA recognized for MAC control packets in addition to the standard 0x0180C2000001*/
int plp_aperta2_pm8x100_gen2_port_rx_mac_sa_set(int unit, int port, pm_info_t pm_info, pm_mac_addr_t mac_sa);
int plp_aperta2_pm8x100_gen2_port_rx_mac_sa_get(int unit, int port, pm_info_t pm_info, pm_mac_addr_t mac_sa);

/*set/get Average inter-packet gap*/
int plp_aperta2_pm8x100_gen2_port_tx_average_ipg_set(int unit, int port, pm_info_t pm_info, int value);
int plp_aperta2_pm8x100_gen2_port_tx_average_ipg_get(int unit, int port, pm_info_t pm_info, int* value);

/*local fault set/get*/
int plp_aperta2_pm8x100_gen2_port_local_fault_control_set(int unit, int port, pm_info_t pm_info, const portmod_local_fault_control_t* control);
int plp_aperta2_pm8x100_gen2_port_local_fault_control_get(int unit, int port, pm_info_t pm_info, portmod_local_fault_control_t* control);

/*remote fault set/get*/
int plp_aperta2_pm8x100_gen2_port_remote_fault_control_set(int unit, int port, pm_info_t pm_info, const portmod_remote_fault_control_t* control);
int plp_aperta2_pm8x100_gen2_port_remote_fault_control_get(int unit, int port, pm_info_t pm_info, portmod_remote_fault_control_t* control);

/*local fault status get*/
int plp_aperta2_pm8x100_gen2_port_local_fault_status_get(int unit, int port, pm_info_t pm_info, int* value);

/*remote fault status get*/
int plp_aperta2_pm8x100_gen2_port_remote_fault_status_get(int unit, int port, pm_info_t pm_info, int* value);

/*local fault status clear*/
int plp_aperta2_pm8x100_gen2_port_local_fault_status_clear(int unit, int port, pm_info_t pm_info);

/*remote fault status clear*/
int plp_aperta2_pm8x100_gen2_port_remote_fault_status_clear(int unit, int port, pm_info_t pm_info);

/*force remote fault indication*/
int plp_aperta2_pm8x100_gen2_port_remote_fault_force_set(int unit, int port, pm_info_t pm_info, int enable);
int plp_aperta2_pm8x100_gen2_port_remote_fault_force_get(int unit, int port, pm_info_t pm_info, int* enable);

/*force local fault indication*/
int plp_aperta2_pm8x100_gen2_port_local_fault_force_set(int unit, int port, pm_info_t pm_info, int enable);
int plp_aperta2_pm8x100_gen2_port_local_fault_force_get(int unit, int port, pm_info_t pm_info, int* enable);

/*local fault reasons get*/
int plp_aperta2_pm8x100_gen2_port_local_fault_reasons_get(int unit, int port, pm_info_t pm_info, uint32* local_fault_reasons);

/*set/get Pause FC configuration*/
int plp_aperta2_pm8x100_gen2_port_pause_control_set(int unit, int port, pm_info_t pm_info, const portmod_pause_control_t* control);
int plp_aperta2_pm8x100_gen2_port_pause_control_get(int unit, int port, pm_info_t pm_info, portmod_pause_control_t* control);

/*set/get PFC FC configuration*/
int plp_aperta2_pm8x100_gen2_port_pfc_control_set(int unit, int port, pm_info_t pm_info, const portmod_pfc_control_t* control);
int plp_aperta2_pm8x100_gen2_port_pfc_control_get(int unit, int port, pm_info_t pm_info, portmod_pfc_control_t* control);

/*get port cores' phymod access*/
int plp_aperta2_pm8x100_gen2_port_core_access_get(int unit, int port, pm_info_t pm_info, int phyn, int max_cores, plp_aperta2_phymod_core_access_t* core_access_arr, int* nof_cores, int* is_most_ext);

/*Get lane phymod access structure. can be used for per lane operations*/
int plp_aperta2_pm8x100_gen2_port_phy_lane_access_get(int unit, int port, pm_info_t pm_info, const portmod_access_get_params_t* params, int max_phys, plp_aperta2_phymod_phy_access_t* access, int* nof_phys, int* is_most_ext);

/*Port PHY Control register read*/
int plp_aperta2_pm8x100_gen2_port_phy_reg_read(int unit, int port, pm_info_t pm_info, int lane, int flags, int reg_addr, uint32* value);

/*Port PHY Control register write*/
int plp_aperta2_pm8x100_gen2_port_phy_reg_write(int unit, int port, pm_info_t pm_info, int lane, int flags, int reg_addr, uint32 value);

/*Port Reset set\get*/
int plp_aperta2_pm8x100_gen2_port_reset_set(int unit, int port, pm_info_t pm_info, int mode, int opcode, int value);
int plp_aperta2_pm8x100_gen2_port_reset_get(int unit, int port, pm_info_t pm_info, int mode, int opcode, int* value);

/*Drv Name Get*/
int plp_aperta2_pm8x100_gen2_port_drv_name_get(int unit, int port, pm_info_t pm_info, char* name, int len);

/*set/get port fec enable according to local/remote FEC ability*/
int plp_aperta2_pm8x100_gen2_port_fec_enable_set(int unit, int port, pm_info_t pm_info, uint32 phy_flags, uint32_t enable);
int plp_aperta2_pm8x100_gen2_port_fec_enable_get(int unit, int port, pm_info_t pm_info, uint32 phy_flags, uint32_t* enable);

/*set/get pass control frames.*/
int plp_aperta2_pm8x100_gen2_port_rx_control_set(int unit, int port, pm_info_t pm_info, const portmod_rx_control_t* rx_ctrl);
int plp_aperta2_pm8x100_gen2_port_rx_control_get(int unit, int port, pm_info_t pm_info, portmod_rx_control_t* rx_ctrl);

/*set PFC config registers.*/
int plp_aperta2_pm8x100_gen2_port_pfc_config_set(int unit, int port, pm_info_t pm_info, const portmod_pfc_config_t* pfc_cfg);
int plp_aperta2_pm8x100_gen2_port_pfc_config_get(int unit, int port, pm_info_t pm_info, portmod_pfc_config_t* pfc_cfg);

/*set Vlan Inner/Outer tag.*/
int plp_aperta2_pm8x100_gen2_port_vlan_tag_set(int unit, int port, pm_info_t pm_info, const portmod_vlan_tag_t* vlan_tag);
int plp_aperta2_pm8x100_gen2_port_vlan_tag_get(int unit, int port, pm_info_t pm_info, portmod_vlan_tag_t* vlan_tag);

/*set port mode.*/
int plp_aperta2_pm8x100_gen2_port_mode_set(int unit, int port, pm_info_t pm_info, const portmod_port_mode_info_t* mode);
int plp_aperta2_pm8x100_gen2_port_mode_get(int unit, int port, pm_info_t pm_info, portmod_port_mode_info_t* mode);

/*set port encap.*/
int plp_aperta2_pm8x100_gen2_port_encap_set(int unit, int port, pm_info_t pm_info, int flags, portmod_encap_t encap);
int plp_aperta2_pm8x100_gen2_port_encap_get(int unit, int port, pm_info_t pm_info, int* flags, portmod_encap_t* encap);

/*port diagnostics control.*/
int plp_aperta2_pm8x100_gen2_port_diag_ctrl(int unit, int port, pm_info_t pm_info, uint32 inst, int op_type, int op_cmd, const void* arg);

/*Disable lag failover.*/
int plp_aperta2_pm8x100_gen2_port_cntmaxsize_set(int unit, int port, pm_info_t pm_info, int val);
int plp_aperta2_pm8x100_gen2_port_cntmaxsize_get(int unit, int port, pm_info_t pm_info, int* val);

/*Get Info needed to restore after drain cells.*/
int plp_aperta2_pm8x100_gen2_port_drain_cell_get(int unit, int port, pm_info_t pm_info, portmod_drain_cells_t* drain_cells);

/*Restore informaation after drain cells.*/
int plp_aperta2_pm8x100_gen2_port_drain_cell_stop(int unit, int port, pm_info_t pm_info, const portmod_drain_cells_t* drain_cells);

/*Restore informaation after drain cells.*/
int plp_aperta2_pm8x100_gen2_port_drain_cell_start(int unit, int port, pm_info_t pm_info);

/**/
int plp_aperta2_pm8x100_gen2_port_drain_cells_rx_enable(int unit, int port, pm_info_t pm_info, int rx_en);

/**/
int plp_aperta2_pm8x100_gen2_port_egress_queue_drain_rx_en(int unit, int port, pm_info_t pm_info, int rx_en);

/**/
int plp_aperta2_pm8x100_gen2_port_mac_ctrl_set(int unit, int port, pm_info_t pm_info, uint64_t ctrl);

/**/
int plp_aperta2_pm8x100_gen2_port_txfifo_cell_cnt_get(int unit, int port, pm_info_t pm_info, uint32* cnt);

/**/
int plp_aperta2_pm8x100_gen2_port_egress_queue_drain_get(int unit, int port, pm_info_t pm_info, uint64_t* ctrl, int* rxen);

/*Set/get port mac reset */
int plp_aperta2_pm8x100_gen2_port_mac_reset_set(int unit, int port, pm_info_t pm_info, int val);
int plp_aperta2_pm8x100_gen2_port_mac_reset_get(int unit, int port, pm_info_t pm_info, int* val);

/*Check if MAC needs to be reset.*/
int plp_aperta2_pm8x100_gen2_port_mac_reset_check(int unit, int port, pm_info_t pm_info, int enable, int* reset);

/*get the speed for the specified port*/
int plp_aperta2_pm8x100_gen2_port_speed_get(int unit, int port, pm_info_t pm_info, int* speed);

/*Port discard set*/
int plp_aperta2_pm8x100_gen2_port_discard_set(int unit, int port, pm_info_t pm_info, int discard);

/*Port tx_en=0 and softreset mac*/
int plp_aperta2_pm8x100_gen2_port_tx_down(int unit, int port, pm_info_t pm_info);

/*"port control phy timesync config set/get"*/
int plp_aperta2_pm8x100_gen2_port_control_phy_timesync_set(int unit, int port, pm_info_t pm_info, portmod_port_control_phy_timesync_t config, uint64_t value);
int plp_aperta2_pm8x100_gen2_port_control_phy_timesync_get(int unit, int port, pm_info_t pm_info, portmod_port_control_phy_timesync_t config, uint64_t* value);

/*"port timesync config set/get"*/
int plp_aperta2_pm8x100_gen2_port_timesync_config_set(int unit, int port, pm_info_t pm_info, const portmod_phy_timesync_config_t* config);
int plp_aperta2_pm8x100_gen2_port_timesync_config_get(int unit, int port, pm_info_t pm_info, portmod_phy_timesync_config_t* config);

/*set/get interrupt enable value. */
int plp_aperta2_pm8x100_gen2_port_interrupt_enable_set(int unit, int port, pm_info_t pm_info, int intr_type, uint32 val);
int plp_aperta2_pm8x100_gen2_port_interrupt_enable_get(int unit, int port, pm_info_t pm_info, int intr_type, uint32* val);

/*get interrupt status value. */
int plp_aperta2_pm8x100_gen2_port_interrupt_get(int unit, int port, pm_info_t pm_info, int intr_type, uint32* val);

/*get interrupt value array. */
int plp_aperta2_pm8x100_gen2_port_interrupts_get(int unit, int port, pm_info_t pm_info, int arr_max_size, uint32* intr_arr, uint32* size);

/* portmod port rsv mask set*/
int plp_aperta2_pm8x100_gen2_port_mac_rsv_mask_set(int unit, int port, pm_info_t pm_info, uint32 rsv_mask);

/*override function for board lane swap. */
int plp_aperta2_pm8x100_gen2_port_lane_map_set(int unit, int port, pm_info_t pm_info, uint32 flags, const plp_aperta2_phymod_lane_map_t* lane_map);
int plp_aperta2_pm8x100_gen2_port_lane_map_get(int unit, int port, pm_info_t pm_info, uint32 flags, plp_aperta2_phymod_lane_map_t* lane_map);

/*Get timestamp and sequence id of tx 1588 packet.*/
int plp_aperta2_pm8x100_gen2_port_timesync_tx_info_get(int unit, int port, pm_info_t pm_info, portmod_fifo_status_t* tx_info);

/*PM Core init routine for DNX devices; XGS does not call this API but calls plp_aperta2_portmod_pm_serdes_core_init() directly*/
int plp_aperta2_pm8x100_gen2_core_add(int unit, int pm_id, pm_info_t pm_info, int flags, const portmod_port_add_info_t* add_info);

/*PM Core init routine*/
int plp_aperta2_pm8x100_gen2_pm_serdes_core_init(int unit, int pm_id, pm_info_t pm_info, const portmod_port_add_info_t* add_info);

/*Returns if the PortMacro associated with the port is initialized or not*/
int plp_aperta2_pm8x100_gen2_pm_is_initialized(int unit, int pm_id, pm_info_t pm_info, int* is_initialized);

/*Port speed validation.*/
int plp_aperta2_pm8x100_gen2_port_speed_config_validate(int unit, int port, pm_info_t pm_info, const portmod_speed_config_t* speed_config, portmod_pbmp_t* affected_pbmp);

/*Enable port macro.*/
int plp_aperta2_pm8x100_gen2_pm_enable(int unit, int pm_id, pm_info_t pm_info, int flags, int enable);

/*Get the logical port bitmap based on the input PM ID*/
int plp_aperta2_pm8x100_gen2_pm_logical_pbmp_get(int unit, int pm_id, pm_info_t pm_info, portmod_pbmp_t* logical_pbmp);

/*Reconfigure the vco rate for pm core.*/
int plp_aperta2_pm8x100_gen2_pm_vco_reconfig(int unit, int pm_id, pm_info_t pm_info, const portmod_vco_type_t* vco);

/* set/get the speed config for the specified port.*/
int plp_aperta2_pm8x100_gen2_port_speed_config_set(int unit, int port, pm_info_t pm_info, const portmod_speed_config_t* speed_config);
int plp_aperta2_pm8x100_gen2_port_speed_config_get(int unit, int port, pm_info_t pm_info, portmod_speed_config_t* speed_config);

/*Validate a set of speed config within a port macro.*/
int plp_aperta2_pm8x100_gen2_pm_speed_config_validate(int unit, int pm_id, pm_info_t pm_info, const portmod_pbmp_t* ports, int flag, portmod_pm_vco_setting_t* vco_setting);

/*Get the suggested VCO values based on the speed config list of a PM*/
int plp_aperta2_pm8x100_gen2_pm_vcos_get(int unit, portmod_dispatch_type_t pm_type, uint32 flags, portmod_pm_vco_setting_t* vco_select);

/*Set/get port auto negotiation ability*/
int plp_aperta2_pm8x100_gen2_port_autoneg_ability_advert_set(int unit, int port, pm_info_t pm_info, int num_abilities, const portmod_port_speed_ability_t* abilities);
int plp_aperta2_pm8x100_gen2_port_autoneg_ability_advert_get(int unit, int port, pm_info_t pm_info, int max_num_abilities, portmod_port_speed_ability_t* abilities, int* actual_num_abilities);

/*Port ability remote Adv get*/
int plp_aperta2_pm8x100_gen2_port_autoneg_ability_remote_get(int unit, int port, pm_info_t pm_info, int max_num_abilities, portmod_port_speed_ability_t* abilities, int* actual_num_abilities);

/*Port tx taps set\get*/
int plp_aperta2_pm8x100_gen2_port_tx_set(int unit, int port, pm_info_t pm_info, const plp_aperta2_phymod_tx_t* tx);
int plp_aperta2_pm8x100_gen2_port_tx_get(int unit, int port, pm_info_t pm_info, plp_aperta2_phymod_tx_t* tx);

/*Port SyncE clock control config*/
int plp_aperta2_pm8x100_gen2_port_synce_clk_ctrl_set(int unit, int port, pm_info_t pm_info, const portmod_port_synce_clk_ctrl_t* cfg);
int plp_aperta2_pm8x100_gen2_port_synce_clk_ctrl_get(int unit, int port, pm_info_t pm_info, portmod_port_synce_clk_ctrl_t* cfg);

/*Process PM interrupts.*/
int plp_aperta2_pm8x100_gen2_pm_interrupt_process(int unit, int pm_id, pm_info_t pm_info, portmod_ecc_intr_info_t* ecc_err_info);

/* Enable port MAC settings. This function sets MAC rx enable and soft reset.
                  This should only be invoked during fast reboot,
                  where the application layer do not wait to drain
                  the packets on a port and should not be called
                  during normal operation.*/
int plp_aperta2_pm8x100_gen2_port_mac_enable_set(int unit, int port, pm_info_t pm_info, int enable);

/*Control one time fec error injection.*/
int plp_aperta2_pm8x100_gen2_port_fec_error_inject_set(int unit, int port, pm_info_t pm_info, uint16 error_control_map, portmod_fec_error_mask_t bit_error_mask);
int plp_aperta2_pm8x100_gen2_port_fec_error_inject_get(int unit, int port, pm_info_t pm_info, uint16* error_control_map, portmod_fec_error_mask_t* bit_error_mask);

/*Local and Remote faults status get*/
int plp_aperta2_pm8x100_gen2_port_faults_status_get(int unit, int port, pm_info_t pm_info, portmod_port_fault_status_t* faults);

/*PMD RX lock status get*/
int plp_aperta2_pm8x100_gen2_port_pmd_rx_lock_status_get(int unit, int port, pm_info_t pm_info, uint32* pmd_lock, uint32* pmd_lock_change);

int _plp_aperta2_pm8x100_gen2_port_phy_to_port_ability(phymod_autoneg_advert_abilities_t* an_advert_abilities,
                                           int* num_abilities,
                                           portmod_port_speed_ability_t* abilities);
int _plp_aperta2_pm8x100_gen2_port_port_to_phy_ability(int num_abilities,
                                           const portmod_port_speed_ability_t* abilities,
                                           phymod_autoneg_advert_abilities_t* an_advert_abilities);


#define aperta2_PM8x100_GEN2_SPEED_ID_TABLE_STATUS_NOT_LOADED             0
#define aperta2_PM8x100_GEN2_SPEED_ID_TABLE_STATUS_IEEE_MODE_LOADED       1
#define aperta2_PM8x100_GEN2_SPEED_ID_TABLE_STATUS_HG3_MODE_LOADED        2

#endif /*_APERTA2_PM8X100_GEN2_H_*/
