/*
 *         
 * $Id: phymod.xml,v 1.1.2.5 Broadcom SDK $
 * 
 * $Copyright: (c) 2020 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *         
 *     
 * DO NOT EDIT THIS FILE!
 *
 */

#ifndef _plp_aperta_PHYMOD_DIAGNOSTICS_DISPATCH_H__H_
#define _plp_aperta_PHYMOD_DIAGNOSTICS_DISPATCH_H__H_

#include <phymod/phymod_definitions.h>
#include <phymod/phymod_diagnostics.h>

typedef int (*__dispatch__phymod_phy_rx_slicer_position_set_f)(const plp_aperta_phymod_phy_access_t* phy, uint32_t flags, const plp_aperta_phymod_slicer_position_t* position);
typedef int (*__dispatch__phymod_phy_rx_slicer_position_get_f)(const plp_aperta_phymod_phy_access_t* phy, uint32_t flags, plp_aperta_phymod_slicer_position_t* position);
typedef int (*__dispatch__phymod_phy_rx_slicer_position_max_get_f)(const plp_aperta_phymod_phy_access_t* phy, uint32_t flags, const plp_aperta_phymod_slicer_position_t* position_min, const plp_aperta_phymod_slicer_position_t* position_max);
typedef int (*__dispatch__phymod_phy_prbs_config_set_f)(const plp_aperta_phymod_phy_access_t* phy, uint32_t flags , const plp_aperta_phymod_prbs_t* prbs);
typedef int (*__dispatch__phymod_phy_prbs_config_get_f)(const plp_aperta_phymod_phy_access_t* phy, uint32_t flags , plp_aperta_phymod_prbs_t* prbs);
typedef int (*__dispatch__phymod_phy_prbs_enable_set_f)(const plp_aperta_phymod_phy_access_t* phy, uint32_t flags , uint32_t enable);
typedef int (*__dispatch__phymod_phy_prbs_enable_get_f)(const plp_aperta_phymod_phy_access_t* phy, uint32_t flags , uint32_t* enable);
typedef int (*__dispatch__phymod_phy_prbs_status_get_f)(const plp_aperta_phymod_phy_access_t* phy, uint32_t flags, plp_aperta_phymod_prbs_status_t* prbs_status);
typedef int (*__dispatch__phymod_phy_pattern_config_set_f)(const plp_aperta_phymod_phy_access_t* phy, const plp_aperta_phymod_pattern_t* pattern);
typedef int (*__dispatch__phymod_phy_pattern_config_get_f)(const plp_aperta_phymod_phy_access_t* phy, plp_aperta_phymod_pattern_t* pattern);
typedef int (*__dispatch__phymod_phy_pattern_enable_set_f)(const plp_aperta_phymod_phy_access_t* phy, uint32_t enable, const plp_aperta_phymod_pattern_t* pattern);
typedef int (*__dispatch__phymod_phy_pattern_enable_get_f)(const plp_aperta_phymod_phy_access_t* phy, uint32_t* enable, const plp_aperta_phymod_pattern_t* pattern);
typedef int (*__dispatch__phymod_core_diagnostics_get_f)(const plp_aperta_phymod_core_access_t* core, plp_aperta_phymod_core_diagnostics_t* diag);
typedef int (*__dispatch__phymod_phy_diagnostics_get_f)(const plp_aperta_phymod_phy_access_t* phy, plp_aperta_phymod_phy_diagnostics_t* diag);
typedef int (*__dispatch__phymod_phy_pam4_diagnostics_get_f)(const plp_aperta_phymod_phy_access_t* phy, phymod_phy_pam4_diagnostics_t* diag);
typedef int (*__dispatch__phymod_phy_pmd_info_dump_f)(const plp_aperta_phymod_phy_access_t* phy, char* type);
typedef int (*__dispatch__phymod_phy_pcs_info_dump_f)(const plp_aperta_phymod_phy_access_t* phy, char* type);
typedef int (*__dispatch__phymod_phy_eyescan_run_f)(const plp_aperta_phymod_phy_access_t* phy, uint32_t flags, plp_aperta_phymod_eyescan_mode_t mode, const plp_aperta_phymod_phy_eyescan_options_t* eyescan_options);
typedef int (*__dispatch__phymod_phy_link_mon_enable_set_f)(const plp_aperta_phymod_phy_access_t* phy, plp_aperta_phymod_link_monitor_mode_t link_mon_mode, uint32_t enable);
typedef int (*__dispatch__phymod_phy_link_mon_enable_get_f)(const plp_aperta_phymod_phy_access_t* phy, plp_aperta_phymod_link_monitor_mode_t link_mon_mode, uint32_t* enable);
typedef int (*__dispatch__phymod_phy_link_mon_status_get_f)(const plp_aperta_phymod_phy_access_t* phy, uint32_t* lock_status, uint32_t* lock_lost_lh, uint32_t* error_count);
typedef int (*__dispatch__phymod_phy_fec_correctable_counter_get_f)(const plp_aperta_phymod_phy_access_t* phy, phymod_fec_type_t fec_type, uint32_t* count);
typedef int (*__dispatch__phymod_phy_fec_uncorrectable_counter_get_f)(const plp_aperta_phymod_phy_access_t* phy, phymod_fec_type_t fec_type, uint32_t* count);
typedef int (*__dispatch__phymod_phy_prbs_error_inject_set_f)(const plp_aperta_phymod_phy_access_t* phy, phymod_prbs_error_inject_t prbs_error_inject);
typedef int (*__dispatch__phymod_phy_prbs_error_analyzer_proj_f)(const plp_aperta_phymod_phy_access_t* phy, uint16_t prbs_error_fec_size, uint8_t hist_errcnt_thresh, uint32_t timeout_s);

typedef struct __phymod_diagnostics__dispatch__s__ {
    __dispatch__phymod_phy_rx_slicer_position_set_f                                  f_phymod_phy_rx_slicer_position_set;
    __dispatch__phymod_phy_rx_slicer_position_get_f                                  f_phymod_phy_rx_slicer_position_get;
    __dispatch__phymod_phy_rx_slicer_position_max_get_f                              f_phymod_phy_rx_slicer_position_max_get;
    __dispatch__phymod_phy_prbs_config_set_f                                         f_phymod_phy_prbs_config_set;
    __dispatch__phymod_phy_prbs_config_get_f                                         f_phymod_phy_prbs_config_get;
    __dispatch__phymod_phy_prbs_enable_set_f                                         f_phymod_phy_prbs_enable_set;
    __dispatch__phymod_phy_prbs_enable_get_f                                         f_phymod_phy_prbs_enable_get;
    __dispatch__phymod_phy_prbs_status_get_f                                         f_phymod_phy_prbs_status_get;
    __dispatch__phymod_phy_pattern_config_set_f                                      f_phymod_phy_pattern_config_set;
    __dispatch__phymod_phy_pattern_config_get_f                                      f_phymod_phy_pattern_config_get;
    __dispatch__phymod_phy_pattern_enable_set_f                                      f_phymod_phy_pattern_enable_set;
    __dispatch__phymod_phy_pattern_enable_get_f                                      f_phymod_phy_pattern_enable_get;
    __dispatch__phymod_core_diagnostics_get_f                                        f_phymod_core_diagnostics_get;
    __dispatch__phymod_phy_diagnostics_get_f                                         f_phymod_phy_diagnostics_get;
    __dispatch__phymod_phy_pam4_diagnostics_get_f                                    f_phymod_phy_pam4_diagnostics_get;
    __dispatch__phymod_phy_pmd_info_dump_f                                           f_phymod_phy_pmd_info_dump;
    __dispatch__phymod_phy_pcs_info_dump_f                                           f_phymod_phy_pcs_info_dump;
    __dispatch__phymod_phy_eyescan_run_f                                             f_phymod_phy_eyescan_run;
    __dispatch__phymod_phy_link_mon_enable_set_f                                     f_phymod_phy_link_mon_enable_set;
    __dispatch__phymod_phy_link_mon_enable_get_f                                     f_phymod_phy_link_mon_enable_get;
    __dispatch__phymod_phy_link_mon_status_get_f                                     f_phymod_phy_link_mon_status_get;
    __dispatch__phymod_phy_fec_correctable_counter_get_f                             f_phymod_phy_fec_correctable_counter_get;
    __dispatch__phymod_phy_fec_uncorrectable_counter_get_f                           f_phymod_phy_fec_uncorrectable_counter_get;
    __dispatch__phymod_phy_prbs_error_inject_set_f                                   f_phymod_phy_prbs_error_inject_set;
    __dispatch__phymod_phy_prbs_error_analyzer_proj_f                                f_phymod_phy_prbs_error_analyzer_proj;
} __phymod_diagnostics__dispatch__t__;

extern __phymod_diagnostics__dispatch__t__* __plp_aperta_phymod_diagnostics__dispatch__[phymodDispatchTypeCount];

#endif /*_PHYMOD_DIAGNOSTICS_DISPATCH_H_*/
