#!/bin/bash

SEND_KICK()
{
        while true
        do
                dog_enable=$(ipmitool mc watchdog get | grep 'Timer Is' | awk '{print $4}')
                echo "[watchdog status] : ${dog_enable}"
                if [[ $dog_enable == *Running* ]]; then
                        ipmitool mc watchdog reset  1>>/dev/null 2>>/dev/null
                fi
                sleep 5;
        done
}

SEND_KICK
