bus "i2c-25" "SCD 0000:03:00.0 SMBus master 1 bus 0"
bus "i2c-28" "SCD 0000:03:00.0 SMBus master 1 bus 3"
bus "i2c-29" "SCD 0000:03:00.0 SMBus master 1 bus 4"
bus "i2c-33" "SCD 0000:03:00.0 SMBus master 2 bus 0"
bus "i2c-34" "SCD 0000:03:00.0 SMBus master 2 bus 1"
bus "i2c-35" "SCD 0000:03:00.0 SMBus master 2 bus 2"
bus "i2c-36" "SCD 0000:03:00.0 SMBus master 2 bus 3"
bus "i2c-37" "SCD 0000:03:00.0 SMBus master 2 bus 4"

chip "max6581-i2c-25-4d"
    ignore temp5
    ignore temp6

chip "raa228228-i2c-33-45"
    label temp1 "P0V8_VDD"
    ignore temp2
    ignore temp3

chip "isl68226-i2c-34-46"
    label temp1 "P0V9_AVDD_0"
    label temp2 "P0V9_AVDD_1"
    ignore temp3
    ignore temp4
    ignore temp5
    ignore temp6
    ignore temp7

chip "isl68226-i2c-35-47"
    label temp1 "P0V75_AVDD_0"
    label temp2 "P0V75_AVDD_1"
    ignore temp3
    ignore temp4
    ignore temp5
    ignore temp6
    ignore temp7

chip "isl68226-i2c-36-4d"
    label temp1 "P3V3_OPTICS_A"
    ignore temp2
    ignore temp3
    ignore temp4
    ignore temp5
    ignore temp6
    ignore temp7

chip "isl68226-i2c-37-4c"
    label temp1 "P3V3_OPTICS_B"
    ignore temp2
    ignore temp3
    ignore temp4
    ignore temp5
    ignore temp6
    ignore temp7

chip "nvme-pci-0400"
    # TODO: sensors complaining about tempX_min and tempX_max
    ignore temp2
    ignore temp3
    ignore temp4
    ignore temp5
    ignore temp6
    ignore temp7

chip "pmbus-i2c-28-58"
    ignore fan3
    ignore fan4

chip "pmbus-i2c-29-58"
    ignore fan3
    ignore fan4
