# Clounix Platform modules

CLOUNIX_MODULE_VERSION = 2.1.1

CLOUNIX_MODULE = clounix-modules_$(CLOUNIX_MODULE_VERSION)_$(CONFIGURED_ARCH).deb
$(CLOUNIX_MODULE)_SRC_PATH = $(PLATFORM_PATH)/clounix-modules
$(CLOUNIX_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
SONIC_DPKG_DEBS += $(CLOUNIX_MODULE)