# sonic clounix one image installer

SONIC_CLOUNIX_PDE_IMAGE = sonic-clounix-pde.bin
$(SONIC_CLOUNIX_PDE_IMAGE)_ENV = -pde
$(SONIC_CLOUNIX_PDE_IMAGE)_MACHINE = clounix
$(SONIC_CLOUNIX_PDE_IMAGE)_IMAGE_TYPE = onie

ifeq ($(INCLUDE_SDK),yes)
$(SONIC_CLOUNIX_PDE_IMAGE)_INSTALLS += $(CLOUNIX_SDK) $(CLOUNIX_SDK_DEV)
$(SONIC_CLOUNIX_PDE_IMAGE)_INSTALLS += $(LINUX_HEADERS_COMMON) $(LINUX_HEADERS) 
else
$(SONIC_CLOUNIX_PDE_IMAGE)_INSTALLS += $(CLOUNIX_SAI)
$(SONIC_CLOUNIX_PDE_IMAGE)_INSTALLS += $(CLOUNIX_MODULE) $(CLX_UTILS)
endif

$(SONIC_CLOUNIX_PDE_IMAGE)_INSTALLS += $(SYSTEMD_SONIC_GENERATOR)
$(SONIC_CLOUNIX_PDE_IMAGE)_INSTALLS += $(PDDF_PLATFORM_MODULE)

$(SONIC_CLOUNIX_PDE_IMAGE)_LAZY_INSTALLS += $(CLOUNIX_CLX12800_48D8E_PLATFORM_MODULE)
$(SONIC_CLOUNIX_PDE_IMAGE)_LAZY_INSTALLS += $(CLOUNIX_CLX25600_48D8E_PLATFORM_MODULE)
$(SONIC_CLOUNIX_PDE_IMAGE)_LAZY_INSTALLS += $(CLOUNIX_PLATFORM_PIT_SYSDIAG_MODULE)

ifeq ($(INSTALL_DEBUG_TOOLS),y)
$(SONIC_CLOUNIX_PDE_IMAGE)_DOCKERS = $(DOCKER_DATABASE_DBG)
$(SONIC_CLOUNIX_PDE_IMAGE)_DOCKERS += $(DOCKER_PLATFORM_MONITOR)
else
$(SONIC_CLOUNIX_PDE_IMAGE)_DOCKERS = $(DOCKER_DATABASE)
$(SONIC_CLOUNIX_PDE_IMAGE)_DOCKERS += $(DOCKER_PLATFORM_MONITOR)
endif

ifeq ($(INCLUDE_SAISERVER),yes)
$(SONIC_CLOUNIX_PDE_IMAGE)_DOCKERS += $(DOCKER_SAISERVER_CLOUNIX)
endif

SONIC_INSTALLERS += $(SONIC_CLOUNIX_PDE_IMAGE)
