# Pegatron Platform modules
CLOUNIX_PLATFORM_MODULE_VERSION = 1.0.0
export CLOUNIX_PLATFORM_MODULE_VERSION
ifeq ($(CONFIGURED_ARCH), amd64)
TARGET_ARCH = x86_64
else
TARGET_ARCH = $(CONFIGURED_ARCH)
endif

CLOUNIX_CLX25600_48D8E_PLATFORM_MODULE = sonic-platform-clounix-clx25600-48d8e_$(CLOUNIX_PLATFORM_MODULE_VERSION)_$(CONFIGURED_ARCH).deb
$(CLOUNIX_CLX25600_48D8E_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-clounix
$(CLOUNIX_CLX25600_48D8E_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON) $(PDDF_PLATFORM_MODULE_SYM)
$(CLOUNIX_CLX25600_48D8E_PLATFORM_MODULE)_PLATFORM = $(TARGET_ARCH)-clounix_clx25600_48d8e-r0
SONIC_DPKG_DEBS += $(CLOUNIX_CLX25600_48D8E_PLATFORM_MODULE)

CLOUNIX_CLX12800_48D8E_PLATFORM_MODULE = sonic-platform-clounix-clx12800-48d8e_$(CLOUNIX_PLATFORM_MODULE_VERSION)_$(CONFIGURED_ARCH).deb
$(CLOUNIX_CLX12800_48D8E_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-clounix
$(CLOUNIX_CLX12800_48D8E_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON) $(PDDF_PLATFORM_MODULE_SYM)
$(CLOUNIX_CLX12800_48D8E_PLATFORM_MODULE)_PLATFORM = $(TARGET_ARCH)-clounix_clx12800_48d8e-r0
$(eval $(call add_extra_package,$(CLOUNIX_CLX25600_48D8E_PLATFORM_MODULE),$(CLOUNIX_CLX12800_48D8E_PLATFORM_MODULE)))


CLOUNIX_PLATFORM_PIT_SYSDIAG_MODULE = sonic-platform-clounix-pit-sysdiag_$(CLOUNIX_PLATFORM_MODULE_VERSION)_$(CONFIGURED_ARCH).deb
$(CLOUNIX_PLATFORM_PIT_SYSDIAG_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-clounix
#$(CLOUNIX_PLATFORM_PIT_SYSDIAG_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(CLOUNIX_PLATFORM_PIT_SYSDIAG_MODULE)_PLATFORM += $(TARGET_ARCH)-clounix_clx12800_48d8e-r0
$(CLOUNIX_PLATFORM_PIT_SYSDIAG_MODULE)_PLATFORM += $(TARGET_ARCH)-clounix_clx25600_48d8e-r0
$(eval $(call add_extra_package,$(CLOUNIX_CLX25600_48D8E_PLATFORM_MODULE),$(CLOUNIX_PLATFORM_PIT_SYSDIAG_MODULE)))

