IFCS_INIT_FILE : "/usr/share/sonic/hwsku/config_64x100G_asterfusion-cx564p-n.yaml"
IFCS_SKU_FILE : "/usr/share/sonic/hwsku/innovium.77500"
IFCS_INNO_CLI_PORT : "9999"
IFCS_TARGET : "device"
INNOVIUM_DIR : "/innovium"
NRZ_PORTS_SIG_DETECT_MODE_TL7 : "1"
PYTHONPATH : "$INNOVIUM_DIR:$INNOVIUM_DIR/cmds:$INNOVIUM_DIR/scripts:$INNOVIUM_DIR/test/:$INNOVIUM_DIR/test/utils:$INNOVIUM_DIR/utils:$INNOVIUM_DIR/pyctypes"
IVM_SAI_DATAPATH_CONFIG_FILE: "/usr/share/sonic/hwsku/ivm.sai.datapath.config.yaml"
BDC_ENABLE: "true"
HDC_ENABLE: "true"
ISAI_CB_UDS: "/etc/sonic/ivm/ivm-flashlight-sock"