/*
 *         
 * $Id: phymod.xml,v 1.1.2.5 Broadcom SDK $
 * 
 * $Copyright: (c) 2020 Broadcom.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *         
 *     
 * DO NOT EDIT THIS FILE!
 *
 */

#include <phymod/phymod.h>
#include <phymod/phymod.h>
#include <phymod/phymod_dispatch.h>

#ifdef PHYMOD_APERTA_SUPPORT

#include <phymod/chip/aperta.h>


__phymod__dispatch__t__ plp_aperta_phymod_aperta_driver = {

    plp_aperta_core_identify,
    plp_aperta_core_info_get,
    plp_aperta_core_lane_map_set,
    plp_aperta_core_lane_map_get,
    plp_aperta_core_reset_set,
    plp_aperta_core_reset_get,
    plp_aperta_core_firmware_info_get,
    plp_aperta_phy_firmware_core_config_set,
    plp_aperta_phy_firmware_core_config_get,
    plp_aperta_phy_firmware_lane_config_set,
    plp_aperta_phy_firmware_lane_config_get,
    plp_aperta_core_pll_sequencer_restart,
    NULL, /* plp_aperta_phymod_core_wait_event */
    plp_aperta_phy_rx_restart,
    plp_aperta_phy_polarity_set,
    plp_aperta_phy_polarity_get,
    NULL, /* plp_aperta_phymod_phy_tx_set */
    NULL, /* plp_aperta_phymod_phy_tx_get */
    plp_aperta_phy_pam4_tx_set,
    plp_aperta_phy_pam4_tx_get,
    plp_aperta_phy_media_type_tx_get,
    NULL, /* plp_aperta_phymod_phy_tx_override_set */
    NULL, /* plp_aperta_phymod_phy_tx_override_get */
    plp_aperta_phy_rx_set,
    plp_aperta_phy_rx_get,
    plp_aperta_phy_rx_adaptation_resume,
    plp_aperta_phy_reset_set,
    plp_aperta_phy_reset_get,
    plp_aperta_phy_power_set,
    plp_aperta_phy_power_get,
    NULL, /* plp_aperta_phymod_phy_hg2_codec_control_set */
    NULL, /* plp_aperta_phymod_phy_hg2_codec_control_get */
    plp_aperta_phy_tx_lane_control_set,
    plp_aperta_phy_tx_lane_control_get,
    plp_aperta_phy_rx_lane_control_set,
    plp_aperta_phy_rx_lane_control_get,
    plp_aperta_phy_fec_enable_set,
    plp_aperta_phy_fec_enable_get,
    NULL, /* plp_aperta_phymod_phy_forced_speed_line_side_set */
    NULL, /* plp_aperta_phymod_phy_forced_speed_line_side_get */
    NULL, /* plp_aperta_phymod_phy_flow_control_mode_set */
    NULL, /* plp_aperta_phymod_phy_flow_control_mode_get */
    NULL, /* plp_aperta_phymod_phy_psm_cos_bmp_set */
    NULL, /* plp_aperta_phymod_phy_psm_cos_bmp_get */
    NULL, /* plp_aperta_phymod_phy_autoneg_oui_set */
    NULL, /* plp_aperta_phymod_phy_autoneg_oui_get */
    NULL, /* plp_aperta_phymod_phy_eee_set */
    NULL, /* plp_aperta_phymod_phy_eee_get */
    plp_aperta_phy_interface_config_set,
    plp_aperta_phy_interface_config_get,
    plp_aperta_phy_cl72_set,
    plp_aperta_phy_cl72_get,
    plp_aperta_phy_cl72_status_get,
    plp_aperta_phy_autoneg_ability_set,
    plp_aperta_phy_autoneg_ability_get,
    plp_aperta_phy_autoneg_remote_ability_get,
    plp_aperta_phy_autoneg_set,
    plp_aperta_phy_autoneg_get,
    NULL, /* plp_aperta_phymod_phy_autoneg_restart_set */
    plp_aperta_phy_autoneg_status_get,
    plp_aperta_core_init,
    NULL, /* plp_aperta_phymod_phy_pll_multiplier_get */
    plp_aperta_phy_init,
    plp_aperta_phy_loopback_set,
    plp_aperta_phy_loopback_get,
    plp_aperta_phy_rx_pmd_locked_get,
    NULL, /* plp_aperta_phymod_phy_rx_signal_detect_get */
    plp_aperta_phy_link_status_get,
    plp_aperta_phy_status_dump,
    NULL, /* plp_aperta_phymod_phy_pcs_userspeed_set */
    NULL, /* plp_aperta_phymod_phy_pcs_userspeed_get */
    plp_aperta_phy_reg_read,
    plp_aperta_phy_reg_write,
    NULL, /* plp_aperta_phymod_phy_private_read */
    NULL, /* plp_aperta_phymod_phy_private_write */
    plp_aperta_phy_rev_id,
    NULL, /* plp_aperta_phymod_phy_lane_cross_switch_map_set */
    NULL, /* plp_aperta_phymod_phy_lane_cross_switch_map_get */
    plp_aperta_phy_intr_enable_set,
    plp_aperta_phy_intr_enable_get,
    plp_aperta_phy_intr_status_get,
    plp_aperta_phy_intr_status_clear,
    plp_aperta_phy_i2c_read,
    plp_aperta_phy_i2c_write,
    plp_aperta_phy_gpio_config_set,
    plp_aperta_phy_gpio_config_get,
    plp_aperta_phy_gpio_pin_value_set,
    plp_aperta_phy_gpio_pin_value_get,
    plp_aperta_timesync_config_set,
    plp_aperta_timesync_config_get,
    plp_aperta_timesync_enable_set,
    plp_aperta_timesync_enable_get,
    plp_aperta_timesync_nco_addend_set,
    plp_aperta_timesync_nco_addend_get,
    plp_aperta_timesync_framesync_mode_set,
    plp_aperta_timesync_framesync_mode_get,
    plp_aperta_timesync_local_time_set,
    plp_aperta_timesync_local_time_get,
    plp_aperta_timesync_load_ctrl_set,
    plp_aperta_timesync_load_ctrl_get,
    NULL, /* plp_aperta_phymod_timesync_tx_timestamp_offset_set */
    NULL, /* plp_aperta_phymod_timesync_tx_timestamp_offset_get */
    NULL, /* plp_aperta_phymod_timesync_rx_timestamp_offset_set */
    NULL, /* plp_aperta_phymod_timesync_rx_timestamp_offset_get */
    plp_aperta_timesync_capture_timestamp_get,
    plp_aperta_timesync_heartbeat_timestamp_get,
    NULL, /* plp_aperta_phymod_timesync_do_sync */
    NULL, /* plp_aperta_phymod_edc_config_set */
    NULL, /* plp_aperta_phymod_edc_config_get */
    NULL, /* plp_aperta_phymod_phy_core_mode_set */
    NULL, /* plp_aperta_phymod_phy_core_mode_get */
    plp_aperta_failover_mode_set,
    plp_aperta_failover_mode_get,
    NULL, /* plp_aperta_phymod_port_init */
    NULL, /* plp_aperta_phymod_phy_autoneg_try_enable */
    NULL, /* plp_aperta_phymod_debug_ether */
    NULL, /* plp_aperta_phymod_phy_short_chn_mode_enable_set */
    NULL, /* plp_aperta_phymod_phy_short_chn_mode_enable_get */
    NULL, /* plp_aperta_phymod_port_enable_set */
    NULL, /* plp_aperta_phymod_port_enable_get */
    NULL, /* plp_aperta_phymod_phy_eye_margin_est_get */
    NULL, /* plp_aperta_phymod_phy_multi_get */
    NULL, /* plp_aperta_phymod_phy_rescal_set */
    NULL, /* plp_aperta_phymod_phy_rescal_get */
    NULL, /* plp_aperta_phymod_phy_sw_an_control_status_get */
    NULL, /* plp_aperta_phymod_phy_sw_an_base_page_exchange_handler */
    NULL, /* plp_aperta_phymod_phy_sw_an_lp_page_rdy_handler */
    NULL, /* plp_aperta_phymod_phy_sw_an_advert_set */
    NULL, /* plp_aperta_phymod_phy_sw_autoneg_enable */
    NULL, /* plp_aperta_phymod_phy_eee_mode_set */
    NULL, /* plp_aperta_phymod_phy_eee_mode_get */
    NULL, /* plp_aperta_phymod_phy_power_mode_set */
    NULL, /* plp_aperta_phymod_phy_power_mode_get */
    NULL, /* plp_aperta_phymod_phy_jfec_config_set */
    NULL, /* plp_aperta_phymod_phy_jfec_config_get */
    NULL, /* plp_aperta_phymod_phy_kp4_config_set */
    NULL, /* plp_aperta_phymod_phy_kp4_config_get */
    plp_aperta_phy_pam4_fec_status_get,
    NULL, /* plp_aperta_phymod_phy_avs_config_set */
    NULL, /* plp_aperta_phymod_phy_avs_config_get */
    NULL, /* plp_aperta_phymod_phy_avs_status_get */
    NULL, /* plp_aperta_phymod_warmboot_init */
    NULL, /* plp_aperta_phymod_logical_lane_set */
    NULL, /* plp_aperta_phymod_logical_lane_get */
    NULL, /* plp_aperta_phymod_phy_dsrds_firmware_lane_config_set */
    NULL, /* plp_aperta_phymod_phy_dsrds_firmware_lane_config_get */
    plp_aperta_synce_config_set,
    plp_aperta_synce_config_get,
    plp_aperta_timesync_time_code_set,
    plp_aperta_timesync_time_code_get,
    plp_aperta_timesync_link_delay_set,
    plp_aperta_timesync_link_delay_get,
    plp_aperta_timesync_timestamp_offset_set,
    plp_aperta_timesync_timestamp_offset_get,
    plp_aperta_timesync_timing_control_set,
    plp_aperta_timesync_timing_control_get,
    plp_aperta_phy_pcs_status_get,
    plp_aperta_timesync_sopmem_get,
    NULL, /* plp_aperta_phymod_phy_speed_config_set */
    NULL, /* plp_aperta_phymod_phy_speed_config_get */
    NULL, /* plp_aperta_phymod_phy_op_mode_get */
    NULL, /* plp_aperta_phymod_phy_tx_taps_default_get */
    NULL, /* plp_aperta_phymod_phy_lane_config_default_get */
    NULL, /* plp_aperta_phymod_phy_firmware_load_info_get */
    NULL, /* plp_aperta_phymod_phy_autoneg_advert_ability_set */
    NULL, /* plp_aperta_phymod_phy_autoneg_advert_ability_get */
    NULL, /* plp_aperta_phymod_phy_autoneg_remote_advert_ability_get */
    NULL, /* plp_aperta_phymod_phy_bond_in_pwrdn_override */
    NULL, /* plp_aperta_phymod_phy_tx_pam4_precoder_enable_set */
    NULL, /* plp_aperta_phymod_phy_tx_pam4_precoder_enable_get */
    NULL, /* plp_aperta_phymod_phy_tx_phase_lock_set */
    NULL, /* plp_aperta_phymod_phy_pll_reconfig */
    NULL, /* plp_aperta_phymod_phy_pll_pwrdn */
    NULL, /* plp_aperta_phymod_phy_linkdown_transmit_set */
    NULL, /* plp_aperta_phymod_phy_linkdown_transmit_get */
    NULL, /* plp_aperta_phymod_phy_fw_init_params_get */
    NULL, /* plp_aperta_phymod_srds_diag_access_enable */
    NULL, /* plp_aperta_phymod_phy_cleanup */
    plp_aperta_timesync_mpls_set,
    plp_aperta_timesync_mpls_get,
    plp_aperta_timesync_inband_filter_set,
    plp_aperta_timesync_inband_filter_get,
    plp_aperta_phy_pai_info_get,
    NULL, /* plp_aperta_phymod_failover_config_set */
    NULL, /* plp_aperta_phymod_failover_config_get */
    NULL, /* plp_aperta_phymod_timesync_sopmem_set */
    NULL, /* plp_aperta_phymod_timesync_pch_set */
    NULL, /* plp_aperta_phymod_timesync_pch_get */
    NULL, /* plp_aperta_phymod_timestamp_univ_set */
    NULL, /* plp_aperta_phymod_timestamp_univ_get */
    NULL, /* plp_aperta_phymod_peripheral_dev_control */
    NULL, /* plp_aperta_phymod_phy_pll_powerdown_get */
    NULL, /* plp_aperta_phymod_phy_fec_bypass_indication_set */
    NULL, /* plp_aperta_phymod_phy_fec_bypass_indication_get */
    NULL, /* plp_aperta_phymod_phy_autoneg_speed_id_table_reload */
    NULL, /* plp_aperta_phymod_phy_stats */
    NULL, /* plp_aperta_phymod_get_port_information */
    NULL, /* plp_aperta_phymod_timesync_ptp_action_set */
    NULL, /* plp_aperta_phymod_timesync_ptp_action_get */
};

#endif /* PHYMOD_APERTA_SUPPORT */
