#!/bin/bash

CONTAINER_NAME="polaris"
SERVICES="vpp fsmmgr pds operd"

echo "Platform specific pre-shutdown sequence" | tee /dev/kmsg /dev/stderr /dev/console

docker exec "$CONTAINER_NAME" sh -c '
    echo "Attempting to kill processes in $CONTAINER_NAME container : $SERVICES" | tee /dev/kmsg /dev/stderr /dev/console
    for service in $SERVICES; do
        killall -q "$service" 2>/dev/null
    done
    exit_code=$?
    if [ $exit_code -eq 0 ]; then
        echo "Successfully killed processes." | tee /dev/kmsg /dev/stderr /dev/console
    else
        echo "No matching processes found or failed to kill." | tee /dev/kmsg /dev/stderr /dev/console
    fi
'
docker_exit_code=$?
if [ $docker_exit_code -eq 0 ]; then
    echo "Platform specific pre-shutdown is successful" | tee /dev/kmsg /dev/stderr /dev/console
else
    echo "Platform specific pre-shutdown failed with exit code $docker_exit_code." | tee /dev/kmsg /dev/stderr /dev/console
    exit $docker_exit_code
fi

