ifcs:
  options:
    log_level: "info"
nodes:
- node_id: "0"
  options:
    sd_low_power_mode_global_default: "true"
    sku: "configs/sku/innovium.77500"
    netdev:
    - auto_create: "no"
      multi_interface: "yes"
    buffer_management_mode: "api_driven"
    max_lossless_tc: "2" 
    ilpm_enable: "1" 
    forward_profile: "IFCS_FORWARD_PROFILE_ID_PROFILE_E"
    ecn_stats_enable: "1" 
    sys_clk: "1720"
    ifc_clk: "1200"
    mac_clk: "1340"
    txring:
    - txring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    rxring:
    - rxring_id: "0"                                         
      desc_count: "1024"                                     
      prio: "1"     
      netdev: "true"      
      queues: "0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39"  
    - rxring_id: "1"                                         
      desc_count: "1024"                                     
      prio: "1"    
      netdev: "true"      
      queues: "1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40"  
    - rxring_id: "2"                                         
      desc_count: "1024"                                     
      prio: "1"
      netdev: "true"      
      queues: "2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 47" 
    - rxring_id: "3"                                         
      desc_count: "1024"                                     
      prio: "1"     
      queues: "42, 43, 44, 45, 46" 

  devports:
  - id: "0"
    sysport: "1000"
    type: "cpu"
  - fec: "KRFEC"
    id: "221"
    lanes: "4:4"
    serdes_group: "27"
    speed: "100G"
    sysport: "221"
    type: "eth"
  - fec: "KRFEC"
    id: "213"
    lanes: "4:4"
    serdes_group: "26"
    speed: "100G"
    sysport: "213"
    type: "eth"
  - fec: "KRFEC"
    id: "205"
    lanes: "4:4"
    serdes_group: "25"
    speed: "100G"
    sysport: "205"
    type: "eth"
  - fec: "KRFEC"
    id: "197"
    lanes: "4:4"
    serdes_group: "24"
    speed: "100G"
    sysport: "197"
    type: "eth"
  - fec: "KRFEC"
    id: "189"
    lanes: "4:4"
    serdes_group: "23"
    speed: "100G"
    sysport: "189"
    type: "eth"
  - fec: "KRFEC"
    id: "181"
    lanes: "4:4"
    serdes_group: "22"
    speed: "100G"
    sysport: "181"
    type: "eth"
  - fec: "KRFEC"
    id: "173"
    lanes: "4:4"
    serdes_group: "21"
    speed: "100G"
    sysport: "173"
    type: "eth"
  - fec: "KRFEC"
    id: "165"
    lanes: "4:4"
    serdes_group: "20"
    speed: "100G"
    sysport: "165"
    type: "eth"
  - fec: "KRFEC"
    id: "253"
    lanes: "4:4"
    serdes_group: "31"
    speed: "100G"
    sysport: "253"
    type: "eth"
  - fec: "KRFEC"
    id: "245"
    lanes: "4:4"
    serdes_group: "30"
    speed: "100G"
    sysport: "245"
    type: "eth"
  - fec: "KRFEC"
    id: "237"
    lanes: "4:4"
    serdes_group: "29"
    speed: "100G"
    sysport: "237"
    type: "eth"
  - fec: "KRFEC"
    id: "229"
    lanes: "4:4"
    serdes_group: "28"
    speed: "100G"
    sysport: "229"
    type: "eth"
  - fec: "KRFEC"
    id: "157"
    lanes: "4:4"
    serdes_group: "19"
    speed: "100G"
    sysport: "157"
    type: "eth"
  - fec: "KRFEC"
    id: "149"
    lanes: "4:4"
    serdes_group: "18"
    speed: "100G"
    sysport: "149"
    type: "eth"
  - fec: "KRFEC"
    id: "141"
    lanes: "4:4"
    serdes_group: "17"
    speed: "100G"
    sysport: "141"
    type: "eth"
  - fec: "KRFEC"
    id: "133"
    lanes: "4:4"
    serdes_group: "16"
    speed: "100G"
    sysport: "133"
    type: "eth"
  - fec: "KRFEC"
    id: "117"
    lanes: "4:4"
    serdes_group: "14"
    speed: "100G"
    sysport: "117"
    type: "eth"
  - fec: "KRFEC"
    id: "125"
    lanes: "4:4"
    serdes_group: "15"
    speed: "100G"
    sysport: "125"
    type: "eth"
  - fec: "KRFEC"
    id: "101"
    lanes: "4:4"
    serdes_group: "12"
    speed: "100G"
    sysport: "101"
    type: "eth"
  - fec: "KRFEC"
    id: "109"
    lanes: "4:4"
    serdes_group: "13"
    speed: "100G"
    sysport: "109"
    type: "eth"
  - fec: "KRFEC"
    id: "21"
    lanes: "4:4"
    serdes_group: "2"
    speed: "100G"
    sysport: "21"
    type: "eth"
  - fec: "KRFEC"
    id: "29"
    lanes: "4:4"
    serdes_group: "3"
    speed: "100G"
    sysport: "29"
    type: "eth"
  - fec: "KRFEC"
    id: "5"
    lanes: "4:4"
    serdes_group: "0"
    speed: "100G"
    sysport: "5"
    type: "eth"
  - fec: "KRFEC"
    id: "13"
    lanes: "4:4"
    serdes_group: "1"
    speed: "100G"
    sysport: "13"
    type: "eth"
  - fec: "KRFEC"
    id: "85"
    lanes: "4:4"
    serdes_group: "10"
    speed: "100G"
    sysport: "85"
    type: "eth"
  - fec: "KRFEC"
    id: "93"
    lanes: "4:4"
    serdes_group: "11"
    speed: "100G"
    sysport: "93"
    type: "eth"
  - fec: "KRFEC"
    id: "69"
    lanes: "4:4"
    serdes_group: "8"
    speed: "100G"
    sysport: "69"
    type: "eth"
  - fec: "KRFEC"
    id: "77"
    lanes: "4:4"
    serdes_group: "9"
    speed: "100G"
    sysport: "77"
    type: "eth"
  - fec: "KRFEC"
    id: "53"
    lanes: "4:4"
    serdes_group: "6"
    speed: "100G"
    sysport: "53"
    type: "eth"
  - fec: "KRFEC"
    id: "61"
    lanes: "4:4"
    serdes_group: "7"
    speed: "100G"
    sysport: "61"
    type: "eth"
  - fec: "KRFEC"
    id: "37"
    lanes: "4:4"
    serdes_group: "4"
    speed: "100G"
    sysport: "37"
    type: "eth"
  - fec: "KRFEC"
    id: "45"
    lanes: "4:4"
    serdes_group: "5"
    speed: "100G"
    sysport: "45"
    type: "eth"
  - fec: "KRFEC"
    id: "209"
    lanes: "0:4"
    serdes_group: "26"
    speed: "100G"
    sysport: "209"
    type: "eth"
  - fec: "KRFEC"
    id: "217"
    lanes: "0:4"
    serdes_group: "27"
    speed: "100G"
    sysport: "217"
    type: "eth"
  - fec: "KRFEC"
    id: "193"
    lanes: "0:4"
    serdes_group: "24"
    speed: "100G"
    sysport: "193"
    type: "eth"
  - fec: "KRFEC"
    id: "201"
    lanes: "0:4"
    serdes_group: "25"
    speed: "100G"
    sysport: "201"
    type: "eth"
  - fec: "KRFEC"
    id: "177"
    lanes: "0:4"
    serdes_group: "22"
    speed: "100G"
    sysport: "177"
    type: "eth"
  - fec: "KRFEC"
    id: "185"
    lanes: "0:4"
    serdes_group: "23"
    speed: "100G"
    sysport: "185"
    type: "eth"
  - fec: "KRFEC"
    id: "161"
    lanes: "0:4"
    serdes_group: "20"
    speed: "100G"
    sysport: "161"
    type: "eth"
  - fec: "KRFEC"
    id: "169"
    lanes: "0:4"
    serdes_group: "21"
    speed: "100G"
    sysport: "169"
    type: "eth"
  - fec: "KRFEC"
    id: "241"
    lanes: "0:4"
    serdes_group: "30"
    speed: "100G"
    sysport: "241"
    type: "eth"
  - fec: "KRFEC"
    id: "249"
    lanes: "0:4"
    serdes_group: "31"
    speed: "100G"
    sysport: "249"
    type: "eth"
  - fec: "KRFEC"
    id: "225"
    lanes: "0:4"
    serdes_group: "28"
    speed: "100G"
    sysport: "225"
    type: "eth"
  - fec: "KRFEC"
    id: "233"
    lanes: "0:4"
    serdes_group: "29"
    speed: "100G"
    sysport: "233"
    type: "eth"
  - fec: "KRFEC"
    id: "145"
    lanes: "0:4"
    serdes_group: "18"
    speed: "100G"
    sysport: "145"
    type: "eth"
  - fec: "KRFEC"
    id: "153"
    lanes: "0:4"
    serdes_group: "19"
    speed: "100G"
    sysport: "153"
    type: "eth"
  - fec: "KRFEC"
    id: "129"
    lanes: "0:4"
    serdes_group: "16"
    speed: "100G"
    sysport: "129"
    type: "eth"
  - fec: "KRFEC"
    id: "137"
    lanes: "0:4"
    serdes_group: "17"
    speed: "100G"
    sysport: "137"
    type: "eth"
  - fec: "KRFEC"
    id: "121"
    lanes: "0:4"
    serdes_group: "15"
    speed: "100G"
    sysport: "121"
    type: "eth"
  - fec: "KRFEC"
    id: "113"
    lanes: "0:4"
    serdes_group: "14"
    speed: "100G"
    sysport: "113"
    type: "eth"
  - fec: "KRFEC"
    id: "105"
    lanes: "0:4"
    serdes_group: "13"
    speed: "100G"
    sysport: "105"
    type: "eth"
  - fec: "KRFEC"
    id: "97"
    lanes: "0:4"
    serdes_group: "12"
    speed: "100G"
    sysport: "97"
    type: "eth"
  - fec: "KRFEC"
    id: "25"
    lanes: "0:4"
    serdes_group: "3"
    speed: "100G"
    sysport: "25"
    type: "eth"
  - fec: "KRFEC"
    id: "17"
    lanes: "0:4"
    serdes_group: "2"
    speed: "100G"
    sysport: "17"
    type: "eth"
  - fec: "KRFEC"
    id: "9"
    lanes: "0:4"
    serdes_group: "1"
    speed: "100G"
    sysport: "9"
    type: "eth"
  - fec: "KRFEC"
    id: "1"
    lanes: "0:4"
    serdes_group: "0"
    speed: "100G"
    sysport: "1"
    type: "eth"
  - fec: "KRFEC"
    id: "89"
    lanes: "0:4"
    serdes_group: "11"
    speed: "100G"
    sysport: "89"
    type: "eth"
  - fec: "KRFEC"
    id: "81"
    lanes: "0:4"
    serdes_group: "10"
    speed: "100G"
    sysport: "81"
    type: "eth"
  - fec: "KRFEC"
    id: "73"
    lanes: "0:4"
    serdes_group: "9"
    speed: "100G"
    sysport: "73"
    type: "eth"
  - fec: "KRFEC"
    id: "65"
    lanes: "0:4"
    serdes_group: "8"
    speed: "100G"
    sysport: "65"
    type: "eth"
  - fec: "KRFEC"
    id: "57"
    lanes: "0:4"
    serdes_group: "7"
    speed: "100G"
    sysport: "57"
    type: "eth"
  - fec: "KRFEC"
    id: "49"
    lanes: "0:4"
    serdes_group: "6"
    speed: "100G"
    sysport: "49"
    type: "eth"
  - fec: "KRFEC"
    id: "41"
    lanes: "0:4"
    serdes_group: "5"
    speed: "100G"
    sysport: "41"
    type: "eth"
  - fec: "KRFEC"
    id: "33"
    lanes: "0:4"
    serdes_group: "4"
    speed: "100G"
    sysport: "33"
    type: "eth"
  isg:
  - id: "0"                     
    lane_swap: "02317654"
    tx_polarity: "11011000"
    rx_polarity: "01101010"
  - id: "1"                     
    lane_swap: "20134567"  
    tx_polarity: "00001010"
    rx_polarity: "00110100"
  - id: "2"                     
    lane_swap: "02137465"
    tx_polarity: "00010010"
    rx_polarity: "10110000"
  - id: "3"                      
    lane_swap: "12036475"
    tx_polarity: "11100111"
    rx_polarity: "10000001"
  - id: "4"                     
    lane_swap: "01237465"
    tx_polarity: "00101101"
    rx_polarity: "00111110"
  - id: "5"                     
    lane_swap: "12304675"
    tx_polarity: "10001011"
    rx_polarity: "01010110"
  - id: "6"                     
    lane_swap: "01237654"
    tx_polarity: "00100110"
    rx_polarity: "00011101"
  - id: "7"                     
    lane_swap: "12037456"
    tx_polarity: "00101000"
    rx_polarity: "00001111"
  - id: "8"                     
    lane_swap: "01237654"
    tx_polarity: "10110110"
    rx_polarity: "01011011"
  - id: "9"                                    
    lane_swap: "12035467"   
    tx_polarity: "11101000"
    rx_polarity: "00011001"
  - id: "10"                        
    lane_swap: "01235674"
    tx_polarity: "01111111"
    rx_polarity: "01011011"
  - id: "11"                     
    lane_swap: "01237564"
    tx_polarity: "01101100"
    rx_polarity: "11011000"
  - id: "12"                    
    lane_swap: "01237546"
    tx_polarity: "00011101"
    rx_polarity: "00000010"
  - id: "13"                    
    lane_swap: "03216475"
    tx_polarity: "10000011"
    rx_polarity: "11011111"
  - id: "14"                    
    lane_swap: "01237564"
    tx_polarity: "00111011"
    rx_polarity: "00000011"
  - id: "15"                       
    lane_swap: "03214567"
    tx_polarity: "00000101"
    rx_polarity: "01000111"
  - id: "16"                    
    lane_swap: "12034576"
    tx_polarity: "00010100"
    rx_polarity: "10000001"
  - id: "17"                    
    lane_swap: "02314567"
    tx_polarity: "00100111"
    rx_polarity: "00100000"
  - id: "18"                   
    lane_swap: "01234576"
    tx_polarity: "00011101"
    rx_polarity: "11100111"
  - id: "19"                   
    lane_swap: "13204567"
    tx_polarity: "00011101"
    rx_polarity: "00111001"
  - id: "20"                   
    lane_swap: "01237564"
    tx_polarity: "00000111"
    rx_polarity: "10010101"
  - id: "21"                   
    lane_swap: "01235647"
    tx_polarity: "00111011"
    rx_polarity: "00111101"
  - id: "22"                   
    lane_swap: "12307564"
    tx_polarity: "11110100"
    rx_polarity: "01010001"
  - id: "23"                   
    lane_swap: "03214657"
    tx_polarity: "00111000"
    rx_polarity: "10000111"
  - id: "24"                    
    lane_swap: "01236547"
    tx_polarity: "00010111"
    rx_polarity: "11001101"
  - id: "25"                     
    lane_swap: "01235647"     
    tx_polarity: "00101011"
    rx_polarity: "01111110"
  - id: "26"                     
    lane_swap: "01234567"
    tx_polarity: "00010101"
    rx_polarity: "11000100"
  - id: "27"                      
    lane_swap: "01234567"
    tx_polarity: "00100000"
    rx_polarity: "00111110"
  - id: "28"                      
    lane_swap: "01236754"
    tx_polarity: "10101001"
    rx_polarity: "11011001"
  - id: "29"                      
    lane_swap: "01234567"
    tx_polarity: "00101010"
    rx_polarity: "10011111"
  - id: "30"                     
    lane_swap: "31204567"
    tx_polarity: "00010101"
    rx_polarity: "01101110"
  - id: "31"                      
    lane_swap: "01234567"
    tx_polarity: "00100011"
    rx_polarity: "11001110"
  - id: "32"
    lane_swap: "01234567"
    rx_polarity: "00000000"
    tx_polarity: "00000000"
