#!/bin/sh

mr_reboot() {

    sudo rmmod x86-64-asterfusion-cx532p_n_tl07e02
#    sudo i2cset -y 0 0x30 0xa1 0
    sudo /sbin/reboot
}

if [ $# -eq 0 ] || [ $@ = "-f" ] || [ $@ = "--force" ] || [ $@ = "reboot" ]; then
    mr_reboot
elif [ $@ = "-p" ] ; then
    sudo halt
else
    echo "unsupported option"
fi
