load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//:flags.bzl", "CFLAGS_ASAN", "CFLAGS_COMMON", "DBGFLAGS", "LDFLAGS_ASAN")
load("//:gnoi.bzl", "gnoi_cc_protos")

# TODO(bazel-ready): Support debug
# if DEBUG
# DBGFLAGS = -ggdb -DDEBUG
# else
# DBGFLAGS = -g
# endif

# TODO(bazel-ready): Fix the proto warnings on build

genrule(
    name = "reboot_dbus.h.gen",
    srcs = [":reboot.xml"],
    outs = ["reboot_dbus.h"],
    cmd = "$(execpath @libdbus_bin//:dbusxx-xml2cpp) $(SRCS) --proxy=$(OUTS)",
    tools = ["@libdbus_bin//:dbusxx-xml2cpp"],
)

cc_library(
    name = "reboot_dbus",
    hdrs = [":reboot_dbus.h.gen"],
    includes = ["."],
)

gnoi_cc_protos(name = "gnoi_cc_protos")

cc_library(
    name = "proto_compat",
    hdrs = ["proto_compat.h"],
    deps = [
        "@sonic_protobuf//:libprotobuf",
    ],
)

cc_binary(
    name = "rebootbackend",
    srcs = glob([
        "*.cpp",
        "*.h",
    ]),
    cxxopts = DBGFLAGS + CFLAGS_COMMON + CFLAGS_ASAN,
    linkopts = LDFLAGS_ASAN,
    visibility = ["//:__subpackages__"],
    deps = [
        ":proto_compat",
        ":reboot_dbus",
        ":gnoi_cc_protos",
        "@sonic_swss_common//:libswsscommon_shared",
        "@trixie//libdbus-c++-dev:libdbus-c++",
    ],
)
