parameters:
  - name: JOBS
    type: object
    default: {}
  - name: BRANCH_FOLDER
    default: 'default'
  - name: CACHE
    values:
      - 'SONIC_DPKG_CACHE_METHOD=wcache'
      - 'SONIC_DPKG_CACHE_METHOD=rcache'
      - 'SONIC_DPKG_CACHE_METHOD=cache'
      - 'SONIC_DPKG_CACHE_METHOD=none'
    default: 'SONIC_DPKG_CACHE_METHOD=rcache'
  - name: OPTIONS
    default: 'SONIC_VERSION_CONTROL_COMPONENTS=py2,py3,web,git,docker MIRROR_SNAPSHOT=y DEFAULT_CONTAINER_REGISTRY=publicmirror.azurecr.io ENABLE_DOCKER_BASE_PULL=y
              SONIC_BUILD_RETRY_COUNT=3 SONIC_BUILD_RETRY_INTERVAL=600 DOCKER_BUILDKIT=0 SONIC_BUILD_JOBS=4 BUILD_PROCESS_TIMEOUT=5400 DOCKER_BUILD_TIMEOUT=5400
              PASSWORD=$(SONIC_PASSWORD) INCLUDE_RESTAPI=y ENABLE_FIPS=y SHUTDOWN_BGP_ON_START=y ENABLE_PFCWD_ON_START=y ENABLE_DHCP_GRAPH_SERVICE=y'
stages:
- ${{ if containsValue(parameters.JOBS, 'vs') }}:
  - stage: BuildVS
    jobs:
    - job: vs
      timeoutInMinutes: 840
      pool:
        type: linux
        isCustom: true
        name: sonicms1ES
      variables:
        ob_artifactBaseName: sonic-buildimage.vs
      steps:
        - template: /.pipelines/template-presteps.yml@self
          parameters:
            PLATFORM_NAME: vs
            PLATFORM_ARCH: amd64
            OPTIONS: ${{ parameters.OPTIONS }}
        - script: |
            # skip because internal branch 3 kvmtest cases keeps failing.
            echo "$(System.PullRequest.SourceBranch)"
            if echo "$(System.PullRequest.SourceBranch)" | grep -e sonicbld/precheck/head/ -e sonicbld/code-sync/internal; then
              echo "##vso[task.setvariable variable=githubPR;isOutput=true]true"
            else
              echo "##vso[task.setvariable variable=githubPR;isOutput=true]false"
            fi
          name: skipstep
          displayName: set githubPR
        - script: |
            set -ex
            set -o pipefail

            OPTIONS="${{ parameters.OPTIONS }} ${{ parameters.CACHE }} SONIC_DPKG_CACHE_SOURCE=/nfs/dpkg_cache/vs INCLUDE_KUBERNETES_MASTER=n BUILD_MULTIASIC_KVM=y"
            if echo "$(Build.Reason)" | grep -i -e schedule -e pullrequest; then
              OPTIONS+=""
            else
              OPTIONS+=" SONIC_DPKG_CACHE_METHOD_OVERRIDE=rcache BUILD_SKIP_TEST=y"
            fi
            make $OPTIONS target/docker-sonic-vs.gz target/sonic-vs.img.gz target/docker-ptf.gz 2>&1 | tee target/build.log
          displayName: Build SONiC image
        - script: |
            set -ex
            gzip -kd target/sonic-vs.img.gz
            SONIC_RUN_CMDS="qemu-img convert target/sonic-vs.img -O vhdx -o subformat=dynamic target/sonic-vs.vhdx" make BLDENV=bookworm -f Makefile.work $OPTIONS sonic-slave-run
            rm target/sonic-vs.img target/*.bin target/*.gz
            gzip target/sonic-vs.vhdx
          displayName: generate vhdx image
          condition: and(succeeded(), eq(variables.VHDX, true))
        - template: /.pipelines/template-poststeps.yml@self
          parameters:
            PLATFORM_NAME: vs
            BRANCH_FOLDER: ${{ parameters.BRANCH_FOLDER }}

- ${{ if or(gt(length(parameters.JOBS), 1), not(containsValue(parameters.JOBS, 'vs'))) }}:
  - stage: Build
    dependsOn: []
    jobs:
    - ${{ if containsValue(parameters.JOBS, 'broadcom') }}:
      - job: broadcom
        timeoutInMinutes: 840
        pool:
          type: linux
          isCustom: true
          name: sonicms1ES
        variables:
          ob_artifactBaseName: sonic-buildimage.broadcom
        steps:
          - template: /.pipelines/template-presteps.yml@self
            parameters:
              PLATFORM_NAME: broadcom
              PLATFORM_ARCH: amd64
              OPTIONS: ${{ parameters.OPTIONS }}
          - script: |
              set -ex
              set -o pipefail

              failures=''
              OPTIONS="${{ parameters.OPTIONS }} ${{ parameters.CACHE }} SONIC_DPKG_CACHE_SOURCE=/nfs/dpkg_cache/broadcom"
              if echo "$(Build.Reason)" | grep -i -e schedule -e pullrequest; then
                OPTIONS+=""
              else
                OPTIONS+=" SONIC_DPKG_CACHE_METHOD_OVERRIDE=rcache BUILD_SKIP_TEST=y"
              fi
              echo "==== Building slim images"
              echo "INCLUDE_ACMS = y" >> rules/config.user
              echo "INCLUDE_MUX = n" >> rules/config.user
              echo "INCLUDE_KUBERNETES = n" >> rules/config.user
              echo "INCLUDE_MACSEC = n" >> rules/config.user
              echo "INCLUDE_P4RT = n" >> rules/config.user
              echo "BUILD_REDUCE_IMAGE_SIZE = y" >> rules/config.user
              echo "INCLUDE_GBSYNCD = n" >> rules/config.user
              echo "INCLUDE_SYSTEM_TELEMETRY = n" >> rules/config.user
              echo "ENABLE_GNMI_TWO_PROCESS = y" >> rules/config.user
              echo "INCLUDE_SYSTEM_EVENTD = n" >> rules/config.user
              make $OPTIONS target/sonic-broadcom.bin target/sonic-aboot-broadcom.swi 2>&1 | tee target/buildslim.log
              mv target/sonic-broadcom.bin target/sonic-broadcom-slim.bin
              mv target/sonic-aboot-broadcom.swi target/sonic-aboot-broadcom-slim.swi
              rm -rf target/*.squashfs
              rm rules/config.user
              mv target/docker-sonic-gnmi.gz target/docker-sonic-gnmi-slim.gz
              echo "==== Finished building slim images"
              echo "==== Building swi images"
              echo "INCLUDE_DHCP_SERVER = y" >> rules/config.user
              make $OPTIONS target/sonic-aboot-broadcom.swi 2>&1 | tee target/buildswi.log
              mv target/sonic-aboot-broadcom.swi target/sonic-aboot-broadcom-dnx.swi target/release/
              rm -rf target/*.squashfs
              rm rules/config.user
              echo "==== Finished building swi images"
              echo "==== Building regular images"
              make $OPTIONS target/sonic-broadcom.bin 2>&1 | tee target/buildregular.log
              mv target/sonic-broadcom.bin target/sonic-broadcom-dnx.bin target/release/
              rm -rf target/*.squashfs
              echo "==== Finished building regular images"
              echo "==== Building syncd-rpc docker"
              make $OPTIONS ENABLE_SYNCD_RPC=y target/docker-syncd-brcm-rpc.gz 2>&1 | tee target/buildrpc.log
              echo "==== Finished building syncd-rpc docker"
              mv target/release/* target/
            displayName: Build SONiC image
          - template: /.pipelines/template-poststeps.yml@self
            parameters:
              PLATFORM_NAME: broadcom
              BRANCH_FOLDER: ${{ parameters.BRANCH_FOLDER }}

    - ${{ if containsValue(parameters.JOBS, 'broadcom-dbg') }}:
      - job: broadcom_dbg
        timeoutInMinutes: 840
        pool:
          type: linux
          isCustom: true
          name: sonicms1ES
        variables:
          ob_artifactBaseName: sonic-buildimage.broadcom-dbg
        steps:
          - template: /.pipelines/template-presteps.yml@self
            parameters:
              PLATFORM_NAME: broadcom
              PLATFORM_ARCH: amd64
              OPTIONS: ${{ parameters.OPTIONS }}
          - script: |
              set -ex
              set -o pipefail

              failures=''
              OPTIONS="${{ parameters.OPTIONS }} ${{ parameters.CACHE }} SONIC_DPKG_CACHE_SOURCE=/nfs/dpkg_cache/broadcom"
              if echo "$(Build.Reason)" | grep -i -e schedule -e pullrequest; then
                OPTIONS+=""
              else
                OPTIONS+=" SONIC_DPKG_CACHE_METHOD_OVERRIDE=rcache BUILD_SKIP_TEST=y"
              fi
              echo "==== Building one debug image"
              make $OPTIONS INSTALL_DEBUG_TOOLS=y target/sonic-broadcom.bin 2>&1 | tee target/builddbg.log
              mv target/sonic-broadcom.bin target/sonic-broadcom-dbg.bin
              echo "==== Finished building one debug image"
            displayName: Build SONiC image
          - template: /.pipelines/template-poststeps.yml@self
            parameters:
              PLATFORM_NAME: broadcom-dbg
              BRANCH_FOLDER: ${{ parameters.BRANCH_FOLDER }}
    - ${{ if containsValue(parameters.JOBS, 'mellanox') }}:
      - job: mellanox
        timeoutInMinutes: 840
        pool:
          type: linux
          isCustom: true
          name: sonicms1ES
        variables:
          ob_artifactBaseName: sonic-buildimage.mellanox
        steps:
          - template: /.pipelines/template-presteps.yml@self
            parameters:
              PLATFORM_NAME: mellanox
              PLATFORM_ARCH: amd64
              OPTIONS: ${{ parameters.OPTIONS }}
          - script: |
              set -ex
              set -o pipefail
              OPTIONS="${{ parameters.OPTIONS }} ${{ parameters.CACHE }} SONIC_DPKG_CACHE_SOURCE=/nfs/dpkg_cache/mellanox"
              if echo "$(Build.Reason)" | grep -i -e schedule -e pullrequest; then
                OPTIONS+=""
              else
                OPTIONS+=" SONIC_DPKG_CACHE_METHOD_OVERRIDE=rcache BUILD_SKIP_TEST=y"
              fi
              make $OPTIONS INCLUDE_VNET_MONITOR=y INCLUDE_DHCP_SERVER=y target/sonic-mellanox.bin 2>&1 | tee target/build.log
              mv target/sonic-mellanox.bin target/release/sonic-mellanox.bin
              make $OPTIONS INCLUDE_VNET_MONITOR=y INCLUDE_SESSION_MONITOR=y target/sonic-mellanox.bin 2>&1 | tee target/build-session-monitor.log
              mv target/sonic-mellanox.bin target/sonic-mellanox-session-monitor.bin
              mv target/release/* target/
              make $OPTIONS ENABLE_SYNCD_RPC=y target/docker-syncd-mlnx-rpc.gz 2>&1 | tee target/buildrpc.log
              cp target/debs/bookworm/python-saithrift*.deb target/
            displayName: Build SONiC image
          - template: /.pipelines/template-poststeps.yml@self
            parameters:
              PLATFORM_NAME: mellanox
              BRANCH_FOLDER: ${{ parameters.BRANCH_FOLDER }}
    - ${{ if containsValue(parameters.JOBS, 'nvidia-bluefield') }}:
      - job: nvidia_bluefield
        timeoutInMinutes: 840
        condition: true
        pool:
          type: linux
          isCustom: true
          name: sonicms1ES-arm64
        variables:
          ob_artifactBaseName: sonic-buildimage.nvidia-bluefield
        steps:
          - template: /.pipelines/template-presteps.yml@self
            parameters:
              PLATFORM_NAME: nvidia-bluefield
              PLATFORM_ARCH: arm64
              OPTIONS: ${{ parameters.OPTIONS }}
          - script: |
              set -ex
              set -o pipefail
              OPTIONS="${{ parameters.OPTIONS }} ${{ parameters.CACHE }} SONIC_DPKG_CACHE_SOURCE=/nfs/dpkg_cache/nvidia-bluefield"
              if echo "$(Build.Reason)" | grep -i -e schedule -e pullrequest; then
                OPTIONS+=""
              else
                OPTIONS+=" SONIC_DPKG_CACHE_METHOD_OVERRIDE=rcache BUILD_SKIP_TEST=y"
              fi
              make $OPTIONS target/sonic-nvidia-bluefield.bin 2>&1 | tee target/build.log
            displayName: Build SONiC image
          - template: /.pipelines/template-poststeps.yml@self
            parameters:
              PLATFORM_NAME: nvidia-bluefield
              BRANCH_FOLDER: ${{ parameters.BRANCH_FOLDER }}
    - ${{ if containsValue(parameters.JOBS, 'marvell-prestera-armhf') }}:
      - job: marvell_prestera_armhf
        timeoutInMinutes: 840
        pool:
          type: linux
          isCustom: true
          name: sonicms1ES-armhf
        variables:
          ob_artifactBaseName: sonic-buildimage.marvell-prestera-armhf
          PLATFORM_ARCH: armhf
        steps:
          - template: /.pipelines/template-presteps.yml@self
            parameters:
              PLATFORM_NAME: marvell-prestera
              PLATFORM_ARCH: armhf
              OPTIONS: ${{ parameters.OPTIONS }}
          - script: |
              set -ex
              set -o pipefail
              OPTIONS="${{ parameters.OPTIONS }} ${{ parameters.CACHE }} SONIC_DPKG_CACHE_SOURCE=/nfs/dpkg_cache/marvell-prestera-armhf INCLUDE_DHCP_SERVER=y"
              if echo "$(Build.Reason)" | grep -i -e schedule -e pullrequest; then
                OPTIONS+=""
              else
                OPTIONS+=" SONIC_DPKG_CACHE_METHOD_OVERRIDE=rcache BUILD_SKIP_TEST=y"
              fi
              make $OPTIONS target/sonic-marvell-prestera-armhf.bin 2>&1 | tee target/build.log
            displayName: Build SONiC image
          - template: /.pipelines/template-poststeps.yml@self
            parameters:
              PLATFORM_NAME: marvell-prestera-armhf
              BRANCH_FOLDER: ${{ parameters.BRANCH_FOLDER }}
    - ${{ if containsValue(parameters.JOBS, 'marvell-prestera-arm64') }}:
      - job: marvell_prestera_arm64
        timeoutInMinutes: 840
        pool:
          type: linux
          isCustom: true
          name: sonicms1ES-arm64
        variables:
          ob_artifactBaseName: sonic-buildimage.marvell-prestera-arm64
          PLATFORM_ARCH: arm64
        steps:
          - template: /.pipelines/template-presteps.yml@self
            parameters:
              PLATFORM_NAME: marvell-prestera
              PLATFORM_ARCH: arm64
              OPTIONS: ${{ parameters.OPTIONS }}
          - script: |
              set -ex
              set -o pipefail
              OPTIONS="${{ parameters.OPTIONS }} ${{ parameters.CACHE }} SONIC_DPKG_CACHE_SOURCE=/nfs/dpkg_cache/marvell-prestera-arm64 INCLUDE_DHCP_SERVER=y"
              if echo "$(Build.Reason)" | grep -i -e schedule -e pullrequest; then
                OPTIONS+=""
              else
                OPTIONS+=" SONIC_DPKG_CACHE_METHOD_OVERRIDE=rcache BUILD_SKIP_TEST=y"
              fi
              make $OPTIONS target/sonic-marvell-prestera-arm64.bin 2>&1 | tee target/build.log
            displayName: Build SONiC image
          - template: /.pipelines/template-poststeps.yml@self
            parameters:
              PLATFORM_NAME: marvell-prestera-arm64
              BRANCH_FOLDER: ${{ parameters.BRANCH_FOLDER }}
    - ${{ if containsValue(parameters.JOBS, 'cisco-8000') }}:
      - template: template-cisco.yml
        parameters:
          NAME: cisco-8000
          OPTIONS: ${{ parameters.OPTIONS }}
          CACHE: ${{ parameters.CACHE }}
          BRANCH_FOLDER: ${{ parameters.BRANCH_FOLDER }}
    - ${{ if containsValue(parameters.JOBS, 'cisco-8000-arm64') }}:
      - template: template-cisco-arm64.yml
        parameters:
          NAME: cisco-8000-arm64
          OPTIONS: ${{ parameters.OPTIONS }}
          CACHE: ${{ parameters.CACHE }}
          BRANCH_FOLDER: ${{ parameters.BRANCH_FOLDER }}
    - ${{ if containsValue(parameters.JOBS, 'pensando') }}:
      - template: template-pensando.yml
        parameters:
          NAME: pensando
          OPTIONS: ${{ parameters.OPTIONS }}
          CACHE: ${{ parameters.CACHE }}
          BRANCH_FOLDER: ${{ parameters.BRANCH_FOLDER }}
- ${{ if eq(variables['System.DefinitionId'], 372481) }}:
  - stage: Summary
    dependsOn:
    - ${{ if or(gt(length(parameters.JOBS), 1), not(containsValue(parameters.JOBS, 'vs'))) }}:
      - Build
    - ${{ if containsValue(parameters.JOBS, 'vs') }}:
      - BuildVS
    condition: and(always(), ne('${{ parameters.BRANCH_FOLDER }}', 'test'))
    jobs:
    - job: analyze_build_result
      pool:
        type: linux
        isCustom: true
        name: sonic-ubuntu-2c
      steps:
      - checkout: none
      - bash: |
          set -ex
          curl -u :$SYSTEM_ACCESSTOKEN https://dev.azure.com/msazure/One/_apis/build/builds/$(Build.BuildId)/timeline?api-version=7.1 > timeline
          cat timeline | jq .records | jq '[.[] | select(.type=="Job" and .result=="failed" and .name!="analyze_build_result" and .name!="Finalize build" and .name!="PolicyValidation" and (.name | contains("kvmtest") | not)) | {name: .name, id: .id, issues: .issues, result: .result, state: .state}]' > failedjobs
          c=$(cat failedjobs | jq length)
          rm -rf log_output
          for i in $(seq 0 $((c-1))); do
            id=$(cat failedjobs | jq .[$i].id -r)
            cat failedjobs | jq -r ".[$i].name | \"- \" + . " >> log_output
            echo "" >> log_output
            cat timeline | jq .records | jq "[.[] | select(.parentId == \"$id\" and .result==\"failed\") ] | .[].name,.[].issues[].message" -r | uniq | sed 's/^/  /' >> log_output
          done
          if [ -e log_output ]; then
            echo "" >> log_output
            echo "https://dev.azure.com/msazure/One/_build/results?buildId=$(Build.BuildId)" >> log_output
            cat log_output
            des=$(cat log_output)
            echo $CERT | base64 -d > cert.pfx
            cert=$(openssl pkcs12 -in cert.pfx -nokeys -nodes -passin pass: | openssl x509 -noout -fingerprint -sha1 | sed 's/^.*=//' | tr -d ':' | tr 'A-Z' 'a-z')
            jq -n --arg des "$des" '{"name":"official_build_failure","description":$des,"client":"https://dev.azure.com/msazure/One/_build?definitionId=372481"}' | curl -H "Content-Type: application/json" -X POST https://notice-center.azurewebsites.net/noti_center/notice -d @- -v -H "thumbprint: $cert"
          fi
        displayName: analyze build result
        env:
          CERT: $(cert-noti)
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
