parameters:
- name: NAME
  values:
  - cisco-8000-arm64
- name: OPTIONS
  type: string
- name: CACHE
  type: string
- name: BRANCH_FOLDER
  type: string

jobs:
  - job: ${{ replace(parameters.NAME, '-', '_') }}
    timeoutInMinutes: 480
    condition: true
    pool:
      type: linux
      isCustom: true
      name: sonicms1ES-arm64
    variables:
      TERM: ''
      SONIC_ENABLE_SECUREBOOT_SIGNATURE: y
      SIGNING_KEY: /etc/certificates/sonic-secure-boot-private.pem
      SIGNING_CERT: $(Build.SourcesDirectory)/target/sonic-secure-boot-public.pem
      ob_artifactBaseName: sonic-buildimage.${{ parameters.NAME }}
    steps:
    - template: /.pipelines/template-presteps.yml@self
      parameters:
        PLATFORM_NAME: cisco-8000
        PLATFORM_ARCH: arm64
        OPTIONS: ${{ parameters.OPTIONS }}
    - template: /.azure-pipelines/azure-pipelines-download-certificate.yml@self
      parameters:
        connectionName: sonic2sub
        kevaultName: sonic-kv
    - script: |
        exit 0
        # disable secure boot for this code drop. cisco will fix in next code drop
        echo $(DEV_SIGNING_KEY) | base64 -d | sudo tee "$(SIGNING_KEY)" 1>/dev/null 2>&1
        echo $(DEV_SIGNING_CERT) | base64 -d > "$(SIGNING_CERT)"
        echo "SECURE_UPGRADE_MODE := dev" >> rules/config.user
        echo "SECURE_UPGRADE_DEV_SIGNING_KEY := $SIGNING_KEY" >> rules/config.user
        echo "SECURE_UPGRADE_SIGNING_CERT := $SIGNING_CERT" >> rules/config.user
      displayName: "Enable secure boot signature"
    - script: |
        cisco_ref=$(cat platform/checkout/${{ parameters.NAME }}.ini | grep '^ref=' | cut -d= -f2)
        echo "The cisco 8000 release version is $cisco_ref"
        echo "##vso[task.setvariable variable=cisco.ref]$cisco_ref"
      displayName: 'Export cisco release version'
    - script: |
        set -ex
        if ! gh --version; then
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y
        fi
        GH_TOKEN=$PAT gh release download -R Cisco-8000-sonic/platform-cisco-8000 $(cisco.ref) --pattern artifactory*
        tar -xzvf artifactory-*.tar.gz -C platform/cisco-8000
      displayName: 'Setup cisco artifacts'
      env:
        PAT: $(TOKEN)
    - script: |
        pushd .
        cd platform/cisco-8000/artifactory/cisco-wb-bsp/
        ln -s bookworm trixie 
        popd
      displayName: 'Create symbol link for trixie'
    - script: |
        rm platform/cisco-8000/platform-setup/.checker
        platform/cisco-8000/platform_setup.sh
      displayName: 'Apply patches for ARM64 on sonic-linux-kernel'
    - script: |
        set -ex
        set -o pipefail
        OPTIONS="${{ parameters.OPTIONS }} ${{ parameters.CACHE }} SONIC_DPKG_CACHE_SOURCE=/nfs/dpkg_cache/${{ parameters.NAME }} ENABLE_NAT=n INCLUDE_VNET_MONITOR=y INCLUDE_DHCP_SERVER=y"
        if echo "$(Build.Reason)" | grep -i -e schedule -e pullrequest; then
          OPTIONS+=""
        else
          OPTIONS+=" SONIC_DPKG_CACHE_METHOD_OVERRIDE=rcache BUILD_SKIP_TEST=y"
        fi
        make $OPTIONS target/sonic-cisco-8000.bin 2>&1 | tee target/build.log
      displayName: Build SONiC image
    - template: /.pipelines/template-poststeps.yml@self
      parameters:
        PLATFORM_NAME: ${{ parameters.NAME }}
        BRANCH_FOLDER: ${{ parameters.BRANCH_FOLDER }}
