# console settings
baud = 115200

# The physical "downstream" device (your Front Panel)
#local-tty = ttySwitchCpu
#local-tty-baud = 115200

# Log file for console output
logfile = /var/log/obmc-console-host-cpu.log

# Maximum log size (20MB)
logsize = 20971520

