# Docker image for smartswitch-azs

DOCKER_SMARTSWITCH_AZS_STEM = docker-smartswitch-azs
DOCKER_SMARTSWITCH_AZS = $(DOCKER_SMARTSWITCH_AZS_STEM).gz
DOCKER_SMARTSWITCH_AZS_DBG = $(DOCKER_SMARTSWITCH_AZS_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_SMARTSWITCH_AZS)_PATH = $(DOCKERS_PATH)/$(DOCKER_SMARTSWITCH_AZS_STEM)

$(DOCKER_SMARTSWITCH_AZS)_PYTHON_WHEELS += $(SONIC_PY_COMMON_PY3) $(SMARTSWITCH_AZS_PY3) $(SCAPY)
$(DOCKER_SMARTSWITCH_AZS)_DEBS_DEPENDS = $(LIBSWSSCOMMON) $(PYTHON3_SWSSCOMMON)
$(DOCKER_SMARTSWITCH_AZS)_DBG_DEPENDS += $(LIBSWSSCOMMON_DBG)

$(DOCKER_SMARTSWITCH_AZS)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_IMAGE_PACKAGES)

$(DOCKER_SMARTSWITCH_AZS)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_BOOKWORM)

$(DOCKER_SMARTSWITCH_AZS)_VERSION = 1.0.0
$(DOCKER_SMARTSWITCH_AZS)_PACKAGE_NAME = smartswitch-azs
$(DOCKER_SMARTSWITCH_AZS)_WARM_SHUTDOWN_BEFORE = swss
$(DOCKER_SMARTSWITCH_AZS)_FAST_SHUTDOWN_BEFORE = swss

ifeq ($(INCLUDE_SMARTSWITCH_AZS), y)
SONIC_DOCKER_IMAGES += $(DOCKER_SMARTSWITCH_AZS)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_SMARTSWITCH_AZS)
endif

ifeq ($(INCLUDE_SMARTSWITCH_AZS), y)
SONIC_DOCKER_DBG_IMAGES += $(DOCKER_SMARTSWITCH_AZS_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_SMARTSWITCH_AZS_DBG)
endif

$(DOCKER_SMARTSWITCH_AZS)_CONTAINER_NAME = smartswitch-azs
$(DOCKER_SMARTSWITCH_AZS)_RUN_OPT += -t
$(DOCKER_SMARTSWITCH_AZS)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_SMARTSWITCH_AZS)_RUN_OPT += -v /etc/network/interfaces:/etc/network/interfaces:ro
$(DOCKER_SMARTSWITCH_AZS)_RUN_OPT += -v /etc/network/interfaces.d/:/etc/network/interfaces.d/:ro
$(DOCKER_SMARTSWITCH_AZS)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)

SONIC_BOOKWORM_DOCKERS += $(DOCKER_SMARTSWITCH_AZS)
SONIC_BOOKWORM_DBG_DOCKERS += $(DOCKER_SMARTSWITCH_AZS_DBG)
