# Docker image for vnet-monitor

DOCKER_VNET_MONITOR_STEM = docker-vnet-monitor
DOCKER_VNET_MONITOR = $(DOCKER_VNET_MONITOR_STEM).gz
DOCKER_VNET_MONITOR_DBG = $(DOCKER_VNET_MONITOR_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_VNET_MONITOR)_PATH = $(DOCKERS_PATH)/$(DOCKER_VNET_MONITOR_STEM)

$(DOCKER_VNET_MONITOR)_PYTHON_WHEELS += $(SONIC_PY_COMMON_PY3) $(VNET_MONITOR_PY3)
$(DOCKER_VNET_MONITOR)_DEBS_DEPENDS = $(LIBSWSSCOMMON) $(PYTHON3_SWSSCOMMON)
$(DOCKER_VNET_MONITOR)_DBG_DEPENDS += $(LIBSWSSCOMMON_DBG)

$(DOCKER_VNET_MONITOR)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BUSTER)_DBG_IMAGE_PACKAGES)

$(DOCKER_VNET_MONITOR)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_BUSTER)

$(DOCKER_VNET_MONITOR)_VERSION = 1.0.0
$(DOCKER_VNET_MONITOR)_PACKAGE_NAME = vnet-monitor
$(DOCKER_VNET_MONITOR)_WARM_SHUTDOWN_BEFORE = swss
$(DOCKER_VNET_MONITOR)_FAST_SHUTDOWN_BEFORE = swss

ifeq ($(INCLUDE_VNET_MONITOR), y)
SONIC_DOCKER_IMAGES += $(DOCKER_VNET_MONITOR)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_VNET_MONITOR)
endif

ifeq ($(INCLUDE_VNET_MONITOR), y)
SONIC_DOCKER_DBG_IMAGES += $(DOCKER_VNET_MONITOR_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_VNET_MONITOR_DBG)
endif

$(DOCKER_VNET_MONITOR)_CONTAINER_NAME = vnet-monitor
$(DOCKER_VNET_MONITOR)_RUN_OPT += --privileged -t
$(DOCKER_VNET_MONITOR)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_VNET_MONITOR)_RUN_OPT += -v /etc/network/interfaces:/etc/network/interfaces:ro
$(DOCKER_VNET_MONITOR)_RUN_OPT += -v /etc/network/interfaces.d/:/etc/network/interfaces.d/:ro
$(DOCKER_VNET_MONITOR)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)

