# docker image for mega (auto-generated by
# optimizations/mega-generic/mega_gen_cli.py --apply -- DO NOT EDIT BY HAND)
# Composed from: swss, bgp, lldp, teamd, mgmt-framework, gnmi, eventd, dhcp_relay
# See optimizations/mega-generic/README.md and the
# generic_mega-container_merge_script plan for the full design.

DOCKER_MEGA_STEM = docker-mega
DOCKER_MEGA = $(DOCKER_MEGA_STEM).gz

$(DOCKER_MEGA)_PATH = $(DOCKERS_PATH)/$(DOCKER_MEGA_STEM)

# --- _INCLUDE_DOCKER: dep union (_DEPENDS/_PYTHON_WHEELS/_FILES) + build
# contexts for every selected feature, handled automatically by
# rules/functions' add_docker_feature/process_include_dockers (plan section 1).
$(DOCKER_MEGA)_INCLUDE_DOCKER += $(DOCKER_ORCHAGENT)
$(DOCKER_MEGA)_INCLUDE_DOCKER += $(DOCKER_FPM_FRR)
$(DOCKER_MEGA)_INCLUDE_DOCKER += $(DOCKER_LLDP)
$(DOCKER_MEGA)_INCLUDE_DOCKER += $(DOCKER_TEAMD)
$(DOCKER_MEGA)_INCLUDE_DOCKER += $(DOCKER_MGMT_FRAMEWORK)
$(DOCKER_MEGA)_INCLUDE_DOCKER += $(DOCKER_GNMI)
$(DOCKER_MEGA)_INCLUDE_DOCKER += $(DOCKER_EVENTD)
$(DOCKER_MEGA)_INCLUDE_DOCKER += $(DOCKER_DHCP_RELAY)

# --- _LOAD_DOCKERS: base layer + per-feature rsync source stage images
# (swss, bgp, lldp, teamd, mgmt-framework, gnmi, eventd, dhcp_relay -- none of the selected
# features have a Dockerfile.common.j2 in this tree, verified at
# generation time, so all of them use the rsync-from-built-image
# strategy here, not just a subset; see gen_mega_mk.py's module
# docstring). gen_dockerfile.py FROMs each as a build stage and
# rsyncs its filesystem in (plan section 6).
$(DOCKER_MEGA)_LOAD_DOCKERS += $(DOCKER_SWSS_LAYER_TRIXIE)
$(DOCKER_MEGA)_LOAD_DOCKERS += $(DOCKER_ORCHAGENT)
$(DOCKER_MEGA)_LOAD_DOCKERS += $(DOCKER_FPM_FRR)
$(DOCKER_MEGA)_LOAD_DOCKERS += $(DOCKER_LLDP)
$(DOCKER_MEGA)_LOAD_DOCKERS += $(DOCKER_TEAMD)
$(DOCKER_MEGA)_LOAD_DOCKERS += $(DOCKER_MGMT_FRAMEWORK)
$(DOCKER_MEGA)_LOAD_DOCKERS += $(DOCKER_GNMI)
$(DOCKER_MEGA)_LOAD_DOCKERS += $(DOCKER_EVENTD)
$(DOCKER_MEGA)_LOAD_DOCKERS += $(DOCKER_DHCP_RELAY)

# --- union of selected features' own _INSTALL_PYTHON_WHEELS ---
$(DOCKER_MEGA)_INSTALL_PYTHON_WHEELS += $(SONIC_UTILITIES_PY3)

# --- union of selected features' own _INSTALL_DEBS ---
$(DOCKER_MEGA)_INSTALL_DEBS += $(PYTHON3_SWSSCOMMON)

$(DOCKER_MEGA)_VERSION = 1.0.0
$(DOCKER_MEGA)_PACKAGE_NAME = mega

SONIC_DOCKER_IMAGES += $(DOCKER_MEGA)
SONIC_TRIXIE_DOCKERS += $(DOCKER_MEGA)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_MEGA)

$(DOCKER_MEGA)_CONTAINER_NAME = mega

# --- _RUN_OPT: union of selected features' own _RUN_OPT, collision-resolved
# (mode conflicts on a shared -v destination default to the more restrictive
# 'ro'; colliding host ports are flagged, not silently merged -- see
# mega_gen.gen_mega_mk.merge_run_opt). NOTE: this covers only the
# Makefile-variable half of docker create's flags -- the per-container-name
# {%- if docker_container_name == "X" %} blocks hardcoded directly into
# docker_image_ctl.j2 (e.g. swss's -e ASIC_VENDOR=..., bgp's frr mount,
# database's $DB_OPT) still need a new 'mega' branch from ctl_parser.py.
$(DOCKER_MEGA)_RUN_OPT += -t
$(DOCKER_MEGA)_RUN_OPT += --cap-add=NET_ADMIN
$(DOCKER_MEGA)_RUN_OPT += --security-opt apparmor=unconfined
$(DOCKER_MEGA)_RUN_OPT += --security-opt="systempaths=unconfined"
$(DOCKER_MEGA)_RUN_OPT += --cap-add=SYS_PTRACE
$(DOCKER_MEGA)_RUN_OPT += --cap-add=SYS_ADMIN
$(DOCKER_MEGA)_RUN_OPT += --mount type=bind,source="/var/platform/",target="/mnt/platform/"
$(DOCKER_MEGA)_RUN_OPT += --pid=host
$(DOCKER_MEGA)_RUN_OPT += --cap-add=SYS_BOOT
$(DOCKER_MEGA)_RUN_OPT += --cap-add=DAC_OVERRIDE
$(DOCKER_MEGA)_RUN_OPT += --security-opt seccomp=unconfined
$(DOCKER_MEGA)_RUN_OPT += --userns=host
$(DOCKER_MEGA)_RUN_OPT += -v /etc/network/interfaces:/etc/network/interfaces:ro
$(DOCKER_MEGA)_RUN_OPT += -v /etc/localtime:/etc/localtime:ro
$(DOCKER_MEGA)_RUN_OPT += -v /etc/network/interfaces.d/:/etc/network/interfaces.d/:ro
$(DOCKER_MEGA)_RUN_OPT += -v /host/machine.conf:/host/machine.conf:ro
$(DOCKER_MEGA)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_MEGA)_RUN_OPT += -v /var/log/swss:/var/log/swss:rw
$(DOCKER_MEGA)_RUN_OPT += -v /zmq_swss:/zmq_swss:rw
$(DOCKER_MEGA)_RUN_OPT += -v /etc:/host_etc:ro
$(DOCKER_MEGA)_RUN_OPT += -v /var/run/dbus:/var/run/dbus:rw
$(DOCKER_MEGA)_RUN_OPT += -v /:/mnt/host:ro
$(DOCKER_MEGA)_RUN_OPT += -v /tmp:/mnt/host/tmp:rw
$(DOCKER_MEGA)_RUN_OPT += -v /var/tmp:/mnt/host/var/tmp:rw
$(DOCKER_MEGA)_RUN_OPT += -v /var/run/gnmi:/var/run/gnmi:rw

# --- warm/fast-reboot shutdown ordering: unioned from selected features'
# own fields, filtering out now-self-referential entries (both endpoints
# merged into this container). Best-effort: no confirmed consumer of
# these fields was found anywhere in this tree; see gen_mega_mk.py.
$(DOCKER_MEGA)_WARM_SHUTDOWN_BEFORE += syncd
$(DOCKER_MEGA)_WARM_SHUTDOWN_AFTER += radv
$(DOCKER_MEGA)_FAST_SHUTDOWN_BEFORE += syncd
$(DOCKER_MEGA)_FAST_SHUTDOWN_AFTER += radv

# --- _BASE_IMAGE_FILES: union of selected features' host CLI wrappers /
# monit configs, retargeted from their own container name to 'mega'
# (mega_gen.gen_mega_mk.retarget_container_refs). Physical files live under
# $(DOCKER_MEGA)_PATH/base_image_files/.
$(DOCKER_MEGA)_BASE_IMAGE_FILES += swssloglevel:/usr/bin/swssloglevel
$(DOCKER_MEGA)_BASE_IMAGE_FILES += vtysh:/usr/bin/vtysh
$(DOCKER_MEGA)_BASE_IMAGE_FILES += rvtysh:/usr/bin/rvtysh
$(DOCKER_MEGA)_BASE_IMAGE_FILES += TSA:/usr/bin/TSA
$(DOCKER_MEGA)_BASE_IMAGE_FILES += TSB:/usr/bin/TSB
$(DOCKER_MEGA)_BASE_IMAGE_FILES += TSC:/usr/bin/TSC
$(DOCKER_MEGA)_BASE_IMAGE_FILES += TS:/usr/bin/TS
$(DOCKER_MEGA)_BASE_IMAGE_FILES += platform_utils:/usr/bin/platform_utils
$(DOCKER_MEGA)_BASE_IMAGE_FILES += idf_isolation:/usr/bin/idf_isolation
$(DOCKER_MEGA)_BASE_IMAGE_FILES += prefix_list:/usr/bin/prefix_list
$(DOCKER_MEGA)_BASE_IMAGE_FILES += lldpctl:/usr/bin/lldpctl
$(DOCKER_MEGA)_BASE_IMAGE_FILES += lldpcli:/usr/bin/lldpcli
$(DOCKER_MEGA)_BASE_IMAGE_FILES += teamdctl:/usr/bin/teamdctl
$(DOCKER_MEGA)_BASE_IMAGE_FILES += sonic-cli:/usr/bin/sonic-cli
$(DOCKER_MEGA)_BASE_IMAGE_FILES += monit_gnmi:/etc/monit/conf.d
