# docker image for gribi

DOCKER_GRIBI_STEM = docker-sonic-gribi
DOCKER_GRIBI = $(DOCKER_GRIBI_STEM).gz
DOCKER_GRIBI_DBG = $(DOCKER_GRIBI_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_GRIBI)_PATH = $(DOCKERS_PATH)/$(DOCKER_GRIBI_STEM)

$(DOCKER_GRIBI)_DEPENDS += $(SONIC_GRIBI)
$(DOCKER_GRIBI)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_TRIXIE)_DBG_DEPENDS)
$(DOCKER_GRIBI)_DBG_DEPENDS += $(SONIC_GRIBI_DBG)
$(DOCKER_GRIBI)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_TRIXIE)_DBG_IMAGE_PACKAGES)

$(DOCKER_GRIBI)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_TRIXIE)

$(DOCKER_GRIBI)_VERSION = 1.0.0
$(DOCKER_GRIBI)_PACKAGE_NAME = gribi
$(DOCKER_GRIBI)_WARM_SHUTDOWN_BEFORE = swss
$(DOCKER_GRIBI)_FAST_SHUTDOWN_BEFORE = swss

SONIC_DOCKER_IMAGES += $(DOCKER_GRIBI)
SONIC_TRIXIE_DOCKERS += $(DOCKER_GRIBI)
SONIC_DOCKER_DBG_IMAGES += $(DOCKER_GRIBI_DBG)
SONIC_TRIXIE_DBG_DOCKERS += $(DOCKER_GRIBI_DBG)

ifeq ($(INCLUDE_GRIBI), y)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_GRIBI)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_GRIBI_DBG)
endif

$(DOCKER_GRIBI)_CONTAINER_NAME = gribi
$(DOCKER_GRIBI)_RUN_OPT += -t
$(DOCKER_GRIBI)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_GRIBI)_RUN_OPT += -v /etc/localtime:/etc/localtime:ro
$(DOCKER_GRIBI)_GIT_COMMIT = $(shell cd "$($(SONIC_GRIBI)_SRC_PATH)" && git log -n 1 --format=format:"%H %s" || echo "Unable to fetch git log for gribi")
