# Docker image for L2MCD
DOCKER_L2MCD_STEM = docker-l2mcd
DOCKER_L2MCD = $(DOCKER_L2MCD_STEM).gz
DOCKER_L2MCD_DBG = $(DOCKER_L2MCD_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_L2MCD)_PATH = $(DOCKERS_PATH)/docker-l2mcd

$(DOCKER_L2MCD)_DEPENDS += $(LIBEVENT) $(L2MCD) $(SWSS) $(LIBSWSSCOMMON)
$(DOCKER_L2MCD)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_DEPENDS)
$(DOCKER_L2MCD)_DBG_DEPENDS += $(SWSS_DBG) $(LIBSWSSCOMMON_DBG)
$(DOCKER_L2MCD)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_IMAGE_PACKAGES)

$(DOCKER_L2MCD)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BOOKWORM)

ifeq ($(INCLUDE_L2MCD), y)
SONIC_DOCKER_IMAGES += $(DOCKER_L2MCD)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_L2MCD)
SONIC_DOCKER_DBG_IMAGES += $(DOCKER_L2MCD_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_L2MCD_DBG)
endif

$(DOCKER_L2MCD)_VERSION = 1.0.0
$(DOCKER_L2MCD)_PACKAGE_NAME = l2mcd
$(DOCKER_L2MCD)_CONTAINER_NAME = l2mcd
$(DOCKER_L2MCD)_RUN_OPT += --privileged -t
$(DOCKER_L2MCD)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_L2MCD)_RUN_OPT += -v /host/warmboot:/var/warmboot

SONIC_BOOKWORM_DOCKERS += $(DOCKER_L2MCD)
SONIC_BOOKWORM_DBG_DOCKERS += $(DOCKER_L2MCD_DBG)
