# docker image for acms watchdog

DOCKER_ACMS_WATCHDOG_STEM = docker-acms-watchdog
DOCKER_ACMS_WATCHDOG = $(DOCKER_ACMS_WATCHDOG_STEM).gz
DOCKER_ACMS_WATCHDOG_DBG = $(DOCKER_ACMS_WATCHDOG_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_ACMS_WATCHDOG)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_BOOKWORM)

$(DOCKER_ACMS_WATCHDOG)_PATH = $(DOCKERS_PATH)/$(DOCKER_ACMS_WATCHDOG_STEM)

$(DOCKER_ACMS_WATCHDOG)_VERSION = 1.0.0
$(DOCKER_ACMS_WATCHDOG)_PACKAGE_NAME = acms_watchdog

ifeq ($(INCLUDE_ACMS), y)
SONIC_DOCKER_IMAGES += $(DOCKER_ACMS_WATCHDOG)
SONIC_BOOKWORM_DOCKERS += $(DOCKER_ACMS_WATCHDOG)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_ACMS_WATCHDOG)
endif

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_ACMS_WATCHDOG_DBG)
SONIC_BOOKWORM_DBG_DOCKERS += $(DOCKER_ACMS_WATCHDOG_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_ACMS_WATCHDOG_DBG)

$(DOCKER_ACMS_WATCHDOG)_CONTAINER_NAME = acms_watchdog
$(DOCKER_ACMS_WATCHDOG)_RUN_OPT += -t --privileged --pid=host
$(DOCKER_ACMS_WATCHDOG)_RUN_OPT += -v /lib/systemd/system:/lib/systemd/system:rw
$(DOCKER_ACMS_WATCHDOG)_RUN_OPT += -v /etc/audit:/etc/audit:rw
$(DOCKER_ACMS_WATCHDOG)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_ACMS_WATCHDOG)_RUN_OPT += -v /etc/localtime:/etc/localtime:ro

$(DOCKER_ACMS_WATCHDOG)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)
