# trixie-based docker image for sonic swss layer

DOCKER_SWSS_LAYER_RESOLUTE = docker-swss-layer-resolute.gz
$(DOCKER_SWSS_LAYER_RESOLUTE)_PATH = $(DOCKERS_PATH)/docker-swss-layer-resolute

$(DOCKER_SWSS_LAYER_RESOLUTE)_DEPENDS += $(SWSS)
$(DOCKER_SWSS_LAYER_RESOLUTE)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_RESOLUTE)

$(DOCKER_SWSS_LAYER_RESOLUTE)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_RESOLUTE)_DBG_DEPENDS) \
                                             $(SWSS_DBG)
$(DOCKER_SWSS_LAYER_RESOLUTE)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_RESOLUTE)_DBG_IMAGE_PACKAGES)

SONIC_DOCKER_IMAGES += $(DOCKER_SWSS_LAYER_RESOLUTE)
SONIC_RESOLUTE_DOCKERS += $(DOCKER_SWSS_LAYER_RESOLUTE)
