# Docker image for session-monitor

DOCKER_SESSION_MONITOR_STEM = docker-session-monitor
DOCKER_SESSION_MONITOR = $(DOCKER_SESSION_MONITOR_STEM).gz
DOCKER_SESSION_MONITOR_DBG = $(DOCKER_SESSION_MONITOR_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_SESSION_MONITOR)_PATH = $(DOCKERS_PATH)/$(DOCKER_SESSION_MONITOR_STEM)

$(DOCKER_SESSION_MONITOR)_PYTHON_WHEELS += $(SONIC_PY_COMMON_PY3) $(SESSION_MONITOR_PY3) $(SCAPY)
$(DOCKER_SESSION_MONITOR)_DEBS_DEPENDS = $(LIBSWSSCOMMON) $(PYTHON3_SWSSCOMMON)
$(DOCKER_SESSION_MONITOR)_DBG_DEPENDS += $(LIBSWSSCOMMON_DBG)

$(DOCKER_SESSION_MONITOR)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_IMAGE_PACKAGES)

$(DOCKER_SESSION_MONITOR)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_BOOKWORM)

$(DOCKER_SESSION_MONITOR)_VERSION = 1.0.0
$(DOCKER_SESSION_MONITOR)_PACKAGE_NAME = session-monitor
$(DOCKER_SESSION_MONITOR)_WARM_SHUTDOWN_BEFORE = swss
$(DOCKER_SESSION_MONITOR)_FAST_SHUTDOWN_BEFORE = swss

ifeq ($(INCLUDE_SESSION_MONITOR), y)
SONIC_DOCKER_IMAGES += $(DOCKER_SESSION_MONITOR)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_SESSION_MONITOR)
endif

ifeq ($(INCLUDE_SESSION_MONITOR), y)
SONIC_DOCKER_DBG_IMAGES += $(DOCKER_SESSION_MONITOR_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_SESSION_MONITOR_DBG)
endif

$(DOCKER_SESSION_MONITOR)_CONTAINER_NAME = session-monitor
$(DOCKER_SESSION_MONITOR)_RUN_OPT += -t
$(DOCKER_SESSION_MONITOR)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_SESSION_MONITOR)_RUN_OPT += -v /etc/network/interfaces:/etc/network/interfaces:ro
$(DOCKER_SESSION_MONITOR)_RUN_OPT += -v /etc/network/interfaces.d/:/etc/network/interfaces.d/:ro
$(DOCKER_SESSION_MONITOR)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)

SONIC_BOOKWORM_DOCKERS += $(DOCKER_SESSION_MONITOR)
SONIC_BOOKWORM_DBG_DOCKERS += $(DOCKER_SESSION_MONITOR_DBG)
