# docker image for docker-gnmi-sidecar

DOCKER_GNMI_SIDECAR_STEM = docker-gnmi-sidecar
DOCKER_GNMI_SIDECAR = $(DOCKER_GNMI_SIDECAR_STEM).gz
DOCKER_GNMI_SIDECAR_DBG = $(DOCKER_GNMI_SIDECAR_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_GNMI_SIDECAR)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_BOOKWORM)

$(DOCKER_GNMI_SIDECAR)_PATH = $(DOCKERS_PATH)/$(DOCKER_GNMI_SIDECAR_STEM)

$(DOCKER_GNMI_SIDECAR)_VERSION = 1.0.0
$(DOCKER_GNMI_SIDECAR)_PACKAGE_NAME = gnmi-sidecar

SONIC_DOCKER_IMAGES += $(DOCKER_GNMI_SIDECAR)
SONIC_BOOKWORM_DOCKERS += $(DOCKER_GNMI_SIDECAR)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_GNMI_SIDECAR)

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_GNMI_SIDECAR_DBG)
SONIC_BOOKWORM_DBG_DOCKERS += $(DOCKER_GNMI_SIDECAR_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_GNMI_SIDECAR_DBG)


$(DOCKER_GNMI_SIDECAR)_DEPENDS += $(LIBSWSSCOMMON)
$(DOCKER_GNMI_SIDECAR)_INSTALL_DEBS = $(LIBSWSSCOMMON) \
                                       $(PYTHON3_SWSSCOMMON) \
                                       $(LIBYANG_PY3)

$(DOCKER_GNMI_SIDECAR)_CONTAINER_NAME = gnmi-sidecar
$(DOCKER_GNMI_SIDECAR)_RUN_OPT += -t --privileged --pid=host
$(DOCKER_GNMI_SIDECAR)_RUN_OPT += -v /lib/systemd/system:/lib/systemd/system:rw
$(DOCKER_GNMI_SIDECAR)_RUN_OPT += -v /etc/audit:/etc/audit:rw
$(DOCKER_GNMI_SIDECAR)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_GNMI_SIDECAR)_RUN_OPT += -v /etc/localtime:/etc/localtime:ro

$(DOCKER_GNMI_SIDECAR)_FILES += $(CONTAINER_CHECKER)
$(DOCKER_GNMI_SIDECAR)_FILES += $(GNMI_SYSTEMD)
$(DOCKER_GNMI_SIDECAR)_FILES += $(K8S_POD_CONTROL)
