# docker image for azure profiler

DOCKER_PROFILER_STEM = docker-sonic-profiler
DOCKER_PROFILER = $(DOCKER_PROFILER_STEM).gz
DOCKER_PROFILER_DBG = $(DOCKER_PROFILER_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_PROFILER)_PATH = $(DOCKERS_PATH)/$(DOCKER_PROFILER_STEM)

$(DOCKER_PROFILER)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_DEPENDS)
$(DOCKER_PROFILER)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BOOKWORM)
$(DOCKER_PROFILER)_VERSION = 1.0.0
$(DOCKER_PROFILER)_PACKAGE_NAME = profiler
$(DOCKER_PROFILER)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_IMAGE_PACKAGES)

SONIC_DOCKER_IMAGES += $(DOCKER_PROFILER)
SONIC_BOOKWORM_DOCKERS += $(DOCKER_PROFILER)
ifeq ($(INCLUDE_SYSTEM_PROFILER), y)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_PROFILER)
endif

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_PROFILER_DBG)
SONIC_BOOKWORM_DBG_DOCKERS += $(DOCKER_PROFILER_DBG)
ifeq ($(INCLUDE_SYSTEM_PROFILER), y)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_PROFILER_DBG)
endif

$(DOCKER_PROFILER)_CONTAINER_NAME = profiler
$(DOCKER_PROFILER)_RUN_OPT += -t
$(DOCKER_PROFILER)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_PROFILER)_RUN_OPT += -v /etc/localtime:/etc/localtime:ro
$(DOCKER_PROFILER)_RUN_OPT += -v /:/mnt/host:ro
$(DOCKER_PROFILER)_RUN_OPT += -v /tmp:/mnt/host/tmp:rw
$(DOCKER_PROFILER)_RUN_OPT += -v /var/tmp:/mnt/host/var/tmp:rw
$(DOCKER_PROFILER)_RUN_OPT += --pid=host
$(DOCKER_PROFILER)_RUN_OPT += --privileged
$(DOCKER_PROFILER)_RUN_OPT += --userns=host

$(DOCKER_PROFILER)_BASE_IMAGE_FILES += monit_profiler:/etc/monit/conf.d
