# gperftools (google-perftools) - tcmalloc

GPERFTOOLS_VERSION = 2.10
GPERFTOOLS_SUBVERSION = 1

export GPERFTOOLS_VERSION
export GPERFTOOLS_SUBVERSION

LIBTCMALLOC = libtcmalloc-minimal4_$(GPERFTOOLS_VERSION)-$(GPERFTOOLS_SUBVERSION)_$(CONFIGURED_ARCH).deb
$(LIBTCMALLOC)_SRC_PATH = $(SRC_PATH)/gperftools
SONIC_MAKE_DEBS += $(LIBTCMALLOC)

LIBGOOGLE_PERFTOOLS_DEV = libgoogle-perftools-dev_$(GPERFTOOLS_VERSION)-$(GPERFTOOLS_SUBVERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(LIBTCMALLOC),$(LIBGOOGLE_PERFTOOLS_DEV)))

LIBGOOGLE_PERFTOOLS4 = libgoogle-perftools4_$(GPERFTOOLS_VERSION)-$(GPERFTOOLS_SUBVERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(LIBTCMALLOC),$(LIBGOOGLE_PERFTOOLS4)))

export LIBTCMALLOC LIBGOOGLE_PERFTOOLS_DEV LIBGOOGLE_PERFTOOLS4
