# iproute2 - built from Salsa (Debian) packaging with EVPN MH patch

IPROUTE2_VERSION = 6.12.0
IPROUTE2_SUBVERSION = 1-sonic.0

export IPROUTE2_VERSION IPROUTE2_SUBVERSION
export IPROUTE2
export IPROUTE2_DBG

IPROUTE2 = iproute2_$(IPROUTE2_VERSION)-$(IPROUTE2_SUBVERSION)_$(CONFIGURED_ARCH).deb
$(IPROUTE2)_SRC_PATH = $(SRC_PATH)/iproute2
SONIC_MAKE_DEBS += $(IPROUTE2)

IPROUTE2_DBG = iproute2-dbgsym_$(IPROUTE2_VERSION)-$(IPROUTE2_SUBVERSION)_$(CONFIGURED_ARCH).deb
$(IPROUTE2_DBG)_DEPENDS += $(IPROUTE2)
$(IPROUTE2_DBG)_RDEPENDS += $(IPROUTE2)
$(eval $(call add_derived_package,$(IPROUTE2),$(IPROUTE2_DBG)))
