# ndppd package

NDPPD_VERSION = 0.2.5
NDPPD_VERSION_FULL = $(NDPPD_VERSION)-6
NDPPD_VERSION_SONIC = $(NDPPD_VERSION_FULL)+sonic1

NDPPD = ndppd_$(NDPPD_VERSION_SONIC)_$(CONFIGURED_ARCH).deb
$(NDPPD)_SRC_PATH = $(SRC_PATH)/ndppd
SONIC_MAKE_DEBS += $(NDPPD)

NDPPD_DBG = ndppd-dbgsym_$(NDPPD_VERSION_SONIC)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(NDPPD),$(NDPPD_DBG)))

export NDPPD_VERSION
export NDPPD_VERSION_FULL
export NDPPD_VERSION_SONIC
export NDPPD
export NDPPD_DBG

DBG_SRC_ARCHIVE += ndppd
