# smartswitch-azs python wheel

SESSION_MONITOR_PY3 = sonic_SESSION_MONITOR-1.0-py3-none-any.whl
$(SESSION_MONITOR_PY3)_SRC_PATH = $(SRC_PATH)/session-monitor
$(SESSION_MONITOR_PY3)_PYTHON_VERSION = 3

$(SESSION_MONITOR_PY3)_DEPENDS += $(SONIC_PY_COMMON_PY3) $(SCAPY)
$(SESSION_MONITOR_PY3)_DEBS_DEPENDS = $(PYTHON3_SWSSCOMMON)

SONIC_PYTHON_WHEELS += $(SESSION_MONITOR_PY3)