# smartswitch-azs python wheel

SMARTSWITCH_AZS_PY3 = sonic_smartswitch_azs-1.0-py3-none-any.whl
$(SMARTSWITCH_AZS_PY3)_SRC_PATH = $(SRC_PATH)/smartswitch-azs
$(SMARTSWITCH_AZS_PY3)_PYTHON_VERSION = 3

$(SMARTSWITCH_AZS_PY3)_DEPENDS += $(SONIC_PY_COMMON_PY3) $(SCAPY)
$(SMARTSWITCH_AZS_PY3)_DEBS_DEPENDS = $(PYTHON3_SWSSCOMMON)

SONIC_PYTHON_WHEELS += $(SMARTSWITCH_AZS_PY3)