# SONiC host userd binary package

SONIC_HOST_USERD = sonic-host-userd_1.0-1_$(CONFIGURED_ARCH).deb
$(SONIC_HOST_USERD)_SRC_PATH = $(SRC_PATH)/sonic-host-services/userd
$(SONIC_HOST_USERD)_DEPENDS += $(LIBSWSSCOMMON_DEV)
$(SONIC_HOST_USERD)_RDEPENDS += $(SONIC_HOST_SERVICES_DATA) $(LIBSWSSCOMMON)
SONIC_DPKG_DEBS += $(SONIC_HOST_USERD)
