# SONiC host services package

SONIC_HOST_SERVICES_PY3 = sonic_host_services-1.0-py3-none-any.whl
$(SONIC_HOST_SERVICES_PY3)_SRC_PATH = $(SRC_PATH)/sonic-host-services
$(SONIC_HOST_SERVICES_PY3)_PYTHON_VERSION = 3
$(SONIC_HOST_SERVICES_PY3)_DEPENDS += $(SONIC_PY_COMMON_PY3) \
                                      $(SONIC_UTILITIES_PY3)
$(SONIC_HOST_SERVICES_PY3)_DEBS_DEPENDS = $(LIBSWSSCOMMON) \
                                          $(PYTHON3_SWSSCOMMON)
SONIC_PYTHON_WHEELS += $(SONIC_HOST_SERVICES_PY3)

# SONiC host services binary package (C++ userd daemon)
SONIC_HOST_SERVICES = sonic-host-services_1.0-1_$(CONFIGURED_ARCH).deb
$(SONIC_HOST_SERVICES)_SRC_PATH = $(SRC_PATH)/sonic-host-services
$(SONIC_HOST_SERVICES)_DEPENDS += $(LIBSWSSCOMMON_DEV)
$(SONIC_HOST_SERVICES)_RDEPENDS += $(SONIC_HOST_SERVICES_DATA) $(LIBSWSSCOMMON)
SONIC_DPKG_DEBS += $(SONIC_HOST_SERVICES)
