SONIC_THERMALCTLD_RS_VERSION = 1.0.0
SONIC_THERMALCTLD_RS_NAME = sonic-thermalctld-rs

SONIC_THERMALCTLD_RS = $(SONIC_THERMALCTLD_RS_NAME)_$(SONIC_THERMALCTLD_RS_VERSION)_$(CONFIGURED_ARCH).deb
$(SONIC_THERMALCTLD_RS)_SRC_PATH = $(SRC_PATH)/sonic-platform-daemons
$(SONIC_THERMALCTLD_RS)_VERSION = $(SONIC_THERMALCTLD_RS_VERSION)
$(SONIC_THERMALCTLD_RS)_NAME = $(SONIC_THERMALCTLD_RS_NAME)
$(SONIC_THERMALCTLD_RS)_DEPENDS = $(LIBSWSSCOMMON_DEV)
$(SONIC_THERMALCTLD_RS)_RDEPENDS = $(LIBSWSSCOMMON)

# Vendor-neutral: this file names no vendor.  A platform opts in from its own
# platform/<vendor>/rules.mk by supplying _BUILD_ENV and appending the package
# to $(DOCKER_PLATFORM_MONITOR)_DEPENDS, which is what causes it to be built.
SONIC_DPKG_DEBS += $(SONIC_THERMALCTLD_RS)

SONIC_THERMALCTLD_RS_DBG = $(SONIC_THERMALCTLD_RS_NAME)-dbgsym_$(SONIC_THERMALCTLD_RS_VERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(SONIC_THERMALCTLD_RS),$(SONIC_THERMALCTLD_RS_DBG)))
