
SONIC_CONTAINERCFGD_RS_NAME = sonic-containercfgd-rs
SONIC_CONTAINERCFGD_RS_VERSION = 1.0.0
SONIC_CONTAINERCFGD_RS = $(SONIC_CONTAINERCFGD_RS_NAME)_$(SONIC_CONTAINERCFGD_RS_VERSION)_$(CONFIGURED_ARCH).deb
$(SONIC_CONTAINERCFGD_RS)_SRC_PATH = $(SRC_PATH)/sonic-containercfgd-rs
$(SONIC_CONTAINERCFGD_RS)_DEPENDS = $(LIBSWSSCOMMON_DEV)
$(SONIC_CONTAINERCFGD_RS)_RDEPENDS = $(LIBSWSSCOMMON)
SONIC_DPKG_DEBS += $(SONIC_CONTAINERCFGD_RS)

SONIC_CONTAINERCFGD_RS_DBGSYM = $(SONIC_CONTAINERCFGD_RS_NAME)-dbgsym_$(SONIC_CONTAINERCFGD_RS_VERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(SONIC_CONTAINERCFGD_RS),$(SONIC_CONTAINERCFGD_RS_DBGSYM)))
