# sonic-acms python3 wheel

SONIC_ACMS_PY3 = sonic_acms-1.0-py3-none-any.whl
$(SONIC_ACMS_PY3)_SRC_PATH = $(SRC_PATH)/sonic-acms
$(SONIC_ACMS_PY3)_PYTHON_VERSION = 3
$(SONIC_ACMS_PY3)_DEBS_DEPENDS = $(PYTHON3_SWSSCOMMON)
$(SONIC_ACMS_PY3)_DEPENDS =  $(SONIC_PY_COMMON_PY3)
$(SONIC_ACMS_PY3)_RDEPENDS = 


SONIC_PYTHON_WHEELS += $(SONIC_ACMS_PY3)
