# SONIE UKI (Recovery Image) rule

# Define the target based on the configured platform
SONIE_UKI = sonie-$(CONFIGURED_PLATFORM).efi

$(SONIE_UKI)_MACHINE = $(CONFIGURED_PLATFORM)
$(SONIE_UKI)_IMAGE_TYPE = recovery

$(SONIE_UKI)_INSTALLS += $($(SONIC_ONE_IMAGE)_INSTALLS)
$(SONIE_UKI)_LAZY_INSTALLS += $($(SONIC_ONE_IMAGE)_LAZY_INSTALLS)
$(SONIE_UKI)_DOCKERS += $(DOCKER_DATABASE)
$(SONIE_UKI)_DOCKERS += $(DOCKER_ORCHAGENT)
$(SONIE_UKI)_DOCKERS += $(DOCKER_PLATFORM_MONITOR)
$(SONIE_UKI)_DOCKERS += $(DOCKER_SYNCD_BASE)

SONIC_INSTALLERS += $(SONIE_UKI)
