SYSLOG-COUNTER_VERSION = 1.0.0
export SYSLOG-COUNTER_VERSION

SYSLOG-COUNTER = syslog-counter_$(SYSLOG-COUNTER_VERSION).deb
$(SYSLOG-COUNTER)_DEPENDS += $(LIBSWSSCOMMON_DEV)
$(SYSLOG-COUNTER)_RDEPENDS +=  $(LIBSWSSCOMMON)
$(SYSLOG-COUNTER)_SRC_PATH = $(SRC_PATH)/syslog-counter
SONIC_DPKG_DEBS += $(SYSLOG-COUNTER)
