SYSLOG-COUNTER_VERSION = 1.0.0-1
export SYSLOG-COUNTER_VERSION

SYSLOG-COUNTER = syslog-counter_$(SYSLOG-COUNTER_VERSION)_$(CONFIGURED_ARCH).deb
$(SYSLOG-COUNTER)_DEPENDS += $(LIBSWSSCOMMON_DEV)
$(SYSLOG-COUNTER)_RDEPENDS +=  $(LIBSWSSCOMMON)
$(SYSLOG-COUNTER)_SRC_PATH = $(SRC_PATH)/syslog-counter
SONIC_MAKE_DEBS += $(SYSLOG-COUNTER)
