# vnet-monitor python wheel

VNET_MONITOR_PY3 = sonic_vnet_monitor-1.0-py3-none-any.whl
$(VNET_MONITOR_PY3)_SRC_PATH = $(SRC_PATH)/vnet-monitor
$(VNET_MONITOR_PY3)_PYTHON_VERSION = 3

$(VNET_MONITOR_PY3)_DEPENDS += $(SONIC_PY_COMMON_PY3) 
$(VNET_MONITOR_PY3)_DEBS_DEPENDS = $(PYTHON3_SWSSCOMMON)

SONIC_PYTHON_WHEELS += $(VNET_MONITOR_PY3)