# sonic vs minion docker image

SONIC_MINION_ROOTFS = sonic-minion-vs-root.tar.gz
DOCKER_SONIC_MINION_VS = docker-sonic-minion-vs.gz

$(SONIC_MINION_ROOTFS)_SRC_PATH = $(PLATFORM_PATH)/docker-sonic-minion-vs
$(DOCKER_SONIC_MINION_VS)_AFTER += $(SONIC_KVM_IMAGE)
$(DOCKER_SONIC_MINION_VS)_PATH = $(PLATFORM_PATH)/docker-sonic-minion-vs
$(DOCKER_SONIC_MINION_VS)_FILES = $(SONIC_MINION_ROOTFS)


SONIC_MAKE_FILES += $(SONIC_MINION_ROOTFS)
SONIC_DOCKER_IMAGES += $(DOCKER_SONIC_MINION_VS)

SONIC_BOOKWORM_DOCKERS += $(DOCKER_SONIC_MINION_VS)

SONIC_PHONY_TARGETS += $(addprefix $(FILES_PATH)/, $(SONIC_MINION_ROOTFS))

