# docker image for docker-ptf-sai

DOCKER_PTF_SAI = docker-ptf-sai.gz
DOCKER_PTF_BASE = docker-ptf.gz
$(DOCKER_PTF_SAI)_PATH = $(DOCKERS_PATH)/docker-ptf-sai
ifeq ($(SONIC_PTF_ENV_PY_VER), mixed)
$(DOCKER_PTF_SAI)_DEPENDS += $(LIBTHRIFT) $(PYTHON_THRIFT) $(PTF) $(PYTHON_SAITHRIFT)
else
$(DOCKER_PTF_SAI)_DEPENDS += $(PYTHON_SAITHRIFT)
endif
$(DOCKER_PTF_SAI)_LOAD_DOCKERS += $(DOCKER_PTF_BASE)
SONIC_DOCKER_IMAGES += $(DOCKER_PTF_SAI)
SONIC_BOOKWORM_DOCKERS += $(DOCKER_PTF_SAI)
