# sonic-stel kernel module (stream telemetry genetlink)

SONIC_STEL_VERSION = 1.0-1
SONIC_STEL_KO_NAME = sonic-stel-module

SONIC_STEL_MODULE = $(SONIC_STEL_KO_NAME)_$(SONIC_STEL_VERSION)_$(CONFIGURED_ARCH).deb
$(SONIC_STEL_MODULE)_SRC_PATH = $(PLATFORM_PATH)/$(SONIC_STEL_KO_NAME)
$(SONIC_STEL_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
SONIC_DPKG_DEBS += $(SONIC_STEL_MODULE)
