# Lucius libsai package

LEMMINGSAI_VERSION = 1.0-3
LEMMINGSAI_LIB_NAME = lucius-libsai
LEMMINGSAI_LIB_DIR = sonic-alpine/libsai-grpc

LEMMINGSAI = $(LEMMINGSAI_LIB_NAME)_$(LEMMINGSAI_VERSION)_$(CONFIGURED_ARCH).deb
$(LEMMINGSAI)_SRC_PATH = $(SRC_PATH)/$(LEMMINGSAI_LIB_DIR)
SONIC_DPKG_DEBS += $(LEMMINGSAI)
