# sonic alpinevs raw image installer

SONIC_RAW_IMAGE = sonic-alpinevs.raw
$(SONIC_RAW_IMAGE)_MACHINE = alpinevs
$(SONIC_RAW_IMAGE)_IMAGE_TYPE = raw
$(SONIC_RAW_IMAGE)_INSTALLS += $(SYSTEMD_SONIC_GENERATOR)
$(SONIC_RAW_IMAGE)_DOCKERS += $(SONIC_INSTALL_DOCKER_IMAGES)
SONIC_INSTALLERS += $(SONIC_RAW_IMAGE)
