steps:
- script: |
    if [ -z "$(SUBMODULE_NAME)" ]; then
      git checkout $(COMMIT_ID)
    else
      git submodule update --init --recursive
      cd src/$(SUBMODULE_NAME)
      git checkout $(COMMIT_ID)
    fi
