# The azure pipeline template for Official build, and upgrade version build

parameters:
- name: 'jobFilters'
  type: object
  default: ''
- name: 'buildOptions'
  type: string
  default: 'SONIC_CONFIG_BUILD_JOBS=1'
- name: 'preSteps'
  type: stepList
  default: []
- name: 'postSteps'
  type: stepList
  default: []
- name: 'jobGroups'
  type: object
  default: ''
- name: 'qemuOrCrossBuild'
  type: boolean
  default: false
- name: SUBMODULE
  type: string
  default: ''
- name: COMMIT_ID
  type: string
  default: ''

jobs:
- template: azure-pipelines-image-template.yml
  parameters:
    jobFilters: ${{ parameters.jobFilters }}
    preSteps: ${{ parameters.preSteps }}
    postSteps: ${{ parameters.postSteps }}
    SUBMODULE: ${{ parameters.SUBMODULE }}
    COMMIT_ID: ${{ parameters.COMMIT_ID }}
    jobVariables:
      PLATFORM_AZP: $(GROUP_NAME)
      PLATFORM_ARCH: amd64
      BUILD_NUMBER: $(Build.BuildId)
      BUILD_OPTIONS: ${{ parameters.buildOptions }}
      DOCKER_DATA_ROOT_FOR_MULTIARCH: /data/march/docker
      dbg_image: no
      asan_image: no
      swi_image: no
      docker_syncd_rpc_image: no
      syncd_rpc_image: no
      platform_rpc: no
      ${{ if parameters.qemuOrCrossBuild }}:
        SONIC_SLAVE_DOCKER_DRIVER: 'vfs'
        CACHE_MODE: 'none'
    ${{ if ne(parameters.jobGroups, '') }}:
      jobGroups: ${{ parameters.jobGroups }}
    ${{ if eq(parameters.jobGroups, '') }}:
      jobGroups:
        - name: vs
          variables:
            dbg_image: yes
            asan_image: yes

        - name: barefoot
          variables:
            docker_syncd_rpc_image: yes
            platform_rpc: bfn
            swi_image: yes

        - name: broadcom
          timeoutInMinutes: 1440
          variables:
            dbg_image: yes
            swi_image: yes
            docker_syncd_rpc_image: yes
            platform_rpc: brcm

        - name: marvell-teralynx
          variables:
            dbg_image: yes

        - name: marvell-prestera-armhf
          ${{ if not(parameters.qemuOrCrossBuild) }}:
            pool: sonicso1ES-armhf
          variables:
            PLATFORM_NAME: marvell-prestera
            PLATFORM_ARCH: armhf

        - name: marvell-prestera-arm64
          ${{ if not(parameters.qemuOrCrossBuild) }}:
            pool: sonicso1ES-arm64
          variables:
            PLATFORM_NAME: marvell-prestera
            PLATFORM_ARCH: arm64

        - name: marvell-prestera

        - name: mellanox
          variables:
            dbg_image: yes
            docker_syncd_rpc_image: yes
            syncd_rpc_image: yes
            platform_rpc: mlnx

        - name: nephos
          variables:
            dbg_image: yes
            docker_syncd_rpc_image: yes
            platform_rpc: nephos

        - name: pensando
          pool: sonicso1ES-arm64
          variables:
            PLATFORM_ARCH: arm64

        - name: nvidia-bluefield
          pool: sonicso1ES-arm64
          variables:
            PLATFORM_ARCH: arm64

        - name: aspeed-arm64
          pool: sonicso1ES-arm64
          variables:
            PLATFORM_NAME: aspeed
            PLATFORM_ARCH: arm64

        - name: vpp
          variables:
            dbg_image: yes

    buildSteps:
      - template: .azure-pipelines/template-skipvstest.yml@buildimage
      - template: .azure-pipelines/template-daemon.yml@buildimage
      - bash: |
          set -ex
          mkdir -p target/rep
          cd target/rep
          git clone https://github.com/thesayyn/p4runtime
          git clone https://github.com/thesayyn/gutil
          git clone https://github.com/thesayyn/p4-constraints
          git clone https://github.com/thesayyn/p4c
          cd -
          sed -i '4i\    version = "0.0.0",' src/sonic-sairedis/SAI/MODULE.bazel
          BLDENV=bookworm make -f Makefile.work $BUILD_OPTIONS sonic-slave-run SONIC_RUN_CMDS="make docker-start -f slave.mk || sudo service docker start; bazel build //dockers/docker-base-bookworm:load; bash bazel-bin/dockers/docker-base-bookworm/load.sh; docker save docker-base-bookworm:latest | pigz > target/docker-base-bookworm.tar.gz"
          BLDENV=bookworm make -f Makefile.work $BUILD_OPTIONS target/docker-base-bookworm.gz
        displayName: "Build sonic image"
      - template: .azure-pipelines/check-dirty-version.yml@buildimage
      - task: PublishBuildArtifacts@1
        displayName: 'Publish target as artifact'
        inputs:
          PathtoPublish: 'target'
          ArtifactName: 'drop'
          publishLocation: 'Container'
      - task: ManifestGeneratorTask@0
        condition: ne(variables.SKIP_MG, 'y')
        timeoutInMinutes: 60
        continueOnError: true
        displayName: "Manifest Generator"
        inputs:
          BuildDropPath: '$(System.DefaultWorkingDirectory)/target/'
          ManifestDirPath: 'target/'
          BuildComponentPath: $(System.DefaultWorkingDirectory)/src/

