jobs:
  - job: CheckoutCode
    steps:
    - script: |
        set -ex

        if [ -n "${{ parameters.COMMIT_ID }}" ]; then
          if [ -z "${{ parameters.SUBMODULE_NAME }}" ]; then
            git checkout ${{ parameters.COMMIT_ID }}
          else
            git submodule update --init --recursive
            cd src/${{ parameters.SUBMODULE_NAME }}
            git checkout ${{ parameters.COMMIT_ID }}
          fi
        fi
    displayName: 'Checkout code'
