script: |
    set -ex

    if [ -n "$COMMIT_ID" ]; then
      if [ -z "$SUBMODULE_NAME" ]; then
        git checkout $COMMIT_ID
      else
        git submodule update --init --recursive
        cd src/$SUBMODULE_NAME
        git checkout $COMMIT_ID
      fi
    fi
