{% from "dockers/dockerfile-macros.j2" import install_debian_packages, install_python_wheels, copy_files %}
FROM docker-config-engine-bookworm-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

ARG docker_container_name

# Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

# Update apt's cache of available packages
RUN apt-get update

# Install keydb-server, redis deprecated
RUN curl -o keydb-server_6.3.4-1%2Bdeb11u1_amd64.deb "https://download.keydb.dev/pkg/open_source/deb/debian11_bullseye/amd64/keydb-latest/keydb-server_6.3.4-1%2Bdeb11u1_amd64.deb"
RUN dpkg -i keydb-server_6.3.4-1%2Bdeb11u1_amd64.deb || apt-get install -f -y
RUN rm keydb-server_6.3.4-1%2Bdeb11u1_amd64.deb

# Install click for CLI
RUN pip3 install click

{% if docker_database_debs.strip() -%}
# Copy locally-built Debian package dependencies
{{ copy_files("debs/", docker_database_debs.split(' '), "/debs/") }}

# Install locally-built Debian packages and implicitly install their dependencies
{{ install_debian_packages(docker_database_debs.split(' ')) }}
{%- endif %}

# Clean up
RUN apt-get clean -y                                  && \
    apt-get autoclean -y                              && \
    apt-get autoremove -y                             && \
    rm -rf /debs ~/.cache                             && \
    sed -ri 's/^# save ""$/save ""/g;                    \
             s/^daemonize yes$/daemonize no/;            \
             s/^logfile .*$/logfile ""/;                 \
             s/^# syslog-enabled no$/syslog-enabled no/; \
             s/^# unixsocket/unixsocket/;                \
             s/\/tmp\/keydb.sock/\/run\/redis\/redis.sock/g;           \
             s/^client-output-buffer-limit pubsub [0-9]+mb [0-9]+mb [0-9]+/client-output-buffer-limit pubsub 0 0 0/; \
             s/^notify-keyspace-events ""$/notify-keyspace-events AKE/; \
             s/^databases [0-9]+$/databases 100/; \
             s/^dir \/var\/lib\/keydb/dir \/var\/lib\/redis/; \
            ' /etc/keydb/keydb.conf

RUN cp /etc/keydb/keydb.conf /etc/redis/redis.conf
RUN chown -R redis:redis /etc/redis/redis.conf
RUN ln -s /usr/bin/keydb-check-rdb /usr/bin/redis-server

COPY ["supervisord.conf.j2", "/usr/share/sonic/templates/"]
COPY ["critical_processes.j2", "/usr/share/sonic/templates/"]
COPY ["docker-database-init.sh", "/usr/local/bin/"]
COPY ["database_config.json.j2", "/usr/share/sonic/templates/"]
COPY ["database_global.json.j2", "/usr/share/sonic/templates/"]
COPY ["files/supervisor-proc-exit-listener", "/usr/bin"]
COPY ["files/sysctl-net.conf", "/etc/sysctl.d/"]
COPY ["files/update_chassisdb_config", "/usr/local/bin/"]
COPY ["flush_unused_database", "/usr/local/bin/"]
COPY ["multi_database_config.json.j2", "/usr/share/sonic/templates/"]

ENTRYPOINT ["/usr/local/bin/docker-database-init.sh"]
