CONSOLE_SPEED=115200
CONSOLE_PORT=0x5060
CONSOLE_DEV=0
ONIE_PLATFORM_EXTRA_CMDLINE_LINUX="iommu=pt modprobe.blacklist=wb_fpga_pcie,spi_gpio,i2c_ismt,i2c_i801,wb_spi_gpio,wb_i2c_i801,intel_spi,ice,igb,mei_me"
