ifcs:
  options:
    log_level: "info"
nodes:
- node_id: "0"
  options:
    sd_low_power_mode_global_default: "true"
    sku: "configs/sku/innovium.77700_B"
    netdev:
    - auto_create: "no"
      multi_interface: "yes"
    buffer_management_mode: "api_driven"
    wred_cr_ip_proto_list: "17"
    cr_assignment_mode: "1"
    max_lossless_tc: "2"
    ilpm_enable: "1"
    forward_profile: "IFCS_FORWARD_PROFILE_ID_PROFILE_E"
    txring:
    - txring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    rxring:
    - rxring_id: "0"                                         
      desc_count: "1024"                                     
      prio: "1"     
      netdev: "true"      
      queues: "0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39"  
    - rxring_id: "1"                                         
      desc_count: "1024"                                     
      prio: "1"    
      netdev: "true"      
      queues: "1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40"  
    - rxring_id: "2"                                         
      desc_count: "1024"                                     
      prio: "1"
      netdev: "true"      
      queues: "2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 47" 
    - rxring_id: "3"                                         
      desc_count: "1024"                                     
      prio: "1"     
      queues: "42, 43, 44, 45, 46" 
    sys_clk: "1720"
    ifc_clk: "1200"
    mac_clk: "1340"

  devports:
  - id: "0"
    sysport: "1000"
    type: "cpu"
  - fec: "KRFEC"
    id: "33"
    lanes: "0:4"
    serdes_group: "4"
    speed: "100G"
    sysport: "33"
    type: "eth"
  - fec: "KRFEC"
    id: "37"
    lanes: "4:4"
    serdes_group: "4"
    speed: "100G"
    sysport: "37"
    type: "eth"
  - fec: "KRFEC"
    id: "25"
    lanes: "0:4"
    serdes_group: "3"
    speed: "100G"
    sysport: "25"
    type: "eth"
  - fec: "KRFEC"
    id: "29"
    lanes: "4:4"
    serdes_group: "3"
    speed: "100G"
    sysport: "29"
    type: "eth"
  - fec: "KRFEC"
    id: "17"
    lanes: "0:4"
    serdes_group: "2"
    speed: "100G"
    sysport: "17"
    type: "eth"
  - fec: "KRFEC"
    id: "21"
    lanes: "4:4"
    serdes_group: "2"
    speed: "100G"
    sysport: "21"
    type: "eth"
  - fec: "KRFEC"
    id: "1"
    lanes: "0:4"
    serdes_group: "0"
    speed: "100G"
    sysport: "1"
    type: "eth"
  - fec: "KRFEC"
    id: "5"
    lanes: "4:4"
    serdes_group: "0"
    speed: "100G"
    sysport: "5"
    type: "eth"
  - fec: "KRFEC"
    id: "233"
    lanes: "0:4"
    serdes_group: "29"
    speed: "100G"
    sysport: "233"
    type: "eth"
  - fec: "KRFEC"
    id: "237"
    lanes: "4:4"
    serdes_group: "29"
    speed: "100G"
    sysport: "237"
    type: "eth"
  - fec: "KRFEC"
    id: "225"
    lanes: "0:4"
    serdes_group: "28"
    speed: "100G"
    sysport: "225"
    type: "eth"
  - fec: "KRFEC"
    id: "229"
    lanes: "4:4"
    serdes_group: "28"
    speed: "100G"
    sysport: "229"
    type: "eth"
  - fec: "KRFEC"
    id: "217"
    lanes: "0:4"
    serdes_group: "27"
    speed: "100G"
    sysport: "217"
    type: "eth"
  - fec: "KRFEC"
    id: "221"
    lanes: "4:4"
    serdes_group: "27"
    speed: "100G"
    sysport: "221"
    type: "eth"
  - fec: "KRFEC"
    id: "209"
    lanes: "0:4"
    serdes_group: "26"
    speed: "100G"
    sysport: "209"
    type: "eth"
  - fec: "KRFEC"
    id: "213"
    lanes: "4:4"
    serdes_group: "26"
    speed: "100G"
    sysport: "213"
    type: "eth"
  - fec: "KRFEC"
    id: "161"
    lanes: "0:4"
    serdes_group: "20"
    speed: "100G"
    sysport: "161"
    type: "eth"
  - fec: "KRFEC"
    id: "165"
    lanes: "4:4"
    serdes_group: "20"
    speed: "100G"
    sysport: "165"
    type: "eth"
  - fec: "KRFEC"
    id: "153"
    lanes: "0:4"
    serdes_group: "19"
    speed: "100G"
    sysport: "153"
    type: "eth"
  - fec: "KRFEC"
    id: "157"
    lanes: "4:4"
    serdes_group: "19"
    speed: "100G"
    sysport: "157"
    type: "eth"
  - fec: "KRFEC"
    id: "145"
    lanes: "0:4"
    serdes_group: "18"
    speed: "100G"
    sysport: "145"
    type: "eth"
  - fec: "KRFEC"
    id: "149"
    lanes: "4:4"
    serdes_group: "18"
    speed: "100G"
    sysport: "149"
    type: "eth"
  - fec: "KRFEC"
    id: "129"
    lanes: "0:4"
    serdes_group: "16"
    speed: "100G"
    sysport: "129"
    type: "eth"
  - fec: "KRFEC"
    id: "133"
    lanes: "4:4"
    serdes_group: "16"
    speed: "100G"
    sysport: "133"
    type: "eth"
  - fec: "KRFEC"
    id: "113"
    lanes: "0:4"
    serdes_group: "14"
    speed: "100G"
    sysport: "113"
    type: "eth"
  - fec: "KRFEC"
    id: "117"
    lanes: "4:4"
    serdes_group: "14"
    speed: "100G"
    sysport: "117"
    type: "eth"
  - fec: "KRFEC"
    id: "105"
    lanes: "0:4"
    serdes_group: "13"
    speed: "100G"
    sysport: "105"
    type: "eth"
  - fec: "KRFEC"
    id: "109"
    lanes: "4:4"
    serdes_group: "13"
    speed: "100G"
    sysport: "109"
    type: "eth"
  - fec: "KRFEC"
    id: "89"
    lanes: "0:4"
    serdes_group: "11"
    speed: "100G"
    sysport: "89"
    type: "eth"
  - fec: "KRFEC"
    id: "93"
    lanes: "4:4"
    serdes_group: "11"
    speed: "100G"
    sysport: "93"
    type: "eth"
  - fec: "KRFEC"
    id: "81"
    lanes: "0:4"
    serdes_group: "10"
    speed: "100G"
    sysport: "81"
    type: "eth"
  - fec: "KRFEC"
    id: "85"
    lanes: "4:4"
    serdes_group: "10"
    speed: "100G"
    sysport: "85"
    type: "eth"
  isg:
  - id: "0"
    tx_polarity: "11011111"
    rx_polarity: "10001000"
    lane_swap: "67543210"
  - id: "1"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"
  - id: "2"
    tx_polarity: "11011000"
    rx_polarity: "10001110"
    lane_swap: "67543210"
  - id: "3"
    tx_polarity: "11101110"
    rx_polarity: "01001000"
    lane_swap: "67542310"
  - id: "4"
    tx_polarity: "11001000"
    rx_polarity: "11000110"
    lane_swap: "67542310"
  - id: "5"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"
  - id: "6"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"
  - id: "7"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"
  - id: "8"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"
  - id: "9"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"
  - id: "10"
    tx_polarity: "10100100"
    rx_polarity: "10101100"
    lane_swap: "67451320"
  - id: "11"
    tx_polarity: "10000000"
    rx_polarity: "11111011"
    lane_swap: "67542310"
  - id: "12"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"
  - id: "13"
    tx_polarity: "11001001"
    rx_polarity: "01001110"
    lane_swap: "76542310"
  - id: "14"
    tx_polarity: "01000100"
    rx_polarity: "01010110"
    lane_swap: "67452301"
  - id: "15"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"
  - id: "16"
    tx_polarity: "00000000"
    rx_polarity: "01111101"
    lane_swap: "67542310"
  - id: "17"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"
  - id: "18"
    tx_polarity: "11101101"
    rx_polarity: "01001101"
    lane_swap: "76542310"
  - id: "19"
    tx_polarity: "00111111"
    rx_polarity: "10101100"
    lane_swap: "67542310"
  - id: "20"
    tx_polarity: "11101100"
    rx_polarity: "01001000"
    lane_swap: "67542310"
  - id: "21"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"
  - id: "22"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"
  - id: "23"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"
  - id: "24"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"
  - id: "25"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"
  - id: "26"
    tx_polarity: "10001110"
    rx_polarity: "11000100"
    lane_swap: "67542310"
  - id: "27"
    tx_polarity: "11000101"
    rx_polarity: "01001010"
    lane_swap: "76542310"
  - id: "28"
    tx_polarity: "11001000"
    rx_polarity: "10000111"
    lane_swap: "67542310"
  - id: "29"
    tx_polarity: "11110111"
    rx_polarity: "00101110"
    lane_swap: "67452310"
  - id: "30"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"
  - id: "31"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"
  - id: "32"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"
